-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w8a16/amc_cnn_8w16a_src_SinglePortRAM_generic_block339.vhd
-- Created: 2023-08-07 19:04:38
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_8w16a_src_SinglePortRAM_generic_block339
-- Source Path: amc_model_w8a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage107/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_8w16a_src_SinglePortRAM_generic_block339 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_8w16a_src_SinglePortRAM_generic_block339;


ARCHITECTURE rtl OF amc_cnn_8w16a_src_SinglePortRAM_generic_block339 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"d2", X"23", X"12", X"1d", X"00", X"2e", X"e6", X"1c", X"fb", X"17", X"0e", X"00", X"d9", X"2c",
                                                        X"01", X"1b", X"d5", X"07", X"e3", X"f7", X"27", X"03", X"f3", X"ec", X"f5", X"cd", X"08", X"0e", X"f4", X"e2", X"ff", X"16", X"c3", X"f8", X"f6", X"e7", X"02", X"37", X"19", X"1b",
                                                        X"e4", X"16", X"03", X"f7", X"25", X"f9", X"14", X"1d", X"36", X"f1", X"e8", X"f3", X"ed", X"1a", X"f9", X"2c", X"02", X"d5", X"fb", X"fb", X"23", X"0c", X"0b", X"01", X"d0", X"f6",
                                                        X"fc", X"17", X"e7", X"ed", X"f8", X"1b", X"1e", X"ea", X"f1", X"ff", X"f5", X"23", X"08", X"eb", X"29", X"00", X"0b", X"13", X"fd", X"f0", X"ff", X"d4", X"36", X"e0", X"fd", X"f4",
                                                        X"ea", X"2e", X"ea", X"0b", X"0c", X"f4", X"03", X"35", X"04", X"e8", X"f2", X"12", X"fa", X"22", X"03", X"ee", X"00", X"f0", X"0d", X"fa", X"19", X"f3", X"02", X"0d", X"fa", X"ff",
                                                        X"ea", X"f6", X"f8", X"d7", X"f3", X"01", X"0a", X"e5", X"28", X"17", X"d6", X"07", X"ef", X"fa", X"07", X"2f", X"15", X"f2", X"fe", X"d9", X"07", X"ff", X"f8", X"0e", X"14", X"0d",
                                                        X"e6", X"15", X"f8", X"ec", X"3c", X"08", X"11", X"e5", X"f4", X"e4", X"19", X"10", X"f3", X"e7", X"22", X"07", X"fb", X"f3", X"fd", X"f0", X"15", X"ee", X"0b", X"2d", X"ec", X"f4",
                                                        X"13", X"ff", X"03", X"e2", X"19", X"f5", X"21", X"fe", X"fb", X"e8", X"f9", X"08", X"06", X"27", X"f3", X"1a", X"f3", X"ee", X"eb", X"1a", X"f4", X"04", X"cb", X"fe", X"11", X"fb",
                                                        X"fc", X"06", X"01", X"d2", X"f4", X"d0", X"06", X"00", X"17", X"16", X"ff", X"f1", X"03", X"f6", X"19", X"0b", X"0b", X"e2", X"d9", X"06", X"f9", X"0f", X"e2", X"03", X"ec", X"29",
                                                        X"10", X"f2", X"30", X"ee", X"1a", X"00", X"ea", X"dd", X"e9", X"d0", X"00", X"01", X"04", X"f9", X"ea", X"21", X"04", X"ea", X"ca", X"00", X"23", X"01", X"0e", X"2c", X"0c", X"2b",
                                                        X"0a", X"1e", X"07", X"ea", X"f7", X"eb", X"0e", X"02", X"c9", X"0a", X"f9", X"00", X"eb", X"33", X"e9", X"da", X"ee", X"0e", X"f6", X"ee", X"18", X"0f", X"11", X"fa", X"06", X"0a",
                                                        X"f1", X"03", X"20", X"20", X"1c", X"24", X"f6", X"1f", X"ea", X"16", X"fc", X"dc", X"00", X"28", X"e6", X"09", X"f0", X"07", X"16", X"34", X"0a", X"e3", X"fe", X"f3", X"f6", X"0a",
                                                        X"21", X"f3", X"22", X"13", X"1a", X"f3", X"fc", X"ed", X"16", X"e8", X"20", X"19", X"0e", X"c8", X"fa", X"17", X"1d", X"df", X"f7", X"0b", X"34", X"ec", X"0f", X"13", X"e5", X"15",
                                                        X"f4", X"dc", X"0c", X"0b", X"ec", X"0d", X"ec", X"0d", X"f2", X"00", X"e1", X"f4", X"0f", X"f3", X"09", X"df", X"13", X"dc", X"15", X"11", X"08", X"0a", X"e9", X"0d", X"08", X"08",
                                                        X"0f", X"f5", X"18", X"1b", X"fe", X"e0", X"f3", X"12", X"1d", X"04", X"f8", X"ef", X"04", X"12", X"0e", X"fa", X"fd", X"fe", X"09", X"2e", X"f1", X"02", X"eb", X"f8", X"19", X"e4",
                                                        X"16", X"f6", X"03", X"f5", X"e9", X"f1", X"d5", X"07", X"f3", X"0a", X"29", X"f3", X"f1", X"25", X"ec", X"dd", X"e6", X"02", X"1a", X"f1", X"1b", X"06", X"d1", X"ff", X"f6", X"0c",
                                                        X"2b", X"15", X"ed", X"36", X"f0", X"11", X"fb", X"09", X"ef", X"d7", X"fe", X"fe", X"f4", X"0f", X"e9", X"00", X"20", X"19", X"f4", X"d6", X"ea", X"27", X"03", X"0c", X"f3", X"e2",
                                                        X"00", X"0b", X"27", X"09", X"f7", X"ed", X"0f", X"2e", X"1a", X"09", X"00", X"d6", X"ee", X"11", X"f3", X"f8", X"08", X"fe", X"06", X"f8", X"02", X"ff", X"ef", X"da", X"e8", X"0d",
                                                        X"f3", X"30", X"f7", X"11", X"fa", X"24", X"f0", X"03", X"e1", X"df", X"0a", X"e9", X"d5", X"ea", X"0b", X"25", X"06", X"e2", X"f6", X"0d", X"fa", X"2c", X"e5", X"04", X"e9", X"eb",
                                                        X"15", X"0f", X"fd", X"de", X"ed", X"fe", X"00", X"f3", X"01", X"13", X"11", X"fa", X"04", X"09", X"09", X"fd", X"16", X"04", X"03", X"0b", X"d7", X"d2", X"f3", X"19", X"e8", X"08",
                                                        X"fc", X"12", X"11", X"f0", X"e6", X"fe", X"06", X"1b", X"28", X"3e", X"23", X"21", X"19", X"28", X"f0", X"eb", X"00", X"fa", X"0a", X"16", X"dc", X"0a", X"e5", X"fc", X"1a", X"0b",
                                                        X"14", X"f1", X"f9", X"e9", X"02", X"f2", X"11", X"e3", X"32", X"1a", X"fc", X"ff", X"e7", X"f3", X"41", X"02", X"3c", X"e7", X"f0", X"fc", X"05", X"02", X"20", X"01", X"fd", X"0d",
                                                        X"00", X"f9", X"02", X"01", X"19", X"18", X"e9", X"f4", X"f7", X"16", X"13", X"eb", X"f2", X"1d", X"f0", X"02", X"f1", X"ec", X"f3", X"e6", X"10", X"10", X"02", X"04", X"12", X"f2",
                                                        X"03", X"fc", X"f6", X"16", X"f4", X"18", X"2f", X"f8", X"07", X"0b", X"ff", X"ce", X"09", X"db", X"13", X"14", X"02", X"0d", X"0d", X"fb", X"03", X"00", X"da", X"f0", X"10", X"11",
                                                        X"f0", X"fc", X"08", X"0e", X"1f", X"21", X"f0", X"f5", X"ea", X"fe", X"ee", X"eb", X"05", X"fc", X"08", X"10", X"ee", X"0f", X"e4", X"24", X"03", X"f1", X"03", X"e8", X"f4", X"21",
                                                        X"07", X"f8", X"e6", X"fb", X"f4", X"fb", X"f2", X"ec", X"04", X"d3", X"03", X"dd", X"04", X"f8", X"fd", X"f2", X"26", X"10", X"c8", X"10", X"df", X"05", X"1f", X"15", X"f1", X"ee",
                                                        X"d6", X"2a", X"03", X"05", X"0a", X"0b", X"09", X"f4", X"02", X"0a", X"e2", X"fe", X"26", X"17", X"0e", X"27", X"f9", X"ee", X"01", X"ef", X"1d", X"db", X"17", X"0b", X"24", X"f9",
                                                        X"0a", X"ec", X"0d", X"f6", X"fe", X"10", X"e6", X"10", X"e7", X"fc", X"f4", X"fe", X"01", X"f6", X"27", X"01", X"07", X"e2", X"00", X"29", X"11", X"0c", X"ef", X"02", X"f9", X"0b",
                                                        X"f5", X"f4", X"18", X"f9", X"e7", X"fe", X"07", X"f9", X"dd", X"fb", X"e7", X"f5", X"ff", X"d1", X"08", X"07", X"f0", X"3f", X"f5", X"f7", X"ff", X"ea", X"10", X"08", X"dc", X"de",
                                                        X"e5", X"14", X"03", X"31", X"fc", X"ff", X"fe", X"09", X"da", X"ea", X"e2", X"eb", X"0b", X"09", X"ff", X"15", X"0d", X"25", X"f6", X"da", X"f3", X"f3", X"14", X"11", X"f9", X"03",
                                                        X"24", X"0f", X"09", X"1b", X"03", X"11", X"00", X"24", X"20", X"2d", X"03", X"f8", X"0d", X"eb", X"0e", X"fc", X"b8", X"13", X"fc", X"fd", X"02", X"1b", X"fc", X"d3", X"f6", X"26",
                                                        X"f1", X"f1", X"18", X"fc", X"0f", X"13", X"d7", X"08", X"f8", X"fc", X"1b", X"05", X"10", X"0d", X"fa", X"f3", X"ec", X"f4", X"18", X"0c", X"07", X"19", X"ba", X"f3", X"f8", X"ed",
                                                        X"12", X"3c", X"1f", X"e8", X"fa", X"fc", X"ed", X"03", X"24", X"0f", X"f6", X"12", X"0f", X"f2", X"ef", X"ed", X"19", X"0c", X"f0", X"cd", X"fb", X"03", X"f1", X"f5", X"07", X"28",
                                                        X"f9", X"f8", X"ff", X"f1", X"01", X"e0", X"04", X"04", X"ee", X"d1", X"f9", X"fa", X"ed", X"fe", X"fe", X"ef", X"09", X"02", X"53", X"ed", X"17", X"2a", X"eb", X"ee", X"ee", X"0d",
                                                        X"2e", X"17", X"00", X"06", X"02", X"f4", X"f5", X"ff", X"ea", X"f9", X"08", X"ff", X"f0", X"f3", X"e6", X"e3", X"27", X"10", X"e8", X"15", X"0a", X"2d", X"f0", X"fa", X"f4", X"fa",
                                                        X"0c", X"1a", X"01", X"f1", X"07", X"13", X"11", X"fa", X"f1", X"eb", X"e6", X"02", X"0d", X"02", X"e9", X"03", X"f5", X"0e", X"fa", X"18", X"fb", X"0e", X"fd", X"d0", X"03", X"f3",
                                                        X"00", X"ed", X"11", X"0d", X"1a", X"17", X"f1", X"1f", X"26", X"fb", X"02", X"09", X"cf", X"35", X"00", X"fe", X"26", X"e3", X"2e", X"0f", X"b8", X"fa", X"03", X"e5", X"26", X"2e",
                                                        X"1f", X"2c", X"e5", X"cd", X"f2", X"0b", X"05", X"d7", X"1b", X"ef", X"2b", X"fc", X"f7", X"f7", X"f9", X"09", X"f0", X"12", X"e0", X"cc", X"ff", X"00", X"fd", X"f0", X"f8", X"f2",
                                                        X"1e", X"fd", X"14", X"04", X"bf", X"05", X"11", X"09", X"07", X"29", X"f9", X"fc", X"fe", X"0e", X"db", X"f8", X"f2", X"f3", X"20", X"00", X"f7", X"03", X"da", X"0e", X"0f", X"f8",
                                                        X"ef", X"03", X"01", X"0c", X"e9", X"fb", X"42", X"ed", X"18", X"0d", X"e0", X"d7", X"ec", X"f7", X"f9", X"0c", X"e1", X"04", X"fc", X"24", X"df", X"02", X"d7", X"f6", X"06", X"f4",
                                                        X"0c", X"fb", X"fc", X"2d", X"f9", X"da", X"04", X"fe", X"05", X"1d", X"f5", X"f6", X"ff", X"fc", X"07", X"f5", X"08", X"26", X"0c", X"2f", X"f9", X"e5", X"eb", X"03", X"0e", X"19",
                                                        X"14", X"0e", X"f7", X"05", X"ed", X"0d", X"fa", X"2e", X"10", X"05", X"fa", X"07", X"05", X"0c", X"22", X"e5", X"08", X"13", X"d4", X"fe", X"f0", X"06", X"1d", X"26", X"0e", X"dc",
                                                        X"ef", X"00", X"f8", X"ed", X"11", X"f2", X"14", X"0e", X"f5", X"f8", X"f6", X"10", X"11", X"f9", X"16", X"f4", X"e1", X"16", X"e6", X"02", X"0c", X"e1", X"1a", X"1d", X"10", X"06",
                                                        X"f2", X"01", X"e4", X"ed", X"e5", X"01", X"07", X"1a", X"03", X"f3", X"04", X"f8", X"f7", X"f9", X"31", X"02", X"fc", X"17", X"04", X"ee", X"ec", X"d9", X"15", X"28", X"0b", X"f2",
                                                        X"fc", X"11", X"f6", X"ff", X"e8", X"fb", X"08", X"28", X"eb", X"e0", X"e9", X"d9", X"2c", X"03", X"03", X"ff", X"e9", X"de", X"e0", X"ed", X"19", X"f6", X"08", X"20", X"15", X"ef",
                                                        X"f9", X"cb", X"11", X"fc", X"fc", X"f5", X"f7", X"1e", X"ff", X"eb", X"f1", X"07", X"fe", X"01", X"f0", X"e7", X"e9", X"d8", X"fd", X"ee", X"f9", X"fa", X"ee", X"f7", X"07", X"1b",
                                                        X"f1", X"19", X"f7", X"12", X"1b", X"28", X"01", X"31", X"e1", X"2c", X"f4", X"ea", X"24", X"f0", X"11", X"f0", X"eb", X"0e", X"f5", X"06", X"0e", X"0b", X"25", X"f8", X"f3", X"ef",
                                                        X"fc", X"fb", X"fb", X"f8", X"23", X"fd", X"ef", X"f7", X"ef", X"0e", X"f9", X"0a", X"1f", X"cb", X"d8", X"16", X"ef", X"04", X"05", X"14", X"21", X"fa", X"ff", X"f7", X"fa", X"ed",
                                                        X"0d", X"12", X"09", X"0f", X"f3", X"d6", X"ef", X"fd", X"0d", X"e5", X"06", X"08", X"25", X"f9", X"12", X"f7", X"df", X"e3", X"0d", X"c5", X"f4", X"29", X"07", X"f9", X"ec", X"11",
                                                        X"dd", X"05", X"e7", X"f2", X"21", X"0a", X"01", X"dd", X"0b", X"f3", X"0f", X"fe", X"ea", X"01", X"e7", X"11", X"fe", X"ef", X"fd", X"f4", X"0d", X"0c", X"ef", X"d9", X"f6", X"f9",
                                                        X"fc", X"03", X"08", X"09", X"0b", X"2a", X"09", X"e4", X"03", X"09", X"0c", X"01", X"00", X"12", X"d3", X"2e", X"fd", X"eb", X"fa", X"09", X"02", X"08", X"02", X"fa", X"17", X"02",
                                                        X"fb", X"1a", X"07", X"34", X"1d", X"df", X"eb", X"f4", X"02", X"01", X"fe", X"e6", X"15", X"07", X"df", X"12", X"04", X"e9", X"07", X"3d", X"12", X"07", X"f3", X"e2", X"e7", X"22",
                                                        X"22", X"06", X"1f", X"0c", X"ff", X"04", X"03", X"fd", X"f9", X"05", X"08", X"07", X"fa", X"07", X"e9", X"0f", X"03", X"08", X"1e", X"02", X"0b", X"f7", X"03", X"e8", X"08", X"06",
                                                        X"f1", X"e8", X"fb", X"d6", X"04", X"ff", X"13", X"12", X"eb", X"e7", X"f0", X"f2", X"01", X"f6", X"ff", X"00", X"f5", X"cb", X"23", X"cd", X"e7", X"f5", X"fd", X"fb", X"e8", X"f7",
                                                        X"14", X"fb", X"0b", X"11", X"ff", X"ef", X"ee", X"d7", X"1b", X"18", X"fd", X"f7", X"e9", X"20", X"f1", X"e8", X"20", X"f6", X"11", X"20", X"f9", X"fb", X"ee", X"1a", X"1b", X"23",
                                                        X"eb", X"f1", X"02", X"ed", X"de", X"01", X"fa", X"f9", X"0a", X"0f", X"db", X"f3", X"f8", X"c8", X"08", X"cb", X"ea", X"01", X"0f", X"fe", X"fa", X"e7", X"d1", X"00", X"f8", X"f1",
                                                        X"0c", X"f2", X"0a", X"f0", X"ff", X"2f", X"f7", X"ef", X"f4", X"14", X"27", X"fa", X"20", X"09", X"ed", X"fc", X"2b", X"07", X"f3", X"e0", X"e6", X"f7", X"eb", X"fb", X"12", X"fd",
                                                        X"2a", X"fd", X"b7", X"0f", X"ea", X"f8", X"f3", X"0a", X"12", X"21", X"ea", X"25", X"02", X"05", X"e8", X"df", X"21", X"f2", X"20", X"11", X"f6", X"f9", X"f2", X"07", X"2d", X"25",
                                                        X"0f", X"16", X"0a", X"fc", X"0a", X"e8", X"f2", X"ec", X"12", X"f9", X"fe", X"ea", X"d8", X"e7", X"15", X"ff", X"f4", X"1e", X"fb", X"0b", X"e7", X"2a", X"d9", X"fe", X"e7", X"fe",
                                                        X"10", X"05", X"d5", X"da", X"19", X"18", X"10", X"e9", X"f5", X"fb", X"f2", X"2c", X"f2", X"09", X"d7", X"03", X"1c", X"19", X"e5", X"f9", X"e6", X"25", X"03", X"0c", X"f0", X"05",
                                                        X"03", X"16", X"fb", X"eb", X"20", X"00", X"0b", X"00", X"e0", X"15", X"fe", X"0b", X"05", X"16", X"fe", X"09", X"10", X"fd", X"e1", X"fb", X"22", X"0b", X"e1", X"f9", X"dc", X"17",
                                                        X"e5", X"08", X"f3", X"b5", X"f2", X"e4", X"18", X"18", X"09", X"16", X"d4", X"02", X"f1", X"15", X"13", X"22", X"2b", X"24", X"ee", X"18", X"f0", X"f0", X"0e", X"00", X"f9", X"13",
                                                        X"da", X"06", X"ea", X"09", X"45", X"0f", X"e8", X"e4", X"f4", X"1c", X"f3", X"f8", X"f8", X"07", X"22", X"06", X"fa", X"ff", X"eb", X"1b", X"07", X"17", X"fe", X"ed", X"fb", X"27",
                                                        X"f4", X"08", X"0d", X"03", X"15", X"0d", X"df", X"f9", X"ef", X"fe", X"f8", X"fe", X"ee", X"f0", X"13", X"f5", X"02", X"f3", X"18", X"ec", X"eb", X"0e", X"27", X"f6", X"ee", X"10",
                                                        X"d6", X"0c", X"0e", X"c5", X"27", X"09", X"0b", X"fe", X"eb", X"2e", X"f4", X"f3", X"0c", X"f9", X"03", X"1d", X"e3", X"e4", X"0f", X"d6", X"22", X"cb", X"f5", X"02", X"fc", X"f2",
                                                        X"01", X"ef", X"31", X"f8", X"f5", X"33", X"fc", X"02", X"fa", X"e2", X"0f", X"13", X"ef", X"ed", X"f6", X"f3", X"06", X"0a", X"19", X"fd", X"0c", X"09", X"02", X"e1", X"0e", X"0e",
                                                        X"fa", X"fa", X"f8", X"f0", X"f5", X"fa", X"05", X"03", X"fc", X"0f", X"01", X"11", X"fa", X"0d", X"fd", X"07", X"f7", X"e4", X"06", X"fb", X"06", X"f5", X"2e", X"ec", X"28", X"08",
                                                        X"f2", X"0d", X"14", X"1a", X"fc", X"12", X"ea", X"df", X"e4", X"09", X"11", X"e4", X"0a", X"13", X"0b", X"f9", X"e4", X"f3", X"f2", X"2a", X"fa", X"dc", X"e8", X"f5", X"05", X"07",
                                                        X"20", X"de", X"0a", X"f0", X"ec", X"03", X"f7", X"f2", X"e0", X"fe", X"0d", X"03", X"e8", X"e8", X"f5", X"02", X"f2", X"fd", X"0b", X"f6", X"f8", X"ef", X"11", X"de", X"f8", X"0c",
                                                        X"f8", X"f4", X"06", X"44", X"fd", X"f8", X"f8", X"3a", X"0b", X"f7", X"dd", X"e9", X"1b", X"13", X"e8", X"14", X"dd", X"f3", X"0b", X"f7", X"fd", X"0d", X"ec", X"49", X"f3", X"f6",
                                                        X"24", X"fb", X"11", X"0f", X"d8", X"0b", X"f9", X"c8", X"03", X"32", X"0e", X"06", X"f6", X"1e", X"e8", X"06", X"d2", X"00", X"07", X"f7", X"ee", X"26", X"e3", X"31", X"f1", X"d9",
                                                        X"ef", X"f1", X"f9", X"09", X"fa", X"0d", X"2a", X"0d", X"ed", X"0a", X"ed", X"21", X"03", X"11", X"f3", X"07", X"f0", X"f6", X"27", X"ee", X"1d", X"0a", X"da", X"0e", X"fc", X"0a",
                                                        X"10", X"1b", X"ee", X"0b", X"f8", X"06", X"f1", X"f0", X"ff", X"ef", X"06", X"17", X"bb", X"0c", X"db", X"ec", X"17", X"28", X"1c", X"cc", X"f0", X"29", X"ec", X"00", X"11", X"f7",
                                                        X"18", X"07", X"1d", X"01", X"f6", X"fd", X"22", X"ef", X"e1", X"ea", X"09", X"fd", X"01", X"05", X"f7", X"ec", X"09", X"08", X"33", X"01", X"0b", X"f6", X"ee", X"ef", X"ee", X"be",
                                                        X"23", X"bd", X"02", X"f0", X"f3", X"18", X"ef", X"03", X"14", X"f2", X"03", X"29", X"fa", X"df", X"00", X"fd", X"25", X"0b", X"f2", X"0b", X"02", X"ed", X"e2", X"f6", X"0c", X"e6",
                                                        X"12", X"24", X"e3", X"ca", X"fa", X"01", X"24", X"25", X"17", X"06", X"02", X"0c", X"f0", X"f8", X"f9", X"fc", X"0b", X"16", X"13", X"e6", X"06", X"e2", X"eb", X"3f", X"04", X"ed",
                                                        X"fe", X"ed", X"0b", X"ed", X"c4", X"1e", X"e2", X"08", X"23", X"28", X"f7", X"09", X"e4", X"de", X"ec", X"06", X"09", X"df", X"2a", X"11");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"11";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

