-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w8a16/amc_cnn_8w16a_src_SinglePortRAM_generic_block407.vhd
-- Created: 2023-08-07 19:04:47
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_8w16a_src_SinglePortRAM_generic_block407
-- Source Path: amc_model_w8a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage54/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_8w16a_src_SinglePortRAM_generic_block407 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_8w16a_src_SinglePortRAM_generic_block407;


ARCHITECTURE rtl OF amc_cnn_8w16a_src_SinglePortRAM_generic_block407 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"53", X"f1", X"f6", X"da", X"1c", X"0f", X"2a", X"b7", X"03", X"dd", X"b8", X"f5", X"09", X"2d",
                                                        X"ff", X"ee", X"0d", X"f5", X"0b", X"0b", X"d1", X"0b", X"27", X"f2", X"07", X"14", X"ea", X"f7", X"12", X"d5", X"20", X"ed", X"28", X"00", X"f4", X"fa", X"2b", X"df", X"13", X"16",
                                                        X"29", X"14", X"e2", X"09", X"db", X"30", X"2b", X"f6", X"47", X"01", X"f5", X"0a", X"2a", X"ee", X"0b", X"0e", X"00", X"05", X"e2", X"f9", X"fc", X"cd", X"f8", X"fc", X"b8", X"e2",
                                                        X"18", X"e0", X"fb", X"1c", X"df", X"3a", X"f6", X"fa", X"d4", X"0d", X"fd", X"13", X"38", X"df", X"24", X"ef", X"14", X"d9", X"f4", X"e9", X"30", X"cf", X"0f", X"42", X"e7", X"19",
                                                        X"d5", X"08", X"11", X"f4", X"d2", X"f1", X"ed", X"0d", X"33", X"ef", X"f8", X"32", X"1d", X"e4", X"f2", X"07", X"05", X"db", X"03", X"fb", X"5c", X"f8", X"f4", X"f2", X"0c", X"ea",
                                                        X"14", X"3b", X"fd", X"04", X"c7", X"03", X"e5", X"e7", X"de", X"f8", X"57", X"03", X"fe", X"e8", X"ff", X"2f", X"09", X"1c", X"13", X"fa", X"db", X"05", X"f0", X"ea", X"1a", X"e8",
                                                        X"f5", X"07", X"f3", X"df", X"c5", X"1c", X"ce", X"dd", X"25", X"06", X"d5", X"f2", X"da", X"f3", X"31", X"13", X"d9", X"ff", X"0f", X"04", X"cd", X"ff", X"09", X"dc", X"03", X"3c",
                                                        X"d6", X"f3", X"23", X"08", X"f6", X"f5", X"d8", X"00", X"1c", X"c9", X"53", X"1a", X"22", X"02", X"08", X"36", X"e8", X"e0", X"c9", X"26", X"1a", X"f4", X"b7", X"02", X"f0", X"cd",
                                                        X"e5", X"26", X"cd", X"cb", X"1d", X"29", X"d8", X"0b", X"20", X"38", X"e4", X"fa", X"4c", X"08", X"05", X"f9", X"ec", X"23", X"e1", X"e3", X"ff", X"20", X"e4", X"f1", X"26", X"ef",
                                                        X"0c", X"f6", X"e8", X"e3", X"01", X"ce", X"2b", X"ed", X"d4", X"18", X"f4", X"e7", X"f9", X"ef", X"f6", X"2c", X"d6", X"e5", X"ea", X"f9", X"0c", X"e0", X"f8", X"25", X"d2", X"22",
                                                        X"21", X"e0", X"ec", X"07", X"19", X"f5", X"24", X"de", X"00", X"f9", X"01", X"e9", X"24", X"2a", X"da", X"cc", X"0a", X"33", X"de", X"fb", X"dc", X"38", X"ec", X"f6", X"fa", X"05",
                                                        X"0d", X"d0", X"3b", X"dd", X"d2", X"34", X"32", X"e0", X"ca", X"f1", X"11", X"e4", X"16", X"e4", X"17", X"fd", X"06", X"fd", X"e9", X"33", X"0b", X"fe", X"0e", X"cf", X"c7", X"06",
                                                        X"dd", X"3f", X"f0", X"f8", X"e5", X"f6", X"f6", X"f5", X"db", X"f4", X"d8", X"06", X"00", X"e6", X"e5", X"e0", X"2d", X"e2", X"0f", X"f2", X"20", X"00", X"11", X"d2", X"48", X"1e",
                                                        X"f4", X"02", X"f4", X"3f", X"f6", X"e8", X"ed", X"ff", X"06", X"ec", X"27", X"fb", X"0e", X"ee", X"e0", X"08", X"ea", X"d3", X"1e", X"19", X"df", X"11", X"da", X"2d", X"0b", X"f8",
                                                        X"16", X"fc", X"07", X"f0", X"f8", X"0d", X"15", X"2a", X"1c", X"e0", X"e8", X"06", X"32", X"f1", X"13", X"e0", X"3a", X"f9", X"eb", X"da", X"dd", X"27", X"f2", X"dc", X"0c", X"15",
                                                        X"db", X"0e", X"10", X"21", X"0f", X"e7", X"e7", X"ff", X"f0", X"e6", X"14", X"ed", X"10", X"e4", X"2c", X"10", X"da", X"0f", X"d8", X"eb", X"20", X"eb", X"0c", X"fa", X"09", X"e9",
                                                        X"1c", X"10", X"c7", X"1a", X"13", X"e3", X"ea", X"f1", X"0a", X"02", X"ed", X"ed", X"1e", X"f2", X"1f", X"04", X"de", X"24", X"10", X"d9", X"0c", X"e5", X"d7", X"14", X"2c", X"ed",
                                                        X"0a", X"df", X"d1", X"04", X"f5", X"e0", X"fa", X"f8", X"c9", X"c2", X"06", X"26", X"de", X"12", X"d6", X"36", X"e8", X"de", X"0d", X"08", X"fb", X"d5", X"28", X"e9", X"07", X"3e",
                                                        X"21", X"15", X"d8", X"fc", X"02", X"0d", X"e4", X"e7", X"bb", X"02", X"17", X"1a", X"01", X"0a", X"35", X"07", X"2a", X"df", X"e4", X"0c", X"e7", X"24", X"ef", X"f1", X"28", X"fd",
                                                        X"f5", X"0e", X"2b", X"f1", X"e7", X"f5", X"12", X"c3", X"e6", X"19", X"00", X"3a", X"fd", X"f2", X"4e", X"f7", X"f6", X"0b", X"ef", X"2b", X"de", X"1f", X"08", X"25", X"df", X"04",
                                                        X"c7", X"ef", X"0b", X"fb", X"c6", X"0a", X"1a", X"d6", X"38", X"22", X"d9", X"0e", X"2d", X"eb", X"d7", X"f9", X"fc", X"23", X"1c", X"f8", X"30", X"ef", X"0c", X"05", X"e5", X"24",
                                                        X"21", X"2a", X"24", X"0e", X"d3", X"0c", X"d0", X"ef", X"ef", X"f4", X"f6", X"f5", X"03", X"e8", X"1e", X"d9", X"dd", X"14", X"fe", X"f7", X"de", X"0c", X"f2", X"00", X"00", X"ec",
                                                        X"b6", X"05", X"f6", X"d9", X"33", X"0a", X"06", X"e9", X"1a", X"3d", X"d6", X"0b", X"bc", X"28", X"27", X"0d", X"0f", X"08", X"10", X"e0", X"04", X"ea", X"e7", X"1b", X"02", X"b2",
                                                        X"f4", X"10", X"cb", X"18", X"eb", X"f6", X"09", X"f1", X"04", X"14", X"0c", X"48", X"f7", X"b9", X"07", X"44", X"f5", X"03", X"09", X"f4", X"16", X"f4", X"3c", X"ec", X"fb", X"e1",
                                                        X"11", X"05", X"05", X"15", X"2a", X"3e", X"c6", X"02", X"e1", X"08", X"10", X"fa", X"fd", X"0a", X"f8", X"d3", X"43", X"30", X"f2", X"07", X"22", X"c6", X"f2", X"f7", X"01", X"39",
                                                        X"e7", X"f3", X"c4", X"09", X"fb", X"ca", X"07", X"ec", X"f0", X"3c", X"16", X"16", X"db", X"02", X"e3", X"34", X"01", X"f1", X"02", X"f2", X"11", X"0b", X"eb", X"d2", X"e9", X"de",
                                                        X"26", X"44", X"d1", X"fd", X"2c", X"2e", X"00", X"e1", X"05", X"02", X"0a", X"d1", X"3d", X"36", X"e9", X"cc", X"fa", X"bd", X"e9", X"1d", X"e6", X"fc", X"eb", X"f5", X"4e", X"f6",
                                                        X"fd", X"df", X"06", X"43", X"cc", X"f9", X"08", X"01", X"ed", X"f0", X"e4", X"3c", X"20", X"f7", X"1e", X"0c", X"f2", X"f3", X"38", X"eb", X"0d", X"da", X"12", X"c1", X"eb", X"08",
                                                        X"03", X"f8", X"f8", X"ff", X"eb", X"fb", X"fa", X"08", X"fd", X"f4", X"15", X"2f", X"17", X"0e", X"eb", X"08", X"c5", X"f9", X"fc", X"ec", X"17", X"f9", X"09", X"fa", X"26", X"f1",
                                                        X"da", X"b4", X"1a", X"08", X"c7", X"e9", X"0c", X"e0", X"2b", X"f6", X"0b", X"ed", X"17", X"ce", X"27", X"16", X"1e", X"ed", X"ff", X"dd", X"cb", X"1b", X"1d", X"3f", X"01", X"fc",
                                                        X"fc", X"fd", X"08", X"de", X"fe", X"4a", X"f5", X"2e", X"00", X"06", X"ef", X"19", X"c1", X"2f", X"03", X"d8", X"e9", X"f0", X"eb", X"0c", X"c6", X"f8", X"f8", X"cd", X"07", X"e9",
                                                        X"d8", X"e9", X"1f", X"f1", X"29", X"da", X"23", X"f4", X"0a", X"02", X"f0", X"13", X"ee", X"44", X"12", X"ea", X"d0", X"0a", X"fe", X"27", X"f7", X"f2", X"e0", X"fd", X"fb", X"bc",
                                                        X"33", X"df", X"08", X"bc", X"14", X"15", X"df", X"f8", X"ee", X"01", X"f0", X"f4", X"d7", X"f7", X"11", X"10", X"30", X"1f", X"f6", X"ce", X"16", X"2d", X"e1", X"fc", X"e5", X"f8",
                                                        X"04", X"f5", X"e4", X"f6", X"18", X"18", X"25", X"21", X"1f", X"38", X"26", X"04", X"d6", X"00", X"c9", X"28", X"0b", X"fb", X"0d", X"e8", X"f6", X"cd", X"e5", X"eb", X"09", X"42",
                                                        X"f9", X"00", X"cb", X"ff", X"1d", X"e2", X"0b", X"fb", X"ea", X"f8", X"f3", X"dc", X"e8", X"e4", X"16", X"04", X"06", X"da", X"d0", X"12", X"fa", X"10", X"0e", X"eb", X"ea", X"ff",
                                                        X"0a", X"df", X"37", X"1e", X"bb", X"cc", X"0f", X"0b", X"d2", X"0e", X"e4", X"15", X"0c", X"13", X"14", X"fe", X"05", X"f5", X"0a", X"f0", X"fb", X"1c", X"0a", X"fa", X"f0", X"07",
                                                        X"e1", X"2d", X"0d", X"e9", X"3c", X"00", X"05", X"fa", X"cb", X"36", X"22", X"22", X"0e", X"15", X"db", X"07", X"fb", X"f2", X"fd", X"f6", X"d6", X"e5", X"eb", X"fa", X"ce", X"04",
                                                        X"e7", X"d9", X"1f", X"cf", X"d0", X"13", X"e9", X"05", X"1d", X"e9", X"2c", X"fa", X"08", X"cb", X"da", X"f1", X"02", X"e3", X"1b", X"d9", X"c5", X"fb", X"1b", X"02", X"28", X"f7",
                                                        X"ce", X"f4", X"25", X"ec", X"0f", X"20", X"1d", X"29", X"09", X"cc", X"db", X"22", X"15", X"2d", X"ec", X"ef", X"4f", X"ff", X"14", X"07", X"2b", X"dc", X"2c", X"fe", X"0d", X"ed",
                                                        X"d5", X"f6", X"de", X"fd", X"2c", X"f7", X"12", X"f7", X"00", X"c9", X"0f", X"16", X"dd", X"cf", X"10", X"31", X"dc", X"19", X"ed", X"1f", X"fe", X"df", X"f9", X"f7", X"00", X"f8",
                                                        X"4b", X"dc", X"f1", X"fc", X"02", X"3f", X"cc", X"01", X"d4", X"1d", X"03", X"e9", X"f6", X"fc", X"ec", X"d2", X"e7", X"49", X"d6", X"c7", X"01", X"dd", X"d4", X"11", X"ea", X"1f",
                                                        X"09", X"ec", X"15", X"0c", X"15", X"e4", X"e5", X"d3", X"0b", X"24", X"10", X"d1", X"ef", X"09", X"da", X"e1", X"ee", X"e8", X"4a", X"00", X"17", X"17", X"e6", X"16", X"32", X"26",
                                                        X"ff", X"ed", X"e3", X"14", X"0d", X"04", X"31", X"f0", X"2a", X"03", X"f7", X"05", X"e7", X"38", X"fa", X"03", X"1f", X"da", X"ea", X"1b", X"fa", X"2d", X"38", X"f4", X"d6", X"0d",
                                                        X"0c", X"eb", X"26", X"17", X"31", X"c6", X"15", X"07", X"e3", X"04", X"ff", X"20", X"03", X"fd", X"20", X"e8", X"16", X"1c", X"28", X"13", X"ca", X"23", X"fa", X"d0", X"cb", X"0a",
                                                        X"e1", X"f1", X"1e", X"f8", X"ee", X"ff", X"03", X"19", X"d8", X"37", X"1f", X"3d", X"0b", X"08", X"d4", X"f0", X"e1", X"24", X"1b", X"e6", X"2b", X"fa", X"0d", X"10", X"27", X"17",
                                                        X"e0", X"db", X"05", X"e6", X"c7", X"10", X"d9", X"0c", X"07", X"e3", X"1b", X"f4", X"0d", X"cb", X"25", X"ff", X"03", X"e0", X"f7", X"fa", X"de", X"f3", X"fa", X"e3", X"18", X"f8",
                                                        X"d5", X"f0", X"fb", X"d4", X"08", X"00", X"21", X"c4", X"e9", X"24", X"f3", X"13", X"d9", X"ed", X"08", X"f8", X"f0", X"ff", X"f1", X"f9", X"f3", X"f7", X"cc", X"f0", X"06", X"1a",
                                                        X"e1", X"f4", X"1e", X"3e", X"fe", X"f6", X"49", X"00", X"fd", X"12", X"ea", X"1f", X"e2", X"0f", X"1a", X"d3", X"ee", X"2a", X"fb", X"2a", X"ee", X"f6", X"0b", X"02", X"1c", X"0e",
                                                        X"f0", X"f1", X"ec", X"41", X"1b", X"ed", X"dc", X"03", X"1c", X"00", X"2f", X"09", X"d1", X"02", X"fa", X"02", X"fb", X"f3", X"f6", X"02", X"1e", X"27", X"e9", X"02", X"dc", X"2a",
                                                        X"f8", X"fe", X"d1", X"ff", X"f6", X"04", X"19", X"2b", X"de", X"b8", X"14", X"39", X"de", X"fd", X"0e", X"fe", X"3f", X"04", X"1d", X"fe", X"fe", X"19", X"ff", X"2e", X"de", X"1e",
                                                        X"f8", X"b9", X"c5", X"04", X"d5", X"3c", X"0e", X"dd", X"25", X"04", X"05", X"d2", X"f6", X"27", X"d0", X"2e", X"f1", X"11", X"dc", X"f4", X"0a", X"ef", X"eb", X"0b", X"02", X"17",
                                                        X"f8", X"e0", X"e2", X"41", X"fd", X"33", X"08", X"c5", X"cf", X"f2", X"f2", X"17", X"12", X"f8", X"42", X"fb", X"05", X"fc", X"1a", X"38", X"33", X"d4", X"1d", X"24", X"f4", X"2b",
                                                        X"e8", X"03", X"3f", X"ff", X"1d", X"f7", X"07", X"13", X"f7", X"3d", X"cd", X"be", X"27", X"e7", X"ec", X"e3", X"00", X"44", X"fc", X"f6", X"e4", X"f9", X"0c", X"cc", X"31", X"e6",
                                                        X"e0", X"46", X"ee", X"e0", X"e2", X"21", X"ed", X"e7", X"39", X"fd", X"4c", X"02", X"11", X"ec", X"23", X"15", X"cb", X"42", X"0e", X"35", X"e1", X"03", X"f0", X"ef", X"01", X"f0",
                                                        X"cd", X"e5", X"1e", X"e0", X"ce", X"f5", X"ed", X"49", X"ff", X"0e", X"d1", X"f3", X"fb", X"25", X"f5", X"f7", X"de", X"ee", X"08", X"e9", X"27", X"3e", X"c3", X"14", X"0d", X"00",
                                                        X"bd", X"09", X"ea", X"28", X"ed", X"09", X"55", X"01", X"f3", X"d7", X"13", X"fd", X"26", X"19", X"16", X"ed", X"e1", X"02", X"dd", X"f6", X"13", X"02", X"06", X"ed", X"f3", X"f9",
                                                        X"f4", X"e5", X"2d", X"b6", X"20", X"fb", X"e4", X"f7", X"0a", X"03", X"15", X"f9", X"e3", X"f3", X"e8", X"f1", X"3d", X"f1", X"15", X"31", X"04", X"d4", X"ce", X"fa", X"c8", X"2c",
                                                        X"fe", X"f1", X"ec", X"fd", X"03", X"f4", X"df", X"05", X"f3", X"e0", X"1b", X"fa", X"e9", X"ee", X"fa", X"2e", X"f6", X"fe", X"f3", X"00", X"12", X"dd", X"26", X"11", X"d6", X"d7",
                                                        X"0c", X"31", X"f4", X"26", X"38", X"29", X"18", X"e8", X"de", X"f9", X"14", X"01", X"21", X"03", X"1c", X"e9", X"12", X"d9", X"d4", X"13", X"fd", X"fd", X"17", X"e1", X"3d", X"f8",
                                                        X"01", X"e8", X"34", X"e7", X"f8", X"e7", X"fd", X"3a", X"ef", X"13", X"17", X"48", X"ef", X"e3", X"f9", X"fd", X"f1", X"c1", X"32", X"f0", X"1d", X"f9", X"f7", X"d6", X"d4", X"f5",
                                                        X"f9", X"37", X"f0", X"de", X"f2", X"fa", X"03", X"eb", X"f4", X"20", X"f7", X"e8", X"2d", X"39", X"ec", X"f8", X"f8", X"42", X"f3", X"f4", X"54", X"fd", X"f0", X"bd", X"d8", X"d7",
                                                        X"d3", X"f1", X"1d", X"e2", X"c9", X"ff", X"20", X"ea", X"ef", X"e9", X"fe", X"0f", X"ed", X"02", X"36", X"25", X"09", X"bb", X"fa", X"07", X"df", X"e5", X"1c", X"f6", X"2e", X"e3",
                                                        X"c9", X"02", X"0a", X"1d", X"f4", X"1e", X"22", X"dc", X"18", X"50", X"e3", X"f4", X"ff", X"f2", X"32", X"f1", X"48", X"fe", X"f0", X"e1", X"dd", X"df", X"f1", X"b7", X"18", X"d8",
                                                        X"e7", X"04", X"dd", X"2a", X"20", X"fc", X"01", X"04", X"1c", X"e5", X"f6", X"4b", X"15", X"2a", X"0f", X"d7", X"cc", X"09", X"ec", X"46", X"1d", X"fc", X"41", X"13", X"f3", X"dd",
                                                        X"31", X"fe", X"34", X"ca", X"0a", X"09", X"de", X"e6", X"04", X"ff", X"fa", X"ed", X"ef", X"f7", X"ff", X"f9", X"dc", X"09", X"d4", X"e8", X"fc", X"3d", X"de", X"f7", X"d7", X"27",
                                                        X"dc", X"ea", X"0c", X"f5", X"fc", X"d1", X"43", X"2b", X"06", X"00", X"1f", X"47", X"df", X"fb", X"02", X"db", X"16", X"ff", X"ee", X"f7", X"e5", X"d3", X"e8", X"01", X"1b", X"ab",
                                                        X"24", X"39", X"dd", X"fc", X"d8", X"0e", X"23", X"ee", X"f1", X"ed", X"fc", X"f8", X"37", X"d2", X"d9", X"cb", X"23", X"de", X"cb", X"1c", X"e5", X"46", X"2f", X"d3", X"2e", X"06",
                                                        X"07", X"c3", X"1f", X"35", X"0a", X"1d", X"17", X"12", X"d5", X"1a", X"13", X"e1", X"ed", X"f7", X"12", X"00", X"21", X"02", X"06", X"1a", X"f5", X"c8", X"ff", X"ba", X"f6", X"11",
                                                        X"02", X"13", X"fe", X"ea", X"09", X"fc", X"02", X"ec", X"15", X"e5", X"dd", X"01", X"28", X"d0", X"dd", X"06", X"f3", X"3c", X"15", X"ee", X"41", X"f7", X"02", X"db", X"23", X"31",
                                                        X"28", X"bb", X"13", X"c6", X"cc", X"30", X"dc", X"2e", X"07", X"e4", X"4d", X"f5", X"06", X"fa", X"08", X"23", X"d7", X"3f", X"12", X"cf", X"ea", X"fe", X"dd", X"f9", X"0d", X"ef",
                                                        X"3a", X"f4", X"f7", X"d3", X"28", X"2a", X"1c", X"e6", X"20", X"cb", X"ca", X"f9", X"26", X"1d", X"f0", X"f6", X"e4", X"ed", X"04", X"de", X"d2", X"d7", X"11", X"fa", X"1d", X"e9",
                                                        X"da", X"10", X"26", X"30", X"ef", X"fd", X"16", X"f0", X"01", X"ee", X"f9", X"d6", X"25", X"21", X"17", X"0f", X"c5", X"11", X"03", X"09", X"0e", X"fe", X"38", X"f9", X"04", X"d2",
                                                        X"27", X"35", X"cd", X"e8", X"11", X"e6", X"ce", X"0d", X"ef", X"23", X"ef", X"e3", X"b8", X"fe", X"0f", X"e9", X"e9", X"f3", X"10", X"da", X"05", X"b5", X"ca", X"f5", X"24", X"e1",
                                                        X"05", X"e4", X"29", X"ed", X"f6", X"ea", X"43", X"02", X"2d", X"cc", X"10", X"30", X"eb", X"00", X"cc", X"e8", X"15", X"0e", X"4f", X"fd", X"fd", X"d3", X"29", X"e8", X"1e", X"fa",
                                                        X"11", X"3b", X"e9", X"f1", X"d2", X"43", X"16", X"e8", X"4d", X"e7", X"18", X"0e", X"14", X"f9", X"d4", X"bd", X"18", X"c9", X"da", X"fd", X"35", X"e2", X"29", X"e6", X"d6", X"f5",
                                                        X"ed", X"0c", X"fa", X"f4", X"26", X"da", X"0c", X"3d", X"d7", X"05", X"ea", X"22", X"0c", X"01", X"10", X"f3", X"fa", X"e7", X"ff", X"07", X"22", X"ee", X"19", X"d5", X"c3", X"fe",
                                                        X"dd", X"e1", X"20", X"d8", X"41", X"f8", X"fa", X"ec", X"20", X"12", X"21", X"1b", X"20", X"0d", X"b9", X"06", X"1c", X"39", X"32", X"f5");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"f5";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

