-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w8a16/amc_cnn_8w16a_src_SinglePortRAM_generic_block388.vhd
-- Created: 2023-08-07 19:04:44
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_8w16a_src_SinglePortRAM_generic_block388
-- Source Path: amc_model_w8a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage37/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_8w16a_src_SinglePortRAM_generic_block388 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_8w16a_src_SinglePortRAM_generic_block388;


ARCHITECTURE rtl OF amc_cnn_8w16a_src_SinglePortRAM_generic_block388 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"f6", X"01", X"f2", X"09", X"f7", X"02", X"f0", X"e9", X"02", X"0b", X"ed", X"02", X"08", X"05",
                                                        X"0f", X"fd", X"10", X"00", X"0b", X"f7", X"02", X"fc", X"f3", X"05", X"fa", X"02", X"07", X"f5", X"06", X"07", X"10", X"03", X"00", X"ff", X"03", X"0b", X"f1", X"04", X"00", X"00",
                                                        X"f8", X"e9", X"fc", X"e9", X"05", X"04", X"0d", X"fd", X"ee", X"0e", X"13", X"07", X"01", X"ff", X"fa", X"fd", X"ff", X"ef", X"00", X"0b", X"00", X"06", X"15", X"01", X"f4", X"0a",
                                                        X"04", X"0f", X"02", X"01", X"03", X"f8", X"06", X"fa", X"fc", X"06", X"0a", X"0c", X"05", X"f3", X"14", X"f7", X"ff", X"1d", X"f8", X"01", X"02", X"fb", X"f9", X"0d", X"f5", X"12",
                                                        X"04", X"0b", X"08", X"00", X"f9", X"f9", X"ff", X"f8", X"f7", X"05", X"00", X"fa", X"fc", X"fc", X"03", X"fd", X"02", X"00", X"08", X"07", X"f2", X"fb", X"fd", X"04", X"ef", X"14",
                                                        X"fd", X"f5", X"f3", X"fc", X"fc", X"0c", X"ff", X"ff", X"12", X"02", X"f9", X"fd", X"f8", X"ee", X"fb", X"06", X"01", X"f5", X"0f", X"f8", X"fc", X"0f", X"06", X"09", X"09", X"f9",
                                                        X"ff", X"fe", X"f8", X"fe", X"00", X"f7", X"00", X"f1", X"00", X"ed", X"f8", X"02", X"05", X"fd", X"fc", X"f4", X"0b", X"06", X"12", X"f1", X"f8", X"f5", X"f0", X"08", X"08", X"fa",
                                                        X"05", X"03", X"fd", X"fd", X"18", X"f2", X"00", X"05", X"0a", X"03", X"f8", X"08", X"f1", X"fe", X"f4", X"ff", X"fb", X"04", X"06", X"01", X"17", X"04", X"f5", X"f6", X"05", X"f6",
                                                        X"fd", X"f9", X"f4", X"02", X"f7", X"fc", X"f3", X"03", X"01", X"0a", X"11", X"fe", X"e6", X"00", X"05", X"fb", X"08", X"10", X"01", X"f5", X"11", X"fa", X"f3", X"15", X"fe", X"05",
                                                        X"0a", X"f8", X"02", X"05", X"0b", X"0a", X"01", X"0d", X"fe", X"06", X"fd", X"09", X"fa", X"0d", X"f9", X"03", X"07", X"08", X"f9", X"fc", X"fb", X"fd", X"ef", X"00", X"00", X"ef",
                                                        X"09", X"fb", X"fb", X"07", X"05", X"05", X"00", X"06", X"08", X"f8", X"03", X"fe", X"f1", X"ed", X"fb", X"f6", X"f0", X"09", X"02", X"08", X"0d", X"12", X"00", X"f2", X"eb", X"02",
                                                        X"0d", X"03", X"ee", X"0d", X"fe", X"00", X"fa", X"05", X"f5", X"0e", X"fd", X"01", X"19", X"04", X"11", X"06", X"06", X"f2", X"f7", X"fb", X"f7", X"0b", X"fc", X"00", X"fa", X"15",
                                                        X"00", X"06", X"03", X"07", X"ea", X"07", X"09", X"f1", X"fc", X"f7", X"fb", X"08", X"03", X"05", X"f9", X"17", X"07", X"04", X"15", X"05", X"f5", X"09", X"0d", X"02", X"06", X"07",
                                                        X"fa", X"03", X"ff", X"f1", X"fb", X"ff", X"01", X"11", X"03", X"02", X"00", X"07", X"0f", X"08", X"fb", X"fa", X"fc", X"06", X"01", X"f3", X"fd", X"00", X"08", X"06", X"12", X"03",
                                                        X"0c", X"fc", X"02", X"03", X"02", X"fc", X"f6", X"13", X"fc", X"03", X"f7", X"17", X"00", X"0a", X"03", X"08", X"f2", X"01", X"06", X"f5", X"00", X"f4", X"f7", X"00", X"04", X"f4",
                                                        X"fc", X"07", X"08", X"0d", X"0f", X"fa", X"f8", X"fe", X"02", X"02", X"f5", X"fd", X"fb", X"fa", X"ee", X"fe", X"f3", X"02", X"fe", X"06", X"0e", X"ef", X"f5", X"02", X"fd", X"ff",
                                                        X"f3", X"0d", X"ff", X"0a", X"f5", X"06", X"04", X"0e", X"02", X"06", X"1a", X"f7", X"05", X"03", X"ff", X"09", X"fc", X"fe", X"f9", X"04", X"fc", X"fa", X"fe", X"ff", X"0d", X"08",
                                                        X"14", X"f7", X"f9", X"0d", X"f9", X"0c", X"fc", X"fc", X"01", X"fa", X"04", X"ef", X"f7", X"fc", X"08", X"05", X"06", X"02", X"f1", X"f8", X"fc", X"08", X"00", X"0a", X"ff", X"03",
                                                        X"04", X"00", X"ec", X"16", X"05", X"03", X"01", X"f8", X"f7", X"fd", X"03", X"fd", X"03", X"09", X"fc", X"fa", X"f9", X"fc", X"ef", X"f5", X"00", X"10", X"05", X"09", X"f8", X"f4",
                                                        X"f9", X"06", X"f8", X"f5", X"f1", X"02", X"01", X"fa", X"f8", X"ff", X"ff", X"ff", X"0f", X"0b", X"02", X"04", X"06", X"f9", X"08", X"04", X"f7", X"0d", X"f4", X"f5", X"f9", X"0f",
                                                        X"11", X"fc", X"17", X"f9", X"f3", X"fe", X"fe", X"f9", X"ea", X"05", X"fc", X"f6", X"07", X"02", X"fa", X"19", X"09", X"08", X"18", X"f7", X"eb", X"0d", X"07", X"ef", X"f9", X"05",
                                                        X"fe", X"0e", X"03", X"03", X"00", X"fc", X"03", X"00", X"fe", X"00", X"14", X"04", X"05", X"f8", X"ef", X"07", X"fa", X"f3", X"fd", X"f9", X"fa", X"ff", X"fe", X"0e", X"0a", X"05",
                                                        X"ec", X"08", X"08", X"02", X"f2", X"0b", X"fa", X"f4", X"00", X"fe", X"02", X"0c", X"fc", X"06", X"06", X"00", X"06", X"0b", X"f9", X"fa", X"f2", X"07", X"fa", X"ec", X"06", X"fb",
                                                        X"ee", X"0b", X"fd", X"03", X"03", X"ff", X"01", X"fa", X"fc", X"00", X"01", X"07", X"05", X"ec", X"03", X"ee", X"e8", X"04", X"00", X"04", X"fe", X"02", X"e6", X"fb", X"01", X"02",
                                                        X"f2", X"0f", X"f6", X"06", X"01", X"fe", X"f8", X"11", X"01", X"03", X"09", X"fb", X"01", X"ff", X"05", X"f4", X"00", X"fd", X"ff", X"f1", X"0a", X"02", X"fe", X"0b", X"fc", X"08",
                                                        X"03", X"fb", X"fe", X"08", X"fb", X"fc", X"08", X"01", X"05", X"0c", X"10", X"0e", X"03", X"02", X"fd", X"04", X"06", X"f0", X"f4", X"07", X"0e", X"09", X"ed", X"0f", X"05", X"e4",
                                                        X"ff", X"0c", X"0b", X"1c", X"02", X"0d", X"01", X"fa", X"f7", X"fc", X"09", X"03", X"ee", X"04", X"00", X"0b", X"13", X"07", X"fe", X"1a", X"01", X"fd", X"06", X"f0", X"00", X"08",
                                                        X"ff", X"f4", X"fb", X"0e", X"07", X"ec", X"ff", X"fc", X"fd", X"fd", X"f8", X"03", X"f0", X"02", X"f2", X"00", X"fa", X"fc", X"10", X"0d", X"02", X"02", X"01", X"fd", X"ec", X"f4",
                                                        X"01", X"fd", X"08", X"fd", X"04", X"0a", X"ff", X"01", X"fe", X"10", X"ff", X"fb", X"f7", X"09", X"ee", X"02", X"f8", X"0f", X"f9", X"fd", X"fa", X"04", X"0d", X"06", X"08", X"04",
                                                        X"ff", X"e8", X"05", X"00", X"fb", X"fa", X"f7", X"10", X"05", X"06", X"00", X"ff", X"02", X"ea", X"0e", X"0a", X"06", X"11", X"fe", X"13", X"f4", X"0c", X"ff", X"02", X"01", X"fd",
                                                        X"ef", X"02", X"ff", X"07", X"fa", X"08", X"fd", X"10", X"01", X"f9", X"eb", X"fe", X"f7", X"0b", X"fc", X"04", X"08", X"fc", X"ff", X"f1", X"e7", X"0c", X"03", X"fd", X"f5", X"f7",
                                                        X"f5", X"06", X"00", X"fd", X"01", X"00", X"13", X"f3", X"ee", X"ec", X"f2", X"14", X"00", X"07", X"04", X"f2", X"f7", X"09", X"ff", X"f5", X"0a", X"0f", X"18", X"05", X"fd", X"fc",
                                                        X"fc", X"11", X"ff", X"fd", X"09", X"eb", X"f2", X"07", X"f6", X"16", X"fd", X"fa", X"0e", X"01", X"fc", X"f5", X"00", X"11", X"0f", X"0c", X"ff", X"00", X"ef", X"ee", X"f0", X"12",
                                                        X"ee", X"f4", X"e9", X"f6", X"04", X"ee", X"fa", X"0d", X"09", X"01", X"0d", X"fa", X"f6", X"0b", X"00", X"06", X"03", X"0a", X"14", X"05", X"fd", X"fb", X"00", X"09", X"09", X"f7",
                                                        X"f4", X"ff", X"f2", X"f8", X"01", X"09", X"f4", X"fa", X"12", X"09", X"00", X"01", X"ff", X"0c", X"06", X"fd", X"09", X"01", X"fd", X"14", X"fe", X"08", X"ee", X"fb", X"12", X"00",
                                                        X"06", X"ea", X"00", X"1c", X"10", X"fd", X"04", X"f7", X"f9", X"16", X"f3", X"04", X"ea", X"09", X"e5", X"fe", X"06", X"fe", X"0d", X"0c", X"09", X"00", X"06", X"fe", X"fd", X"11",
                                                        X"f2", X"11", X"e5", X"1e", X"fb", X"f6", X"06", X"fb", X"04", X"17", X"08", X"ef", X"f0", X"f4", X"f2", X"07", X"f8", X"12", X"e1", X"01", X"12", X"0e", X"0d", X"ed", X"fa", X"20",
                                                        X"0b", X"f9", X"14", X"f7", X"f7", X"eb", X"fa", X"01", X"0e", X"ff", X"f2", X"04", X"00", X"f7", X"fd", X"1f", X"14", X"05", X"f6", X"f4", X"ff", X"ff", X"ec", X"12", X"f6", X"00",
                                                        X"02", X"f7", X"01", X"f3", X"f5", X"1f", X"0f", X"05", X"fe", X"f6", X"f7", X"0c", X"ed", X"07", X"f3", X"14", X"0b", X"00", X"00", X"ef", X"fa", X"27", X"03", X"02", X"f6", X"fe",
                                                        X"f6", X"04", X"e5", X"f1", X"e9", X"15", X"fb", X"ff", X"09", X"01", X"fb", X"19", X"fc", X"f0", X"fa", X"fd", X"e8", X"03", X"fd", X"0f", X"f6", X"01", X"ff", X"05", X"fd", X"fe",
                                                        X"fb", X"0c", X"14", X"ff", X"08", X"f7", X"f0", X"06", X"f1", X"0c", X"e3", X"03", X"fe", X"f5", X"03", X"fa", X"f3", X"23", X"16", X"0c", X"ea", X"f4", X"fd", X"ed", X"ed", X"fc",
                                                        X"ef", X"1b", X"07", X"f5", X"f8", X"fa", X"f9", X"1a", X"0b", X"0a", X"02", X"fc", X"ff", X"05", X"f2", X"f6", X"ef", X"07", X"01", X"04", X"f9", X"f2", X"fc", X"15", X"0b", X"f1",
                                                        X"f4", X"ee", X"f5", X"06", X"df", X"f3", X"f0", X"03", X"f9", X"ff", X"03", X"f1", X"f2", X"16", X"0b", X"05", X"f2", X"fe", X"f5", X"fc", X"ea", X"ff", X"dc", X"01", X"fc", X"0a",
                                                        X"fd", X"0d", X"ff", X"10", X"0e", X"f5", X"ed", X"fc", X"fe", X"da", X"f3", X"12", X"e1", X"ff", X"f5", X"02", X"16", X"0b", X"fb", X"13", X"0f", X"01", X"ed", X"e9", X"03", X"e5",
                                                        X"ec", X"03", X"e9", X"0a", X"f2", X"0a", X"f9", X"08", X"fb", X"11", X"0d", X"f6", X"fe", X"ed", X"f7", X"0e", X"f9", X"19", X"eb", X"08", X"09", X"0e", X"ff", X"fc", X"f7", X"13",
                                                        X"09", X"03", X"06", X"09", X"09", X"09", X"f2", X"05", X"ec", X"00", X"0f", X"03", X"fc", X"0c", X"f0", X"18", X"10", X"09", X"04", X"05", X"02", X"fe", X"f2", X"09", X"fb", X"f8",
                                                        X"17", X"00", X"04", X"f9", X"f6", X"21", X"12", X"04", X"fc", X"f7", X"00", X"ef", X"05", X"0a", X"04", X"fe", X"12", X"fe", X"05", X"06", X"f1", X"12", X"08", X"f3", X"f1", X"06",
                                                        X"f8", X"f1", X"f4", X"fb", X"f7", X"03", X"11", X"fd", X"04", X"0d", X"fb", X"0d", X"0e", X"ff", X"ee", X"ef", X"f5", X"ec", X"f3", X"07", X"f4", X"08", X"e9", X"02", X"00", X"09",
                                                        X"0a", X"14", X"05", X"0b", X"f7", X"f7", X"f0", X"01", X"f2", X"04", X"fa", X"02", X"12", X"f3", X"00", X"f9", X"01", X"15", X"0b", X"f4", X"fe", X"f9", X"fb", X"06", X"f5", X"04",
                                                        X"ee", X"fc", X"07", X"fd", X"07", X"f8", X"02", X"1b", X"08", X"09", X"09", X"fe", X"02", X"09", X"f7", X"07", X"fb", X"00", X"15", X"03", X"08", X"06", X"0b", X"13", X"0d", X"06",
                                                        X"fa", X"f4", X"f0", X"f4", X"fd", X"07", X"00", X"02", X"ff", X"ff", X"06", X"03", X"fb", X"06", X"04", X"f2", X"fd", X"eb", X"f7", X"f8", X"00", X"0b", X"fa", X"0c", X"0f", X"fd",
                                                        X"ff", X"fd", X"ff", X"fc", X"fc", X"ff", X"f9", X"f7", X"fc", X"fb", X"09", X"f9", X"01", X"05", X"11", X"fa", X"06", X"0e", X"06", X"07", X"04", X"f6", X"fd", X"09", X"fe", X"0d",
                                                        X"ff", X"04", X"fc", X"fd", X"fd", X"04", X"fd", X"fa", X"07", X"09", X"02", X"0d", X"f8", X"f6", X"f2", X"ff", X"fc", X"ff", X"08", X"fb", X"eb", X"fc", X"ff", X"fc", X"08", X"0a",
                                                        X"0a", X"00", X"fa", X"f8", X"ea", X"f7", X"f6", X"01", X"f7", X"06", X"f3", X"04", X"fc", X"07", X"00", X"05", X"01", X"fd", X"10", X"02", X"fd", X"f0", X"f9", X"00", X"05", X"fb",
                                                        X"0f", X"fd", X"ff", X"06", X"fc", X"02", X"03", X"01", X"03", X"f7", X"f0", X"06", X"fd", X"01", X"08", X"fc", X"1a", X"05", X"00", X"0f", X"02", X"03", X"fb", X"f9", X"02", X"f5",
                                                        X"f4", X"0b", X"06", X"06", X"05", X"09", X"ec", X"fa", X"0c", X"01", X"f1", X"f7", X"fa", X"f8", X"02", X"fa", X"f4", X"01", X"02", X"03", X"0d", X"12", X"fe", X"04", X"08", X"f4",
                                                        X"f7", X"05", X"fe", X"f4", X"ff", X"f8", X"01", X"f3", X"07", X"15", X"11", X"fe", X"16", X"fb", X"03", X"03", X"0a", X"1c", X"0a", X"11", X"fb", X"fc", X"f6", X"f4", X"05", X"05",
                                                        X"13", X"0f", X"fc", X"01", X"ff", X"08", X"f4", X"11", X"fc", X"f7", X"f4", X"00", X"f5", X"fc", X"f8", X"05", X"08", X"04", X"fe", X"05", X"0c", X"f9", X"08", X"03", X"fb", X"08",
                                                        X"0a", X"f1", X"f9", X"fd", X"01", X"f7", X"0d", X"01", X"f0", X"09", X"fe", X"03", X"04", X"01", X"04", X"08", X"04", X"0a", X"e8", X"f5", X"08", X"02", X"0b", X"10", X"fd", X"05",
                                                        X"0f", X"fb", X"05", X"f8", X"ff", X"05", X"09", X"fc", X"f3", X"05", X"0a", X"00", X"16", X"03", X"fa", X"ff", X"fd", X"07", X"05", X"03", X"f9", X"08", X"f9", X"02", X"f0", X"12",
                                                        X"07", X"11", X"06", X"0b", X"fc", X"fa", X"fd", X"fd", X"ea", X"fc", X"f3", X"04", X"04", X"05", X"01", X"0e", X"05", X"08", X"0f", X"f8", X"f1", X"04", X"06", X"12", X"e9", X"f8",
                                                        X"f5", X"f1", X"f6", X"f9", X"fc", X"06", X"01", X"02", X"0e", X"08", X"f5", X"06", X"11", X"11", X"0c", X"ff", X"f5", X"f6", X"f8", X"0b", X"f6", X"00", X"0b", X"07", X"16", X"ff",
                                                        X"09", X"04", X"09", X"05", X"0b", X"0a", X"fe", X"fa", X"fa", X"e9", X"04", X"f7", X"09", X"f9", X"1b", X"07", X"16", X"02", X"01", X"fc", X"fd", X"f7", X"ec", X"f8", X"f2", X"06",
                                                        X"fc", X"f8", X"fd", X"07", X"18", X"04", X"18", X"01", X"f3", X"05", X"f3", X"fa", X"f6", X"fa", X"f5", X"f4", X"f7", X"00", X"07", X"0c", X"07", X"fe", X"e3", X"fc", X"f8", X"00",
                                                        X"03", X"f7", X"f0", X"01", X"ff", X"06", X"f3", X"08", X"0f", X"13", X"03", X"fe", X"f6", X"00", X"fc", X"fd", X"f0", X"03", X"fa", X"f4", X"0a", X"fc", X"fd", X"fe", X"07", X"01",
                                                        X"08", X"f0", X"05", X"05", X"05", X"08", X"02", X"f4", X"f7", X"fc", X"ff", X"f8", X"02", X"0e", X"0e", X"12", X"0f", X"fa", X"f7", X"0a", X"04", X"fc", X"fb", X"f4", X"f4", X"01",
                                                        X"02", X"03", X"02", X"01", X"12", X"09", X"11", X"05", X"06", X"fc", X"09", X"fe", X"e7", X"f0", X"f6", X"fb", X"fa", X"03", X"02", X"0e", X"0e", X"06", X"12", X"01", X"fb", X"03",
                                                        X"00", X"10", X"fc", X"f4", X"f8", X"0b", X"01", X"0b", X"f4", X"07", X"0e", X"04", X"11", X"03", X"f6", X"03", X"08", X"0f", X"03", X"fd", X"f6", X"f9", X"02", X"06", X"f3", X"f6",
                                                        X"0d", X"08", X"09", X"01", X"f9", X"fc", X"04", X"06", X"09", X"f8", X"f1", X"fc", X"f7", X"f8", X"f6", X"06", X"fc", X"f4", X"0e", X"02", X"e9", X"07", X"01", X"fc", X"f8", X"05",
                                                        X"f6", X"11", X"04", X"fc", X"f8", X"03", X"08", X"f8", X"13", X"05", X"ff", X"01", X"05", X"0f", X"0b", X"ff", X"fc", X"f8", X"0a", X"ff", X"fc", X"0c", X"ff", X"05", X"0f", X"fb",
                                                        X"00", X"04", X"01", X"fd", X"fd", X"09", X"01", X"04", X"01", X"06", X"f9", X"01", X"01", X"fb", X"01", X"fd", X"09", X"f5", X"08", X"01", X"e2", X"ee", X"e9", X"ee", X"f8", X"ff",
                                                        X"ff", X"f9", X"05", X"f6", X"0e", X"fe", X"f4", X"08", X"f0", X"fc", X"f8", X"f6", X"f0", X"04", X"ff", X"06", X"05", X"0a", X"06", X"00", X"11", X"04", X"06", X"0a", X"05", X"fe",
                                                        X"ef", X"f1", X"f3", X"f9", X"07", X"01", X"01", X"09", X"0b", X"fe", X"11", X"fb", X"01", X"fb", X"09", X"f3", X"fa", X"fa", X"ff", X"03", X"fa", X"04", X"f5", X"13", X"0e", X"07",
                                                        X"12", X"02", X"f7", X"0b", X"08", X"01", X"ee", X"ff", X"f8", X"f5", X"f8", X"02", X"fb", X"03", X"03", X"09", X"0e", X"0b", X"f3", X"01", X"07", X"ff", X"f6", X"06", X"ff", X"f7",
                                                        X"fa", X"fb", X"f7", X"0c", X"00", X"09", X"11", X"fc", X"05", X"00", X"01", X"03", X"e3", X"fb", X"f9", X"0d", X"08", X"0f", X"f8", X"04", X"fa", X"fd", X"04", X"fd", X"f4", X"ff",
                                                        X"12", X"f1", X"f8", X"f4", X"fb", X"fd", X"07", X"f9", X"fe", X"08", X"fe", X"0f", X"ff", X"fd", X"f7", X"f6", X"05", X"12", X"02", X"f9", X"00", X"07", X"f1", X"07", X"ef", X"13",
                                                        X"0a", X"07", X"10", X"fa", X"14", X"fc", X"f7", X"03", X"fe", X"fa", X"f3", X"f5", X"00", X"f5", X"f7", X"25", X"10", X"03", X"17", X"fc");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"fc";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

