-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/model_qat_2x2_w8a16/amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block450.vhd
-- Created: 2025-02-27 23:58:54
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block450
-- Source Path: model_qat_2x2_w8a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage93/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block450 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block450;


ARCHITECTURE rtl OF amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block450 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"26", X"24", X"e5", X"00", X"ff", X"e5", X"01", X"0a", X"ff", X"09", X"10", X"eb", X"f8", X"1b",
                                                        X"fa", X"1b", X"17", X"22", X"e4", X"f9", X"f3", X"02", X"0e", X"ea", X"fa", X"f3", X"05", X"f8", X"f6", X"0c", X"fc", X"09", X"0d", X"0b", X"e6", X"02", X"e4", X"05", X"f3", X"ef",
                                                        X"fc", X"fd", X"14", X"f1", X"fa", X"0b", X"f4", X"ff", X"fa", X"10", X"ed", X"11", X"f6", X"0f", X"16", X"ee", X"00", X"fb", X"f2", X"0f", X"f3", X"03", X"03", X"10", X"f0", X"10",
                                                        X"ee", X"07", X"0d", X"16", X"04", X"05", X"fd", X"06", X"15", X"0e", X"ef", X"0e", X"0b", X"07", X"f7", X"25", X"f2", X"fc", X"00", X"14", X"f9", X"f6", X"ea", X"ff", X"13", X"fc",
                                                        X"f8", X"10", X"fc", X"0c", X"e8", X"12", X"f6", X"07", X"fa", X"15", X"e9", X"ef", X"e8", X"ec", X"04", X"06", X"fc", X"0f", X"06", X"06", X"e6", X"0d", X"f5", X"fd", X"f2", X"1b",
                                                        X"04", X"f5", X"f4", X"0e", X"12", X"08", X"fa", X"1a", X"10", X"f9", X"ee", X"13", X"f6", X"fc", X"f7", X"20", X"08", X"07", X"fd", X"fd", X"04", X"01", X"fb", X"1f", X"1d", X"02",
                                                        X"f0", X"03", X"f9", X"ea", X"f7", X"10", X"ec", X"14", X"00", X"01", X"0f", X"0a", X"04", X"0a", X"0d", X"f7", X"f1", X"11", X"f6", X"ee", X"ff", X"02", X"f6", X"13", X"f8", X"03",
                                                        X"f9", X"fc", X"02", X"09", X"01", X"f8", X"f9", X"15", X"fe", X"ea", X"01", X"fb", X"ee", X"03", X"f7", X"04", X"02", X"ee", X"09", X"fc", X"f9", X"f2", X"ff", X"0d", X"f6", X"f6",
                                                        X"0b", X"02", X"f5", X"01", X"fd", X"02", X"08", X"00", X"0b", X"f9", X"00", X"00", X"06", X"19", X"f7", X"f4", X"0a", X"f5", X"f5", X"05", X"08", X"06", X"f1", X"07", X"00", X"0d",
                                                        X"f6", X"f8", X"1d", X"1b", X"f9", X"02", X"09", X"01", X"12", X"fe", X"07", X"16", X"fd", X"0a", X"fd", X"05", X"fd", X"0d", X"14", X"23", X"ee", X"fc", X"f5", X"e1", X"14", X"06",
                                                        X"04", X"13", X"14", X"07", X"fc", X"0d", X"fe", X"01", X"20", X"16", X"f4", X"00", X"fb", X"f7", X"f7", X"19", X"f7", X"ef", X"1c", X"06", X"fc", X"09", X"fd", X"06", X"1d", X"09",
                                                        X"fb", X"1c", X"ff", X"fa", X"f2", X"10", X"f8", X"ff", X"f2", X"05", X"fb", X"19", X"03", X"03", X"15", X"1d", X"f4", X"0a", X"ef", X"ef", X"e9", X"fd", X"04", X"f0", X"0a", X"f0",
                                                        X"fb", X"15", X"f9", X"fb", X"05", X"0a", X"f8", X"04", X"fe", X"1c", X"e9", X"00", X"f2", X"f1", X"1a", X"0b", X"f6", X"fc", X"f9", X"f9", X"fb", X"27", X"e6", X"0c", X"ee", X"13",
                                                        X"fd", X"09", X"f2", X"fe", X"f0", X"f7", X"00", X"19", X"01", X"05", X"e7", X"2e", X"f1", X"ff", X"e4", X"1d", X"16", X"0a", X"f0", X"0c", X"f9", X"fc", X"f7", X"0c", X"fd", X"fe",
                                                        X"e0", X"10", X"e6", X"02", X"f4", X"31", X"0c", X"ff", X"eb", X"01", X"05", X"01", X"f5", X"2e", X"0f", X"01", X"d6", X"1b", X"f0", X"f9", X"fc", X"1e", X"07", X"11", X"fc", X"ed",
                                                        X"f9", X"f2", X"f8", X"19", X"09", X"f0", X"e3", X"07", X"f0", X"f6", X"ff", X"1c", X"f8", X"03", X"f2", X"0c", X"12", X"fb", X"f0", X"0f", X"07", X"03", X"ed", X"0d", X"fc", X"f0",
                                                        X"fc", X"0e", X"02", X"01", X"ed", X"0e", X"04", X"f3", X"fe", X"10", X"04", X"03", X"ec", X"0a", X"f8", X"f8", X"f5", X"09", X"0b", X"02", X"02", X"0f", X"f4", X"04", X"01", X"0d",
                                                        X"09", X"fb", X"e8", X"15", X"fb", X"f6", X"07", X"02", X"fd", X"fb", X"fa", X"09", X"13", X"fc", X"f6", X"fa", X"08", X"f8", X"0d", X"0c", X"00", X"fc", X"ff", X"f2", X"d5", X"ff",
                                                        X"0d", X"00", X"f5", X"d1", X"ff", X"14", X"f6", X"f3", X"11", X"19", X"f0", X"fc", X"00", X"f2", X"ff", X"f5", X"09", X"fd", X"f9", X"f5", X"06", X"0f", X"f6", X"02", X"13", X"00",
                                                        X"f0", X"f9", X"14", X"f4", X"09", X"e4", X"03", X"0e", X"f4", X"01", X"00", X"0e", X"fa", X"0f", X"16", X"0b", X"f0", X"05", X"02", X"f2", X"08", X"f5", X"08", X"fe", X"f7", X"f5",
                                                        X"ff", X"f3", X"05", X"06", X"17", X"01", X"f5", X"03", X"ec", X"f8", X"d6", X"ef", X"fd", X"f9", X"20", X"ee", X"f9", X"0c", X"fe", X"0b", X"10", X"21", X"e8", X"fe", X"07", X"fa",
                                                        X"08", X"0b", X"01", X"0e", X"00", X"f9", X"fc", X"f8", X"01", X"13", X"0b", X"1e", X"ee", X"05", X"04", X"02", X"e9", X"0b", X"fd", X"fe", X"0b", X"0c", X"fe", X"fd", X"03", X"0b",
                                                        X"f2", X"19", X"e9", X"f5", X"f1", X"19", X"01", X"02", X"fd", X"ef", X"f6", X"f2", X"eb", X"05", X"fb", X"f0", X"f4", X"0f", X"e7", X"0f", X"01", X"0c", X"ff", X"04", X"fc", X"0b",
                                                        X"0c", X"fe", X"ea", X"0b", X"11", X"00", X"f5", X"15", X"f9", X"f8", X"f4", X"19", X"ff", X"0a", X"fa", X"fb", X"f6", X"ee", X"f6", X"04", X"03", X"f6", X"e4", X"1d", X"e3", X"12",
                                                        X"f8", X"1b", X"01", X"12", X"f1", X"07", X"f3", X"01", X"f2", X"0a", X"0a", X"03", X"e7", X"13", X"f3", X"00", X"f4", X"1a", X"0a", X"f4", X"f6", X"fd", X"04", X"05", X"f0", X"0a",
                                                        X"11", X"f6", X"e6", X"11", X"ee", X"fb", X"ff", X"19", X"fe", X"f9", X"f1", X"f7", X"f0", X"06", X"eb", X"05", X"1d", X"ff", X"f2", X"0f", X"e6", X"f8", X"f6", X"19", X"0b", X"01",
                                                        X"f9", X"00", X"f2", X"11", X"f9", X"10", X"05", X"01", X"ea", X"15", X"ff", X"f6", X"0a", X"05", X"0b", X"f9", X"fe", X"09", X"fb", X"04", X"f5", X"f3", X"03", X"f2", X"f5", X"18",
                                                        X"f3", X"f9", X"ff", X"fd", X"07", X"f1", X"fd", X"ee", X"0f", X"06", X"fe", X"fe", X"06", X"f9", X"fc", X"14", X"ee", X"f3", X"0d", X"e9", X"06", X"f3", X"fd", X"01", X"06", X"f6",
                                                        X"fe", X"fd", X"ef", X"fa", X"11", X"20", X"f0", X"fd", X"0c", X"eb", X"0e", X"00", X"09", X"15", X"0a", X"07", X"06", X"01", X"f5", X"04", X"15", X"1a", X"e3", X"f2", X"07", X"eb",
                                                        X"fb", X"f6", X"08", X"00", X"0b", X"04", X"f8", X"0d", X"f9", X"0e", X"13", X"1e", X"fd", X"f6", X"ff", X"f2", X"08", X"f8", X"01", X"03", X"04", X"10", X"fb", X"04", X"fb", X"13",
                                                        X"1c", X"0d", X"ed", X"06", X"01", X"fb", X"0b", X"0a", X"01", X"f1", X"02", X"03", X"fc", X"f9", X"05", X"08", X"10", X"2a", X"f2", X"f1", X"f6", X"f4", X"0c", X"00", X"fc", X"0a",
                                                        X"fc", X"01", X"fe", X"e6", X"f8", X"fc", X"04", X"14", X"f8", X"0a", X"f2", X"03", X"0d", X"05", X"fb", X"02", X"0b", X"f8", X"f3", X"1a", X"f9", X"f8", X"02", X"0e", X"ec", X"0a",
                                                        X"f5", X"12", X"14", X"fb", X"ef", X"f0", X"15", X"f2", X"f5", X"1e", X"0a", X"f3", X"01", X"0c", X"f2", X"0a", X"ed", X"26", X"e5", X"f6", X"f5", X"fb", X"fd", X"09", X"06", X"00",
                                                        X"0b", X"02", X"ec", X"fe", X"ee", X"08", X"f1", X"27", X"08", X"00", X"f8", X"f5", X"f2", X"12", X"f8", X"03", X"02", X"f2", X"e9", X"0b", X"e7", X"09", X"e7", X"11", X"f8", X"fe",
                                                        X"e9", X"f7", X"06", X"fa", X"fb", X"fa", X"08", X"f6", X"e8", X"1a", X"e0", X"f8", X"f9", X"24", X"15", X"f1", X"e7", X"0d", X"f6", X"f2", X"07", X"04", X"04", X"01", X"df", X"11",
                                                        X"fc", X"03", X"fb", X"21", X"fb", X"f7", X"eb", X"f9", X"01", X"fc", X"02", X"02", X"fb", X"f0", X"e0", X"0c", X"fa", X"eb", X"fd", X"02", X"fa", X"07", X"0d", X"03", X"0b", X"ed",
                                                        X"fa", X"0b", X"06", X"f5", X"d9", X"0a", X"fd", X"f2", X"0e", X"0c", X"0e", X"ff", X"fe", X"09", X"f7", X"fe", X"00", X"09", X"0c", X"03", X"f3", X"13", X"ee", X"f2", X"fd", X"f0",
                                                        X"01", X"f5", X"08", X"fd", X"08", X"08", X"fe", X"f9", X"0d", X"ee", X"04", X"15", X"f8", X"ee", X"07", X"01", X"f2", X"f3", X"0e", X"ff", X"f6", X"03", X"00", X"10", X"ff", X"fd",
                                                        X"07", X"07", X"eb", X"06", X"16", X"f7", X"de", X"02", X"03", X"0d", X"0b", X"05", X"fa", X"0f", X"03", X"fb", X"1e", X"0d", X"fd", X"09", X"10", X"e0", X"ed", X"0f", X"0a", X"0d",
                                                        X"1a", X"00", X"f7", X"15", X"fd", X"09", X"21", X"17", X"f2", X"fa", X"ec", X"ef", X"fb", X"0d", X"fc", X"eb", X"11", X"08", X"00", X"03", X"f5", X"07", X"19", X"0e", X"f7", X"08",
                                                        X"05", X"ec", X"fd", X"1c", X"07", X"06", X"15", X"f2", X"fa", X"0a", X"f1", X"08", X"16", X"0f", X"f2", X"fb", X"f8", X"f3", X"02", X"01", X"02", X"f4", X"09", X"03", X"f4", X"10",
                                                        X"ea", X"05", X"0f", X"11", X"ec", X"0a", X"f4", X"01", X"0c", X"04", X"09", X"fd", X"f3", X"00", X"ff", X"0a", X"ff", X"04", X"03", X"10", X"ed", X"fc", X"e8", X"14", X"18", X"01",
                                                        X"fe", X"f8", X"fd", X"fa", X"ec", X"11", X"fe", X"f6", X"f0", X"0f", X"f4", X"0b", X"09", X"1e", X"0e", X"fb", X"f6", X"05", X"0c", X"11", X"eb", X"0f", X"07", X"03", X"ff", X"05",
                                                        X"e7", X"03", X"f5", X"1c", X"08", X"f1", X"f1", X"fd", X"10", X"fa", X"f8", X"08", X"05", X"f9", X"ec", X"12", X"ef", X"07", X"fe", X"1c", X"06", X"f8", X"f6", X"f0", X"04", X"f6",
                                                        X"fa", X"fd", X"0f", X"f6", X"ef", X"05", X"fb", X"05", X"f3", X"20", X"fc", X"06", X"f7", X"e2", X"07", X"18", X"f8", X"0b", X"07", X"fc", X"f2", X"15", X"08", X"02", X"00", X"23",
                                                        X"eb", X"06", X"f7", X"05", X"0a", X"15", X"fc", X"08", X"09", X"ff", X"f1", X"08", X"f3", X"f1", X"11", X"0a", X"f5", X"0f", X"f5", X"0c", X"0d", X"f7", X"f8", X"21", X"0d", X"0f",
                                                        X"e2", X"1a", X"f3", X"f2", X"01", X"1d", X"fc", X"00", X"fc", X"ef", X"12", X"01", X"0c", X"0a", X"12", X"01", X"ec", X"0e", X"f5", X"ef", X"0a", X"00", X"e5", X"fd", X"f9", X"fa",
                                                        X"14", X"02", X"04", X"08", X"fb", X"01", X"00", X"0a", X"fc", X"ea", X"06", X"10", X"f8", X"fe", X"0d", X"f7", X"00", X"04", X"07", X"02", X"06", X"fc", X"0a", X"12", X"e5", X"e4",
                                                        X"10", X"f3", X"fc", X"04", X"0b", X"17", X"f0", X"00", X"fd", X"06", X"01", X"14", X"1f", X"17", X"e5", X"ef", X"fd", X"de", X"09", X"f8", X"04", X"fa", X"03", X"00", X"fd", X"14",
                                                        X"fa", X"fd", X"16", X"12", X"e4", X"fc", X"01", X"01", X"fa", X"fd", X"06", X"03", X"16", X"ec", X"fd", X"0e", X"f8", X"01", X"18", X"1a", X"fa", X"fc", X"fb", X"06", X"f1", X"fc",
                                                        X"07", X"02", X"04", X"02", X"f8", X"03", X"f7", X"0e", X"17", X"0a", X"ed", X"f5", X"fc", X"f8", X"fe", X"13", X"f7", X"11", X"0f", X"01", X"f9", X"0d", X"f1", X"10", X"08", X"19",
                                                        X"f3", X"02", X"f5", X"ff", X"ff", X"06", X"02", X"fd", X"f8", X"0f", X"fd", X"1b", X"02", X"08", X"0a", X"1c", X"f8", X"ff", X"f6", X"0b", X"28", X"f7", X"02", X"f6", X"12", X"fc",
                                                        X"fe", X"19", X"06", X"04", X"0d", X"21", X"ef", X"07", X"f3", X"13", X"05", X"f7", X"f4", X"ed", X"09", X"0a", X"fc", X"1d", X"00", X"f9", X"f9", X"16", X"ed", X"18", X"f9", X"12",
                                                        X"e3", X"f6", X"ed", X"e9", X"09", X"09", X"02", X"1d", X"04", X"f0", X"ed", X"19", X"f3", X"0a", X"eb", X"1e", X"09", X"f3", X"ef", X"ef", X"e8", X"f2", X"ff", X"19", X"07", X"07",
                                                        X"dd", X"15", X"f6", X"fc", X"f8", X"1f", X"f7", X"f2", X"fc", X"e3", X"00", X"0a", X"ef", X"0a", X"14", X"02", X"e8", X"23", X"fa", X"fd", X"f9", X"17", X"22", X"e8", X"f2", X"ee",
                                                        X"f3", X"fb", X"f1", X"1d", X"18", X"fd", X"eb", X"0a", X"f2", X"fa", X"07", X"17", X"f6", X"fb", X"f1", X"05", X"f2", X"00", X"ff", X"fc", X"09", X"fe", X"ec", X"05", X"f9", X"f3",
                                                        X"18", X"0a", X"f0", X"f6", X"f6", X"1a", X"fa", X"03", X"f7", X"09", X"f4", X"03", X"f7", X"16", X"f6", X"f2", X"01", X"0b", X"04", X"09", X"f5", X"07", X"12", X"11", X"fa", X"f9",
                                                        X"01", X"02", X"00", X"22", X"f8", X"fe", X"02", X"fe", X"19", X"07", X"02", X"f1", X"13", X"02", X"00", X"0d", X"03", X"ef", X"0b", X"23", X"f8", X"fa", X"0c", X"f4", X"06", X"04",
                                                        X"fc", X"0b", X"fa", X"13", X"04", X"0c", X"fb", X"f3", X"0c", X"11", X"f1", X"ed", X"00", X"de", X"f1", X"f2", X"16", X"00", X"02", X"ea", X"0c", X"14", X"ee", X"fc", X"1d", X"15",
                                                        X"f9", X"ed", X"02", X"f2", X"00", X"e7", X"00", X"1b", X"f8", X"fa", X"f9", X"15", X"f2", X"0e", X"1f", X"12", X"e5", X"06", X"ff", X"ee", X"eb", X"ee", X"12", X"03", X"16", X"01",
                                                        X"f3", X"15", X"0f", X"14", X"14", X"10", X"ea", X"04", X"03", X"00", X"f5", X"f8", X"fa", X"0d", X"f5", X"09", X"f9", X"12", X"f5", X"13", X"17", X"0b", X"02", X"1f", X"fa", X"04",
                                                        X"1a", X"04", X"fc", X"f8", X"08", X"18", X"fd", X"07", X"02", X"fa", X"17", X"13", X"ec", X"09", X"f0", X"fe", X"0d", X"04", X"f8", X"f3", X"f9", X"02", X"f7", X"0c", X"03", X"03",
                                                        X"08", X"0e", X"f4", X"fd", X"03", X"09", X"f8", X"0a", X"fd", X"04", X"eb", X"eb", X"f4", X"f4", X"fa", X"fe", X"eb", X"07", X"ed", X"0e", X"f2", X"23", X"f4", X"00", X"fd", X"fc",
                                                        X"04", X"05", X"f3", X"0d", X"13", X"f5", X"e8", X"16", X"f8", X"04", X"04", X"22", X"03", X"fb", X"df", X"ed", X"f0", X"fc", X"f9", X"fc", X"09", X"fb", X"f2", X"13", X"ec", X"fa",
                                                        X"ff", X"23", X"0d", X"fa", X"f3", X"0c", X"e7", X"fa", X"07", X"0b", X"0c", X"16", X"fa", X"06", X"f3", X"f4", X"03", X"13", X"03", X"f3", X"f9", X"fc", X"f2", X"07", X"03", X"f5",
                                                        X"05", X"0f", X"e6", X"13", X"02", X"fc", X"04", X"14", X"fe", X"fa", X"f4", X"02", X"09", X"fc", X"01", X"fd", X"05", X"fc", X"f1", X"06", X"fb", X"00", X"05", X"10", X"02", X"12",
                                                        X"f9", X"f6", X"fb", X"0e", X"f5", X"fc", X"0a", X"f4", X"f1", X"0f", X"f5", X"ed", X"07", X"02", X"14", X"0d", X"02", X"0e", X"f6", X"fa", X"04", X"fd", X"f6", X"f7", X"f9", X"16",
                                                        X"ef", X"f6", X"06", X"f8", X"0d", X"0f", X"06", X"fb", X"00", X"fc", X"06", X"fd", X"ff", X"fc", X"0b", X"16", X"00", X"f4", X"09", X"f5", X"f8", X"0d", X"fe", X"ee", X"fc", X"ff",
                                                        X"00", X"08", X"03", X"fd", X"0c", X"1f", X"f6", X"00", X"fd", X"f1", X"f8", X"f9", X"fb", X"ff", X"07", X"09", X"fc", X"08", X"0d", X"0b", X"28", X"13", X"e3", X"fa", X"01", X"f0",
                                                        X"ee", X"fe", X"fd", X"03", X"07", X"0a", X"fe", X"15", X"0b", X"14", X"1d", X"0f", X"f2", X"09", X"fd", X"f6", X"ef", X"01", X"08", X"01", X"f3", X"0b", X"01", X"05", X"fc", X"05",
                                                        X"14", X"24", X"f5", X"0b", X"fa", X"f0", X"01", X"0d", X"fd", X"ea", X"14", X"0d", X"f9", X"13", X"f6", X"07", X"12", X"14", X"f7", X"06", X"f4", X"01", X"fb", X"09", X"f3", X"00",
                                                        X"ff", X"ff", X"ff", X"04", X"ef", X"09", X"f8", X"09", X"e6", X"ff", X"03", X"19", X"f2", X"f6", X"fe", X"04", X"f5", X"10", X"ee", X"f8", X"09", X"07", X"f0", X"16", X"f8", X"0f",
                                                        X"09", X"0a", X"f0", X"02", X"f6", X"fc", X"11", X"fb", X"fe", X"f3", X"fb", X"f3", X"ea", X"15", X"eb", X"fc", X"f5", X"18", X"02", X"02", X"f8", X"f1", X"0e", X"f7", X"f9", X"f0",
                                                        X"f1", X"ff", X"db", X"13", X"e8", X"01", X"05", X"1f", X"fc", X"0e", X"f8", X"18", X"07", X"fd", X"00", X"19", X"fc", X"07", X"e2", X"02", X"ee", X"03", X"ff", X"1e", X"ee", X"02",
                                                        X"f3", X"f4", X"fc", X"00", X"f9", X"fd", X"22", X"fa", X"e0", X"0d", X"ef", X"03", X"08", X"23", X"f4", X"f1", X"e8", X"fe", X"0c", X"03", X"00", X"0c", X"13", X"03", X"d9", X"14",
                                                        X"ee", X"f8", X"0d", X"0c", X"ef", X"fe", X"05", X"f8", X"eb", X"09", X"03", X"0b", X"11", X"ed", X"e3", X"05", X"ea", X"ed", X"05", X"08", X"f2", X"03", X"f4", X"ff", X"f0", X"eb",
                                                        X"fe", X"11", X"0b", X"ff", X"e9", X"18", X"00", X"e3", X"1b", X"18", X"11", X"f5", X"07", X"0a", X"01", X"f1", X"0f", X"12", X"06", X"03");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"03";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

