-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/model_qat_2x2_w8a16/amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block411.vhd
-- Created: 2025-02-27 23:58:50
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block411
-- Source Path: model_qat_2x2_w8a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage58/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block411 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block411;


ARCHITECTURE rtl OF amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block411 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"0c", X"de", X"fa", X"f6", X"01", X"0a", X"05", X"06", X"ea", X"08", X"26", X"fc", X"ed", X"fe",
                                                        X"f7", X"02", X"03", X"e6", X"01", X"0d", X"f5", X"0d", X"f0", X"fe", X"fa", X"f5", X"1a", X"0e", X"f0", X"0b", X"06", X"f7", X"fe", X"ec", X"00", X"04", X"f2", X"ff", X"f9", X"fd",
                                                        X"ff", X"f7", X"ff", X"02", X"ed", X"e7", X"f7", X"f6", X"ef", X"f3", X"09", X"fe", X"ea", X"f6", X"03", X"ee", X"00", X"fb", X"09", X"f8", X"f7", X"ec", X"ef", X"f3", X"ed", X"f8",
                                                        X"0b", X"06", X"e6", X"f3", X"03", X"f6", X"05", X"ec", X"18", X"09", X"ef", X"0a", X"06", X"fd", X"ff", X"f7", X"12", X"fc", X"f1", X"fc", X"fa", X"fc", X"ec", X"f4", X"05", X"0c",
                                                        X"f3", X"fb", X"04", X"f1", X"06", X"e8", X"fa", X"0c", X"fb", X"fb", X"07", X"01", X"f5", X"00", X"11", X"08", X"e9", X"08", X"0d", X"fe", X"03", X"02", X"ff", X"0b", X"ff", X"ec",
                                                        X"0d", X"12", X"e6", X"09", X"10", X"15", X"ee", X"01", X"ff", X"fa", X"0a", X"0d", X"0a", X"0e", X"02", X"f9", X"15", X"12", X"fc", X"04", X"10", X"0c", X"00", X"fa", X"09", X"fe",
                                                        X"0f", X"01", X"14", X"ff", X"fd", X"08", X"1a", X"1b", X"f9", X"08", X"0c", X"fa", X"f6", X"f2", X"f6", X"07", X"fd", X"04", X"09", X"fe", X"f9", X"00", X"0d", X"09", X"fe", X"02",
                                                        X"f3", X"18", X"fc", X"fa", X"fb", X"0a", X"fb", X"06", X"0e", X"e7", X"fe", X"06", X"f7", X"00", X"f8", X"09", X"fb", X"fb", X"fa", X"0b", X"f6", X"08", X"f1", X"fc", X"10", X"f2",
                                                        X"ff", X"11", X"fd", X"02", X"ff", X"0e", X"14", X"0b", X"fa", X"16", X"f4", X"05", X"0c", X"06", X"06", X"ef", X"08", X"ed", X"16", X"11", X"00", X"f8", X"fa", X"fc", X"f9", X"0b",
                                                        X"f8", X"08", X"0b", X"f2", X"fe", X"f2", X"fb", X"eb", X"0f", X"0a", X"fd", X"09", X"17", X"f6", X"f2", X"ff", X"fc", X"04", X"0a", X"fd", X"02", X"f6", X"02", X"0b", X"00", X"06",
                                                        X"f7", X"13", X"0e", X"0e", X"f9", X"08", X"ff", X"12", X"09", X"f6", X"09", X"e5", X"fe", X"09", X"fe", X"0e", X"f1", X"0b", X"15", X"01", X"fb", X"fb", X"f9", X"0e", X"f8", X"05",
                                                        X"f5", X"fb", X"fb", X"f9", X"fc", X"13", X"e4", X"fd", X"0c", X"0b", X"f6", X"0a", X"03", X"05", X"f5", X"09", X"07", X"e4", X"0f", X"04", X"1d", X"01", X"f2", X"06", X"06", X"04",
                                                        X"f7", X"03", X"fa", X"fc", X"f7", X"02", X"06", X"e7", X"f5", X"f1", X"11", X"02", X"f2", X"f4", X"19", X"de", X"ee", X"09", X"f0", X"ef", X"fa", X"08", X"0a", X"f5", X"02", X"fa",
                                                        X"0c", X"0b", X"fc", X"12", X"13", X"0d", X"f7", X"fd", X"fc", X"fd", X"ee", X"0a", X"0a", X"ec", X"f7", X"02", X"f1", X"fe", X"f6", X"02", X"0f", X"e9", X"f0", X"00", X"f7", X"f7",
                                                        X"0a", X"06", X"03", X"fa", X"0d", X"f0", X"f1", X"07", X"fb", X"04", X"21", X"0f", X"fa", X"0b", X"ed", X"fd", X"ec", X"11", X"10", X"0c", X"f1", X"f0", X"fd", X"0a", X"f6", X"f5",
                                                        X"22", X"0e", X"fc", X"07", X"fe", X"f3", X"fe", X"fe", X"0a", X"0b", X"09", X"fe", X"fc", X"02", X"f3", X"06", X"19", X"fd", X"fb", X"ea", X"ff", X"f1", X"00", X"f8", X"fd", X"14",
                                                        X"00", X"fa", X"06", X"fd", X"f9", X"0c", X"17", X"00", X"fc", X"05", X"07", X"fb", X"0f", X"fd", X"0a", X"07", X"f9", X"f4", X"02", X"04", X"fb", X"01", X"2b", X"22", X"fa", X"04",
                                                        X"0a", X"01", X"0f", X"fc", X"fb", X"0d", X"f1", X"f8", X"1b", X"07", X"fe", X"05", X"fd", X"17", X"04", X"02", X"0e", X"02", X"fc", X"fa", X"0a", X"13", X"fb", X"10", X"05", X"08",
                                                        X"f9", X"07", X"0a", X"01", X"01", X"fe", X"06", X"fa", X"00", X"fe", X"0c", X"05", X"f7", X"05", X"09", X"0a", X"fb", X"f8", X"23", X"06", X"00", X"fd", X"f7", X"f6", X"01", X"05",
                                                        X"0b", X"0d", X"f5", X"fc", X"28", X"03", X"fb", X"f6", X"24", X"0a", X"00", X"f6", X"0d", X"00", X"ff", X"fe", X"0b", X"07", X"f8", X"04", X"05", X"fe", X"f6", X"01", X"24", X"07",
                                                        X"04", X"ff", X"fd", X"05", X"08", X"06", X"11", X"0a", X"fa", X"20", X"0c", X"09", X"f7", X"05", X"10", X"03", X"01", X"f2", X"03", X"08", X"fe", X"fa", X"08", X"fb", X"f8", X"08",
                                                        X"04", X"03", X"ff", X"0e", X"04", X"fe", X"f7", X"f6", X"00", X"0e", X"fd", X"f7", X"10", X"f7", X"03", X"13", X"02", X"f6", X"f8", X"09", X"08", X"04", X"f7", X"f9", X"fb", X"04",
                                                        X"07", X"fb", X"06", X"e9", X"0e", X"16", X"09", X"08", X"08", X"23", X"25", X"fe", X"fa", X"09", X"fd", X"12", X"0c", X"03", X"04", X"eb", X"04", X"04", X"05", X"0c", X"f1", X"10",
                                                        X"07", X"e5", X"fc", X"0b", X"fc", X"0f", X"05", X"f9", X"19", X"e8", X"07", X"0c", X"f7", X"0e", X"f1", X"00", X"f4", X"f3", X"f6", X"06", X"03", X"01", X"13", X"ee", X"ff", X"f3",
                                                        X"15", X"eb", X"f8", X"0e", X"03", X"19", X"10", X"fc", X"f3", X"06", X"e9", X"09", X"03", X"ff", X"0d", X"e2", X"02", X"02", X"00", X"16", X"08", X"02", X"1f", X"e5", X"fe", X"f6",
                                                        X"e8", X"f1", X"12", X"06", X"ff", X"04", X"0b", X"f6", X"05", X"1d", X"fb", X"02", X"14", X"f3", X"f9", X"13", X"07", X"03", X"fc", X"fa", X"0c", X"09", X"ff", X"ec", X"04", X"08",
                                                        X"02", X"11", X"13", X"04", X"fc", X"f9", X"05", X"f7", X"0b", X"f2", X"09", X"00", X"ff", X"fc", X"0c", X"0f", X"f9", X"10", X"17", X"00", X"f1", X"06", X"02", X"03", X"15", X"0e",
                                                        X"06", X"0b", X"f2", X"e3", X"11", X"15", X"f2", X"01", X"1a", X"09", X"00", X"fd", X"15", X"fc", X"f1", X"fe", X"f9", X"0d", X"eb", X"f8", X"19", X"12", X"f0", X"03", X"19", X"16",
                                                        X"00", X"f7", X"16", X"00", X"0e", X"e9", X"0d", X"13", X"dc", X"ff", X"15", X"0e", X"06", X"f9", X"07", X"15", X"fc", X"01", X"09", X"f0", X"03", X"f5", X"02", X"06", X"fb", X"f3",
                                                        X"02", X"01", X"0e", X"07", X"16", X"10", X"f9", X"fa", X"09", X"09", X"ff", X"04", X"0e", X"13", X"f9", X"fe", X"02", X"03", X"e0", X"fa", X"ff", X"1a", X"fd", X"04", X"14", X"fa",
                                                        X"fa", X"0b", X"0b", X"12", X"dc", X"05", X"f5", X"ff", X"ed", X"e2", X"04", X"11", X"f1", X"12", X"01", X"ee", X"05", X"00", X"f7", X"11", X"ec", X"01", X"ee", X"13", X"fa", X"f9",
                                                        X"10", X"10", X"f5", X"0a", X"04", X"f6", X"01", X"00", X"ef", X"03", X"f6", X"ee", X"02", X"11", X"f1", X"05", X"13", X"fe", X"f8", X"fc", X"03", X"09", X"f3", X"f9", X"10", X"08",
                                                        X"e1", X"1b", X"19", X"01", X"f7", X"f5", X"09", X"12", X"03", X"fe", X"fe", X"fa", X"fd", X"f4", X"05", X"ff", X"f4", X"0e", X"16", X"f9", X"00", X"0f", X"0f", X"01", X"f1", X"06",
                                                        X"fa", X"0b", X"f7", X"f8", X"01", X"f2", X"05", X"14", X"09", X"f5", X"f2", X"17", X"17", X"06", X"fb", X"0f", X"f8", X"13", X"02", X"f4", X"0d", X"e2", X"15", X"fc", X"f8", X"0b",
                                                        X"fd", X"22", X"10", X"f6", X"ff", X"10", X"f5", X"03", X"14", X"fe", X"11", X"f7", X"10", X"f8", X"0e", X"08", X"04", X"11", X"26", X"02", X"03", X"06", X"fc", X"0a", X"05", X"f9",
                                                        X"08", X"f8", X"0b", X"fc", X"06", X"0d", X"f9", X"07", X"11", X"03", X"02", X"03", X"f7", X"0b", X"0e", X"f4", X"17", X"f6", X"01", X"0f", X"13", X"1b", X"0f", X"06", X"09", X"ec",
                                                        X"03", X"fd", X"f7", X"01", X"f7", X"fd", X"0f", X"e0", X"0b", X"08", X"e9", X"08", X"e6", X"08", X"0a", X"f7", X"03", X"e5", X"fd", X"06", X"fe", X"0a", X"0b", X"e9", X"0d", X"f8",
                                                        X"f4", X"02", X"f1", X"14", X"f5", X"f6", X"f6", X"0c", X"ef", X"02", X"0e", X"04", X"13", X"ed", X"fa", X"ff", X"0a", X"01", X"03", X"08", X"07", X"e9", X"f9", X"01", X"02", X"ff",
                                                        X"0c", X"f3", X"fd", X"e0", X"04", X"fc", X"15", X"ff", X"ff", X"17", X"16", X"e8", X"ec", X"01", X"f5", X"09", X"fc", X"f7", X"04", X"e8", X"f4", X"04", X"11", X"0b", X"fa", X"05",
                                                        X"f4", X"04", X"00", X"f4", X"f8", X"f7", X"02", X"f9", X"14", X"f2", X"01", X"f2", X"0d", X"02", X"00", X"13", X"20", X"02", X"01", X"ed", X"0f", X"fe", X"ee", X"f3", X"07", X"00",
                                                        X"02", X"ed", X"ff", X"01", X"fc", X"fb", X"08", X"0c", X"01", X"f0", X"fd", X"03", X"03", X"01", X"08", X"ff", X"f5", X"fc", X"0f", X"0f", X"fe", X"fd", X"0b", X"17", X"fe", X"f6",
                                                        X"06", X"06", X"ee", X"ec", X"04", X"05", X"f0", X"01", X"09", X"02", X"eb", X"f3", X"06", X"06", X"f1", X"0d", X"fa", X"f4", X"04", X"fd", X"12", X"02", X"e2", X"01", X"04", X"09",
                                                        X"f7", X"e2", X"1d", X"05", X"fd", X"ef", X"00", X"e9", X"fb", X"fc", X"fc", X"06", X"ea", X"fa", X"04", X"0e", X"ed", X"ee", X"33", X"14", X"01", X"f9", X"0a", X"e8", X"f6", X"00",
                                                        X"0a", X"03", X"de", X"04", X"03", X"08", X"fd", X"ef", X"14", X"05", X"02", X"f7", X"fb", X"ee", X"02", X"fc", X"0d", X"fd", X"e5", X"f9", X"eb", X"0a", X"eb", X"ed", X"2d", X"0d",
                                                        X"01", X"fb", X"0a", X"00", X"07", X"04", X"16", X"03", X"e9", X"03", X"0c", X"02", X"f6", X"ff", X"31", X"15", X"04", X"f1", X"03", X"07", X"06", X"03", X"0d", X"14", X"eb", X"0a",
                                                        X"0b", X"05", X"03", X"f1", X"08", X"11", X"03", X"02", X"11", X"fc", X"0d", X"f8", X"0b", X"01", X"f7", X"12", X"03", X"11", X"01", X"01", X"22", X"08", X"fa", X"03", X"03", X"f4",
                                                        X"fc", X"00", X"0a", X"0e", X"f6", X"14", X"12", X"0e", X"05", X"10", X"f9", X"0b", X"00", X"ef", X"03", X"fe", X"f6", X"09", X"0f", X"0c", X"ef", X"1b", X"f9", X"01", X"f4", X"eb",
                                                        X"ff", X"ff", X"03", X"fd", X"fd", X"02", X"fe", X"08", X"0c", X"f7", X"fb", X"05", X"1c", X"0e", X"f4", X"01", X"0b", X"01", X"ff", X"02", X"f7", X"fb", X"01", X"11", X"0f", X"f0",
                                                        X"00", X"f8", X"0b", X"1b", X"0d", X"03", X"e1", X"f6", X"fb", X"11", X"f4", X"05", X"fd", X"fb", X"0a", X"eb", X"04", X"ed", X"ff", X"0f", X"17", X"1f", X"03", X"f5", X"ff", X"03",
                                                        X"f4", X"03", X"f9", X"fe", X"01", X"eb", X"16", X"fa", X"07", X"11", X"fb", X"15", X"17", X"e9", X"fb", X"02", X"e2", X"09", X"05", X"06", X"0d", X"e4", X"11", X"01", X"17", X"06",
                                                        X"06", X"15", X"14", X"f2", X"fc", X"fb", X"f0", X"04", X"0c", X"fd", X"fc", X"f6", X"10", X"e5", X"10", X"07", X"01", X"19", X"08", X"fe", X"f3", X"07", X"f5", X"04", X"07", X"f8",
                                                        X"07", X"f3", X"f9", X"d5", X"1d", X"0d", X"01", X"0c", X"fe", X"ee", X"f5", X"02", X"f7", X"f9", X"1a", X"ef", X"03", X"fa", X"fa", X"e8", X"14", X"0e", X"f5", X"fd", X"21", X"f9",
                                                        X"f1", X"09", X"fb", X"f7", X"0a", X"f6", X"05", X"02", X"f9", X"d9", X"11", X"19", X"f6", X"11", X"10", X"fe", X"f8", X"08", X"f7", X"fe", X"08", X"ee", X"01", X"03", X"02", X"ee",
                                                        X"ec", X"10", X"f9", X"fa", X"fe", X"01", X"f9", X"0f", X"08", X"ee", X"0b", X"00", X"11", X"fd", X"fc", X"08", X"f9", X"0d", X"e5", X"04", X"0f", X"11", X"f8", X"1e", X"fa", X"f7",
                                                        X"0a", X"fd", X"0a", X"03", X"f3", X"ea", X"fa", X"0d", X"ee", X"08", X"17", X"0e", X"fb", X"13", X"13", X"fa", X"0b", X"08", X"03", X"06", X"0b", X"00", X"f5", X"0d", X"ed", X"05",
                                                        X"23", X"08", X"01", X"15", X"00", X"02", X"02", X"0d", X"06", X"fe", X"f2", X"f3", X"19", X"12", X"fe", X"f9", X"10", X"04", X"00", X"0c", X"fd", X"03", X"fd", X"fe", X"15", X"fe",
                                                        X"ff", X"fe", X"11", X"11", X"e6", X"fc", X"00", X"1b", X"fb", X"07", X"fc", X"ff", X"f5", X"f6", X"07", X"09", X"f9", X"00", X"03", X"0a", X"e8", X"fb", X"14", X"1d", X"f8", X"fb",
                                                        X"07", X"04", X"fd", X"fd", X"0d", X"fc", X"f5", X"fc", X"21", X"f7", X"f0", X"f4", X"1c", X"15", X"ef", X"f0", X"f8", X"f9", X"f4", X"f3", X"01", X"fe", X"ee", X"f0", X"0b", X"05",
                                                        X"ff", X"d6", X"04", X"04", X"f0", X"02", X"fa", X"e8", X"0b", X"f2", X"02", X"02", X"ff", X"00", X"ff", X"ff", X"f6", X"08", X"16", X"09", X"f2", X"09", X"0c", X"fb", X"07", X"05",
                                                        X"04", X"08", X"f1", X"05", X"fa", X"0b", X"fb", X"0b", X"f9", X"fe", X"f6", X"20", X"05", X"f6", X"00", X"fa", X"07", X"fc", X"07", X"fd", X"08", X"0a", X"fb", X"09", X"14", X"fb",
                                                        X"00", X"15", X"fe", X"01", X"09", X"fb", X"06", X"07", X"12", X"fe", X"11", X"11", X"fb", X"16", X"06", X"06", X"fe", X"fa", X"f8", X"fd", X"fe", X"fb", X"10", X"fd", X"08", X"01",
                                                        X"0e", X"01", X"fd", X"0d", X"04", X"0f", X"fb", X"f6", X"fa", X"fa", X"fb", X"08", X"14", X"03", X"f7", X"fa", X"0e", X"fd", X"ff", X"0a", X"14", X"f4", X"f8", X"04", X"f0", X"f8",
                                                        X"f6", X"0b", X"fd", X"0f", X"17", X"06", X"07", X"02", X"fe", X"0d", X"14", X"10", X"ed", X"0c", X"f5", X"0a", X"04", X"fb", X"08", X"0e", X"07", X"05", X"f6", X"09", X"06", X"19",
                                                        X"1e", X"0b", X"f9", X"fb", X"f5", X"fc", X"02", X"f6", X"fb", X"02", X"01", X"fc", X"0a", X"fd", X"04", X"07", X"fd", X"f6", X"f1", X"17", X"05", X"f3", X"13", X"fe", X"ff", X"fa",
                                                        X"02", X"05", X"02", X"f9", X"eb", X"fb", X"00", X"fa", X"f5", X"00", X"f5", X"ff", X"06", X"f4", X"fa", X"ed", X"02", X"03", X"fc", X"02", X"ec", X"16", X"0b", X"eb", X"00", X"02",
                                                        X"e7", X"0b", X"01", X"03", X"ff", X"ec", X"fe", X"09", X"09", X"ff", X"fd", X"fe", X"1c", X"f1", X"ef", X"fc", X"fb", X"0c", X"03", X"07", X"13", X"f4", X"f9", X"ef", X"0c", X"0a",
                                                        X"f3", X"fd", X"2d", X"fb", X"f4", X"0c", X"ee", X"06", X"f8", X"fa", X"ff", X"fb", X"fa", X"f3", X"08", X"08", X"f9", X"09", X"fa", X"f0", X"ef", X"0e", X"00", X"fc", X"f7", X"00",
                                                        X"00", X"f5", X"ea", X"ff", X"17", X"03", X"01", X"00", X"2a", X"f7", X"fb", X"ec", X"f6", X"fe", X"fe", X"0b", X"02", X"f9", X"f5", X"fc", X"1d", X"0b", X"00", X"06", X"08", X"fc",
                                                        X"f8", X"f2", X"fb", X"ef", X"00", X"fb", X"02", X"07", X"08", X"fc", X"09", X"fe", X"fd", X"ff", X"20", X"03", X"fa", X"fd", X"02", X"f8", X"0c", X"fc", X"14", X"f8", X"04", X"eb",
                                                        X"16", X"00", X"f1", X"0c", X"1e", X"05", X"00", X"06", X"ff", X"04", X"02", X"fe", X"fe", X"04", X"0e", X"ee", X"f0", X"04", X"ff", X"0e", X"01", X"08", X"fe", X"04", X"09", X"fe",
                                                        X"01", X"f6", X"0a", X"08", X"00", X"e8", X"f5", X"01", X"f4", X"f2", X"f8", X"fa", X"eb", X"03", X"05", X"f2", X"f0", X"f1", X"08", X"fd", X"ea", X"03", X"fc", X"05", X"01", X"f0",
                                                        X"12", X"07", X"f2", X"08", X"01", X"f5", X"f1", X"09", X"f4", X"fd", X"ed", X"f5", X"09", X"07", X"f2", X"f9", X"1d", X"03", X"fb", X"05", X"fe", X"f4", X"fe", X"ff", X"0e", X"f2",
                                                        X"06", X"e9", X"14", X"04", X"fe", X"f6", X"1a", X"11", X"fd", X"fe", X"01", X"f4", X"02", X"f6", X"05", X"09", X"f0", X"f2", X"00", X"06", X"ed", X"f7", X"0c", X"0a", X"eb", X"00",
                                                        X"fc", X"fc", X"0c", X"e7", X"04", X"f0", X"0d", X"0b", X"f4", X"09", X"e2", X"1b", X"1e", X"f1", X"f0", X"fd", X"e8", X"07", X"04", X"f8", X"03", X"fa", X"03", X"08", X"fe", X"10",
                                                        X"f5", X"10", X"1d", X"12", X"f4", X"1c", X"f9", X"0a", X"07", X"03", X"0d", X"fd", X"ff", X"e1", X"12", X"18", X"fd", X"07", X"06", X"10", X"f6", X"10", X"01", X"0f", X"fc", X"0f",
                                                        X"19", X"fb", X"05", X"05", X"11", X"0f", X"0a", X"0d", X"f4", X"fb", X"f7", X"12", X"08", X"02", X"fe", X"fd", X"10", X"06", X"ff", X"f2", X"f7", X"16", X"f4", X"08", X"13", X"0a",
                                                        X"f7", X"10", X"02", X"04", X"01", X"f6", X"09", X"04", X"04", X"0b", X"0c", X"0a", X"f9", X"07", X"f8", X"0b", X"e8", X"13", X"f6", X"f4");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"f4";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

