-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/model_qat_2x2_w8a16/amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block446.vhd
-- Created: 2025-02-27 23:58:54
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block446
-- Source Path: model_qat_2x2_w8a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage9/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block446 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block446;


ARCHITECTURE rtl OF amc_cnn_qat_8w16a_src_SinglePortRAM_generic_block446 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"04", X"09", X"fc", X"ff", X"02", X"01", X"f2", X"f3", X"00", X"07", X"35", X"00", X"f9", X"06",
                                                        X"07", X"0f", X"00", X"00", X"06", X"09", X"f5", X"f3", X"03", X"f7", X"05", X"06", X"0c", X"07", X"ff", X"0f", X"1b", X"00", X"0a", X"05", X"ff", X"05", X"08", X"eb", X"02", X"0b",
                                                        X"05", X"0c", X"05", X"0d", X"05", X"ff", X"1d", X"0a", X"f2", X"06", X"ff", X"07", X"18", X"e4", X"ef", X"0a", X"05", X"18", X"0d", X"08", X"0a", X"00", X"05", X"06", X"f8", X"03",
                                                        X"fa", X"0b", X"02", X"ff", X"01", X"03", X"06", X"08", X"07", X"0e", X"00", X"fe", X"05", X"1a", X"01", X"0a", X"07", X"fa", X"f7", X"e9", X"0c", X"ef", X"06", X"f5", X"0d", X"02",
                                                        X"fb", X"08", X"0a", X"03", X"f9", X"fe", X"f6", X"02", X"fd", X"ef", X"13", X"df", X"0f", X"f6", X"0c", X"0d", X"f3", X"04", X"f5", X"05", X"f5", X"08", X"f7", X"07", X"e3", X"02",
                                                        X"fa", X"e8", X"08", X"e6", X"17", X"03", X"ee", X"01", X"00", X"f9", X"10", X"14", X"f9", X"08", X"0c", X"f4", X"ff", X"e9", X"fb", X"01", X"12", X"ea", X"f9", X"09", X"08", X"08",
                                                        X"fc", X"13", X"00", X"13", X"13", X"fc", X"05", X"ee", X"05", X"07", X"14", X"0c", X"04", X"0d", X"0b", X"12", X"02", X"1f", X"03", X"0a", X"01", X"e5", X"02", X"06", X"fa", X"f7",
                                                        X"00", X"1a", X"ff", X"05", X"0a", X"07", X"05", X"1d", X"04", X"ff", X"fe", X"ed", X"07", X"fc", X"fb", X"fb", X"13", X"0a", X"fe", X"f7", X"12", X"10", X"02", X"0c", X"f8", X"f7",
                                                        X"00", X"f0", X"ec", X"00", X"f4", X"10", X"04", X"f0", X"07", X"f7", X"fd", X"0f", X"f2", X"ff", X"08", X"05", X"fb", X"00", X"01", X"fb", X"fb", X"06", X"e6", X"02", X"fa", X"01",
                                                        X"05", X"07", X"e8", X"fc", X"01", X"03", X"fa", X"f3", X"fa", X"ff", X"0a", X"00", X"06", X"12", X"f7", X"00", X"0b", X"fb", X"f0", X"ff", X"fd", X"00", X"f9", X"f9", X"f2", X"f2",
                                                        X"04", X"ed", X"18", X"02", X"f6", X"f3", X"fb", X"01", X"f3", X"fe", X"ff", X"f2", X"f0", X"d5", X"01", X"f7", X"00", X"eb", X"10", X"f7", X"fc", X"ed", X"f6", X"ff", X"08", X"0d",
                                                        X"08", X"19", X"0d", X"d8", X"0e", X"15", X"fc", X"0a", X"31", X"18", X"04", X"ff", X"16", X"13", X"ff", X"16", X"12", X"0b", X"05", X"03", X"02", X"0c", X"e6", X"15", X"17", X"0b",
                                                        X"13", X"00", X"11", X"1b", X"07", X"1b", X"0d", X"0c", X"05", X"e3", X"18", X"0c", X"ee", X"fc", X"08", X"06", X"07", X"03", X"09", X"0d", X"02", X"12", X"09", X"09", X"07", X"e5",
                                                        X"0a", X"fc", X"fb", X"f3", X"03", X"06", X"02", X"f9", X"fe", X"0c", X"fc", X"0f", X"fc", X"f0", X"09", X"f0", X"ed", X"e8", X"ff", X"fd", X"eb", X"ff", X"fd", X"07", X"f3", X"fb",
                                                        X"01", X"0b", X"f5", X"01", X"ff", X"e5", X"f8", X"ee", X"fb", X"fe", X"04", X"f5", X"01", X"0b", X"ef", X"03", X"e8", X"1b", X"fc", X"f5", X"f6", X"e6", X"0e", X"d7", X"07", X"fd",
                                                        X"1a", X"04", X"ff", X"fc", X"f5", X"01", X"fd", X"1d", X"02", X"fa", X"f2", X"f8", X"fc", X"f7", X"ed", X"f0", X"0f", X"03", X"08", X"16", X"f7", X"03", X"00", X"ff", X"f7", X"f2",
                                                        X"03", X"e2", X"0f", X"f5", X"03", X"f2", X"0f", X"f9", X"0c", X"11", X"08", X"ff", X"09", X"0b", X"0d", X"03", X"05", X"f4", X"00", X"01", X"f0", X"00", X"1c", X"13", X"14", X"0e",
                                                        X"08", X"0d", X"0c", X"09", X"04", X"0a", X"f5", X"f2", X"fb", X"0a", X"f4", X"03", X"ef", X"18", X"12", X"01", X"12", X"0b", X"00", X"10", X"f8", X"fc", X"fb", X"e2", X"f5", X"fa",
                                                        X"f5", X"f5", X"fb", X"08", X"0f", X"03", X"fc", X"12", X"ee", X"03", X"ff", X"f4", X"04", X"ee", X"f2", X"fb", X"09", X"0a", X"ff", X"f2", X"fc", X"f9", X"f5", X"0a", X"e9", X"02",
                                                        X"ef", X"02", X"f9", X"fb", X"ef", X"f4", X"0a", X"f6", X"fb", X"18", X"ed", X"f2", X"0d", X"0e", X"f5", X"01", X"ef", X"f7", X"fa", X"f5", X"ff", X"df", X"fd", X"f3", X"2f", X"fe",
                                                        X"ec", X"f9", X"06", X"06", X"f4", X"10", X"ef", X"05", X"00", X"f4", X"fa", X"f1", X"ff", X"0c", X"2c", X"f8", X"f4", X"05", X"07", X"fa", X"00", X"07", X"07", X"fc", X"0c", X"ed",
                                                        X"07", X"f2", X"00", X"11", X"12", X"e8", X"09", X"f6", X"04", X"ff", X"00", X"13", X"0b", X"12", X"01", X"02", X"e0", X"fd", X"fc", X"10", X"0b", X"0e", X"0f", X"fe", X"0b", X"0e",
                                                        X"f9", X"14", X"0a", X"13", X"10", X"fa", X"fb", X"00", X"f1", X"fa", X"02", X"fd", X"02", X"07", X"0c", X"09", X"ff", X"01", X"07", X"16", X"01", X"ef", X"ea", X"04", X"f1", X"09",
                                                        X"fb", X"06", X"05", X"10", X"05", X"f7", X"06", X"01", X"fa", X"07", X"0a", X"f1", X"07", X"fa", X"fc", X"04", X"11", X"0f", X"fa", X"f6", X"fd", X"ff", X"03", X"0b", X"05", X"0a",
                                                        X"04", X"f9", X"f2", X"f6", X"0c", X"03", X"0f", X"07", X"02", X"f9", X"07", X"f5", X"05", X"14", X"01", X"ff", X"fa", X"fc", X"f3", X"f2", X"05", X"eb", X"22", X"fc", X"f5", X"f2",
                                                        X"fd", X"f8", X"fa", X"0b", X"05", X"07", X"f3", X"db", X"f2", X"e8", X"fd", X"03", X"06", X"09", X"ff", X"0d", X"16", X"07", X"fa", X"0b", X"10", X"00", X"14", X"ec", X"f2", X"ea",
                                                        X"04", X"07", X"37", X"0a", X"02", X"00", X"07", X"11", X"fd", X"09", X"fc", X"00", X"09", X"df", X"ff", X"f2", X"01", X"0a", X"1e", X"f8", X"01", X"06", X"05", X"0f", X"0c", X"1d",
                                                        X"04", X"0f", X"05", X"eb", X"14", X"01", X"f3", X"ff", X"02", X"03", X"01", X"23", X"13", X"0a", X"09", X"0a", X"ed", X"03", X"07", X"ef", X"00", X"fc", X"fd", X"00", X"06", X"0d",
                                                        X"f4", X"1e", X"07", X"06", X"f7", X"fc", X"f2", X"f9", X"f7", X"ff", X"ff", X"f1", X"03", X"f4", X"f7", X"e7", X"fd", X"f5", X"fb", X"f5", X"f4", X"02", X"f4", X"f0", X"ee", X"ed",
                                                        X"f5", X"ec", X"01", X"f1", X"09", X"f0", X"ff", X"f8", X"f8", X"f9", X"fa", X"0b", X"f6", X"f7", X"fb", X"da", X"f5", X"f8", X"05", X"09", X"09", X"e6", X"f9", X"15", X"0c", X"02",
                                                        X"f6", X"07", X"f4", X"0b", X"f7", X"f5", X"e4", X"eb", X"00", X"08", X"14", X"0a", X"fa", X"23", X"1a", X"02", X"0a", X"10", X"fe", X"0c", X"ff", X"ee", X"f7", X"10", X"ee", X"03",
                                                        X"fa", X"03", X"ff", X"18", X"0a", X"12", X"01", X"11", X"f8", X"0f", X"0c", X"f0", X"15", X"12", X"ee", X"1d", X"07", X"06", X"08", X"0b", X"0e", X"0e", X"ff", X"17", X"06", X"fd",
                                                        X"04", X"e3", X"f5", X"04", X"f1", X"15", X"fe", X"00", X"0b", X"01", X"0b", X"0d", X"f9", X"14", X"01", X"07", X"02", X"ed", X"11", X"01", X"04", X"04", X"df", X"0e", X"fb", X"16",
                                                        X"0f", X"07", X"f2", X"fa", X"ff", X"f9", X"fb", X"f5", X"07", X"eb", X"0f", X"f4", X"f1", X"f5", X"f2", X"ff", X"0f", X"0a", X"f5", X"01", X"ea", X"fb", X"f7", X"f8", X"00", X"e8",
                                                        X"17", X"e6", X"04", X"f2", X"ee", X"fc", X"09", X"f6", X"ee", X"0d", X"01", X"00", X"f7", X"fa", X"08", X"ee", X"0a", X"f9", X"31", X"f6", X"f5", X"0f", X"00", X"05", X"f4", X"1b",
                                                        X"04", X"0e", X"f6", X"ff", X"f2", X"f2", X"ef", X"0a", X"37", X"1b", X"02", X"04", X"06", X"00", X"0e", X"06", X"06", X"08", X"05", X"ec", X"02", X"0c", X"ff", X"02", X"12", X"13",
                                                        X"0a", X"09", X"09", X"09", X"0b", X"10", X"08", X"09", X"04", X"e7", X"00", X"0d", X"f3", X"0c", X"21", X"1c", X"14", X"f5", X"00", X"0c", X"0f", X"10", X"04", X"08", X"ff", X"d7",
                                                        X"f3", X"f7", X"03", X"04", X"fd", X"06", X"05", X"f8", X"08", X"0f", X"05", X"0d", X"09", X"f2", X"ec", X"df", X"f1", X"04", X"f9", X"f8", X"e4", X"ed", X"0b", X"f4", X"ff", X"f8",
                                                        X"fa", X"02", X"f9", X"03", X"04", X"f4", X"ee", X"ee", X"ff", X"ee", X"00", X"f9", X"ff", X"01", X"06", X"e7", X"ed", X"09", X"fe", X"f6", X"01", X"ea", X"01", X"f5", X"05", X"f9",
                                                        X"f8", X"f6", X"f8", X"eb", X"f6", X"f3", X"f8", X"06", X"f0", X"04", X"f1", X"f0", X"08", X"ea", X"0d", X"f2", X"03", X"f9", X"ef", X"05", X"fc", X"00", X"fd", X"10", X"f5", X"0f",
                                                        X"f8", X"e0", X"fe", X"f3", X"02", X"fa", X"2e", X"11", X"fd", X"f1", X"0b", X"0f", X"0c", X"08", X"03", X"09", X"fe", X"f4", X"00", X"fc", X"e1", X"16", X"0c", X"0c", X"f9", X"f2",
                                                        X"04", X"08", X"06", X"fc", X"fd", X"08", X"04", X"ed", X"de", X"03", X"f7", X"05", X"03", X"fa", X"03", X"f1", X"08", X"fa", X"fb", X"0f", X"ff", X"0b", X"13", X"e1", X"f1", X"06",
                                                        X"07", X"05", X"f8", X"f3", X"0e", X"fa", X"fc", X"f9", X"fb", X"0c", X"0c", X"07", X"ff", X"ee", X"01", X"06", X"10", X"f7", X"e9", X"06", X"05", X"f5", X"14", X"f6", X"01", X"06",
                                                        X"fb", X"fb", X"0e", X"e9", X"fa", X"fb", X"02", X"04", X"01", X"fc", X"fc", X"fd", X"fb", X"fe", X"ef", X"01", X"fc", X"f9", X"ff", X"f1", X"e2", X"e9", X"fd", X"02", X"fc", X"ee",
                                                        X"fb", X"f4", X"e9", X"f2", X"00", X"15", X"f1", X"e7", X"02", X"f0", X"f6", X"e8", X"fc", X"ef", X"06", X"ef", X"fd", X"06", X"f9", X"fa", X"fe", X"1b", X"fa", X"00", X"fb", X"ff",
                                                        X"fc", X"f5", X"fe", X"02", X"21", X"14", X"04", X"fa", X"ff", X"fb", X"07", X"04", X"f5", X"05", X"0a", X"e0", X"22", X"11", X"f6", X"05", X"0d", X"09", X"00", X"06", X"06", X"09",
                                                        X"fb", X"12", X"07", X"14", X"15", X"f8", X"08", X"11", X"ea", X"15", X"06", X"09", X"00", X"03", X"09", X"15", X"03", X"19", X"f7", X"06", X"15", X"d4", X"00", X"00", X"e7", X"0f",
                                                        X"04", X"fc", X"ff", X"09", X"fa", X"0b", X"0b", X"16", X"f1", X"f5", X"0a", X"ef", X"fb", X"fc", X"f3", X"0e", X"06", X"03", X"00", X"0e", X"02", X"0b", X"f7", X"14", X"02", X"f3",
                                                        X"f9", X"ee", X"f1", X"f4", X"f3", X"13", X"09", X"00", X"05", X"ed", X"00", X"08", X"f0", X"0c", X"01", X"05", X"11", X"f7", X"ed", X"e3", X"f7", X"00", X"0d", X"f8", X"f0", X"f2",
                                                        X"fa", X"07", X"ee", X"07", X"f8", X"f6", X"f3", X"f9", X"e6", X"e2", X"09", X"ec", X"04", X"0e", X"f5", X"05", X"04", X"e6", X"13", X"fb", X"04", X"04", X"06", X"e6", X"ec", X"f4",
                                                        X"fe", X"02", X"1c", X"ec", X"fd", X"0a", X"0c", X"05", X"fe", X"0b", X"0f", X"fc", X"fc", X"f7", X"ef", X"ef", X"07", X"11", X"f6", X"14", X"0d", X"fa", X"1a", X"fe", X"fd", X"13",
                                                        X"03", X"0a", X"05", X"d7", X"fc", X"02", X"fe", X"15", X"11", X"2e", X"0a", X"06", X"09", X"0f", X"fc", X"09", X"fc", X"fd", X"0b", X"e0", X"fa", X"0a", X"02", X"f9", X"0a", X"07",
                                                        X"01", X"fc", X"fe", X"0d", X"f5", X"12", X"08", X"01", X"0c", X"fc", X"03", X"fd", X"0d", X"16", X"12", X"fc", X"f9", X"fe", X"00", X"0d", X"02", X"04", X"fd", X"05", X"f4", X"f0",
                                                        X"fe", X"fb", X"06", X"f3", X"04", X"fa", X"f0", X"10", X"fc", X"f8", X"f0", X"11", X"fe", X"f8", X"f3", X"02", X"eb", X"ea", X"02", X"ed", X"1a", X"f8", X"02", X"f2", X"f5", X"ed",
                                                        X"fd", X"17", X"f2", X"07", X"f6", X"f6", X"f7", X"f4", X"02", X"fa", X"04", X"fe", X"ff", X"e9", X"08", X"fd", X"05", X"07", X"07", X"12", X"f4", X"e0", X"eb", X"f5", X"0e", X"fc",
                                                        X"0f", X"1a", X"fc", X"ed", X"11", X"fe", X"11", X"08", X"fd", X"07", X"0f", X"f7", X"08", X"f6", X"fe", X"1c", X"1d", X"fc", X"0c", X"02", X"05", X"0b", X"0d", X"1c", X"01", X"0c",
                                                        X"15", X"d0", X"06", X"02", X"f0", X"0a", X"21", X"04", X"0b", X"0c", X"01", X"0f", X"0b", X"22", X"14", X"0c", X"01", X"db", X"0d", X"0e", X"ec", X"12", X"1c", X"03", X"12", X"11",
                                                        X"fc", X"1a", X"fd", X"05", X"08", X"00", X"fe", X"fc", X"fa", X"06", X"f4", X"ef", X"09", X"fe", X"04", X"f8", X"fc", X"fc", X"fc", X"09", X"00", X"e7", X"f7", X"e8", X"ed", X"f5",
                                                        X"f6", X"f9", X"ef", X"e6", X"02", X"ff", X"f5", X"f7", X"f1", X"11", X"00", X"03", X"ec", X"fa", X"fd", X"f1", X"f3", X"dd", X"31", X"f8", X"f6", X"09", X"fb", X"fe", X"ff", X"05",
                                                        X"03", X"01", X"fe", X"f0", X"08", X"e0", X"0b", X"f1", X"13", X"f6", X"f5", X"0c", X"0c", X"07", X"02", X"07", X"f0", X"02", X"02", X"e8", X"f2", X"d8", X"0c", X"14", X"1b", X"fa",
                                                        X"fb", X"0b", X"0c", X"11", X"0d", X"08", X"f1", X"0e", X"12", X"e6", X"fc", X"e6", X"ff", X"0c", X"14", X"02", X"fe", X"09", X"07", X"08", X"0a", X"07", X"08", X"0c", X"08", X"07",
                                                        X"f2", X"fb", X"f8", X"19", X"1a", X"fd", X"13", X"03", X"09", X"0b", X"0e", X"fe", X"08", X"00", X"ed", X"08", X"e3", X"04", X"ec", X"e5", X"10", X"ff", X"13", X"f6", X"05", X"f9",
                                                        X"0e", X"0d", X"0e", X"f7", X"0a", X"e6", X"ef", X"fd", X"06", X"02", X"f7", X"fb", X"09", X"03", X"f7", X"f6", X"01", X"19", X"10", X"f9", X"f6", X"ec", X"f8", X"01", X"fb", X"eb",
                                                        X"fb", X"05", X"05", X"f7", X"fa", X"fe", X"04", X"08", X"ff", X"f6", X"f5", X"ee", X"f1", X"e9", X"07", X"f7", X"03", X"fb", X"f1", X"00", X"ff", X"05", X"00", X"0b", X"f6", X"fc",
                                                        X"04", X"02", X"f8", X"ec", X"04", X"10", X"0f", X"fb", X"fc", X"06", X"f4", X"0c", X"06", X"09", X"fc", X"07", X"04", X"08", X"fc", X"f4", X"ee", X"f7", X"22", X"fb", X"fb", X"0d",
                                                        X"00", X"0c", X"08", X"ff", X"0a", X"0b", X"01", X"e8", X"f6", X"fb", X"f0", X"04", X"05", X"0b", X"04", X"13", X"05", X"0d", X"07", X"0f", X"f7", X"0d", X"07", X"f2", X"ff", X"fb",
                                                        X"ff", X"00", X"0d", X"09", X"06", X"0d", X"fd", X"10", X"0b", X"05", X"0c", X"14", X"06", X"e8", X"fa", X"15", X"f0", X"f6", X"e4", X"fb", X"fe", X"03", X"01", X"ff", X"0a", X"ff",
                                                        X"f9", X"06", X"02", X"e9", X"f4", X"02", X"00", X"04", X"05", X"04", X"fb", X"e6", X"09", X"03", X"f7", X"0c", X"0a", X"f3", X"fc", X"e6", X"fa", X"00", X"04", X"f4", X"02", X"00",
                                                        X"f7", X"04", X"02", X"f5", X"f3", X"11", X"08", X"07", X"f6", X"f2", X"01", X"e1", X"05", X"f4", X"1b", X"ed", X"f1", X"fa", X"00", X"0b", X"f8", X"05", X"fe", X"ff", X"fe", X"e4",
                                                        X"04", X"e4", X"05", X"f7", X"22", X"fe", X"fb", X"f9", X"fe", X"0b", X"f3", X"0f", X"04", X"05", X"00", X"f7", X"05", X"ff", X"fe", X"fc", X"13", X"03", X"06", X"f7", X"fc", X"04",
                                                        X"06", X"12", X"00", X"06", X"0d", X"e6", X"01", X"05", X"f8", X"03", X"0f", X"00", X"08", X"f6", X"f8", X"fd", X"04", X"15", X"11", X"09", X"06", X"f5", X"f5", X"f2", X"f9", X"07",
                                                        X"01", X"0c", X"09", X"02", X"09", X"02", X"01", X"18", X"05", X"03", X"0a", X"e8", X"e4", X"00", X"f1", X"fe", X"01", X"fd", X"0c", X"06", X"f8", X"02", X"09", X"0b", X"fd", X"0b",
                                                        X"ff", X"ea", X"fd", X"fe", X"fe", X"05", X"ff", X"00", X"03", X"12", X"03", X"0f", X"f5", X"fa", X"03", X"f3", X"f1", X"0d", X"fa", X"fb", X"01", X"08", X"fe", X"f9", X"01", X"f6",
                                                        X"f8", X"f4", X"e2", X"f7", X"03", X"fb", X"f3", X"f2", X"00", X"f9", X"f9", X"e9", X"0b", X"0c", X"fe", X"fe", X"ff", X"ec", X"f8", X"0f", X"ff", X"f8", X"00", X"ed", X"f8", X"f4",
                                                        X"fc", X"ff", X"04", X"03", X"f7", X"fe", X"ff", X"f9", X"fe", X"0e", X"f7", X"03", X"0d", X"f5", X"f1", X"fd", X"fa", X"0e", X"02", X"e8", X"fb", X"1a", X"01", X"08", X"f8", X"1b",
                                                        X"fe", X"fe", X"05", X"e1", X"08", X"06", X"04", X"09", X"1b", X"0c", X"00", X"21", X"13", X"02", X"f9", X"04", X"fc", X"0d", X"0d", X"e5", X"fe", X"00", X"fe", X"f7", X"01", X"08",
                                                        X"06", X"19", X"00", X"fd", X"f7", X"24", X"10", X"0c", X"fe", X"f9", X"f3", X"00", X"f7", X"00", X"09", X"12", X"00", X"0e", X"ff", X"f5");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"f5";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

