-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/model_pqt_2x2_w16a16/amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block361.vhd
-- Created: 2025-02-19 19:19:37
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block361
-- Source Path: model_pqt_2x2_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage127/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block361 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block361;


ARCHITECTURE rtl OF amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block361 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"fffe", X"fd1b", X"ff85", X"0056", X"f7ef", X"05dd",
                                                        X"fc07", X"faca", X"fe56", X"fd53", X"fa00", X"00cf", X"06c0", X"f90a", X"01ac", X"01a5", X"087d", X"0323", X"0052", X"ffbb",
                                                        X"0350", X"00ae", X"037f", X"fa8a", X"f9cc", X"031e", X"ff3e", X"0217", X"020a", X"fe07", X"03ec", X"0059", X"fffd", X"fd01",
                                                        X"f9a9", X"01bb", X"053f", X"fc86", X"fc70", X"fb29", X"02c4", X"ff8c", X"061b", X"ffb0", X"04c9", X"f991", X"06ab", X"fa6e",
                                                        X"ff6d", X"fdc6", X"0474", X"04a3", X"0459", X"0558", X"0223", X"04ce", X"038c", X"0404", X"ff0a", X"007e", X"0887", X"00d8",
                                                        X"03af", X"ff3a", X"04a7", X"0135", X"03c3", X"f997", X"fcef", X"ff69", X"fee4", X"fe9a", X"f8d0", X"fb1b", X"0213", X"0181",
                                                        X"03d5", X"f94d", X"02f7", X"ff89", X"ff2e", X"fd35", X"ff5f", X"fc64", X"ff71", X"f8f0", X"02c7", X"008b", X"011c", X"04ad",
                                                        X"fea1", X"05c5", X"045f", X"04b5", X"fc2b", X"fda8", X"05d3", X"f9b1", X"fc6f", X"01cd", X"fbca", X"0526", X"fd55", X"f9de",
                                                        X"ff41", X"04c5", X"031c", X"023b", X"ff6b", X"fa93", X"fbde", X"fdff", X"065a", X"016a", X"ff7d", X"0136", X"025c", X"fb8a",
                                                        X"02e4", X"fc52", X"fcb7", X"011f", X"fdc6", X"07a8", X"fcb4", X"fb88", X"0241", X"f9c6", X"ff1a", X"0283", X"fe5d", X"fe6d",
                                                        X"fa86", X"0183", X"fc93", X"fea6", X"033b", X"fcd8", X"fa67", X"ffb3", X"038c", X"fbbe", X"ff3b", X"fc6e", X"0250", X"062b",
                                                        X"015c", X"fdc9", X"fe44", X"fa3a", X"05a5", X"ff50", X"fcdf", X"fff5", X"00fd", X"0348", X"0081", X"fd67", X"05c0", X"feec",
                                                        X"04cf", X"fc8f", X"f995", X"00b4", X"feb9", X"f63e", X"ff38", X"f732", X"0339", X"fff5", X"fb26", X"0429", X"fb64", X"fc64",
                                                        X"ff78", X"faee", X"fc9f", X"03c5", X"fa49", X"f59b", X"fcec", X"ffb0", X"fe71", X"f9a8", X"fd1e", X"fa4b", X"f97a", X"faae",
                                                        X"fe75", X"f93e", X"06ed", X"00fa", X"04fe", X"fbf2", X"f8d0", X"ffd9", X"fbb3", X"01cc", X"051b", X"fda3", X"0062", X"f903",
                                                        X"f9c8", X"fd73", X"0350", X"00a8", X"fbf3", X"fded", X"03ac", X"fe6c", X"fee5", X"fcc9", X"fee1", X"fe00", X"0111", X"f719",
                                                        X"01ca", X"032b", X"f985", X"03f2", X"00f0", X"fdb8", X"fae4", X"0101", X"fc7c", X"0455", X"f7c9", X"fb4d", X"fefc", X"01ca",
                                                        X"0120", X"f8e3", X"0520", X"013b", X"004e", X"0107", X"fca3", X"fdf9", X"ffb3", X"062f", X"fefd", X"0084", X"fe08", X"028f",
                                                        X"ffe8", X"0294", X"03ce", X"fe46", X"fbe3", X"007a", X"fdad", X"02db", X"ff9d", X"016b", X"028a", X"fee0", X"fb7a", X"00da",
                                                        X"fc2d", X"fff5", X"fcab", X"0036", X"02f0", X"013a", X"fb88", X"fe4c", X"fb27", X"fe14", X"07d7", X"fb9f", X"ffe6", X"fd29",
                                                        X"005a", X"fe7e", X"0190", X"fa8e", X"fd03", X"f966", X"f9b0", X"01e4", X"0255", X"fd6d", X"fd8e", X"0502", X"fe6e", X"ff11",
                                                        X"fdc6", X"01fe", X"fca8", X"fd65", X"042c", X"ff78", X"0216", X"04ca", X"ff80", X"0003", X"0447", X"fd2c", X"fa62", X"05c1",
                                                        X"feba", X"0157", X"0624", X"02ce", X"fce4", X"faa0", X"022f", X"0469", X"002c", X"fd9e", X"fbb9", X"015b", X"fe1d", X"fc11",
                                                        X"038c", X"0168", X"07f8", X"f8b5", X"fec1", X"fce6", X"fc97", X"ffe2", X"0047", X"047d", X"fcc9", X"ff80", X"01e0", X"ffe4",
                                                        X"ffec", X"04b6", X"fb94", X"ffb0", X"0420", X"00b7", X"0244", X"0032", X"0751", X"ffda", X"002d", X"0057", X"00e0", X"0246",
                                                        X"0044", X"0397", X"ff98", X"fccc", X"0312", X"fc76", X"fdf0", X"fb86", X"0133", X"fc2f", X"0283", X"f9a3", X"fcc4", X"0237",
                                                        X"ff1a", X"0528", X"ff74", X"0222", X"0217", X"0113", X"fe89", X"066a", X"fc95", X"01a5", X"06df", X"fe9f", X"00f9", X"03f2",
                                                        X"0006", X"ffe1", X"ff04", X"fc45", X"0150", X"fb87", X"049c", X"01aa", X"fa36", X"fdca", X"fc49", X"0323", X"06ff", X"fa5d",
                                                        X"fb6d", X"f9fc", X"025e", X"047f", X"ffb3", X"0499", X"fec2", X"0158", X"0161", X"fc79", X"f8b8", X"022f", X"fb31", X"fb41",
                                                        X"0275", X"fdef", X"fdeb", X"0350", X"0044", X"fcb2", X"02ab", X"074b", X"0015", X"ff46", X"fb81", X"f9fb", X"fb5d", X"028a",
                                                        X"03a4", X"0388", X"0016", X"fee2", X"ffc9", X"034b", X"0238", X"fe2b", X"0515", X"0658", X"fd5b", X"fefa", X"fbcc", X"f7b6",
                                                        X"f946", X"0564", X"0260", X"fbd2", X"05c8", X"fd29", X"fab9", X"0251", X"fbf1", X"0533", X"018f", X"032e", X"04cb", X"0084",
                                                        X"03dc", X"fce9", X"0111", X"02df", X"056e", X"fdcd", X"fe12", X"00c6", X"fe39", X"fb1d", X"009c", X"011d", X"fe05", X"01b4",
                                                        X"fbcc", X"006e", X"fdd1", X"ff2a", X"fb6e", X"0536", X"fa29", X"0441", X"00aa", X"fcef", X"0210", X"018c", X"03f1", X"ffb3",
                                                        X"ff95", X"fd19", X"fca4", X"027c", X"03b3", X"f826", X"00ab", X"ff9a", X"011d", X"037b", X"fdbb", X"fef5", X"fada", X"03db",
                                                        X"ffb8", X"0451", X"fe97", X"fdcf", X"fe80", X"01e5", X"03bc", X"01c2", X"fe84", X"ffb0", X"ff8b", X"f8c6", X"0447", X"fe4d",
                                                        X"fa78", X"0286", X"fa83", X"ff3f", X"fea5", X"ff09", X"fd44", X"f7a6", X"04fd", X"f863", X"fdef", X"08ef", X"007f", X"f811",
                                                        X"05a0", X"02a6", X"0309", X"039d", X"0477", X"0312", X"0011", X"0187", X"0701", X"fac4", X"fa58", X"0355", X"fc17", X"ff5e",
                                                        X"04e5", X"f70a", X"fe43", X"fd53", X"0232", X"00af", X"00e1", X"02b2", X"fbfc", X"fc9e", X"ffb1", X"fc8a", X"04d7", X"fe59",
                                                        X"f98f", X"fb9f", X"0588", X"ff4b", X"fe0d", X"05b2", X"0a98", X"fe6f", X"fb82", X"fe16", X"f7ae", X"fd37", X"075d", X"fe8f",
                                                        X"ff74", X"042a", X"0173", X"0526", X"fe86", X"fd25", X"fd0a", X"fe66", X"fd96", X"020b", X"0368", X"0165", X"02be", X"fff0",
                                                        X"fcbc", X"045b", X"0456", X"0390", X"fd63", X"fefa", X"0203", X"ff72", X"04ce", X"fc49", X"00c5", X"0495", X"029f", X"0181",
                                                        X"fff3", X"0a53", X"05ba", X"fc7e", X"0338", X"ffcc", X"fa8b", X"0587", X"fe71", X"000e", X"fecf", X"0052", X"0553", X"0268",
                                                        X"0542", X"fb5e", X"ff16", X"00f2", X"fcda", X"fe12", X"ff92", X"0635", X"024a", X"ff3f", X"0523", X"fe73", X"0854", X"00f2",
                                                        X"0832", X"03c8", X"fd5f", X"05c9", X"01d3", X"0034", X"003f", X"004f", X"fc09", X"fddd", X"fcdb", X"04c7", X"fcc0", X"fdfc",
                                                        X"00dc", X"02a6", X"03a2", X"0433", X"046f", X"032b", X"0032", X"fe15", X"fa34", X"0437", X"00e6", X"037e", X"0185", X"fe6c",
                                                        X"fdab", X"fe31", X"04c3", X"0383", X"054a", X"03eb", X"06d6", X"00ae", X"fe85", X"0066", X"0298", X"f8ce", X"00ef", X"fced",
                                                        X"fd07", X"fd99", X"01b3", X"03bb", X"0419", X"ff2d", X"045a", X"fd96", X"0591", X"fd3e", X"038c", X"fec2", X"fbba", X"ff2e",
                                                        X"f8f7", X"01c1", X"fc28", X"0012", X"fee3", X"03c9", X"0372", X"fc0e", X"ffc3", X"ffc6", X"007a", X"00e4", X"035b", X"ff7b",
                                                        X"0249", X"fb09", X"fcbc", X"fc75", X"fb8b", X"fcba", X"feab", X"0254", X"04c3", X"033f", X"00f2", X"0201", X"0514", X"f96d",
                                                        X"fbad", X"ff51", X"0558", X"f7e9", X"0125", X"0600", X"f864", X"0166", X"0488", X"fe18", X"fb28", X"0243", X"006e", X"fd2e",
                                                        X"fda7", X"01af", X"fa04", X"ff42", X"ffd4", X"00eb", X"009f", X"fcd0", X"016c", X"fd26", X"fe64", X"0120", X"ffde", X"fe91",
                                                        X"0239", X"ffdb", X"fe29", X"fc0b", X"0131", X"0387", X"0076", X"fd11", X"fe76", X"fc2d", X"f8fa", X"ffc8", X"ff34", X"fdc2",
                                                        X"fae9", X"058e", X"ff82", X"ff53", X"024f", X"01d2", X"ffce", X"fdb9", X"fe05", X"fc9b", X"0020", X"04f8", X"f9c6", X"04af",
                                                        X"ff72", X"0372", X"f9f4", X"fcd5", X"0360", X"012e", X"0040", X"0335", X"f9d1", X"00bd", X"fef2", X"0141", X"00d7", X"0074",
                                                        X"fba9", X"007d", X"0146", X"fb95", X"03fe", X"0438", X"01ce", X"fcdf", X"ffc3", X"009f", X"02c8", X"fcf4", X"07e3", X"0230",
                                                        X"f9a1", X"fd9a", X"01af", X"0265", X"0035", X"fc8e", X"faea", X"fe4a", X"fd17", X"fb9d", X"019e", X"02bb", X"0183", X"fa95",
                                                        X"051a", X"f816", X"03e7", X"fdeb", X"00db", X"027f", X"02f7", X"0469", X"fcf4", X"fe3d", X"fd06", X"0358", X"fbcd", X"fda0",
                                                        X"0387", X"ff95", X"02e7", X"024d", X"03f7", X"f597", X"fc84", X"039f", X"fbfc", X"fa84", X"034f", X"fe7d", X"00eb", X"0232",
                                                        X"05b2", X"fc9c", X"fc01", X"fe3c", X"fddd", X"f7e6", X"fe56", X"fc42", X"00a2", X"081c", X"f912", X"ffc0", X"03d5", X"fafb",
                                                        X"fd55", X"f962", X"026a", X"02bf", X"0320", X"04d8", X"036c", X"f830", X"fedb", X"0085", X"f9cb", X"06b6", X"02e9", X"0238",
                                                        X"0189", X"fb7d", X"fe29", X"013b", X"013e", X"057a", X"023c", X"faa8", X"fc89", X"ff81", X"01fc", X"fade", X"f81e", X"051c",
                                                        X"ff6a", X"fca5", X"05f8", X"fe2e", X"fd28", X"f812", X"0105", X"0458", X"0445", X"feb4", X"fe7a", X"00ba", X"fd96", X"f5f8",
                                                        X"ff83", X"0186", X"fb41", X"03f0", X"029a", X"fb8f", X"f974", X"01c8", X"0672", X"0708", X"02b1", X"fdff", X"00a2", X"fb1f",
                                                        X"0325", X"ff2e", X"0134", X"07fd", X"ff53", X"0369", X"f8d9", X"fc02", X"f9d9", X"009c", X"fdcd", X"0272", X"fe59", X"fc13",
                                                        X"f956", X"01d6", X"fe3c", X"fc94", X"015d", X"ff3a", X"01b3", X"fdb1", X"fe0d", X"0326", X"00b0", X"fea3", X"0337", X"fe21",
                                                        X"018f", X"02db", X"00b5", X"f8d8", X"f9c2", X"fda6", X"fc9b", X"0237", X"0286", X"03a3", X"fb4e", X"0291", X"05e6", X"024a",
                                                        X"0391", X"00b4", X"00e6", X"f6d2", X"fc5b", X"fbcc", X"02ad", X"021f", X"0163", X"01b3", X"002f", X"003a", X"f983", X"0233",
                                                        X"fb89", X"ff48", X"0281", X"03f5", X"006e", X"01e5", X"fc9e", X"f73d", X"fc69", X"ff6b", X"f9f2", X"0141", X"0448", X"fa0e",
                                                        X"f88b", X"01a8", X"f938", X"ff6d", X"0271", X"ff33", X"ff39", X"ffb3", X"fbf5", X"fe82", X"0152", X"02eb", X"fc4e", X"ff95",
                                                        X"0301", X"0304", X"fcec", X"0203", X"012c", X"0206", X"0078", X"ff7b", X"fcef", X"fe3c", X"fe5a", X"fc4a", X"fc92", X"0265",
                                                        X"0485", X"fab4", X"04ca", X"fb10", X"029f", X"ff4c", X"0964", X"fc00", X"017d", X"02ed", X"02d4", X"039b", X"f9c6", X"fdd7",
                                                        X"02d5", X"0059", X"fbbd", X"0201", X"ff5c", X"04ff", X"053b", X"fae9", X"0125", X"0034", X"f9f8", X"fc19", X"fb23", X"02c1",
                                                        X"ffb4", X"f961", X"019f", X"02d1", X"f987", X"02cd", X"052f", X"02aa", X"fea4", X"fa76", X"06e8", X"04a0", X"fadb", X"fc74",
                                                        X"03c4", X"0276", X"fc31", X"fb16", X"01b6", X"044a", X"ff4e", X"fb98", X"01fa", X"fbba", X"01d4", X"02f7", X"00a2", X"042d",
                                                        X"0373", X"fc91", X"0498", X"022e", X"02a7", X"feb0", X"ffbf", X"03b0", X"0115", X"fff2", X"fbd9", X"011e", X"014b", X"0296",
                                                        X"ff04", X"fd0e", X"00af", X"03be", X"0246", X"fc89", X"02f5", X"03f4", X"fc2b", X"fb65", X"0018", X"fe0c", X"02a9", X"faf3",
                                                        X"042f", X"fb27", X"03f1", X"0091", X"ff2c", X"fc53", X"fb9e", X"fddb", X"faa5", X"fc44", X"f934", X"fde6", X"fb3d", X"ff73",
                                                        X"07d7", X"00d4", X"ff08", X"f974", X"ff36", X"fb58", X"fe65", X"009f", X"01a9", X"0009", X"01c8", X"00b4", X"fb7b", X"fc0b",
                                                        X"051a", X"fe8d", X"0495", X"0333", X"ff46", X"f82d", X"fdd8", X"050a", X"fa9d", X"fd8d", X"006a", X"0845", X"0066", X"fd2c",
                                                        X"fa41", X"fa9c", X"02e2", X"0376", X"0451", X"0078", X"09ad", X"01d8", X"0401", X"0172", X"0615", X"04a0", X"fc8a", X"0064",
                                                        X"0206", X"fb7c", X"fafb", X"016b", X"0232", X"f9e4", X"fd40", X"ff98", X"fcc9", X"fd7a", X"ff42", X"ff47", X"0002", X"05a7",
                                                        X"fa18", X"ff37", X"02e5", X"feba", X"0187", X"047c", X"fb78", X"fbac", X"fd4d", X"0164", X"0451", X"0560", X"ff39", X"fe0e",
                                                        X"fac2", X"0288", X"012c", X"fccd", X"0207", X"fd71", X"fd82", X"fb77", X"f7bb", X"0476", X"016a", X"ffaa", X"fcca", X"ffb1",
                                                        X"0229", X"fb5c", X"06a7", X"fd71", X"fe1a", X"ff29", X"02a2", X"01ae", X"fbc4", X"014a", X"feb6", X"0053", X"ff24", X"fa32",
                                                        X"fd69", X"0189", X"000b", X"fed3", X"fbf3", X"ffb7", X"0050", X"f8e6", X"024d", X"f9ea", X"fd86", X"fadd", X"fb4d", X"020e",
                                                        X"f72a", X"fb3e", X"fbb9", X"0142", X"0707", X"031f", X"fef4", X"fa8f", X"f7e6", X"ff4c", X"fdf4", X"fce3", X"003d", X"fb43",
                                                        X"fe38", X"0249", X"0835", X"ffe2", X"05da", X"fd4d", X"fbce", X"0392", X"fb22", X"fce6", X"f861", X"ff9e", X"00bf", X"ffe1",
                                                        X"0330", X"ff7d", X"0028", X"0275", X"fc6c", X"f824", X"fe4c", X"fb22", X"fda0", X"04b9", X"fd77", X"02af", X"ff13", X"fe8d",
                                                        X"fed7", X"0105", X"ff1b", X"fc7f", X"fa69", X"fbc1", X"01a9", X"fcdf", X"0856", X"fda7", X"fbb0", X"002d", X"f9bf", X"fb37",
                                                        X"ff70", X"059d", X"fd3c", X"00b2", X"050e", X"ff0b", X"f9a5", X"019d", X"03cb", X"faa6", X"027a", X"fcfe", X"fbe5", X"fcd3",
                                                        X"feed", X"fdcc", X"ff03", X"02c2", X"05f3", X"f935", X"fff5", X"fc12", X"fc50", X"0067", X"0417", X"f87a", X"0103", X"033c",
                                                        X"fec4", X"ff0f", X"0129", X"00ac", X"01cb", X"0617", X"ff81", X"fd1b", X"0363", X"f833", X"fb0e", X"fd33", X"fe2c", X"f8a9",
                                                        X"fc22", X"0277", X"01e3", X"fd44", X"00f6", X"fab0", X"fc6d", X"03a3", X"fd80", X"fe72", X"00be", X"fe4d", X"fcd9", X"faa2",
                                                        X"f984", X"fd15", X"0350", X"fe7a", X"065f", X"0152", X"fd9e", X"04d6", X"034f", X"0288", X"0307", X"f9c4", X"033d", X"fd6f",
                                                        X"f998", X"073b", X"fe46", X"008d", X"fcfc", X"fb57", X"febb", X"f9ee", X"fe76", X"03ab", X"01ab", X"ff09", X"f882", X"fa5b",
                                                        X"fa7e", X"039d", X"fcd8", X"fd80", X"04a5", X"fa50", X"03c9", X"f8d3", X"0632", X"00e3", X"0421", X"057d", X"ff84", X"035a",
                                                        X"fa7a", X"fced", X"fda3", X"fc06", X"00d7", X"0309", X"0446", X"fd61", X"fcd2", X"f7d6", X"ff02", X"fb2b", X"fc27", X"feb8",
                                                        X"fc95", X"fa4e", X"0224", X"f9ae", X"fec7", X"031d", X"fd28", X"febc", X"fdac", X"fac3", X"045b", X"fd3e", X"fe50", X"fb2a",
                                                        X"fb48", X"fc70", X"033e", X"faeb", X"022b", X"fc58", X"fa54", X"feb0", X"f914", X"0485", X"fb8b", X"047f", X"03be", X"fe30",
                                                        X"003a", X"fef2", X"fd1f", X"fa20", X"01b1", X"fb48", X"0527", X"fe1f", X"fbeb", X"fae3", X"fcb1", X"fe8f", X"02f9", X"028c",
                                                        X"003c", X"02be", X"ff9f", X"03cf", X"ff6f", X"fee8", X"fd60", X"005a", X"ff24", X"00ed", X"fb01", X"0507", X"fe76", X"0113",
                                                        X"fec8", X"feb6", X"fc5f", X"fa62", X"064d", X"02af", X"ffd2", X"0155", X"fc4b", X"00e1", X"ff13", X"0208", X"024a", X"000a",
                                                        X"fe6a", X"fa34", X"085a", X"022d", X"fbf5", X"fc21", X"0adb", X"fe49", X"f96f", X"fe68", X"048f", X"03e9", X"0004", X"fe94",
                                                        X"fa58", X"067b", X"fb9f", X"0579", X"0b02", X"00a2", X"0509", X"fd27", X"0565", X"0060", X"076b", X"fbb9", X"ffb4", X"04e7",
                                                        X"0423", X"fcf1", X"fb67", X"0080", X"0364", X"fba2", X"033c", X"f912", X"028a", X"fdcc", X"0a7c", X"fcff", X"fbbc", X"f997",
                                                        X"feb7", X"fb95", X"0165", X"f913", X"fc1c", X"049c", X"fedb", X"03b6", X"018d", X"fab3", X"0153", X"fd34", X"feec", X"045c",
                                                        X"014f", X"ff26", X"fbc6", X"f959", X"02b9", X"f9e1", X"fc0d", X"fc22", X"0481", X"fc96", X"0069", X"ffcc", X"001f", X"049d",
                                                        X"ff99", X"fbb0", X"fecb", X"003e", X"fc08", X"016b", X"0680", X"f98e", X"01a0", X"fe9b", X"0096", X"01b3", X"0478", X"0403",
                                                        X"0713", X"fd53", X"0055", X"fc87", X"fb23", X"f962", X"fb7f", X"0302", X"05e8", X"fbef", X"f910", X"034c", X"03cd", X"ff07",
                                                        X"04bd", X"0142", X"053e", X"01a2", X"020d", X"00ef", X"019b", X"fffc", X"04de", X"fac8", X"050f", X"014c", X"fa43", X"0058",
                                                        X"fe02", X"00be", X"fe1a", X"fdd9", X"09d3", X"fa91", X"0358", X"03c9", X"f8a5", X"ff80", X"01b4", X"020e", X"01e9", X"01b3",
                                                        X"0054", X"fcd8", X"fc09", X"02bf", X"fe36", X"0238", X"031c", X"0143", X"030d", X"f931", X"fcd1", X"04a0", X"0340", X"03a6",
                                                        X"03aa", X"fc3f", X"fc89", X"fd4f", X"f889", X"0190", X"01f7", X"fb9c", X"01b1", X"feb6", X"03be", X"fec4", X"fdf5", X"fc03",
                                                        X"fd7c", X"ff0d", X"004d", X"ff6a", X"0470", X"f83c", X"f9fc", X"03e7", X"fdc7", X"01be", X"fbc8", X"001e", X"006e", X"00ad",
                                                        X"043d", X"fe63", X"014c", X"fda0", X"0103", X"fa89", X"fdd3", X"ffb1", X"fb87", X"fe1b", X"0266", X"fba9", X"fe89", X"fa93",
                                                        X"04cd", X"0264", X"024c", X"037d", X"fed8", X"f896", X"0137", X"0383", X"fe50", X"ffe1", X"fe1b", X"ff34", X"fc20", X"03f1",
                                                        X"fad8", X"0326", X"fd83", X"ff35", X"fdc3", X"febe", X"fddb", X"f988", X"02ae", X"0174", X"02af", X"fc25", X"0268", X"fedf",
                                                        X"fd4c", X"fcff", X"0317", X"fa52", X"0270", X"f8b3", X"013d", X"fd84", X"00cc", X"fb8b", X"fc1b", X"006c", X"faea", X"fd0b",
                                                        X"01bd", X"0177", X"0650", X"fc1b", X"07ca", X"fb9c", X"fe7a", X"0266", X"fe00", X"0116", X"ff76", X"f7bf", X"fc55", X"fe16",
                                                        X"019f", X"02dd", X"fbd4", X"ff99", X"032b", X"00c5", X"065a", X"fcc7", X"00f4", X"00a5", X"01e4", X"04ec", X"ff4a", X"f5e2",
                                                        X"00fe", X"fe44", X"03cf", X"0159", X"00c9", X"fbdf", X"fe11", X"fb15", X"ffb9", X"f818", X"0154", X"014d", X"020a", X"fece",
                                                        X"f60c", X"fe52", X"fbfc", X"f8e9", X"030d", X"fb8a", X"fae0", X"fce2", X"00b8", X"fc4f", X"fd8b", X"02ef", X"023a", X"00cb",
                                                        X"03a5", X"feb7", X"00e8", X"f958", X"036d", X"fe17", X"fc49", X"0303", X"f964", X"0428", X"fbed", X"fffa", X"fd5f", X"0045",
                                                        X"054b", X"fe2d", X"ffc5", X"ff38", X"fc47", X"fd81", X"ffaa", X"006d", X"00c9", X"ff14", X"020b", X"0122", X"f9d4", X"fb1e",
                                                        X"fc2b", X"0482", X"fe54", X"fd01", X"016f", X"fb6b", X"ffc1", X"02c9", X"fc87", X"ffd6", X"005a", X"fe11", X"fa0d", X"052a",
                                                        X"01f7", X"0151", X"f979", X"fb72", X"01bb", X"00d6", X"0154", X"f7f1", X"00e0", X"fdc8", X"fc0a", X"f84c", X"044f", X"fcfe",
                                                        X"fb55", X"fbc4", X"028e", X"f8ea", X"0578", X"fc95", X"025a", X"0143", X"0544", X"fbce", X"01de", X"f94d", X"011c", X"f722",
                                                        X"0405", X"fb5e", X"fb80", X"fe28", X"0093", X"fea7", X"fd14", X"fe23", X"0298", X"ff39", X"0390", X"023d", X"fd48", X"0385",
                                                        X"fb49", X"ff72", X"fbe7", X"ffa7", X"ffee", X"0403", X"fd47", X"ffbb", X"0194", X"0182", X"0192", X"0092", X"022c", X"fb07",
                                                        X"f8ed", X"fcab", X"049b", X"fd9a", X"0064", X"fd5f", X"ffb1", X"026d", X"0777", X"fb80", X"fdf8", X"fcbb", X"03aa", X"feb1",
                                                        X"0244", X"fb66", X"fc61", X"045b", X"fb18", X"0398", X"fb2a", X"03e0", X"0118", X"0402", X"0381", X"ffd8", X"0008", X"fdb0",
                                                        X"0555", X"fdef", X"fd7d", X"fa92", X"0314", X"069b", X"fcfb", X"fc0d", X"fe4b", X"02a5", X"0135", X"02be", X"01fa", X"fb0c",
                                                        X"078e", X"017c", X"07e0", X"02f9", X"06f2", X"011e", X"fdfb", X"0107", X"fbee", X"ff8d", X"fecc", X"ff31", X"057a", X"0560",
                                                        X"0470", X"fc83", X"ff83", X"fdfd", X"02ad", X"fd70", X"ffac", X"050f", X"04a3", X"003e", X"00a7", X"ff58", X"fc0a", X"fb1c",
                                                        X"02e6", X"fff9", X"037d", X"0000", X"0029", X"fcad", X"0390", X"fc73", X"fe36", X"03fa", X"011d", X"005e", X"feea", X"02be",
                                                        X"fa57", X"01a1", X"0073", X"fda4", X"fc05", X"02ba", X"086d", X"f9e9", X"fc50", X"03b6", X"fae0", X"fa0f", X"fd27", X"ff38",
                                                        X"01d6", X"f8c0", X"f9dd", X"f88d", X"f8df", X"0603", X"fcf1", X"fff1", X"fc69", X"feb3", X"0334", X"f868", X"0002", X"f8e8",
                                                        X"ff99", X"021d", X"01c4", X"fa3b", X"0029", X"0278", X"fed5", X"055c", X"00d0", X"f82d", X"042c", X"fc7b", X"0133", X"02bc",
                                                        X"02e2", X"f92d", X"00af", X"01bb", X"047c", X"fa1a", X"fa27", X"04ae", X"ffbb", X"0118", X"06e0", X"fbf8", X"003b", X"ff61",
                                                        X"0711", X"0268", X"fa76", X"fe7a", X"0025", X"f918", X"0341", X"fa42", X"fdf4", X"0586", X"01ac", X"fe3f", X"fd48", X"fbc6",
                                                        X"064b", X"f9ba", X"01ea", X"feb6", X"f936", X"01b3", X"fb8f", X"f789", X"0419", X"fc76", X"0428", X"04ff", X"04d4", X"fe87",
                                                        X"0513", X"fdb7", X"01cd", X"fe91");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"fe91";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

