-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/model_pqt_2x2_w16a16/amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block109.vhd
-- Created: 2025-02-19 19:19:32
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block109
-- Source Path: model_pqt_2x2_w16a16/DUT HDL/Conv Layer 2/Filter Matrix Multiplier1/ParallelMACs 10/Weight Storage12/SinglePortRAM_generic
-- Hierarchy Level: 5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block109 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block109;


ARCHITECTURE rtl OF amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block109 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"c038", X"e315", X"d7c9", X"ef16", X"efd7", X"0201",
                                                        X"fc76", X"fba4", X"0127", X"1e95", X"1c7d", X"bb64", X"04e9", X"fc62", X"f7b6", X"f706", X"f82d", X"fc98", X"049e", X"0228",
                                                        X"098b", X"f4da", X"fd75", X"05d8");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"05d8";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

