-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/model_pqt_2x2_w16a16/amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block388.vhd
-- Created: 2025-02-19 19:19:39
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block388
-- Source Path: model_pqt_2x2_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage37/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block388 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block388;


ARCHITECTURE rtl OF amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block388 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"23de", X"fb19", X"0a85", X"0e06", X"10a7", X"1623",
                                                        X"fc08", X"1360", X"0f80", X"fe6c", X"0936", X"14b2", X"fb11", X"0aab", X"f75c", X"139c", X"17be", X"068c", X"087d", X"0595",
                                                        X"1088", X"0a37", X"0157", X"0bff", X"0c00", X"031e", X"121b", X"06fd", X"061b", X"1085", X"f9f9", X"09cf", X"156d", X"0888",
                                                        X"0293", X"050b", X"0d5c", X"153f", X"f801", X"1091", X"0bb5", X"0518", X"09d5", X"0ae2", X"0a6e", X"0483", X"05f5", X"0acd",
                                                        X"179c", X"0afe", X"05b7", X"0d3e", X"0668", X"07fb", X"0652", X"0c75", X"0000", X"fe09", X"0e4f", X"04ab", X"067c", X"06ff",
                                                        X"1f90", X"080d", X"202d", X"0778", X"0587", X"0b1b", X"0413", X"0c9c", X"fe0d", X"0965", X"02f2", X"fda9", X"07d6", X"0b1e",
                                                        X"0c9c", X"09d9", X"1280", X"0afa", X"16b4", X"0618", X"0ca5", X"0785", X"0941", X"fa93", X"004f", X"0db4", X"0285", X"fca3",
                                                        X"0699", X"0bf3", X"0642", X"1027", X"1418", X"0c57", X"15ac", X"08b8", X"0e08", X"0340", X"0a65", X"060f", X"f9d4", X"0d55",
                                                        X"06a9", X"f555", X"0acd", X"09a7", X"07d8", X"01b4", X"078b", X"09e0", X"1181", X"fab8", X"0144", X"01a6", X"08ac", X"fe1a",
                                                        X"e485", X"0f25", X"fe07", X"f95f", X"07ea", X"04e6", X"f343", X"09a1", X"0c8e", X"09cf", X"078e", X"f868", X"fa97", X"fb7f",
                                                        X"06dc", X"0d1a", X"e3af", X"07f2", X"03e1", X"f80d", X"0a49", X"021a", X"f97c", X"f919", X"fd47", X"0af6", X"07c0", X"0069",
                                                        X"f940", X"fdf7", X"0439", X"001d", X"e820", X"f982", X"f9c7", X"f949", X"ff93", X"004a", X"06b4", X"f313", X"f23d", X"003a",
                                                        X"f300", X"ffa1", X"fd7e", X"fbf8", X"02ca", X"0f90", X"eb05", X"fbe5", X"fdec", X"faa2", X"053c", X"f565", X"fa32", X"f683",
                                                        X"0dad", X"f7b3", X"02b5", X"fb30", X"04cc", X"fcb5", X"fbda", X"f6d6", X"e808", X"f7da", X"fb0c", X"f9b9", X"005c", X"f6e6",
                                                        X"f1d5", X"f431", X"fe43", X"f32d", X"fe5d", X"f369", X"03b0", X"fc70", X"f8f2", X"f70d", X"ea62", X"fbe4", X"0328", X"fa7a",
                                                        X"fbe8", X"f722", X"f64f", X"f1e2", X"0afb", X"011b", X"00c2", X"f717", X"fdf8", X"05ea", X"f329", X"f6ca", X"feb5", X"f7e2",
                                                        X"fb0e", X"011e", X"f99f", X"f6de", X"0a87", X"f373", X"223d", X"0184", X"fd87", X"f4b6", X"0011", X"009f", X"fcf7", X"f453",
                                                        X"027d", X"f896", X"f873", X"fb76", X"fcc5", X"fe07", X"f399", X"fb29", X"075b", X"fdca", X"0850", X"fbd6", X"ff3e", X"fafa",
                                                        X"f84c", X"f8b2", X"fc56", X"f6cd", X"f7a7", X"fc6e", X"febc", X"f476", X"fb85", X"ff30", X"0428", X"fbac", X"0517", X"0084",
                                                        X"fc13", X"019f", X"f6db", X"00d9", X"f0ae", X"000e", X"f9a6", X"fc62", X"f689", X"fcc8", X"fa9b", X"04e8", X"146e", X"f96a",
                                                        X"0aa3", X"0060", X"0075", X"0337", X"f6c7", X"00e0", X"fa42", X"fc2f", X"01bd", X"fba6", X"fdb7", X"0464", X"feec", X"0156",
                                                        X"fd46", X"07c8", X"1456", X"fc0a", X"fee3", X"0078", X"f8f3", X"1406", X"f786", X"fe23", X"037c", X"ff9f", X"016f", X"0485",
                                                        X"f37f", X"04a5", X"fa5b", X"0940", X"0d95", X"02a1", X"1071", X"0889", X"fbb8", X"fdb3", X"f0ac", X"03d2", X"03b9", X"0278",
                                                        X"049f", X"0da4", X"09a7", X"0518", X"0834", X"fcd4", X"0cfd", X"0478", X"fdf0", X"0960", X"0086", X"f638", X"ecb4", X"04fb",
                                                        X"070a", X"f863", X"0614", X"0228", X"06b9", X"069f", X"fd9f", X"087f", X"03cd", X"fdc7", X"0769", X"0662", X"0379", X"0a3e",
                                                        X"eaa0", X"0349", X"0514", X"ffdf", X"04ad", X"0b9d", X"ffd6", X"06c5", X"0ce6", X"046f", X"10c1", X"0772", X"0428", X"0281",
                                                        X"0531", X"07a9", X"ec93", X"0438", X"0397", X"0267", X"0968", X"0314", X"fc4e", X"0555", X"1214", X"ff47", X"15a1", X"fb16",
                                                        X"fd2b", X"06c9", X"0467", X"07bb", X"fa58", X"02b9", X"fbf0", X"00e1", X"01a1", X"0312", X"0a56", X"fd46", X"06b6", X"ffc4",
                                                        X"08c1", X"fd15", X"fc97", X"ff61", X"f9c2", X"027d", X"027c", X"fbce", X"fca7", X"fb12", X"fede", X"f9ec", X"fe43", X"0034",
                                                        X"0f68", X"fe9d", X"0773", X"ffdc", X"ffb9", X"fd8b", X"fb67", X"0385", X"00a4", X"fc1e", X"fffb", X"f91c", X"fc51", X"0082",
                                                        X"fdea", X"f774", X"18dd", X"03ec", X"fe2b", X"fc4b", X"fecd", X"fc2c", X"fbe3", X"f854", X"f7ad", X"f87f", X"f988", X"fefc",
                                                        X"fdf9", X"fd91", X"0496", X"fb7a", X"ed17", X"f8ed", X"fadf", X"fd43", X"f9b1", X"f9f7", X"f73f", X"fb06", X"e4dc", X"faca",
                                                        X"f464", X"fe53", X"f7c5", X"f99b", X"fe1a", X"f435", X"fe84", X"f868", X"f859", X"f521", X"fe16", X"f72f", X"fa20", X"ffbe",
                                                        X"ee8f", X"f4bb", X"fa91", X"f566", X"f7cf", X"f895", X"f3cc", X"e7c5", X"faf5", X"fd0c", X"f7a8", X"f769", X"f742", X"f614",
                                                        X"fd57", X"f3a5", X"f91c", X"ed2c", X"f5ce", X"fc71", X"eabb", X"fc29", X"f0df", X"ed0b", X"0231", X"fcbc", X"02d6", X"f01f",
                                                        X"f3db", X"f263", X"fd07", X"0737", X"0556", X"f1e8", X"eea4", X"f42a", X"eb2f", X"ff17", X"fb3c", X"ee97", X"054c", X"f82f",
                                                        X"fbbf", X"f759", X"fb42", X"fa52", X"f211", X"fe35", X"ff4c", X"f3a7", X"fdb8", X"00ad", X"f344", X"fb37", X"00a3", X"ed06",
                                                        X"1393", X"fd85", X"f72e", X"f3a1", X"0493", X"f9a0", X"f7c1", X"eeaf", X"f42c", X"eeff", X"eeba", X"fa89", X"f003", X"f6e1",
                                                        X"020b", X"efb7", X"17b8", X"fa6a", X"05b5", X"f716", X"fcbe", X"fba4", X"efe3", X"fd1c", X"f606", X"f6b9", X"f624", X"0651",
                                                        X"f1d4", X"ff54", X"0ba2", X"f084", X"fefb", X"f8ce", X"f7c5", X"00c8", X"fd2a", X"fa6c", X"f60c", X"fb33", X"e607", X"fa00",
                                                        X"f743", X"09e7", X"fdd7", X"01bd", X"ffb9", X"f13b", X"f207", X"f564", X"01f1", X"0099", X"0131", X"0634", X"fd50", X"07b5",
                                                        X"e74f", X"f94f", X"047d", X"fd2f", X"fe97", X"fe10", X"04f1", X"046a", X"f1ba", X"fc8f", X"099f", X"faa0", X"03f4", X"06b7",
                                                        X"018e", X"046a", X"ead3", X"f971", X"03de", X"f8de", X"006f", X"0489", X"0a09", X"034a", X"f2b3", X"0578", X"1190", X"fe0f",
                                                        X"0436", X"03d2", X"00c2", X"f9d3", X"efd6", X"069c", X"0127", X"fef4", X"04d5", X"031a", X"05a4", X"060d", X"04e8", X"fe44",
                                                        X"08dd", X"fd44", X"0903", X"0a08", X"02cb", X"0974", X"05a4", X"0635", X"06d7", X"fc94", X"0c11", X"0760", X"02a4", X"07ee",
                                                        X"047f", X"05ea", X"0ec0", X"0a73", X"0c24", X"04b3", X"06d2", X"0e13", X"feb7", X"0fc1", X"0aac", X"f8cb", X"0e8c", X"030c",
                                                        X"0af5", X"0ced", X"09eb", X"0c65", X"0941", X"086e", X"035c", X"073a", X"05d8", X"142a", X"f4b3", X"05d3", X"048d", X"0204",
                                                        X"110c", X"0051", X"05d4", X"0745", X"0729", X"07e5", X"0c01", X"07aa", X"08dc", X"05c9", X"001d", X"164a", X"f81d", X"1072",
                                                        X"057c", X"ff67", X"062f", X"0b26", X"0b03", X"05ae", X"fdeb", X"0c86", X"0764", X"01e9", X"0d77", X"fcba", X"02c0", X"10f0",
                                                        X"027f", X"0504", X"07f4", X"feba", X"039e", X"04f7", X"09fd", X"07df", X"ff55", X"0772", X"0eb5", X"057e", X"0bd5", X"0b2f",
                                                        X"fa40", X"0db5", X"f906", X"06ea", X"0a6a", X"faeb", X"0edf", X"fc5c", X"11f8", X"02c1", X"0f40", X"0857", X"11b8", X"02cd",
                                                        X"01b5", X"0b94", X"0678", X"0882", X"f7e5", X"0817", X"031e", X"0056", X"0ee3", X"090c", X"1351", X"0c7c", X"0d1a", X"05d4",
                                                        X"1552", X"0a4e", X"0714", X"0db2", X"0a98", X"fa29", X"f520", X"0f04", X"09d9", X"0c4d", X"0e57", X"05a9", X"12a3", X"08ec",
                                                        X"023d", X"0d87", X"0d22", X"fce6", X"0491", X"03e2", X"0351", X"0c72", X"fb4c", X"054d", X"0800", X"076a", X"0ca2", X"0cac",
                                                        X"07cd", X"089f", X"0a50", X"0e81", X"0ed8", X"fefb", X"0571", X"0605", X"02b4", X"0c11", X"e850", X"095b", X"02b1", X"fb94",
                                                        X"06ea", X"0520", X"0406", X"15ca", X"0021", X"0bbf", X"0e85", X"fbf3", X"fb76", X"04e6", X"0661", X"1648", X"eb09", X"03b8",
                                                        X"026e", X"f7e8", X"0bc8", X"0481", X"ff05", X"1204", X"0dcb", X"02a6", X"07f9", X"0bd9", X"f978", X"009e", X"01d5", X"0332",
                                                        X"fdb8", X"080b", X"fbec", X"06aa", X"0592", X"0649", X"fc44", X"02b0", X"1250", X"006e", X"0e27", X"03b9", X"0207", X"fec1",
                                                        X"0427", X"0834", X"089e", X"08bc", X"fd62", X"05cf", X"0ec6", X"078c", X"01f0", X"0b40", X"1472", X"0234", X"1047", X"03d7",
                                                        X"01cc", X"06f5", X"04e9", X"14ce", X"fe7b", X"0a0b", X"0aae", X"0173", X"0412", X"029a", X"140d", X"090e", X"1147", X"05c9",
                                                        X"1843", X"066b", X"0542", X"0d4e", X"ffcb", X"fc16", X"efab", X"0e98", X"08c0", X"015d", X"0a75", X"0ce9", X"11d4", X"1363",
                                                        X"09bd", X"07a9", X"0d25", X"018c", X"fe89", X"0045", X"fe47", X"10e2", X"f19f", X"0678", X"036b", X"fad5", X"08b6", X"04e1",
                                                        X"fea6", X"1206", X"0403", X"09a2", X"0edc", X"0052", X"fe04", X"066b", X"fef0", X"0372", X"f1ad", X"088d", X"080b", X"031d",
                                                        X"0ed2", X"0ea0", X"09fc", X"03a7", X"105d", X"0690", X"12e3", X"0226", X"0817", X"0579", X"05f5", X"0c37", X"fa0b", X"039f",
                                                        X"014b", X"00fe", X"0cec", X"0843", X"0401", X"fdd1", X"0f1e", X"0715", X"0edd", X"02ec", X"0201", X"026b", X"ffd0", X"0595",
                                                        X"03d1", X"0005", X"0514", X"017c", X"09a6", X"fe17", X"0f64", X"013d", X"1501", X"fe2b", X"0f8f", X"f9f4", X"00e8", X"0666",
                                                        X"0366", X"eac2", X"f898", X"fe06", X"00fe", X"fa34", X"02a0", X"011f", X"0845", X"0283", X"f59d", X"04f7", X"080a", X"faab",
                                                        X"faa9", X"f9e8", X"fbf4", X"fc8c", X"f43e", X"f94d", X"fd45", X"f9e6", X"fd67", X"f4aa", X"ff3a", X"0072", X"0ba5", X"fcd9",
                                                        X"0031", X"f831", X"0251", X"f8d6", X"fa86", X"ede6", X"f0f4", X"f193", X"f430", X"000a", X"fa40", X"007d", X"09c8", X"f775",
                                                        X"0b00", X"fa59", X"f785", X"f64b", X"02f4", X"f7fe", X"f533", X"f57f", X"f01d", X"ec6a", X"f4a7", X"003b", X"f57c", X"f811",
                                                        X"025a", X"e62a", X"0e19", X"f4aa", X"fb13", X"ed5d", X"fdbc", X"fabc", X"e7dc", X"eca1", X"ed3a", X"e737", X"efbe", X"f8dc",
                                                        X"ef70", X"f61d", X"044d", X"eb9f", X"f6a3", X"f40d", X"f784", X"efce", X"fa5d", X"f513", X"f067", X"f338", X"ed59", X"e20f",
                                                        X"ec67", X"fc6d", X"e56c", X"f72f", X"fc98", X"e9c3", X"eb4b", X"f02e", X"eefc", X"e9f2", X"f3ca", X"f41e", X"ec2f", X"dfcf",
                                                        X"f228", X"e7b9", X"ed64", X"f615", X"e32d", X"ef67", X"f25c", X"e646", X"fab8", X"f0e2", X"efc5", X"ed8b", X"f32d", X"e5d9",
                                                        X"e8fe", X"f433", X"f7df", X"e171", X"efd3", X"fcdd", X"e18a", X"ef7e", X"f737", X"e85f", X"f4cf", X"eed3", X"e5d7", X"f31e",
                                                        X"f6be", X"f3c8", X"ee03", X"ea25", X"f713", X"e18c", X"ed86", X"ff19", X"e197", X"f6ee", X"0514", X"e5b6", X"0f46", X"f903",
                                                        X"e6f8", X"f31a", X"f6cd", X"f202", X"e771", X"ef20", X"0729", X"e4c1", X"ead5", X"fff0", X"e62f", X"f305", X"f99f", X"ec67",
                                                        X"0694", X"eab6", X"f5e5", X"f77d", X"fcb4", X"f6d2", X"e998", X"f3e1", X"f805", X"eeb8", X"ed3e", X"0194", X"ee69", X"fae3",
                                                        X"fca0", X"f356", X"f623", X"ef03", X"f898", X"f881", X"f6f8", X"01db", X"eb31", X"f5a9", X"f374", X"ec89", X"f5f4", X"fe37",
                                                        X"ed62", X"fa40", X"f532", X"f560", X"f99c", X"f923", X"fe5e", X"f32d", X"0245", X"fb98", X"f781", X"0157", X"efb6", X"f30e",
                                                        X"efe6", X"f949", X"f95f", X"ff8c", X"ff6c", X"03e0", X"edd1", X"f79b", X"03ba", X"fcc7", X"056b", X"028f", X"fc2e", X"fe1a",
                                                        X"f54f", X"0100", X"fcda", X"005e", X"0172", X"fc50", X"04ff", X"fa48", X"0661", X"fb71", X"01b9", X"0325", X"0204", X"02b2",
                                                        X"008e", X"0eff", X"fb6c", X"0310", X"00d6", X"fca4", X"0580", X"0008", X"eff5", X"01ef", X"13e9", X"fef5", X"0cc1", X"0504",
                                                        X"fba1", X"0630", X"fda7", X"1363", X"f8e8", X"094e", X"051c", X"fe01", X"0c02", X"03fb", X"faa4", X"0dde", X"0613", X"0c8a",
                                                        X"194c", X"0aee", X"0227", X"04f1", X"fe06", X"16d3", X"019d", X"1029", X"0c2f", X"f908", X"0ea3", X"037c", X"fb73", X"1062",
                                                        X"0c9b", X"02ec", X"185f", X"0aad", X"0a64", X"0e0f", X"09c8", X"134b", X"019b", X"11ca", X"0961", X"06ed", X"0c60", X"0ce5",
                                                        X"fc19", X"0f97", X"0c36", X"0616", X"1e89", X"0d78", X"087e", X"0fb3", X"1148", X"1003", X"0731", X"14eb", X"0dcc", X"0f6d",
                                                        X"170e", X"1084", X"062a", X"10e0", X"0a5d", X"06ef", X"2718", X"11f7", X"05cf", X"0472", X"1026", X"0d79", X"007a", X"1644",
                                                        X"12da", X"02ac", X"132c", X"0f96", X"0487", X"1379", X"0285", X"0ab8", X"123c", X"08c6", X"0744", X"1034", X"0f45", X"2bbe",
                                                        X"fb38", X"10f4", X"0f1e", X"041b", X"0ca6", X"1630", X"10ce", X"1023", X"0863", X"0ae4", X"10fb", X"099d", X"0cfb", X"0780",
                                                        X"0655", X"1981", X"fd3e", X"1200", X"0dea", X"0012", X"12fe", X"169c", X"0460", X"08db", X"07c4", X"0724", X"1561", X"081a",
                                                        X"0220", X"0799", X"0216", X"143d", X"fbb4", X"0e04", X"0a93", X"fc84", X"0704", X"fe26", X"0bdb", X"082d", X"05ba", X"098e",
                                                        X"1354", X"0832", X"fd95", X"0283", X"fc7e", X"0902", X"f8dc", X"0303", X"06be", X"010f", X"08aa", X"07f3", X"0f70", X"fafc",
                                                        X"fbdb", X"03b4", X"0bfc", X"0412", X"03bd", X"022c", X"02e5", X"fb5d", X"f751", X"04b2", X"f7e9", X"08c6", X"007b", X"00af",
                                                        X"0aae", X"fb5f", X"fed7", X"fd8d", X"0750", X"017d", X"06fd", X"05d4", X"0348", X"fc99", X"fef5", X"021e", X"0526", X"04fd",
                                                        X"f844", X"fa98", X"0e43", X"f74d", X"01a6", X"05e0", X"07e6", X"f763", X"017e", X"fc88", X"00a2", X"f0c6", X"f426", X"f9b5",
                                                        X"fb10", X"fb75", X"fa69", X"fe50", X"0996", X"f5d9", X"fefa", X"005a", X"0534", X"f9f4", X"f978", X"f899", X"fc8e", X"fccf",
                                                        X"ecbc", X"f31c", X"ff85", X"fffb", X"fc0a", X"0871", X"fd02", X"f712", X"fd65", X"fe31", X"fd9f", X"f900", X"fc11", X"fbfe",
                                                        X"fef9", X"0272", X"e9bc", X"f31a", X"faa0", X"fe7e", X"f5d2", X"0301", X"f0a9", X"fb7f", X"e9f9", X"fd63", X"0509", X"fca2",
                                                        X"f7dc", X"fbd2", X"00e8", X"15e7", X"f58e", X"f9cc", X"f528", X"fb81", X"fcce", X"fc0f", X"fa19", X"f36a", X"fc3b", X"fcba",
                                                        X"09e7", X"fa7b", X"025b", X"0411", X"fb40", X"fff7", X"e64a", X"00fb", X"0238", X"f693", X"fc19", X"ffbf", X"fdf8", X"f935",
                                                        X"04dd", X"fbd4", X"13b6", X"fd99", X"ffae", X"02ec", X"fb6b", X"f9a7", X"e8ce", X"0518", X"0395", X"fad1", X"002a", X"016f",
                                                        X"fa2c", X"0142", X"fc3b", X"ff8f", X"0b11", X"fc20", X"fe87", X"0779", X"079c", X"fa01", X"fd90", X"03bb", X"00c6", X"fb9a",
                                                        X"0ab6", X"0601", X"fa11", X"0357", X"f411", X"0813", X"0f38", X"055a", X"01d6", X"025e", X"ffda", X"f75a", X"04c3", X"0128",
                                                        X"0abe", X"f809", X"0370", X"fddf", X"033b", X"ffa7", X"0a4f", X"0533", X"1211", X"0541", X"0a79", X"077d", X"00f8", X"0713",
                                                        X"059d", X"0d14", X"0288", X"0428", X"00ab", X"035c", X"0a9e", X"0686", X"129c", X"030d", X"1293", X"0814", X"045b", X"09e8",
                                                        X"02dd", X"f4f9", X"fb66", X"0d2a", X"0ea0", X"01f1", X"0760", X"06fb", X"0595", X"0cbc", X"05c2", X"08a6", X"1e82", X"09df",
                                                        X"f835", X"03dc", X"03fa", X"0284", X"f53f", X"0e94", X"0e65", X"fa45", X"12e0", X"08d0", X"f8e5", X"0ce5", X"0c97", X"0dc0",
                                                        X"1ed2", X"022c", X"ff25", X"0c28", X"0b15", X"07dd", X"f437", X"1284", X"086d", X"f739", X"1219", X"0cd5", X"050e", X"0843",
                                                        X"ff1e", X"0b4d", X"183a", X"0aec", X"fe33", X"0a13", X"0db2", X"0833", X"e5c9", X"14f5", X"064c", X"fe54", X"0dd6", X"0983",
                                                        X"0788", X"0ef8", X"fe07", X"00d8", X"19b6", X"0859", X"06dd", X"08a6", X"0517", X"09bc", X"f7e3", X"04fa", X"0ad5", X"03f7",
                                                        X"0eae", X"ffe1", X"ffc6", X"0323", X"0a1a", X"0e37", X"1716", X"fe2a", X"0790", X"ff3b", X"05c7", X"0a47", X"fce7", X"03f5",
                                                        X"0147", X"fbef", X"06ba", X"05d0", X"0303", X"04ab", X"0aa3", X"012b", X"1522", X"0032", X"01ed", X"0407", X"05d7", X"03c6",
                                                        X"f444", X"07ca", X"036c", X"fbb6", X"0cf3", X"01e2", X"0324", X"04ed", X"10ba", X"0009", X"068a", X"fd01", X"fb52", X"fb40",
                                                        X"fbbf", X"0a7e", X"ee88", X"0440", X"05d1", X"fa17", X"05e4", X"f766", X"0e65", X"fe6a", X"172f", X"f82a", X"04a6", X"fbee",
                                                        X"0573", X"fc79", X"f821", X"0176", X"eeb1", X"fcbe", X"03a8", X"fa5a", X"01f3", X"fda1", X"0299", X"fd37", X"0ca4", X"f9ed",
                                                        X"04e2", X"fdef", X"0292", X"fffd", X"f774", X"00db", X"f8de", X"f78f", X"01a1", X"fcd0", X"f708", X"f9e2", X"fdf7", X"f0bf",
                                                        X"1124", X"f462", X"012c", X"f43b", X"f5e9", X"f2f5", X"f3d6", X"07c6", X"f74c", X"f30e", X"fd66", X"f602", X"fca2", X"f526",
                                                        X"04c7", X"f8a4", X"f340", X"fc4d", X"f858", X"f291", X"f01b", X"fcae", X"f900", X"094b", X"efa3", X"ec2f", X"f77a", X"f6a4",
                                                        X"f8b5", X"f2ff", X"fe83", X"f4d1", X"f59c", X"f638", X"f2e2", X"ed47", X"f65e", X"f979", X"f2d5", X"eb4b", X"e304", X"e873",
                                                        X"f25a", X"f266", X"f605", X"effc", X"0007", X"e9a8", X"0ab0", X"f4fd", X"fa28", X"e8c1", X"f430", X"f279", X"eafc", X"f289",
                                                        X"ff9e", X"e83c", X"f7db", X"f847", X"e7de", X"ec11", X"083e", X"eb1f", X"f16a", X"f457", X"f38d", X"ee74", X"f2b2", X"f711",
                                                        X"f2f3", X"f688", X"f29e", X"e21e", X"eee2", X"ff33", X"f11e", X"f0b6", X"0824", X"e1ae", X"e607", X"f08a", X"f317", X"eb79",
                                                        X"f845", X"f22a", X"f17d", X"f6e3", X"e708", X"e86f", X"eca4", X"f647", X"f0f3", X"f51e", X"f341", X"e6f8", X"f5a6", X"eedc",
                                                        X"f45f", X"ea3e", X"fb1c", X"f392", X"e9b8", X"fb90", X"efa1", X"e946", X"e953", X"f043", X"e06d", X"ec22", X"fe0f", X"e766",
                                                        X"0426", X"ee42", X"eb79", X"efce", X"f91e", X"f2ac", X"e8fe", X"e390", X"f287", X"e525", X"eb43", X"f538", X"e437", X"e89a",
                                                        X"f458", X"e3b1", X"f634", X"e634", X"ebaf", X"f3c8", X"f7b6", X"f82d", X"e691", X"e549", X"01e5", X"e78a", X"eb48", X"f5df",
                                                        X"e7cb", X"f3b0", X"008c", X"eb5d", X"e868", X"f344", X"f1de", X"effa", X"fae8", X"f7e9", X"f39f", X"e737", X"f94d", X"ec64",
                                                        X"f453", X"fafc", X"e28b", X"f479", X"0595", X"f565", X"f321", X"f66e", X"fb45", X"f59e", X"f015", X"fb4d", X"f3e5", X"e229",
                                                        X"f8db", X"f1e2", X"f849", X"f9a1", X"ec3a", X"f82a", X"0223", X"f63e", X"e6ee", X"f71b", X"f252", X"f1c3", X"f3c9", X"f68a",
                                                        X"f9ee", X"01da", X"feb5", X"f66e", X"fe06", X"eebc", X"f3e7", X"f203", X"f7cd", X"f80e", X"0601", X"ff88", X"0145", X"033d",
                                                        X"ef4b", X"fc9c", X"f7b4", X"07df", X"f081", X"fc6c", X"f88b", X"fc40", X"fe6a", X"f52b", X"031c", X"0077", X"0a6b", X"ff54",
                                                        X"fcf6", X"01ea", X"025a", X"09d3", X"fabc", X"0174", X"f602", X"01e8", X"fd01", X"fdae", X"fea2", X"00b7", X"04a7", X"0208",
                                                        X"1595", X"fd45", X"0839", X"fe3f", X"07a3", X"0573", X"ff84", X"0025", X"f180", X"0479", X"fba6", X"05ee", X"059f", X"013a",
                                                        X"0684", X"03b3", X"0473", X"02c1", X"0a72", X"0657", X"0cd1", X"0cff", X"05c7", X"fe1e", X"f6aa", X"0aef", X"04e8", X"fb81",
                                                        X"04c2", X"081f", X"fda9", X"06c1", X"fc41", X"0971", X"0c94", X"036e", X"0305", X"0c37", X"004c", X"0b5f", X"f5a6", X"0b39",
                                                        X"011c", X"fb37", X"04f1", X"09dd", X"fb85", X"0327", X"0614", X"071e", X"0b77", X"02f5", X"067d", X"0bbe", X"01bb", X"107d",
                                                        X"fcd0", X"08d2", X"04bc", X"fa0f", X"0c01", X"0583", X"015a", X"11b9", X"1313", X"119b", X"10a3", X"0960", X"0153", X"09a2",
                                                        X"0ec2", X"0c5e", X"fdac", X"06c7", X"06f1", X"fb54", X"09c0", X"fbd3", X"033f", X"0dd7", X"061f", X"0441", X"1511", X"0967",
                                                        X"0064", X"0800", X"05d3", X"12b5", X"02cf", X"08c3", X"0c0d", X"f8b6", X"12d5", X"06b4", X"ff38", X"0eb2", X"0cae", X"0c4c",
                                                        X"1adb", X"08f0", X"fd1c", X"0447", X"0e3b", X"10bd", X"02f5", X"0d1b", X"0819", X"fd29", X"1631", X"00eb", X"fe64", X"12ae",
                                                        X"0a61", X"09ce", X"1487", X"06af", X"fe86", X"0bad", X"0ab4", X"1027", X"f73b", X"17c8", X"06b0", X"fcf7", X"0c13", X"09cf",
                                                        X"1074", X"13c7", X"0ee1", X"0b8a");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"0b8a";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

