-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/model_pqt_2x2_w16a16/amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block451.vhd
-- Created: 2025-02-19 19:19:45
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block451
-- Source Path: model_pqt_2x2_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage94/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block451 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block451;


ARCHITECTURE rtl OF amc_cnn_16w16a_ptq_src_SinglePortRAM_generic_block451 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"f3c1", X"0ad5", X"f8d8", X"fee3", X"0470", X"01ca",
                                                        X"075c", X"fc56", X"0175", X"fff1", X"fd5f", X"ff5b", X"0423", X"fe54", X"0810", X"f61b", X"fbdd", X"06bf", X"fff8", X"f87f",
                                                        X"fd54", X"f985", X"ffec", X"fc6b", X"07b4", X"0015", X"002c", X"fce9", X"f86c", X"01ff", X"0486", X"f9c2", X"ffd4", X"0272",
                                                        X"f80e", X"f7d2", X"027c", X"064f", X"ff9d", X"06f7", X"0b6f", X"0885", X"08fd", X"fa35", X"0928", X"fb10", X"0693", X"066d",
                                                        X"07d1", X"00e4", X"faeb", X"fad7", X"f260", X"f587", X"ffbb", X"fffd", X"02ec", X"fd01", X"0553", X"05c5", X"0569", X"ff9d",
                                                        X"fce7", X"fefb", X"fa1c", X"fdfa", X"fde7", X"f73e", X"fb44", X"01c8", X"f36b", X"fe38", X"0397", X"fd5c", X"0243", X"f824",
                                                        X"fb87", X"f687", X"006e", X"f833", X"ff06", X"ff72", X"fa27", X"fa82", X"016a", X"fe48", X"007d", X"f92c", X"00e2", X"06aa",
                                                        X"ff5e", X"fde8", X"0917", X"fa7e", X"f7d6", X"0478", X"fcf8", X"053c", X"fdc8", X"f6de", X"f8c8", X"07af", X"fd54", X"f973",
                                                        X"f821", X"feab", X"028a", X"f732", X"0304", X"f149", X"00c5", X"f760", X"f6a3", X"059d", X"fe7f", X"fb09", X"fdfe", X"05ac",
                                                        X"0634", X"fc19", X"f6f9", X"fc51", X"0037", X"f4fa", X"04cd", X"f753", X"0536", X"f732", X"fb7e", X"0015", X"055d", X"fb5c",
                                                        X"0192", X"0272", X"07b5", X"00d0", X"f959", X"fdf2", X"f920", X"007c", X"048e", X"024d", X"00ab", X"0225", X"04b8", X"086f",
                                                        X"0716", X"00aa", X"f95e", X"f3a1", X"00d0", X"fb4b", X"fd93", X"fc6a", X"01a0", X"f99f", X"fdcf", X"0672", X"0409", X"fd39",
                                                        X"ffda", X"018a", X"fe46", X"02df", X"00aa", X"00e1", X"fd66", X"049f", X"f3f0", X"fd8e", X"fa32", X"0125", X"fcd6", X"04ef",
                                                        X"fec2", X"f670", X"f932", X"fa8c", X"fed2", X"ffa3", X"fbd0", X"007d", X"fc5f", X"fa19", X"fbd1", X"02f2", X"0209", X"fb3d",
                                                        X"ff9d", X"ffaf", X"000b", X"fbaa", X"fe54", X"ff03", X"04b1", X"f86c", X"ff2b", X"0ad3", X"0116", X"f7b9", X"00c9", X"fc33",
                                                        X"f80f", X"fa2b", X"f94a", X"fb8c", X"fc16", X"f505", X"fc5b", X"0406", X"ffcf", X"0272", X"00a0", X"fb36", X"02f8", X"f4b8",
                                                        X"0135", X"02e7", X"ff6c", X"f8c8", X"047a", X"f2a9", X"0550", X"03f9", X"0170", X"fed4", X"f93e", X"064b", X"05a6", X"f64b",
                                                        X"fd48", X"fa81", X"fb1e", X"0605", X"04a0", X"0518", X"0294", X"f7bc", X"03c1", X"fae5", X"fa2f", X"01e2", X"020e", X"fcb8",
                                                        X"01c8", X"fdd9", X"0527", X"ffad", X"fb79", X"045b", X"ffce", X"ffa2", X"07d2", X"0202", X"0911", X"fd3b", X"01bf", X"0370",
                                                        X"fda3", X"0366", X"0601", X"fa0f", X"08b2", X"fd83", X"003d", X"f81a", X"0355", X"f409", X"fed2", X"ff58", X"02c2", X"0a78",
                                                        X"fdbd", X"fde5", X"007b", X"fd4d", X"ffd9", X"0b4c", X"00ea", X"f7fb", X"061a", X"f4b1", X"fd44", X"fb67", X"f5d4", X"f6ac",
                                                        X"0728", X"0776", X"fb22", X"0815", X"0196", X"fb11", X"fdc7", X"fab9", X"0269", X"ff32", X"06b8", X"f1f7", X"05a0", X"0310",
                                                        X"f723", X"ffbc", X"065c", X"faf2", X"fadf", X"ff21", X"ff53", X"043e", X"0614", X"07c5", X"feed", X"010c", X"0047", X"fe20",
                                                        X"039c", X"0545", X"fb8d", X"00f9", X"f853", X"f5d4", X"ff2f", X"00b1", X"0431", X"0471", X"06cf", X"08d2", X"06f7", X"0677",
                                                        X"fb0d", X"fd8e", X"fc4a", X"f8ea", X"f727", X"fb79", X"f95d", X"fa76", X"f14f", X"ff3e", X"0353", X"0083", X"f903", X"f7d1",
                                                        X"0883", X"f72d", X"021e", X"f95d", X"fa1c", X"f7b5", X"00c1", X"f6c4", X"0a64", X"fa6c", X"f696", X"059a", X"f9fc", X"f9d1",
                                                        X"fead", X"01ce", X"06e1", X"f9cb", X"fd5a", X"fffa", X"01a3", X"f8ad", X"05f2", X"0154", X"ffaa", X"0375", X"fbe2", X"fe44",
                                                        X"0251", X"fb33", X"fe32", X"f9e6", X"0737", X"fe69", X"fd4b", X"01a5", X"0119", X"0315", X"058e", X"fdaf", X"0140", X"f8ea",
                                                        X"fbed", X"0381", X"fa25", X"0149", X"01fc", X"feb8", X"fe4c", X"fbc9", X"fc76", X"008f", X"fa55", X"fcc3", X"fb9d", X"fd60",
                                                        X"0ef2", X"fd4c", X"0153", X"0506", X"fca6", X"f4d9", X"fe74", X"0490", X"fe1e", X"fb62", X"071c", X"fe42", X"06b1", X"fcd6",
                                                        X"fa7e", X"f175", X"f9fd", X"06ee", X"ff1e", X"03db", X"01ff", X"f87f", X"fdde", X"ffea", X"ffc5", X"f818", X"0677", X"0bd0",
                                                        X"07f1", X"fd20", X"07e1", X"f8b5", X"fe95", X"fe00", X"ff58", X"fdf7", X"02ef", X"042f", X"0578", X"ff37", X"feb8", X"f61c",
                                                        X"fe3e", X"0154", X"0a92", X"f937", X"ff65", X"0357", X"02c1", X"ff9d", X"050b", X"0338", X"02dc", X"feb5", X"02ea", X"0261",
                                                        X"024e", X"f9b2", X"06cd", X"02ae", X"ffb2", X"fe8d", X"03e2", X"f855", X"0286", X"f870", X"fbbe", X"ff1d", X"01c9", X"fdbd",
                                                        X"ff97", X"faf7", X"0115", X"ffb2", X"0aad", X"fa10", X"fd32", X"04a7", X"f85e", X"fc61", X"09f1", X"ff4b", X"0041", X"ff09",
                                                        X"f877", X"fffe", X"f888", X"027c", X"ffc4", X"0913", X"f93d", X"fb81", X"00ac", X"fdff", X"0595", X"f828", X"05d2", X"0025",
                                                        X"f984", X"0401", X"0122", X"f974", X"fc38", X"ff3e", X"02e0", X"feb7", X"fd56", X"fef3", X"fa34", X"039b", X"fcfb", X"fdef",
                                                        X"fc87", X"0119", X"f986", X"04b5", X"08e5", X"0758", X"fb3e", X"fab4", X"fdad", X"0384", X"fdea", X"fb8d", X"f9d2", X"ff8a",
                                                        X"006e", X"04fb", X"0255", X"05e6", X"fd33", X"f988", X"fbe8", X"fc45", X"fb8b", X"01bf", X"faa1", X"fa27", X"f901", X"02f4",
                                                        X"0642", X"fce4", X"fb26", X"0327", X"f5ff", X"0258", X"002c", X"fe4a", X"038f", X"ff31", X"0594", X"0366", X"f8aa", X"ff08",
                                                        X"fbdf", X"013d", X"06d2", X"01a2", X"fab7", X"093c", X"f771", X"f965", X"ffac", X"04e2", X"054f", X"05a2", X"0059", X"fac4",
                                                        X"01af", X"fd42", X"fbc9", X"06b3", X"097f", X"f92b", X"02fa", X"034a", X"006f", X"fdb9", X"0091", X"ff8f", X"04c0", X"fb6c",
                                                        X"05f1", X"fe17", X"02d0", X"fb5b", X"0166", X"0017", X"009b", X"fade", X"f97a", X"fc84", X"f6b5", X"023b", X"0550", X"ff64",
                                                        X"fe9f", X"fa3c", X"088c", X"f6d0", X"f917", X"f6b3", X"ff6f", X"f970", X"0527", X"0080", X"fb10", X"00b6", X"f539", X"fcc9",
                                                        X"075a", X"0105", X"f81d", X"f4f9", X"04d2", X"f8be", X"ff5f", X"fc40", X"0016", X"0430", X"0276", X"025f", X"028b", X"fb28",
                                                        X"ffab", X"fd34", X"fec2", X"05b2", X"f999", X"f790", X"0942", X"00ad", X"015f", X"fa8c", X"fd60", X"fef8", X"0799", X"0078",
                                                        X"fc2b", X"f45d", X"f824", X"0049", X"0472", X"056d", X"f389", X"fb1d", X"0585", X"fda3", X"fdf3", X"f364", X"fdee", X"0c8c",
                                                        X"0aa5", X"0570", X"0f92", X"fe0b", X"03b1", X"0447", X"fd2a", X"01bb", X"fac7", X"f94b", X"06c1", X"02a6", X"049f", X"ed51",
                                                        X"086f", X"ff20", X"02da", X"fc10", X"022e", X"f6b8", X"fbc6", X"fd39", X"0245", X"f966", X"fe0e", X"fa29", X"050f", X"f6f6",
                                                        X"0167", X"f4f3", X"0464", X"f9ed", X"fee7", X"ffac", X"00a1", X"f721", X"0895", X"fa8c", X"0057", X"f791", X"06d5", X"0285",
                                                        X"06ca", X"061a", X"01e7", X"fc5a", X"03ec", X"f771", X"00a4", X"06b3", X"f483", X"f6e9", X"0504", X"fc66", X"ff5d", X"fac4",
                                                        X"f8f1", X"fbbe", X"f745", X"0b0b", X"04c9", X"fe9b", X"fccc", X"05cc", X"0163", X"ff6d", X"0549", X"fac9", X"0287", X"fe35",
                                                        X"0297", X"0623", X"fe75", X"fa8b", X"001e", X"08f9", X"045e", X"01f4", X"fd7a", X"03ca", X"0194", X"f93a", X"fea9", X"f676",
                                                        X"01e1", X"fa6e", X"02d4", X"07fd", X"f903", X"ffda", X"fe9f", X"fe15", X"f889", X"fe37", X"0306", X"0af2", X"068e", X"fd54",
                                                        X"09fb", X"f7aa", X"0028", X"fdf1", X"fd3e", X"0733", X"04b4", X"ffd7", X"f64f", X"0188", X"fc55", X"fe92", X"fba5", X"049e",
                                                        X"005b", X"07e2", X"088f", X"07ab", X"f21b", X"fae6", X"0dc5", X"06bb", X"02d2", X"05e4", X"f9ff", X"03fb", X"fcd6", X"ff4a",
                                                        X"f903", X"0b5c", X"03d7", X"fbf0", X"087b", X"fd2c", X"fdde", X"f79e", X"01ca", X"fe6b", X"087e", X"017b", X"068b", X"0058",
                                                        X"01e4", X"0639", X"0742", X"f9b5", X"fdcb", X"04f9", X"fae1", X"02ce", X"fe3d", X"fe88", X"0706", X"fbf9", X"fec9", X"02d4",
                                                        X"04c7", X"01dc", X"fc58", X"fe08", X"fb3a", X"fc21", X"fea8", X"0971", X"f73c", X"fc82", X"fff5", X"faf5", X"0253", X"fa8a",
                                                        X"0536", X"0a4f", X"fbf3", X"f777", X"01e8", X"0972", X"fc58", X"ffab", X"ff68", X"0bea", X"fb77", X"0248", X"0532", X"0523",
                                                        X"fdba", X"00c9", X"05bc", X"ff47", X"0285", X"0515", X"ff37", X"00ce", X"fcde", X"f69a", X"fed7", X"045c", X"f92f", X"01d0",
                                                        X"ff45", X"f67d", X"0702", X"03a4", X"ff03", X"fb11", X"fbda", X"ff8b", X"fd4b", X"0282", X"f96e", X"f9bf", X"009b", X"0320",
                                                        X"01a1", X"f9d1", X"0ac1", X"f752", X"fdd0", X"0463", X"fb17", X"fa09", X"fcad", X"05f9", X"fce9", X"0471", X"fa81", X"ff21",
                                                        X"f7d4", X"0466", X"fb5b", X"041f", X"fa3a", X"fda8", X"fa83", X"f710", X"04ff", X"0215", X"0419", X"0549", X"005b", X"0176",
                                                        X"f45b", X"f924", X"fdc5", X"f947", X"0071", X"feac", X"f214", X"f7b4", X"f341", X"fcec", X"0822", X"0c73", X"02b1", X"0253",
                                                        X"0bd0", X"03ef", X"fbeb", X"eae6", X"f911", X"0270", X"f9be", X"070b", X"f5ee", X"f675", X"ef06", X"f56e", X"10ac", X"08c9",
                                                        X"ff61", X"f98c", X"0466", X"015b", X"f87e", X"f143", X"ee37", X"08db", X"fa04", X"0072", X"fa1e", X"fd27", X"f42d", X"f9c2",
                                                        X"1130", X"07be", X"0424", X"f5e2", X"04b2", X"faca", X"fb72", X"f312", X"f4a7", X"0f72", X"fb23", X"f9c9", X"0329", X"fc6d",
                                                        X"fbd8", X"fe3f", X"0ee0", X"0f4e", X"fee3", X"fbc7", X"014f", X"0359", X"fda8", X"f50f", X"000c", X"0611", X"fa9b", X"0426",
                                                        X"069d", X"0463", X"fe10", X"fe74", X"0005", X"026a", X"027d", X"feae", X"0a62", X"f9f8", X"fc78", X"fa4c", X"f9b9", X"fe6b",
                                                        X"feee", X"ff73", X"f7ff", X"f4bd", X"01d6", X"0318", X"fe37", X"fe14", X"03a5", X"0cb5", X"fd45", X"033b", X"f603", X"ff5e",
                                                        X"f94b", X"fe97", X"f578", X"fcc5", X"fde4", X"f5bd", X"f71e", X"fe92", X"0152", X"fc09", X"fc47", X"ff6f", X"ffc5", X"fb32",
                                                        X"fad8", X"f94f", X"f4f8", X"fb22", X"06b4", X"f793", X"0762", X"f598", X"fa70", X"00c3", X"0255", X"04a3", X"fb9c", X"f90e",
                                                        X"0ad4", X"05e7", X"0396", X"00c3", X"f9a5", X"fd32", X"055a", X"fddb", X"0439", X"0030", X"fe52", X"0534", X"fb69", X"f6d0",
                                                        X"f9a6", X"f8ce", X"007e", X"fd9b", X"0496", X"0395", X"ff56", X"0335", X"0b60", X"ffb7", X"fe96", X"fe59", X"fb8f", X"fcf5",
                                                        X"fd98", X"0081", X"0155", X"f5ec", X"facd", X"07f2", X"0a2f", X"f8b2", X"0564", X"0ab0", X"f6ac", X"0a4d", X"007f", X"06d0",
                                                        X"fed7", X"fbd1", X"001d", X"fe4e", X"fa55", X"07b3", X"f827", X"0442", X"0bba", X"fabd", X"fb37", X"0332", X"f72d", X"0970",
                                                        X"001f", X"03c6", X"f14f", X"fb70", X"f8d4", X"f0a3", X"f6f8", X"fb70", X"0225", X"fe1d", X"0c0d", X"fb34", X"fc1f", X"06e7",
                                                        X"f9ae", X"f480", X"fccc", X"0e9b", X"fe78", X"05d2", X"fd4f", X"f1ca", X"ff30", X"0332", X"0592", X"f9f0", X"0680", X"fa11",
                                                        X"0401", X"fb8d", X"066d", X"f692", X"0003", X"02bc", X"f5f0", X"0053", X"f5f6", X"0111", X"fe16", X"fe4e", X"05fb", X"faff",
                                                        X"ffd2", X"00b7", X"ff73", X"f7e4", X"0465", X"f5c7", X"fb59", X"fe46", X"fe6f", X"00ec", X"fc0f", X"0358", X"02c0", X"01d9",
                                                        X"0554", X"fe27", X"089a", X"fd65", X"fcf6", X"fccd", X"f972", X"009a", X"01d3", X"009f", X"f83a", X"f6a9", X"0413", X"02ff",
                                                        X"fb93", X"103c", X"0764", X"fa27", X"02bd", X"feca", X"f972", X"04d0", X"02b4", X"faa5", X"0033", X"f9d6", X"002a", X"00a9",
                                                        X"0594", X"0764", X"0780", X"04e6", X"0450", X"04e1", X"0428", X"ffcd", X"ff62", X"ff57", X"faec", X"ff52", X"075c", X"f775",
                                                        X"0300", X"063c", X"04a0", X"077a", X"089e", X"ff5a", X"fb2b", X"04b3", X"f7e9", X"0781", X"fe3a", X"0381", X"015f", X"fe4e",
                                                        X"08b4", X"f160", X"058d", X"078d", X"0118", X"fe3a", X"017f", X"fa73", X"fd7f", X"0370", X"fcec", X"0863", X"07ae", X"062d",
                                                        X"0ad6", X"fda2", X"fb6f", X"f988", X"0a42", X"0bbf", X"ff4b", X"0465", X"02fe", X"fc35", X"0130", X"04fe", X"f276", X"0287",
                                                        X"04a5", X"fd7b", X"0613", X"0049", X"0341", X"f59c", X"002d", X"fed9", X"00de", X"fc9d", X"fde5", X"0632", X"0086", X"fca8",
                                                        X"fa96", X"fbc0", X"fae3", X"ff69", X"0530", X"fbb5", X"fc3a", X"fd50", X"06d4", X"04e4", X"0537", X"0637", X"04ae", X"010f",
                                                        X"0095", X"f949", X"01be", X"022c", X"ff61", X"fd34", X"0226", X"fa47", X"0562", X"f7f8", X"0207", X"fd67", X"fb21", X"ff3c",
                                                        X"05ca", X"01c8", X"fd14", X"fd0f", X"f4d7", X"fecb", X"fc09", X"fa58", X"0040", X"0093", X"fcf3", X"fe79", X"fe6d", X"021f",
                                                        X"f8d5", X"fd3b", X"fcbd", X"04f5", X"0028", X"f883", X"f57f", X"007a", X"f9ae", X"f36d", X"0bd7", X"fec7", X"fff2", X"f21e",
                                                        X"fde1", X"02d1", X"f9f0", X"05c8", X"0841", X"014f", X"00d9", X"f93b", X"fbfe", X"f9fb", X"f35f", X"f7b1", X"0837", X"f775",
                                                        X"f9b1", X"fb18", X"0175", X"0183", X"0318", X"0487", X"03e1", X"0118", X"0480", X"fc7d", X"f587", X"f989", X"fd1a", X"fae7",
                                                        X"0212", X"030b", X"00a0", X"ef4f", X"045f", X"0400", X"03f3", X"0240", X"0924", X"f98c", X"056a", X"0375", X"f37e", X"0368",
                                                        X"0363", X"0036", X"fdd1", X"ff69", X"ff03", X"f977", X"0949", X"0360", X"fa02", X"0211", X"fe7c", X"f4fa", X"fd07", X"fa52",
                                                        X"f876", X"fb22", X"fc88", X"faae", X"005d", X"fd2b", X"09ee", X"fa33", X"f76a", X"fe4d", X"0267", X"ffcc", X"0424", X"0474",
                                                        X"fef6", X"f96b", X"0109", X"fe18", X"fbac", X"f897", X"0104", X"f598", X"0024", X"f935", X"f396", X"fb92", X"f982", X"fec1",
                                                        X"02c0", X"0023", X"07bf", X"fa3f", X"fea5", X"f4b1", X"f8e0", X"f999", X"f9cd", X"fba1", X"fe21", X"fad3", X"f5f8", X"023b",
                                                        X"01c1", X"fc96", X"004f", X"f9c4", X"0518", X"f5d4", X"00e8", X"f715", X"f827", X"f9d5", X"0058", X"f7b0", X"0b3a", X"f92d",
                                                        X"f8ab", X"fa7a", X"ff63", X"f7c1", X"f5c0", X"fcf1", X"08dd", X"f9e2", X"043c", X"ffac", X"f3bf", X"f649", X"0215", X"f742",
                                                        X"014f", X"ffd0", X"fb95", X"03cf", X"fe57", X"0435", X"fd26", X"ff0c", X"01d3", X"ff0f", X"0386", X"f6e0", X"0081", X"f780",
                                                        X"f862", X"0137", X"04cb", X"0121", X"017f", X"fd2d", X"fef4", X"0297", X"0146", X"fa42", X"fd41", X"06d1", X"fb1a", X"fbd4",
                                                        X"05e6", X"02c5", X"02c5", X"f9d0", X"f752", X"07b9", X"fcd1", X"030c", X"fe15", X"ffa6", X"05d9", X"ff0f", X"f97b", X"fd6c",
                                                        X"fa9d", X"ffc3", X"0db6", X"fa05", X"f7ab", X"06b5", X"f2c8", X"f5d3", X"002a", X"0357", X"f3b4", X"f7f5", X"0706", X"0709",
                                                        X"f6a3", X"fc0b", X"fdae", X"ff87", X"0d81", X"f6c9", X"0122", X"f84a", X"02c7", X"f9a6", X"ff1d", X"ff63", X"004a", X"07b2",
                                                        X"05f8", X"008e", X"03b4", X"0070", X"f88a", X"0928", X"0378", X"f6be", X"0384", X"fb11", X"0268", X"f5a1", X"0833", X"ff92",
                                                        X"02bf", X"fdc8", X"041a", X"fa39", X"fde1", X"fe38", X"ffa2", X"0537", X"ff9a", X"ffb9", X"0657", X"fd15", X"fe9a", X"f91b",
                                                        X"02ba", X"0207", X"0197", X"008a", X"fd68", X"fda7", X"04a4", X"009f", X"f7ed", X"088e", X"0572", X"fabe", X"0618", X"faa7",
                                                        X"0f9e", X"f6fc", X"0389", X"0723", X"0b3e", X"00cb", X"06e8", X"f941", X"08f4", X"fa35", X"f688", X"09ee", X"0848", X"fa36",
                                                        X"07c8", X"fbc7", X"05b9", X"f2da", X"f91f", X"008d", X"00d6", X"fd8f", X"fead", X"f8f1", X"0495", X"f5cc", X"f3c6", X"fe2b",
                                                        X"fc7a", X"fbcb", X"02b4", X"f6d7", X"0630", X"f78e", X"f891", X"0309", X"0352", X"fde3", X"0362", X"ff38", X"08bf", X"f9e9",
                                                        X"f9ff", X"f4f3", X"f9b9", X"01dc", X"0214", X"f6f2", X"00a0", X"f4f0", X"f506", X"0020", X"073e", X"09e1", X"fe13", X"0407",
                                                        X"055a", X"01f1", X"034a", X"fd39", X"f08d", X"08e3", X"0026", X"f6fe", X"feea", X"00ca", X"fbc1", X"fe83", X"0490", X"06bf",
                                                        X"f979", X"02ec", X"0589", X"ff98", X"f651", X"024f", X"ecce", X"faf8", X"f703", X"f9b2", X"03c2", X"ff3a", X"0492", X"0368",
                                                        X"f9a2", X"02de", X"f8fb", X"fa19", X"ff85", X"03ed", X"f974", X"fcae", X"fcaa", X"f762", X"fc8f", X"fde7", X"04c2", X"f9cc",
                                                        X"ff2f", X"04b6", X"02a8", X"f831", X"ef69", X"f736", X"00cf", X"00c9", X"f8b8", X"0b84", X"fd5a", X"f835", X"0dc6", X"f9c9",
                                                        X"f8f2", X"f76f", X"fbe2", X"0a5a", X"fea2", X"f6f5", X"f7ac", X"f313", X"01a0", X"0264", X"02da", X"01d9", X"07a6", X"f1f8",
                                                        X"0146", X"fd9e", X"0258", X"fe98", X"0552", X"ffa6", X"f712", X"f975", X"fdf2", X"03eb", X"f674", X"fe4c", X"fe33", X"068d",
                                                        X"0ba1", X"f7f1", X"fc2d", X"0721", X"f912", X"ff6e", X"ff7f", X"ff5e", X"fccf", X"fa11", X"00e6", X"03d1", X"013e", X"0098",
                                                        X"0057", X"006c", X"03bf", X"005b", X"0148", X"fda8", X"f697", X"0243", X"fd0f", X"02a9", X"05b3", X"fd4f", X"05ec", X"04b8",
                                                        X"ffc6", X"ff48", X"02ae", X"0172", X"035b", X"0161", X"fff4", X"fed3", X"0740", X"fd86", X"fd17", X"fdc9", X"02ce", X"0637",
                                                        X"0219", X"0447", X"0c04", X"01de", X"ff7a", X"fd72", X"fc56", X"02cd", X"f784", X"0535", X"093e", X"faaa", X"ff0b", X"0464",
                                                        X"0107", X"fcee", X"f870", X"fd40", X"0202", X"fff3", X"f867", X"f367", X"f66e", X"fabe", X"f2ae", X"fb0b", X"035a", X"f8f6",
                                                        X"0277", X"fd79", X"02f6", X"f92b", X"f64f", X"f948", X"038d", X"fc93", X"f76c", X"003d", X"f427", X"ffbe", X"0158", X"fdd7",
                                                        X"03e7", X"fcd0", X"fd7e", X"fbf5", X"fc14", X"00fb", X"fb0f", X"025d", X"05d7", X"fec9", X"f700", X"fcf9", X"f8de", X"f674",
                                                        X"0335", X"fedc", X"fd32", X"02b8", X"feb3", X"0445", X"f999", X"fc97", X"faa6", X"034d", X"01fc", X"059c", X"fbbe", X"f817",
                                                        X"f80c", X"f9ba", X"ff16", X"fa49", X"073d", X"fcf3", X"01c2", X"036c", X"f845", X"f981", X"0191", X"fde6", X"fc42", X"fdf8",
                                                        X"f8de", X"fd27", X"0581", X"045e", X"f085", X"fad7", X"f88f", X"fcf4", X"02ab", X"02d4", X"046b", X"0177", X"fab5", X"fb34",
                                                        X"ffcc", X"fff2", X"fcb0", X"fad5", X"01b4", X"f604", X"0479", X"fdcb", X"fb33", X"0102", X"fbc5", X"08d9", X"fc12", X"038a",
                                                        X"fd80", X"fe47", X"00d0", X"057c", X"07e3", X"008f", X"07be", X"fbad", X"0022", X"03be", X"0ad0", X"075c", X"fb1d", X"0498",
                                                        X"fff6", X"f896", X"0081", X"f7a7", X"00fb", X"01c3", X"0cf4", X"fc55", X"0370", X"053b", X"f6f1", X"000d", X"fb63", X"0790",
                                                        X"f706", X"0887", X"facc", X"f424", X"fa8c", X"0815", X"002b", X"fb32", X"0de5", X"f995", X"f9a7", X"0110", X"fcc4", X"f6e4",
                                                        X"01b6", X"01c7", X"feb0", X"06dd", X"f957", X"fa2a", X"fd47", X"f5c2", X"06d4", X"f933", X"0c39", X"00a7", X"fa9c", X"fcc4",
                                                        X"fcc6", X"f744", X"fcf0", X"00c3", X"fc27", X"04f8", X"fd59", X"f868", X"fb06", X"0075", X"fff4", X"fcee", X"0455", X"febe",
                                                        X"f80e", X"f932", X"fc34", X"f867", X"f5e1", X"0011", X"fff0", X"faab", X"fedb", X"fc1a", X"fecb", X"05f2", X"05b4", X"f924",
                                                        X"0582", X"00df", X"f96c", X"f2ab", X"feb1", X"f32c", X"ff51", X"f64f", X"f838", X"0425", X"0781", X"01d7", X"fa0d", X"f660",
                                                        X"03c2", X"f7c1", X"fdbc", X"fe86", X"f86d", X"f177", X"028b", X"fc61", X"f61a", X"f7ad", X"f508", X"0904", X"00eb", X"fd0d",
                                                        X"fbad", X"f4f4", X"0050", X"0010", X"0650", X"02a8", X"f5df", X"f362", X"ff15", X"fa59", X"01b4", X"fc96", X"049b", X"09f4",
                                                        X"0627", X"f014", X"0854", X"fa5b", X"06bd", X"0182", X"fe82", X"084f", X"0611", X"fa06", X"06d0", X"f7eb", X"f5f1", X"0469",
                                                        X"fce0", X"0bb2", X"fa89", X"fa72", X"fe5b", X"f139", X"f748", X"011d", X"ff0c", X"064c", X"060f", X"fbd7", X"0745", X"fa6a",
                                                        X"08d8", X"fb55", X"02f0", X"0764", X"f647", X"f868", X"0153", X"065b", X"0259", X"0185", X"04e5", X"0e32", X"0bdd", X"fc16",
                                                        X"0e6c", X"f4d3", X"fc7b", X"fbd1");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"fbd1";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

