-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w4a16/amc_cnn_4w16a_src_SinglePortRAM_generic_block431.vhd
-- Created: 2023-06-15 16:03:10
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_4w16a_src_SinglePortRAM_generic_block431
-- Source Path: amc_model_w4a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage76/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_4w16a_src_SinglePortRAM_generic_block431 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_4w16a_src_SinglePortRAM_generic_block431;


ARCHITECTURE rtl OF amc_cnn_4w16a_src_SinglePortRAM_generic_block431 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"d6", X"fa", X"ef", X"25", X"f4", X"eb", X"f1", X"e3", X"e9", X"e1", X"e3", X"f8", X"df", X"ee",
                                                        X"10", X"04", X"f3", X"00", X"11", X"23", X"e6", X"e6", X"ed", X"08", X"da", X"37", X"df", X"26", X"eb", X"d9", X"2f", X"26", X"f7", X"fa", X"d9", X"11", X"09", X"41", X"eb", X"0b",
                                                        X"0d", X"fc", X"f6", X"c9", X"e0", X"0d", X"3f", X"05", X"2f", X"00", X"f2", X"14", X"ef", X"60", X"d8", X"38", X"dc", X"cc", X"0f", X"fa", X"ef", X"fa", X"fa", X"0c", X"2d", X"f7",
                                                        X"0e", X"16", X"f1", X"12", X"c7", X"0a", X"e5", X"1f", X"f2", X"ce", X"26", X"1d", X"08", X"f8", X"22", X"05", X"fe", X"27", X"02", X"fe", X"09", X"07", X"f1", X"d7", X"11", X"03",
                                                        X"0c", X"ef", X"d8", X"eb", X"c8", X"00", X"ef", X"3f", X"ea", X"bb", X"1b", X"f9", X"f2", X"3d", X"e2", X"e4", X"08", X"03", X"08", X"ee", X"00", X"0b", X"e0", X"3b", X"f9", X"ae",
                                                        X"08", X"e2", X"da", X"24", X"de", X"f4", X"1e", X"ef", X"01", X"f0", X"15", X"ef", X"d3", X"0e", X"e8", X"f8", X"bc", X"f0", X"fa", X"e2", X"f1", X"d5", X"03", X"f2", X"10", X"01",
                                                        X"1d", X"22", X"15", X"e2", X"e5", X"f7", X"12", X"0b", X"2c", X"33", X"00", X"d3", X"ec", X"f6", X"24", X"1c", X"33", X"f6", X"12", X"13", X"02", X"26", X"1f", X"10", X"fe", X"2d",
                                                        X"07", X"f8", X"f1", X"01", X"20", X"0e", X"1f", X"f6", X"e2", X"ef", X"0e", X"26", X"f2", X"18", X"fc", X"dc", X"11", X"2a", X"08", X"03", X"1d", X"ec", X"2e", X"fb", X"da", X"d1",
                                                        X"f0", X"16", X"11", X"0e", X"14", X"ef", X"e1", X"f9", X"13", X"f0", X"0a", X"db", X"e6", X"13", X"f4", X"fa", X"f0", X"05", X"ef", X"15", X"de", X"2b", X"f4", X"e3", X"ff", X"07",
                                                        X"f7", X"e9", X"fc", X"05", X"f6", X"2e", X"03", X"00", X"ce", X"fe", X"f7", X"07", X"03", X"3e", X"f4", X"10", X"f7", X"03", X"cc", X"0f", X"1a", X"10", X"f5", X"dc", X"2b", X"f3",
                                                        X"07", X"cd", X"f5", X"07", X"ea", X"00", X"12", X"1a", X"cd", X"1a", X"0a", X"ce", X"d6", X"cd", X"47", X"fd", X"28", X"03", X"fb", X"05", X"ec", X"01", X"df", X"fd", X"d5", X"00",
                                                        X"16", X"e0", X"f2", X"1f", X"f6", X"22", X"16", X"d1", X"13", X"ed", X"d9", X"fa", X"f7", X"ff", X"09", X"12", X"05", X"29", X"dc", X"2c", X"28", X"f9", X"1b", X"b2", X"fe", X"09",
                                                        X"e9", X"fe", X"ec", X"01", X"fd", X"f1", X"0e", X"cc", X"e6", X"4e", X"06", X"0d", X"2b", X"25", X"fa", X"2e", X"1d", X"14", X"09", X"0b", X"dc", X"ee", X"0a", X"2b", X"f1", X"49",
                                                        X"db", X"fa", X"d0", X"34", X"04", X"cb", X"dd", X"05", X"24", X"fb", X"18", X"08", X"e4", X"10", X"f5", X"fd", X"ef", X"fc", X"0c", X"f6", X"0c", X"ee", X"12", X"f8", X"df", X"03",
                                                        X"09", X"0a", X"00", X"1e", X"f7", X"ec", X"c7", X"f8", X"e8", X"cb", X"f8", X"de", X"22", X"e9", X"d8", X"fb", X"e5", X"02", X"e1", X"19", X"eb", X"e2", X"27", X"ea", X"02", X"25",
                                                        X"cd", X"03", X"ef", X"13", X"f8", X"f4", X"c3", X"03", X"0c", X"d9", X"e0", X"e9", X"04", X"e7", X"e5", X"48", X"04", X"e2", X"e6", X"03", X"1c", X"f4", X"14", X"01", X"06", X"e5",
                                                        X"03", X"1c", X"13", X"0b", X"ef", X"01", X"fc", X"03", X"e7", X"fd", X"01", X"09", X"ec", X"13", X"e0", X"1d", X"ed", X"4a", X"37", X"13", X"32", X"cb", X"fa", X"04", X"df", X"06",
                                                        X"e4", X"06", X"1a", X"0a", X"06", X"b7", X"dd", X"1f", X"03", X"0d", X"08", X"3f", X"07", X"0c", X"f5", X"04", X"ff", X"01", X"ee", X"ee", X"09", X"ef", X"ed", X"53", X"c9", X"00",
                                                        X"db", X"d8", X"10", X"24", X"24", X"fd", X"2b", X"11", X"d9", X"ea", X"02", X"da", X"fc", X"42", X"e4", X"10", X"f4", X"02", X"01", X"fa", X"0b", X"fc", X"41", X"eb", X"ca", X"05",
                                                        X"fa", X"14", X"0b", X"dd", X"f7", X"f7", X"1c", X"32", X"08", X"2c", X"f3", X"f4", X"fd", X"ff", X"f1", X"15", X"0a", X"38", X"f3", X"e4", X"19", X"18", X"2e", X"24", X"f4", X"01",
                                                        X"0b", X"02", X"bb", X"fc", X"dd", X"e4", X"f7", X"e8", X"01", X"d4", X"4d", X"e7", X"03", X"e4", X"ca", X"e9", X"e8", X"fa", X"02", X"0e", X"f4", X"08", X"f5", X"fd", X"0c", X"db",
                                                        X"ca", X"01", X"fc", X"dd", X"f4", X"0d", X"f5", X"0e", X"1d", X"02", X"00", X"0a", X"03", X"e0", X"09", X"3a", X"05", X"fd", X"f3", X"fd", X"f8", X"0e", X"ed", X"f4", X"29", X"05",
                                                        X"ed", X"fe", X"d1", X"3b", X"ee", X"26", X"d9", X"0c", X"e8", X"e0", X"f0", X"28", X"f3", X"17", X"1c", X"14", X"2c", X"f4", X"f0", X"f9", X"fb", X"3b", X"d0", X"21", X"e7", X"d5",
                                                        X"ed", X"10", X"0a", X"14", X"1a", X"f1", X"ed", X"07", X"f7", X"d3", X"df", X"0a", X"28", X"18", X"2f", X"02", X"fa", X"31", X"eb", X"1f", X"f0", X"04", X"0b", X"0e", X"f8", X"d0",
                                                        X"05", X"09", X"f5", X"06", X"ff", X"02", X"ef", X"f1", X"f2", X"f4", X"f3", X"ef", X"c3", X"0c", X"d6", X"1e", X"ef", X"ef", X"f4", X"08", X"0d", X"2e", X"e4", X"30", X"11", X"f4",
                                                        X"de", X"02", X"de", X"00", X"1a", X"05", X"f6", X"da", X"fa", X"d1", X"ce", X"d3", X"fc", X"ce", X"e2", X"09", X"f6", X"13", X"d3", X"ed", X"f3", X"43", X"df", X"f5", X"23", X"f8",
                                                        X"09", X"37", X"ed", X"0c", X"11", X"05", X"f6", X"14", X"14", X"0f", X"e0", X"f8", X"f9", X"1b", X"f2", X"f7", X"21", X"07", X"e3", X"d4", X"ea", X"03", X"3a", X"f6", X"e0", X"1c",
                                                        X"f4", X"d3", X"e4", X"41", X"c3", X"0c", X"03", X"03", X"0d", X"f4", X"e2", X"04", X"2d", X"f9", X"fa", X"f3", X"ef", X"f8", X"fa", X"34", X"d1", X"19", X"e7", X"fb", X"fd", X"1a",
                                                        X"12", X"07", X"1e", X"eb", X"06", X"08", X"d7", X"02", X"fe", X"29", X"ef", X"1e", X"ea", X"fc", X"f7", X"dc", X"03", X"05", X"13", X"fe", X"d5", X"e6", X"f2", X"14", X"03", X"1c",
                                                        X"ed", X"ff", X"d8", X"4c", X"f8", X"25", X"fd", X"e4", X"07", X"e8", X"df", X"f0", X"f6", X"ea", X"0a", X"22", X"41", X"eb", X"10", X"30", X"fe", X"0d", X"ec", X"fd", X"e1", X"f3",
                                                        X"e4", X"19", X"02", X"fe", X"0f", X"cd", X"02", X"f8", X"05", X"df", X"f1", X"ea", X"0c", X"fd", X"de", X"0d", X"d4", X"19", X"f6", X"17", X"d7", X"c9", X"f7", X"ed", X"f9", X"18",
                                                        X"05", X"1b", X"ef", X"f7", X"0a", X"01", X"0e", X"02", X"e0", X"de", X"ff", X"0d", X"45", X"fa", X"06", X"f7", X"eb", X"e3", X"0a", X"fe", X"27", X"1e", X"1f", X"17", X"f3", X"31",
                                                        X"0c", X"20", X"04", X"10", X"e8", X"17", X"07", X"cb", X"e8", X"fa", X"00", X"1d", X"1d", X"f8", X"02", X"e0", X"02", X"22", X"ef", X"1e", X"2a", X"d2", X"f6", X"29", X"19", X"21",
                                                        X"02", X"ef", X"30", X"13", X"f2", X"d5", X"ec", X"2a", X"e9", X"17", X"e7", X"0a", X"02", X"04", X"f7", X"0e", X"18", X"0a", X"ff", X"f8", X"15", X"d4", X"f2", X"3e", X"dd", X"10",
                                                        X"f1", X"17", X"e3", X"2f", X"ff", X"fc", X"f9", X"ea", X"09", X"f1", X"eb", X"22", X"ef", X"e5", X"d2", X"ed", X"0e", X"0a", X"d3", X"e9", X"06", X"ea", X"ea", X"09", X"c5", X"07",
                                                        X"da", X"32", X"ee", X"d4", X"3f", X"d3", X"ea", X"2c", X"f8", X"d4", X"ea", X"08", X"0d", X"05", X"e6", X"01", X"da", X"0b", X"dc", X"d1", X"37", X"ff", X"1e", X"dd", X"f9", X"d4",
                                                        X"ee", X"f4", X"d8", X"fa", X"14", X"f2", X"f9", X"27", X"01", X"12", X"0e", X"05", X"0b", X"e9", X"e2", X"cd", X"de", X"14", X"fc", X"18", X"1d", X"25", X"fc", X"d0", X"e4", X"20",
                                                        X"ef", X"0a", X"e3", X"cc", X"01", X"1c", X"f5", X"00", X"14", X"01", X"18", X"f3", X"f7", X"27", X"fc", X"19", X"25", X"0d", X"02", X"cb", X"df", X"ce", X"fa", X"fd", X"3b", X"10",
                                                        X"1d", X"10", X"f8", X"e2", X"f2", X"59", X"f0", X"28", X"00", X"dd", X"08", X"2f", X"e3", X"01", X"f4", X"f4", X"1b", X"08", X"0a", X"f6", X"0b", X"1e", X"12", X"04", X"fd", X"d3",
                                                        X"0b", X"22", X"24", X"eb", X"e0", X"f2", X"13", X"ef", X"fe", X"3f", X"e4", X"e2", X"f4", X"0a", X"fe", X"07", X"04", X"cb", X"05", X"10", X"f6", X"00", X"03", X"1a", X"18", X"d1",
                                                        X"f9", X"d7", X"28", X"f6", X"13", X"22", X"e7", X"de", X"e0", X"f3", X"17", X"fc", X"ce", X"f2", X"ed", X"30", X"e8", X"dd", X"da", X"e9", X"fa", X"1a", X"e2", X"13", X"0b", X"01",
                                                        X"07", X"ec", X"ee", X"14", X"cf", X"12", X"e3", X"ed", X"3e", X"05", X"eb", X"e9", X"ea", X"ca", X"ef", X"0a", X"da", X"1d", X"00", X"d9", X"08", X"12", X"e3", X"32", X"0f", X"fd",
                                                        X"dd", X"32", X"18", X"de", X"09", X"ec", X"ee", X"f9", X"2e", X"f4", X"f2", X"1a", X"04", X"25", X"00", X"21", X"ef", X"ef", X"08", X"1c", X"0e", X"03", X"43", X"09", X"f8", X"09",
                                                        X"d6", X"ef", X"fb", X"5d", X"c1", X"1d", X"f1", X"30", X"f4", X"28", X"31", X"0a", X"37", X"f3", X"0f", X"02", X"dd", X"bd", X"d9", X"22", X"fb", X"0c", X"f5", X"e3", X"15", X"f0",
                                                        X"f6", X"0c", X"de", X"0d", X"ba", X"f5", X"ee", X"32", X"f9", X"f9", X"0e", X"07", X"f6", X"d1", X"fb", X"0e", X"e8", X"ec", X"df", X"fa", X"fa", X"0c", X"df", X"e3", X"eb", X"05",
                                                        X"2f", X"ec", X"e7", X"3b", X"f2", X"0b", X"f0", X"19", X"f7", X"f9", X"ba", X"f1", X"f2", X"38", X"f8", X"e7", X"e3", X"e2", X"13", X"18", X"f8", X"ec", X"17", X"0d", X"d2", X"17",
                                                        X"11", X"fe", X"eb", X"ca", X"fa", X"f0", X"36", X"00", X"ef", X"ff", X"f4", X"08", X"d3", X"09", X"2b", X"18", X"dd", X"08", X"eb", X"2d", X"0b", X"26", X"dd", X"ee", X"ea", X"11",
                                                        X"fa", X"26", X"1f", X"eb", X"01", X"f8", X"3b", X"1f", X"11", X"a2", X"f3", X"12", X"0d", X"19", X"f5", X"0b", X"08", X"e3", X"01", X"ee", X"12", X"fa", X"1e", X"05", X"f3", X"2b",
                                                        X"03", X"2d", X"b2", X"0b", X"07", X"2f", X"fc", X"f5", X"f5", X"08", X"3a", X"0f", X"f9", X"15", X"ff", X"d8", X"02", X"fb", X"e1", X"fe", X"32", X"f0", X"f3", X"03", X"1e", X"09",
                                                        X"24", X"ee", X"12", X"ee", X"27", X"2b", X"ee", X"30", X"f3", X"10", X"1e", X"48", X"07", X"d6", X"01", X"f7", X"e8", X"f9", X"d5", X"0a", X"ed", X"37", X"f0", X"d4", X"0d", X"f7",
                                                        X"f0", X"cc", X"fa", X"e1", X"1d", X"fe", X"17", X"f0", X"e9", X"f1", X"fb", X"41", X"c1", X"cc", X"00", X"f8", X"e4", X"01", X"e7", X"ea", X"f1", X"ef", X"02", X"f4", X"da", X"ff",
                                                        X"ee", X"d5", X"ec", X"fa", X"d2", X"07", X"17", X"51", X"f0", X"db", X"02", X"ef", X"26", X"24", X"df", X"f5", X"14", X"da", X"ef", X"17", X"35", X"fb", X"e9", X"4c", X"dd", X"23",
                                                        X"1e", X"fe", X"06", X"0c", X"fb", X"fc", X"e7", X"e9", X"fd", X"20", X"fe", X"14", X"34", X"e6", X"0e", X"fc", X"ef", X"03", X"11", X"2a", X"39", X"07", X"17", X"b7", X"ef", X"3a",
                                                        X"0a", X"00", X"ea", X"be", X"02", X"18", X"1c", X"0e", X"28", X"f2", X"03", X"ee", X"f2", X"21", X"09", X"43", X"f8", X"0a", X"d6", X"1d", X"ec", X"e2", X"0d", X"f2", X"f2", X"01",
                                                        X"31", X"04", X"f9", X"04", X"ee", X"2e", X"de", X"14", X"fa", X"33", X"17", X"11", X"ec", X"11", X"0d", X"02", X"d1", X"fe", X"11", X"15", X"fd", X"dc", X"e6", X"ef", X"e1", X"12",
                                                        X"f5", X"1e", X"1b", X"f7", X"f0", X"e5", X"da", X"db", X"19", X"dd", X"f2", X"f2", X"f3", X"d1", X"fb", X"e3", X"d0", X"f9", X"06", X"ee", X"db", X"f2", X"df", X"1a", X"10", X"4b",
                                                        X"f0", X"e9", X"03", X"fb", X"d4", X"16", X"0a", X"26", X"ed", X"fc", X"24", X"21", X"ce", X"f9", X"e1", X"d1", X"f6", X"f3", X"e0", X"09", X"e1", X"ce", X"fd", X"19", X"0c", X"f0",
                                                        X"f1", X"1f", X"05", X"fb", X"cb", X"31", X"f5", X"2a", X"12", X"0b", X"05", X"0f", X"f3", X"06", X"2e", X"f4", X"07", X"04", X"25", X"03", X"1c", X"23", X"d5", X"44", X"05", X"05",
                                                        X"fd", X"17", X"1d", X"f1", X"04", X"ff", X"10", X"11", X"04", X"03", X"d4", X"ca", X"ec", X"18", X"bf", X"2a", X"f4", X"ce", X"fd", X"13", X"df", X"11", X"33", X"f6", X"fa", X"ea",
                                                        X"23", X"f7", X"e9", X"27", X"22", X"e0", X"14", X"1e", X"07", X"e1", X"fe", X"0f", X"d8", X"f3", X"d9", X"03", X"ed", X"0a", X"e7", X"fb", X"db", X"07", X"16", X"53", X"09", X"d1",
                                                        X"df", X"06", X"03", X"f5", X"ee", X"db", X"d0", X"07", X"e7", X"fa", X"29", X"1f", X"e9", X"02", X"f2", X"13", X"00", X"f3", X"eb", X"04", X"e7", X"26", X"f8", X"e1", X"ea", X"bb",
                                                        X"1a", X"f4", X"17", X"f2", X"f7", X"f6", X"10", X"f2", X"0a", X"fe", X"e0", X"e8", X"f9", X"3a", X"ef", X"f8", X"e6", X"06", X"17", X"13", X"e5", X"0c", X"d8", X"06", X"27", X"00",
                                                        X"01", X"de", X"ff", X"c3", X"dc", X"08", X"0f", X"f3", X"f9", X"ff", X"f0", X"2f", X"08", X"ed", X"27", X"17", X"eb", X"0e", X"d9", X"1f", X"06", X"39", X"fc", X"19", X"e6", X"0a",
                                                        X"f4", X"eb", X"0c", X"f5", X"2e", X"06", X"36", X"02", X"f0", X"d6", X"03", X"4b", X"cb", X"fc", X"df", X"e5", X"f6", X"f5", X"35", X"06", X"f3", X"0e", X"23", X"06", X"01", X"d0",
                                                        X"e0", X"06", X"ec", X"e8", X"ff", X"00", X"f5", X"32", X"0b", X"0e", X"2b", X"0d", X"f2", X"04", X"ff", X"0b", X"f5", X"0c", X"de", X"ff", X"1f", X"ff", X"f2", X"21", X"eb", X"10",
                                                        X"cc", X"eb", X"e8", X"0c", X"05", X"d9", X"f2", X"e8", X"e8", X"0d", X"f2", X"1e", X"06", X"3c", X"e9", X"f7", X"19", X"fc", X"d3", X"1d", X"11", X"e6", X"fe", X"be", X"38", X"f2",
                                                        X"e1", X"4f", X"d3", X"f5", X"fd", X"1f", X"06", X"f7", X"f4", X"f6", X"0b", X"e4", X"0c", X"dc", X"0c", X"fe", X"ec", X"4e", X"e3", X"1b", X"ec", X"0a", X"e6", X"fc", X"e6", X"02",
                                                        X"fc", X"cf", X"f8", X"0f", X"d3", X"00", X"06", X"f0", X"05", X"0f", X"15", X"02", X"10", X"fc", X"01", X"1e", X"1f", X"ff", X"e3", X"4a", X"08", X"17", X"09", X"18", X"18", X"fc",
                                                        X"0b", X"f4", X"03", X"15", X"12", X"fd", X"eb", X"f5", X"05", X"44", X"1b", X"2e", X"fd", X"d2", X"01", X"11", X"f3", X"ed", X"23", X"08", X"e8", X"ef", X"e4", X"fc", X"ee", X"57",
                                                        X"0d", X"fa", X"13", X"0e", X"fd", X"03", X"e4", X"07", X"f8", X"da", X"f3", X"fc", X"f7", X"2b", X"ff", X"ea", X"12", X"11", X"e0", X"ef", X"0c", X"f9", X"dd", X"01", X"d5", X"ff",
                                                        X"cd", X"19", X"1e", X"15", X"f8", X"14", X"f4", X"fa", X"16", X"cb", X"0b", X"10", X"eb", X"0b", X"ea", X"eb", X"ef", X"0e", X"0f", X"30", X"dc", X"eb", X"fe", X"f2", X"d4", X"26",
                                                        X"11", X"c6", X"e9", X"f8", X"dc", X"f5", X"f9", X"1b", X"fb", X"1a", X"fd", X"f4", X"41", X"f5", X"e7", X"fe", X"09", X"d7", X"03", X"01", X"ef", X"22", X"00", X"f5", X"f9", X"e9",
                                                        X"f5", X"df", X"18", X"f9", X"26", X"31", X"eb", X"0d", X"11", X"da", X"14", X"f1", X"e8", X"e3", X"0b", X"cb", X"e2", X"3f", X"e4", X"0f", X"2d", X"fb", X"f0", X"15", X"21", X"07",
                                                        X"2a", X"f5", X"3d", X"0f", X"db", X"d0", X"05", X"36", X"d5", X"0f", X"e0", X"10", X"0e", X"08", X"e1", X"fd", X"1e", X"0c", X"04", X"0c", X"ef", X"2a", X"06", X"3a", X"1b", X"0c",
                                                        X"12", X"fb", X"f7", X"e1", X"f2", X"00", X"fa", X"fd", X"d0", X"fa", X"04", X"31", X"ef", X"37", X"f2", X"ed", X"12", X"ff", X"fc", X"f8", X"f6", X"1f", X"1e", X"f1", X"cb", X"0f",
                                                        X"ff", X"03", X"0e", X"d5", X"e3", X"eb", X"ff", X"f9", X"07", X"e5", X"0d", X"0f", X"1e", X"13", X"f3", X"18", X"fd", X"10", X"0d", X"fa", X"11", X"d0", X"ef", X"47", X"ee", X"fe",
                                                        X"c9", X"da", X"f9", X"07", X"10", X"14", X"1c", X"14", X"1b", X"e7", X"e3", X"f0", X"fb", X"4d", X"d2", X"f8", X"0a", X"f8", X"d4", X"f9");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"f9";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

