-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w4a16/amc_cnn_4w16a_src_SinglePortRAM_generic_block390.vhd
-- Created: 2023-06-15 16:03:05
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_4w16a_src_SinglePortRAM_generic_block390
-- Source Path: amc_model_w4a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage39/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_4w16a_src_SinglePortRAM_generic_block390 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_4w16a_src_SinglePortRAM_generic_block390;


ARCHITECTURE rtl OF amc_cnn_4w16a_src_SinglePortRAM_generic_block390 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00",
                                                        X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"00", X"10", X"ec", X"f0", X"05", X"f0", X"05", X"0f", X"f6", X"08", X"f1", X"f9", X"0c", X"00", X"01",
                                                        X"f1", X"f9", X"fd", X"fa", X"f2", X"10", X"06", X"f0", X"fb", X"f6", X"02", X"e3", X"f3", X"0c", X"ff", X"14", X"f8", X"0c", X"fd", X"fd", X"fe", X"06", X"08", X"f3", X"09", X"02",
                                                        X"01", X"fd", X"02", X"0a", X"f1", X"11", X"ef", X"f3", X"ff", X"e6", X"e5", X"02", X"f8", X"f7", X"f7", X"fb", X"fe", X"1c", X"03", X"0b", X"fa", X"01", X"f3", X"08", X"f8", X"0e",
                                                        X"fb", X"05", X"03", X"f5", X"18", X"02", X"fd", X"1b", X"ff", X"07", X"03", X"04", X"e7", X"fc", X"0f", X"00", X"11", X"f9", X"09", X"fc", X"10", X"fd", X"09", X"05", X"f3", X"01",
                                                        X"f5", X"fd", X"df", X"fe", X"ed", X"ee", X"15", X"13", X"10", X"ec", X"fd", X"0a", X"f8", X"e1", X"f0", X"fd", X"01", X"ff", X"0d", X"ff", X"06", X"f7", X"07", X"0c", X"00", X"f6",
                                                        X"1c", X"fa", X"08", X"20", X"f9", X"0a", X"04", X"f9", X"12", X"08", X"10", X"fd", X"05", X"0b", X"07", X"05", X"10", X"07", X"08", X"1f", X"fd", X"fb", X"02", X"04", X"03", X"f6",
                                                        X"01", X"fd", X"10", X"f5", X"13", X"03", X"ec", X"fe", X"0a", X"02", X"fa", X"01", X"12", X"01", X"ee", X"06", X"0c", X"03", X"f0", X"11", X"01", X"07", X"24", X"f7", X"09", X"f2",
                                                        X"02", X"17", X"08", X"fd", X"15", X"03", X"fc", X"0b", X"0e", X"0d", X"0d", X"04", X"11", X"03", X"00", X"27", X"fa", X"01", X"0c", X"f8", X"13", X"04", X"0a", X"0b", X"0e", X"07",
                                                        X"03", X"0d", X"03", X"0b", X"00", X"f8", X"0a", X"09", X"04", X"03", X"00", X"0c", X"10", X"09", X"f1", X"12", X"17", X"0a", X"0c", X"05", X"00", X"d5", X"f1", X"f9", X"0e", X"07",
                                                        X"1e", X"07", X"0f", X"fa", X"fe", X"fa", X"09", X"03", X"17", X"f8", X"05", X"d8", X"01", X"14", X"f4", X"fe", X"1b", X"06", X"02", X"09", X"f0", X"0c", X"f7", X"03", X"fb", X"07",
                                                        X"06", X"1a", X"0e", X"03", X"fb", X"f4", X"27", X"05", X"03", X"1e", X"fb", X"f9", X"fb", X"0b", X"fd", X"f1", X"05", X"d6", X"ec", X"05", X"01", X"08", X"0d", X"03", X"09", X"f1",
                                                        X"10", X"06", X"f8", X"00", X"ec", X"ff", X"04", X"1a", X"fa", X"08", X"07", X"0f", X"0a", X"fe", X"03", X"0c", X"f3", X"04", X"f9", X"fb", X"fe", X"07", X"f7", X"ff", X"0c", X"05",
                                                        X"fc", X"02", X"eb", X"f9", X"f1", X"05", X"09", X"f7", X"ff", X"ef", X"06", X"09", X"f6", X"dd", X"0c", X"01", X"f3", X"0b", X"f5", X"0a", X"f9", X"fc", X"fe", X"f0", X"f8", X"ff",
                                                        X"f4", X"10", X"00", X"d5", X"ff", X"f3", X"fc", X"02", X"e7", X"0c", X"04", X"fc", X"f9", X"e5", X"fe", X"0d", X"f5", X"07", X"f6", X"fa", X"03", X"ea", X"f6", X"fc", X"fb", X"f7",
                                                        X"fe", X"f0", X"04", X"f4", X"fd", X"f8", X"e5", X"00", X"f6", X"f2", X"f6", X"ef", X"f3", X"ff", X"e6", X"f7", X"f3", X"ed", X"0f", X"f2", X"fc", X"ea", X"e9", X"0e", X"fb", X"e3",
                                                        X"07", X"f3", X"ef", X"02", X"e7", X"f1", X"00", X"f5", X"1a", X"f3", X"fe", X"f0", X"ef", X"0b", X"00", X"00", X"ff", X"ee", X"f4", X"f4", X"dc", X"05", X"eb", X"f5", X"ef", X"f6",
                                                        X"04", X"00", X"fd", X"0f", X"00", X"ff", X"f6", X"f0", X"f8", X"03", X"f7", X"08", X"06", X"fb", X"0a", X"f7", X"f7", X"03", X"f5", X"10", X"03", X"f8", X"0a", X"fb", X"07", X"08",
                                                        X"db", X"04", X"02", X"00", X"fc", X"f8", X"02", X"fd", X"09", X"08", X"05", X"0a", X"04", X"ff", X"00", X"07", X"f2", X"0a", X"f8", X"f6", X"05", X"ea", X"03", X"06", X"fb", X"00",
                                                        X"04", X"f1", X"f5", X"fe", X"00", X"09", X"fe", X"fe", X"06", X"fd", X"0b", X"fe", X"fd", X"0b", X"16", X"07", X"f9", X"05", X"0f", X"0d", X"fc", X"fc", X"fd", X"ef", X"f3", X"01",
                                                        X"02", X"fa", X"06", X"fd", X"01", X"fe", X"05", X"fa", X"f9", X"01", X"eb", X"ff", X"0d", X"f6", X"05", X"0c", X"0c", X"11", X"16", X"03", X"05", X"11", X"05", X"28", X"1e", X"07",
                                                        X"0f", X"fe", X"00", X"fd", X"fc", X"fb", X"fd", X"fd", X"09", X"08", X"0c", X"07", X"0b", X"e7", X"ff", X"04", X"0c", X"f7", X"0e", X"03", X"06", X"03", X"06", X"ed", X"07", X"05",
                                                        X"18", X"f1", X"03", X"e4", X"05", X"04", X"07", X"fb", X"10", X"fb", X"08", X"10", X"fd", X"05", X"01", X"07", X"17", X"02", X"04", X"f2", X"12", X"ff", X"e8", X"00", X"0c", X"08",
                                                        X"03", X"fa", X"f2", X"0d", X"0e", X"0c", X"f6", X"f9", X"f8", X"03", X"f7", X"03", X"0e", X"12", X"11", X"03", X"f4", X"0c", X"f5", X"0e", X"05", X"11", X"19", X"00", X"fc", X"e3",
                                                        X"f1", X"f9", X"01", X"fb", X"02", X"0d", X"fe", X"08", X"ff", X"06", X"0b", X"0d", X"15", X"00", X"fd", X"f7", X"07", X"0d", X"f6", X"f0", X"19", X"0a", X"06", X"09", X"25", X"09",
                                                        X"09", X"00", X"06", X"fe", X"fd", X"d6", X"ec", X"0a", X"0a", X"0f", X"0c", X"11", X"09", X"ff", X"f6", X"0e", X"fc", X"01", X"00", X"09", X"06", X"e8", X"0f", X"0d", X"07", X"11",
                                                        X"12", X"02", X"f8", X"f4", X"f2", X"11", X"06", X"1f", X"0e", X"03", X"ff", X"ff", X"ee", X"f3", X"0b", X"ff", X"13", X"01", X"09", X"fd", X"07", X"0e", X"05", X"f7", X"ff", X"f3",
                                                        X"01", X"1d", X"f9", X"f4", X"fb", X"fe", X"00", X"fd", X"14", X"f2", X"fb", X"f6", X"ff", X"04", X"07", X"01", X"0b", X"d7", X"02", X"07", X"02", X"ff", X"f2", X"fd", X"fa", X"ff",
                                                        X"0b", X"f0", X"ff", X"ee", X"08", X"f9", X"00", X"e7", X"fa", X"ef", X"f0", X"fe", X"f2", X"f3", X"07", X"ea", X"f2", X"03", X"f3", X"16", X"fc", X"17", X"01", X"15", X"09", X"fb",
                                                        X"ea", X"04", X"f7", X"f3", X"09", X"e7", X"ff", X"f2", X"00", X"06", X"fe", X"0f", X"00", X"ed", X"f9", X"08", X"f4", X"08", X"e4", X"04", X"08", X"e9", X"0a", X"f6", X"08", X"fa",
                                                        X"05", X"04", X"f9", X"1f", X"13", X"03", X"0d", X"07", X"f6", X"fa", X"f7", X"fa", X"fc", X"0a", X"02", X"f8", X"12", X"f0", X"0b", X"d1", X"fb", X"07", X"fa", X"fb", X"fc", X"f8",
                                                        X"05", X"09", X"f2", X"f8", X"01", X"fd", X"ff", X"04", X"fc", X"01", X"ff", X"f5", X"03", X"fc", X"fb", X"f3", X"04", X"04", X"0e", X"08", X"ed", X"01", X"12", X"f9", X"fe", X"10",
                                                        X"03", X"09", X"fd", X"02", X"05", X"ff", X"fd", X"15", X"fc", X"fb", X"fc", X"fb", X"f3", X"f6", X"03", X"f5", X"fe", X"06", X"f7", X"00", X"f4", X"05", X"10", X"fb", X"01", X"fe",
                                                        X"ff", X"07", X"0e", X"03", X"06", X"02", X"10", X"fe", X"08", X"01", X"ff", X"07", X"f9", X"09", X"0b", X"04", X"0a", X"fa", X"09", X"05", X"fe", X"0c", X"06", X"fb", X"fa", X"02",
                                                        X"03", X"08", X"02", X"04", X"10", X"04", X"f8", X"fd", X"0a", X"fa", X"06", X"e8", X"f8", X"0a", X"f5", X"fc", X"fa", X"02", X"04", X"11", X"ff", X"05", X"fa", X"04", X"07", X"fb",
                                                        X"06", X"d6", X"f7", X"0e", X"02", X"09", X"05", X"f7", X"fe", X"09", X"08", X"08", X"ff", X"f6", X"03", X"01", X"03", X"ec", X"f3", X"ff", X"fc", X"05", X"ff", X"04", X"0a", X"09",
                                                        X"e6", X"ff", X"fc", X"fc", X"04", X"10", X"f8", X"12", X"02", X"09", X"07", X"02", X"f7", X"0b", X"fe", X"f5", X"f8", X"11", X"08", X"fa", X"01", X"0c", X"03", X"11", X"04", X"0f",
                                                        X"07", X"0c", X"fe", X"fb", X"fd", X"f9", X"0f", X"03", X"15", X"01", X"fe", X"03", X"02", X"fb", X"fe", X"10", X"01", X"00", X"10", X"02", X"06", X"fd", X"f5", X"fb", X"0f", X"08",
                                                        X"15", X"ee", X"0e", X"08", X"02", X"06", X"05", X"00", X"fe", X"07", X"07", X"0c", X"fe", X"0a", X"00", X"fe", X"f4", X"0c", X"06", X"f2", X"ec", X"0b", X"fc", X"06", X"f0", X"12",
                                                        X"07", X"f9", X"09", X"00", X"fd", X"0a", X"f5", X"f1", X"04", X"0c", X"f5", X"ff", X"f4", X"f9", X"e2", X"f9", X"f4", X"e8", X"f2", X"fa", X"f9", X"fb", X"06", X"f2", X"f9", X"fd",
                                                        X"fb", X"01", X"fb", X"fc", X"e7", X"02", X"ff", X"fe", X"fe", X"01", X"01", X"06", X"ff", X"10", X"f9", X"f1", X"fc", X"04", X"00", X"06", X"ff", X"fb", X"03", X"04", X"fe", X"f8",
                                                        X"fb", X"00", X"02", X"01", X"fe", X"fd", X"12", X"02", X"fd", X"0c", X"e8", X"01", X"00", X"f0", X"f9", X"f5", X"04", X"f7", X"01", X"01", X"05", X"ec", X"09", X"fd", X"06", X"02",
                                                        X"f5", X"fa", X"f9", X"f9", X"0e", X"fe", X"04", X"ef", X"0e", X"00", X"07", X"04", X"eb", X"ff", X"05", X"fe", X"0d", X"03", X"03", X"09", X"17", X"fd", X"0e", X"f8", X"f6", X"fe",
                                                        X"0c", X"00", X"fa", X"11", X"02", X"05", X"0a", X"04", X"fd", X"1a", X"ed", X"07", X"06", X"10", X"00", X"f7", X"0d", X"fd", X"04", X"06", X"02", X"fe", X"18", X"03", X"03", X"fe",
                                                        X"05", X"fd", X"0b", X"0a", X"fb", X"13", X"f7", X"e2", X"f9", X"fd", X"01", X"05", X"06", X"f6", X"01", X"0d", X"09", X"0e", X"03", X"fb", X"13", X"01", X"f9", X"1a", X"01", X"00",
                                                        X"07", X"09", X"0d", X"01", X"05", X"f7", X"0b", X"fa", X"06", X"01", X"19", X"03", X"fc", X"f6", X"fc", X"fd", X"fb", X"00", X"07", X"0b", X"01", X"02", X"f5", X"fc", X"ff", X"03",
                                                        X"06", X"ff", X"08", X"f8", X"00", X"fb", X"0a", X"10", X"0c", X"fe", X"0d", X"09", X"04", X"03", X"fc", X"00", X"05", X"f9", X"00", X"ed", X"06", X"fe", X"ff", X"fd", X"f2", X"0a",
                                                        X"0b", X"02", X"09", X"0a", X"fb", X"01", X"12", X"04", X"fc", X"ea", X"fc", X"08", X"f3", X"0d", X"06", X"e8", X"ff", X"03", X"00", X"15", X"ff", X"0b", X"09", X"01", X"00", X"ea",
                                                        X"ed", X"16", X"f8", X"05", X"17", X"02", X"0a", X"0f", X"fc", X"0e", X"03", X"0c", X"02", X"0c", X"09", X"02", X"05", X"0b", X"fe", X"f0", X"0b", X"fe", X"fa", X"01", X"02", X"00",
                                                        X"04", X"01", X"05", X"fb", X"02", X"db", X"fe", X"05", X"fa", X"f0", X"08", X"fd", X"05", X"01", X"ff", X"fe", X"f9", X"02", X"06", X"01", X"05", X"fc", X"fd", X"0e", X"03", X"00",
                                                        X"0a", X"05", X"f2", X"ff", X"f5", X"09", X"f9", X"f7", X"06", X"03", X"02", X"e3", X"0b", X"09", X"fd", X"ff", X"fb", X"01", X"07", X"fd", X"04", X"f7", X"f9", X"07", X"f7", X"f7",
                                                        X"01", X"10", X"fa", X"00", X"fb", X"08", X"0d", X"f9", X"fe", X"01", X"f6", X"fb", X"08", X"00", X"ff", X"0f", X"f7", X"d3", X"f5", X"fa", X"0e", X"0d", X"f9", X"00", X"06", X"ef",
                                                        X"01", X"f9", X"0a", X"01", X"04", X"fd", X"ff", X"10", X"fe", X"f8", X"f9", X"fd", X"f9", X"07", X"06", X"01", X"06", X"f6", X"0e", X"01", X"fb", X"06", X"f3", X"dd", X"06", X"00",
                                                        X"0c", X"06", X"f7", X"fb", X"0f", X"f8", X"11", X"f7", X"06", X"09", X"f5", X"fe", X"04", X"0e", X"08", X"01", X"ff", X"fb", X"f0", X"01", X"f9", X"11", X"07", X"f6", X"04", X"fe",
                                                        X"fd", X"09", X"fc", X"ff", X"0b", X"f9", X"01", X"01", X"f5", X"02", X"0b", X"ed", X"fa", X"f8", X"f4", X"12", X"ff", X"fd", X"03", X"0f", X"12", X"00", X"06", X"02", X"f2", X"fe",
                                                        X"11", X"fe", X"f5", X"ee", X"09", X"fc", X"08", X"fb", X"02", X"e7", X"03", X"f8", X"06", X"f5", X"f5", X"fc", X"f9", X"f9", X"04", X"fb", X"0b", X"12", X"01", X"fe", X"02", X"f3",
                                                        X"03", X"08", X"00", X"03", X"02", X"08", X"13", X"0d", X"0f", X"fe", X"fd", X"05", X"0d", X"13", X"0e", X"e4", X"f0", X"00", X"0a", X"fb", X"1a", X"0e", X"01", X"01", X"fa", X"05",
                                                        X"00", X"15", X"02", X"04", X"05", X"12", X"f5", X"10", X"f9", X"04", X"07", X"03", X"11", X"f5", X"1b", X"02", X"fc", X"0a", X"ff", X"fc", X"10", X"ed", X"09", X"07", X"f5", X"fa",
                                                        X"ff", X"04", X"09", X"0b", X"13", X"fe", X"0a", X"0c", X"0c", X"f5", X"fe", X"06", X"03", X"0c", X"01", X"fb", X"05", X"fb", X"05", X"01", X"01", X"03", X"09", X"01", X"01", X"05",
                                                        X"08", X"14", X"09", X"ff", X"ee", X"00", X"fd", X"fb", X"f2", X"07", X"03", X"f6", X"fd", X"fc", X"06", X"09", X"ed", X"f5", X"02", X"fb", X"04", X"f1", X"23", X"05", X"f1", X"0d",
                                                        X"fc", X"f4", X"00", X"fe", X"05", X"f8", X"ff", X"f3", X"fe", X"fc", X"ee", X"fa", X"08", X"fd", X"fa", X"fa", X"f7", X"01", X"01", X"02", X"0e", X"11", X"fb", X"db", X"fb", X"fe",
                                                        X"f9", X"ff", X"04", X"f6", X"f4", X"11", X"fb", X"ff", X"01", X"f4", X"f3", X"fc", X"04", X"e4", X"fd", X"f9", X"09", X"02", X"09", X"fa", X"f1", X"f4", X"f9", X"f8", X"14", X"db",
                                                        X"ed", X"f2", X"00", X"09", X"fe", X"07", X"ff", X"ed", X"f9", X"ff", X"f8", X"f8", X"00", X"03", X"fb", X"e7", X"fd", X"06", X"05", X"12", X"08", X"ff", X"fc", X"05", X"00", X"fe",
                                                        X"02", X"f6", X"0b", X"0c", X"fc", X"f6", X"fa", X"ff", X"fe", X"dc", X"eb", X"f8", X"fc", X"0f", X"08", X"06", X"f9", X"f2", X"03", X"fb", X"fe", X"f5", X"fb", X"05", X"fd", X"e4",
                                                        X"fe", X"04", X"f8", X"06", X"f1", X"0b", X"fe", X"04", X"06", X"ff", X"08", X"f3", X"f9", X"fa", X"fd", X"fd", X"f1", X"08", X"02", X"09", X"fa", X"fc", X"05", X"f8", X"f1", X"f7",
                                                        X"0c", X"f5", X"f3", X"fb", X"fa", X"03", X"f5", X"03", X"f6", X"03", X"02", X"f2", X"0d", X"00", X"f2", X"f8", X"04", X"0a", X"f7", X"fb", X"fb", X"05", X"f7", X"fc", X"0c", X"02",
                                                        X"08", X"05", X"07", X"f7", X"03", X"11", X"05", X"05", X"fe", X"ff", X"ff", X"16", X"fd", X"f1", X"fa", X"fc", X"fc", X"08", X"09", X"08", X"00", X"f9", X"07", X"10", X"f6", X"f5",
                                                        X"0e", X"fc", X"f1", X"f9", X"0a", X"01", X"e8", X"fa", X"0a", X"0c", X"08", X"15", X"f1", X"08", X"1a", X"09", X"10", X"f7", X"ec", X"f8", X"f3", X"f9", X"f6", X"04", X"f3", X"fc",
                                                        X"09", X"f8", X"fa", X"f5", X"fd", X"00", X"f8", X"0b", X"10", X"02", X"eb", X"f1", X"0a", X"03", X"f1", X"01", X"f4", X"ff", X"03", X"03", X"fd", X"07", X"f9", X"13", X"fb", X"03",
                                                        X"09", X"02", X"f5", X"fd", X"f3", X"0d", X"02", X"fc", X"07", X"ea", X"fa", X"fd", X"02", X"df", X"0c", X"0a", X"05", X"05", X"ee", X"ff", X"06", X"01", X"09", X"02", X"f0", X"f4",
                                                        X"06", X"fe", X"08", X"1d", X"fd", X"05", X"fd", X"f9", X"e8", X"04", X"f5", X"01", X"08", X"03", X"ef", X"f8", X"f9", X"02", X"f9", X"eb", X"f3", X"08", X"ff", X"0b", X"04", X"02",
                                                        X"fa", X"02", X"fa", X"0e", X"07", X"f1", X"ed", X"00", X"02", X"0d", X"08", X"f3", X"f6", X"fb", X"fa", X"f9", X"ff", X"f5", X"04", X"ff", X"fa", X"f6", X"06", X"00", X"07", X"0a",
                                                        X"01", X"ff", X"00", X"fa", X"e4", X"00", X"ff", X"10", X"0d", X"f7", X"09", X"fe", X"11", X"ec", X"fd", X"0a", X"f2", X"08", X"ff", X"07", X"11", X"fa", X"f8", X"f8", X"fe", X"fa",
                                                        X"ff", X"fd", X"1b", X"02", X"07", X"fe", X"f7", X"0a", X"ff", X"0d", X"f9", X"f1", X"06", X"f9", X"03", X"f3", X"fe", X"f9", X"f9", X"f9", X"02", X"ea", X"ed", X"05", X"07", X"0d",
                                                        X"f7", X"03", X"0c", X"0d", X"fc", X"0e", X"05", X"08", X"06", X"07", X"fd", X"e9", X"00", X"06", X"ff", X"08", X"21", X"02", X"0e", X"fb", X"04", X"06", X"fb", X"07", X"1c", X"00",
                                                        X"f5", X"f3", X"f7", X"fc", X"04", X"0a", X"12", X"f6", X"18", X"07", X"fe", X"11", X"f9", X"0b", X"02", X"f4", X"f9", X"1b", X"13", X"0b", X"ff", X"fc", X"0c", X"ea", X"0c", X"e8",
                                                        X"05", X"09", X"fe", X"fb", X"f1", X"01", X"fe", X"fb", X"ee", X"0a", X"f9", X"00", X"03", X"0e", X"04", X"00", X"0e", X"07", X"0a", X"ed", X"08", X"0b", X"00", X"f9", X"eb", X"05",
                                                        X"0f", X"00", X"08", X"0e", X"02", X"fb", X"fe", X"f8", X"0b", X"f5", X"09", X"ea", X"09", X"e7", X"0a", X"0a", X"04", X"01", X"e9", X"0b");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"0b";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

