-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16_4x2/amc_cnn_16w16a_4x2_src_SinglePortRAM_generic_block356.vhd
-- Created: 2024-11-04 16:44:13
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_4x2_src_SinglePortRAM_generic_block356
-- Source Path: amc_model_w16a16_4x2/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage122/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_4x2_src_SinglePortRAM_generic_block356 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_4x2_src_SinglePortRAM_generic_block356;


ARCHITECTURE rtl OF amc_cnn_16w16a_4x2_src_SinglePortRAM_generic_block356 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"ff29", X"0104", X"0170", X"fd95", X"00ca", X"fd85",
                                                        X"fd18", X"fe18", X"0169", X"012e", X"fe88", X"fce4", X"fe6f", X"fe78", X"ff93", X"00bb", X"fd39", X"00d2", X"fec6", X"ffe7",
                                                        X"ff8c", X"0125", X"ffd8", X"fe07", X"0155", X"fd97", X"fe58", X"fdcd", X"0099", X"fead", X"fdbf", X"002a", X"ffb9", X"008d",
                                                        X"00da", X"fcdf", X"fdcb", X"ff44", X"015a", X"fe4d", X"ffa3", X"fed6", X"ff98", X"fdd8", X"feeb", X"006e", X"fedc", X"011d",
                                                        X"fd03", X"ffa7", X"fe94", X"fdac", X"fcf4", X"ffe4", X"fd37", X"fced", X"0220", X"fda9", X"fe54", X"fd7e", X"0181", X"ffa7",
                                                        X"fd34", X"ff1d", X"fe4c", X"fda1", X"026a", X"fe65", X"0029", X"ffb7", X"ffc1", X"fd37", X"ff1d", X"ffa9", X"020c", X"00a7",
                                                        X"fdde", X"0049", X"fd2b", X"fcda", X"ff35", X"0231", X"0234", X"0095", X"fde9", X"0189", X"ffcc", X"fede", X"fe4f", X"01b2",
                                                        X"fce5", X"fe29", X"fe8c", X"fe56", X"fead", X"feef", X"01b7", X"ffbb", X"fdf3", X"0004", X"002c", X"fda2", X"0054", X"ff39",
                                                        X"ff70", X"ffc8", X"fe07", X"fe0b", X"0198", X"ffe2", X"fec2", X"ff83", X"0194", X"ff39", X"fd58", X"fffa", X"01b4", X"ffed",
                                                        X"fefe", X"0232", X"02c9", X"feb3", X"fda6", X"026b", X"001b", X"0210", X"fd65", X"fff9", X"0071", X"ff26", X"0022", X"00ad",
                                                        X"023e", X"0014", X"0160", X"fee9", X"011d", X"01e9", X"0156", X"fdb8", X"ffc4", X"ff71", X"fef0", X"ff9e", X"fdbe", X"010a",
                                                        X"00f6", X"ff7a", X"ff4d", X"0161", X"ff7d", X"024b", X"ff1b", X"012f", X"006f", X"0107", X"01b6", X"01e5", X"fe66", X"fdcf",
                                                        X"fe5e", X"00c4", X"fe2c", X"ff5f", X"01a7", X"fe0e", X"fd03", X"fe72", X"ffe5", X"ff91", X"0037", X"ffd9", X"fd70", X"fe0f",
                                                        X"01c7", X"00af", X"fe29", X"feee", X"ff50", X"0167", X"00e2", X"fcff", X"0069", X"fddd", X"0292", X"0078", X"00ba", X"fd77",
                                                        X"0272", X"ffeb", X"fe26", X"fff7", X"0008", X"0074", X"fd98", X"013b", X"00f8", X"fe02", X"fd27", X"fed1", X"01f3", X"00e9",
                                                        X"fd7c", X"01ea", X"fdfd", X"fdf4", X"fd0c", X"003c", X"fe57", X"fd38", X"00e6", X"0266", X"ff58", X"fd40", X"0199", X"00a4",
                                                        X"fda0", X"fe81", X"005a", X"fdb9", X"0045", X"fd1f", X"fd6f", X"fff0", X"ff75", X"0233", X"0191", X"00c0", X"019d", X"ff40",
                                                        X"ff0b", X"fd44", X"024c", X"00e1", X"fdb1", X"01d8", X"02a8", X"0043", X"fd9d", X"fe97", X"fe92", X"028c", X"fd8a", X"025a",
                                                        X"0219", X"0292", X"fe4c", X"ff45", X"fd7c", X"fdc3", X"fedb", X"fe25", X"ff8e", X"fefd", X"ff37", X"fe73", X"00a7", X"02a4",
                                                        X"fd93", X"fe37", X"0185", X"feeb", X"fe58", X"fd42", X"0210", X"0075", X"0086", X"fd9b", X"01b9", X"01f0", X"01df", X"ffa4",
                                                        X"00f6", X"0178", X"023e", X"feb8", X"01e2", X"0100", X"ff44", X"0210", X"ff4c", X"fecc", X"ff79", X"fd59", X"fda3", X"ffa2",
                                                        X"fdc3", X"fdb9", X"ff74", X"000e", X"fd6e", X"0065", X"fffb", X"fe74", X"01e6", X"0089", X"0137", X"0271", X"ffb2", X"fd0c",
                                                        X"fe7a", X"02a8", X"fdfe", X"020b", X"01a5", X"0165", X"023c", X"ff0b", X"ffbf", X"fd22", X"fe90", X"023c", X"012c", X"fdad",
                                                        X"0045", X"ffa0", X"fd82", X"fd71", X"ff7f", X"fe28", X"fd95", X"fe39", X"029f", X"ffe3", X"ff91", X"01ef", X"0164", X"02d0",
                                                        X"fd7d", X"fd8e", X"fe9b", X"0269", X"022e", X"01c7", X"003e", X"ffe0", X"fd0e", X"ff3c", X"fdb6", X"01d9", X"027b", X"00de",
                                                        X"0258", X"0079", X"0185", X"0189", X"fee4", X"012e", X"01c8", X"fe8b", X"0251", X"00b3", X"fe52", X"02a5", X"fe44", X"00fc",
                                                        X"fdd8", X"00af", X"ff75", X"01bf", X"01aa", X"fd5a", X"00fb", X"005c", X"01cb", X"01af", X"00a9", X"0185", X"fd92", X"000a",
                                                        X"ff63", X"ff45", X"ff2b", X"feeb", X"002e", X"fee7", X"005e", X"00a2", X"027a", X"fdd1", X"fd36", X"027b", X"0144", X"fd2a",
                                                        X"ff91", X"fd7e", X"ff70", X"027b", X"02a6", X"fe89", X"0244", X"fd35", X"ff1e", X"0200", X"feae", X"feeb", X"feea", X"003b",
                                                        X"fce4", X"00cf", X"fd3e", X"00db", X"ffc9", X"0025", X"ffa8", X"ff99", X"015e", X"fcad", X"00db", X"0101", X"0102", X"00fb",
                                                        X"01b6", X"00d1", X"01ea", X"fcff", X"fcde", X"01bb", X"ff41", X"ffd5", X"0032", X"fe70", X"fd4a", X"ff3a", X"0013", X"ff4c",
                                                        X"fe4f", X"feba", X"ffaf", X"ffa2", X"020a", X"fe47", X"fdd4", X"fe0b", X"00b3", X"fef3", X"fd04", X"fd2e", X"ff3c", X"fe86",
                                                        X"029d", X"01c5", X"025d", X"ffa9", X"0260", X"fd91", X"0082", X"ff27", X"fcf1", X"002b", X"ff5d", X"0194", X"00a6", X"00e9",
                                                        X"0212", X"fd95", X"0117", X"005a", X"ffd1", X"0133", X"fd34", X"0134", X"ff86", X"0202", X"0169", X"fece", X"02c0", X"fe20",
                                                        X"00dd", X"017b", X"01b6", X"0228", X"fd46", X"0076", X"fef0", X"ff79", X"fdeb", X"ffbe", X"0000", X"ff51", X"0248", X"000f",
                                                        X"0141", X"ff57", X"0117", X"fcd6", X"fe63", X"fd11", X"fdbc", X"fea8", X"fdd9", X"ffee", X"01b4", X"fd24", X"0274", X"ff8e",
                                                        X"ff1f", X"0247", X"ff2c", X"ff1c", X"00cc", X"015e", X"fe2b", X"0239", X"fea1", X"ffe8", X"fd16", X"fe80", X"0266", X"0196",
                                                        X"00a2", X"fef5", X"fe21", X"016d", X"01ce", X"fe91", X"fd0a", X"0039", X"00d0", X"fcb1", X"fe4e", X"0213", X"ffd4", X"001e",
                                                        X"01bb", X"fe7b", X"ff76", X"02c5", X"0134", X"ff94", X"ff7f", X"0248", X"0170", X"01e0", X"ffb0", X"01cc", X"008e", X"fe63",
                                                        X"fd44", X"fdac", X"fd06", X"fcbf", X"02c2", X"fd93", X"00df", X"012c", X"00eb", X"01f4", X"fdbe", X"ff7a", X"ff9f", X"0026",
                                                        X"0022", X"fdfa", X"fe74", X"fe5d", X"fcce", X"ffa7", X"00f6", X"015f", X"0212", X"fd23", X"0284", X"fed9", X"ff55", X"fd28",
                                                        X"0000", X"0278", X"ff12", X"016b", X"fe6a", X"fd36", X"fe14", X"0187", X"0239", X"fe09", X"007b", X"0051", X"01ec", X"0125",
                                                        X"01d1", X"fe8e", X"fe37", X"025f", X"0189", X"fe27", X"01cf", X"fe98", X"00db", X"029f", X"0065", X"022f", X"fd5e", X"0056",
                                                        X"0169", X"011e", X"ffd7", X"ffe0", X"ff8c", X"025b", X"fff8", X"feb1", X"fe55", X"fd0b", X"0043", X"ff10", X"ffe4", X"fed7",
                                                        X"fcf4", X"fd3c", X"0183", X"ffb4", X"fedd", X"fdf4", X"0189", X"ffd3", X"007f", X"0001", X"00f4", X"0083", X"ff75", X"fea9",
                                                        X"fe3d", X"fee6", X"fcea", X"fedc", X"ff7f", X"005a", X"fd65", X"fea4", X"ff12", X"016c", X"fe6d", X"00a6", X"01aa", X"012b",
                                                        X"fdff", X"01f6", X"fdbb", X"fdde", X"0091", X"ffec", X"01a7", X"0281", X"002c", X"fdb8", X"014d", X"fe60", X"026f", X"fe99",
                                                        X"01da", X"0068", X"fdc7", X"fd2a", X"ff8b", X"00cc", X"fe15", X"00eb", X"fe3f", X"fd21", X"0177", X"024d", X"fdf5", X"ffa2",
                                                        X"fe50", X"feb4", X"0124", X"ff6e", X"01bf", X"ffd9", X"fdcb", X"fd83", X"fd16", X"ffa0", X"00fc", X"0260", X"005c", X"fe43",
                                                        X"0147", X"fe03", X"01a7", X"ff3e", X"fdf4", X"0005", X"fff8", X"00c8", X"fddf", X"01e4", X"ffc2", X"ff04", X"0085", X"00d1",
                                                        X"fd1a", X"0164", X"fe40", X"0137", X"01d7", X"0131", X"fe83", X"027b", X"fdd5", X"fd43", X"fcf9", X"0009", X"fd46", X"fd76",
                                                        X"fd68", X"ff9d", X"0038", X"0138", X"00b0", X"01da", X"fe19", X"fe63", X"fda6", X"fdb3", X"ff41", X"fdce", X"fe5c", X"fcf5",
                                                        X"01e0", X"fec0", X"fe67", X"0161", X"fe97", X"fd4d", X"02c0", X"fdbe", X"feb8", X"0241", X"0111", X"00cb", X"0128", X"01de",
                                                        X"0163", X"fcf6", X"0204", X"fd3e", X"019c", X"0030", X"fd33", X"fe41", X"0003", X"025e", X"fe5c", X"fe9c", X"009d", X"0003",
                                                        X"01a9", X"01ff", X"027f", X"0100", X"fed1", X"00b3", X"011f", X"001f", X"fd90", X"004e", X"012d", X"02a2", X"ffcd", X"0065",
                                                        X"fe76", X"fdc7", X"0072", X"0073", X"ffef", X"fdb5", X"fe4c", X"019c", X"ff9d", X"fe4b", X"013a", X"ff37", X"fd0d", X"ffcd",
                                                        X"ff0b", X"fe1b", X"ff38", X"fcef", X"0064", X"00f0", X"0281", X"fdf7", X"ffa6", X"fe86", X"fdf1", X"fe56", X"fe15", X"0111",
                                                        X"0086", X"fe11", X"0232", X"0000", X"0001", X"fdce", X"017c", X"0115", X"0138", X"00c9", X"01ec", X"ff45", X"02ba", X"0247",
                                                        X"fd75", X"fcd0", X"fe74", X"fcc9", X"01d9", X"0107", X"fda6", X"028d", X"0153", X"00af", X"fcf2", X"01fa", X"fd31", X"fec3",
                                                        X"fd85", X"ffbe", X"fdd6", X"01ea", X"feaa", X"fd3d", X"01e0", X"000e", X"ffc6", X"0240", X"feea", X"00b9", X"00ff", X"ffe6",
                                                        X"ff00", X"feed", X"00f1", X"fe9d", X"0068", X"fdcf", X"0228", X"ff7d", X"fddd", X"fe11", X"fd1a", X"fea1", X"01d0", X"025d",
                                                        X"ffa4", X"0193", X"fe35", X"0073", X"ff37", X"014f", X"fd01", X"ff55", X"029a", X"ff6e", X"fe9a", X"008e", X"fd99", X"ff7b",
                                                        X"fd92", X"ffe2", X"0168", X"ff6f", X"0058", X"025c", X"fee8", X"fff1", X"00a4", X"fcd5", X"0141", X"ff02", X"fef3", X"ff2f",
                                                        X"00e0", X"0028", X"fd39", X"0102", X"012c", X"fff9", X"ffa6", X"00b0", X"01fd", X"025c", X"01ea", X"009d", X"00be", X"fec2",
                                                        X"fe29", X"fd86", X"0085", X"fd75", X"00d1", X"015d", X"00c9", X"ff66", X"fe52", X"ff80", X"0160", X"02aa", X"fd8d", X"012c",
                                                        X"fded", X"fe7f", X"01b6", X"0140", X"fe75", X"ff92", X"0228", X"0113", X"0036", X"026d", X"000f", X"0074", X"feba", X"fdf5",
                                                        X"025f", X"ff53", X"016f", X"0108", X"0253", X"fe9a", X"fdfc", X"fcbe", X"01dc", X"ff3f", X"0004", X"008f", X"021d", X"fee4",
                                                        X"fda8", X"fe3e", X"fd23", X"0174", X"0102", X"025f", X"011c", X"019b", X"00ca", X"0234", X"ff83", X"fd41", X"01ad", X"ffd8",
                                                        X"01af", X"00f1", X"0285", X"fee6", X"00ac", X"01ca", X"0057", X"01f4", X"fefa", X"fe7a", X"0285", X"fd96", X"010d", X"fea2",
                                                        X"00c9", X"ff74", X"ff45", X"fdb1", X"fe0d", X"ff70", X"fd87", X"fe67", X"ff4f", X"fde7", X"0212", X"ffe1", X"fee2", X"0032",
                                                        X"021d", X"005c", X"006b", X"0219", X"01f1", X"fe2e", X"01f5", X"0214", X"ff8c", X"0191", X"feb0", X"01f5", X"01c2", X"0133",
                                                        X"fe86", X"01fb", X"ff1c", X"fe0f", X"0169", X"fd03", X"fff4", X"fde1", X"027e", X"fe99", X"01d9", X"01e1", X"ffae", X"fecd",
                                                        X"0075", X"fe02", X"0172", X"fd94", X"0104", X"ff86", X"01db", X"ffd8", X"0146", X"00e9", X"02ac", X"fffc", X"ff81", X"fe47",
                                                        X"fd81", X"fd2a", X"fcd5", X"ffdf", X"fde2", X"ffb4", X"0258", X"ffad", X"0185", X"0091", X"00ba", X"fe4a", X"0225", X"fd66",
                                                        X"fe9a", X"0034", X"014f", X"ff04", X"01e1", X"fd90", X"ff57", X"ff41", X"ff25", X"fd79", X"023d", X"fcfa", X"0255", X"0248",
                                                        X"0143", X"fe7e", X"0106", X"fdf5", X"013a", X"00cb", X"019b", X"01cf", X"feb1", X"fe63", X"00c6", X"027c", X"00ab", X"0195",
                                                        X"fd1f", X"fdc1", X"00d5", X"fcbb", X"fd9f", X"ff75", X"fe7e", X"0029", X"fd54", X"ff74", X"008a", X"fd4d", X"fef8", X"fd40",
                                                        X"fd0e", X"fe28", X"0043", X"fd3a", X"feff", X"fe4f", X"0116", X"fe7c", X"fd64", X"fd45", X"fd20", X"fe5e", X"0017", X"fced",
                                                        X"ffb5", X"fd5c", X"fe24", X"0101", X"01c1", X"fe8c", X"023d", X"fda0", X"fd40", X"0219", X"ffaa", X"0019", X"ff77", X"fd4c",
                                                        X"01b9", X"fec0", X"fe91", X"0123", X"00d6", X"ffae", X"0179", X"feb4", X"0259", X"ffb6", X"017b", X"0061", X"0186", X"fd54",
                                                        X"fe6f", X"fcea", X"017e", X"018e", X"00b6", X"0068", X"0115", X"01dd", X"ffab", X"ff04", X"0139", X"ff5e", X"ffc3", X"ffde",
                                                        X"0254", X"fe33", X"ff6e", X"016f", X"fd34", X"fd2d", X"fe30", X"00af", X"01f3", X"0187", X"01f0", X"0055", X"027c", X"fecd",
                                                        X"fdd2", X"ff85", X"00c2", X"fd38", X"ffa6", X"fd8c", X"0076", X"fe62", X"00bf", X"fd95", X"004a", X"001c", X"fcf5", X"01e1",
                                                        X"016c", X"fd96", X"02a2", X"ffff", X"fd32", X"fe76", X"ffbd", X"fd03", X"fd52", X"01d5", X"0154", X"fecc", X"01a6", X"fd39",
                                                        X"fdcb", X"fe36", X"019f", X"feea", X"020e", X"01ae", X"0117", X"fdc2", X"fe3b", X"0109", X"004d", X"fe2a", X"fdaa", X"0277",
                                                        X"ff61", X"feca", X"fcf1", X"0042", X"fe61", X"02bb", X"0230", X"01ac", X"02a7", X"fcfd", X"fd14", X"ff95", X"fd7c", X"fd60",
                                                        X"0138", X"0151", X"0240", X"fe99", X"014a", X"027a", X"ff9e", X"fef9", X"ff4f", X"00ed", X"0157", X"ff3a", X"01c1", X"ff56",
                                                        X"01b3", X"ff56", X"fff0", X"ff47", X"019f", X"fd66", X"0002", X"fcee", X"0043", X"0021", X"ff98", X"016b", X"0018", X"0258",
                                                        X"019a", X"fd56", X"fdd3", X"fe05", X"012e", X"ff4b", X"fd37", X"00d8", X"00fb", X"fe6d", X"02be", X"0160", X"fd82", X"0138",
                                                        X"029e", X"ff42", X"ff2b", X"ffb1", X"fe25", X"00f4", X"ff78", X"fff6", X"009d", X"00d2", X"0141", X"026e", X"ffd4", X"fdb5",
                                                        X"ffa5", X"0007", X"ff1d", X"00a6", X"0229", X"010d", X"fea7", X"0219", X"fd49", X"0148", X"fd41", X"fddc", X"023f", X"fe97",
                                                        X"ff18", X"00ca", X"fd0f", X"002c", X"fe1a", X"01f6", X"01a4", X"ff4d", X"ff37", X"fdd5", X"fe55", X"018b", X"fd61", X"01b1",
                                                        X"fe82", X"fdc5", X"0199", X"002b", X"fdfa", X"fd25", X"fd65", X"ffca", X"0052", X"ff73", X"fdf6", X"0174", X"0130", X"01d5",
                                                        X"fe4d", X"0039", X"fde8", X"0180", X"fcfd", X"fde6", X"fda5", X"fcd6", X"0181", X"fd4c", X"ffa3", X"ff3b", X"fde7", X"ff67",
                                                        X"0068", X"fd0b", X"fd8c", X"fec7", X"00a8", X"0000", X"0265", X"005d", X"fdc5", X"ffcf", X"00eb", X"0109", X"ff77", X"fe49",
                                                        X"fedb", X"00e9", X"fd42", X"0228", X"01b2", X"025c", X"02da", X"002c", X"0223", X"0045", X"fcc5", X"01b2", X"fe27", X"fd4f",
                                                        X"01d9", X"0126", X"fd92", X"fe97", X"ff17", X"01fd", X"01d2", X"0059", X"0150", X"ffba", X"fdf4", X"0180", X"0127", X"000f",
                                                        X"fd6b", X"fd2c", X"feec", X"fdd5", X"fd77", X"017a", X"ffd5", X"fe46", X"fcf3", X"0201", X"fdb0", X"ff80", X"fde0", X"ffdb",
                                                        X"01c4", X"ff47", X"fef7", X"fedf", X"fdcf", X"feaf", X"fe34", X"fdfa", X"fe6b", X"0081", X"01c1", X"fd50", X"028c", X"fd3f",
                                                        X"00d1", X"01a8", X"fe8a", X"fe1a", X"fedf", X"febb", X"fd65", X"fd2e", X"fee7", X"0070", X"fd95", X"ffad", X"0116", X"0093",
                                                        X"01e0", X"007e", X"ff29", X"fd30", X"fe1d", X"0235", X"010c", X"0093", X"fcdd", X"006f", X"00d8", X"0068", X"01d8", X"01d3",
                                                        X"020f", X"0247", X"fe79", X"fdc0", X"fd60", X"fdc4", X"026a", X"fe0a", X"fdd7", X"fe83", X"ffec", X"fdf1", X"fd53", X"0083",
                                                        X"fdce", X"0171", X"ff85", X"fe2d", X"01ee", X"ff89", X"0209", X"fff8", X"000d", X"000d", X"0260", X"fdbc", X"fd86", X"ff72",
                                                        X"0032", X"01a1", X"ff6a", X"011e", X"fe65", X"fd70", X"0087", X"fefd", X"027c", X"0206", X"ffa2", X"fd37", X"0280", X"fe95",
                                                        X"ff39", X"fd06", X"023b", X"ff93", X"fe19", X"fd99", X"fe62", X"ff0e", X"0036", X"01d1", X"0141", X"014b", X"0224", X"fe14",
                                                        X"0121", X"0172", X"ff49", X"00e1", X"ffce", X"fcc4", X"019a", X"0008", X"0077", X"0102", X"0253", X"ffed", X"0157", X"00c3",
                                                        X"00bb", X"ff81", X"fd9a", X"007f", X"01c0", X"ff23", X"0142", X"ff37", X"0298", X"fe75", X"fdfd", X"01fc", X"00b6", X"fd19",
                                                        X"feb1", X"0133", X"ff72", X"fd8b", X"fed6", X"fedb", X"020d", X"0276", X"01e3", X"fe90", X"fef1", X"0217", X"ffca", X"fe3a",
                                                        X"ff9f", X"fe81", X"ffb5", X"0187", X"fdfe", X"0261", X"fefa", X"0198", X"feaa", X"feb2", X"003d", X"00ec", X"fd06", X"ff24",
                                                        X"0139", X"fd32", X"fe68", X"fdbe", X"003c", X"ff08", X"fce9", X"fead", X"fdad", X"ffb5", X"ff9b", X"ff63", X"ff77", X"ffa2",
                                                        X"fdad", X"00c3", X"feb6", X"ff71", X"0106", X"0186", X"0115", X"0089", X"0103", X"021b", X"fd79", X"0238", X"ff6f", X"fea8",
                                                        X"fe0b", X"fefb", X"026d", X"fee4", X"fdf3", X"01c4", X"0211", X"fdea", X"fe47", X"0132", X"01d0", X"fdcc", X"fd69", X"fd50",
                                                        X"fef7", X"019c", X"fffb", X"fe7d", X"0189", X"0066", X"003c", X"fe3a", X"ff21", X"00c1", X"007a", X"ffe0", X"ff37", X"0244",
                                                        X"0277", X"00b3", X"fd1e", X"00fb", X"0260", X"fcf6", X"fe57", X"fdc0", X"fe18", X"ff5c", X"fe11", X"fe2a", X"0111", X"ffab",
                                                        X"004b", X"ff8b", X"0095", X"ff6e", X"007e", X"fea9", X"fdee", X"ff1a", X"fe28", X"00e1", X"00de", X"fd4c", X"fdaf", X"fef7",
                                                        X"fdd1", X"fe85", X"0267", X"fcd1", X"00c1", X"fe76", X"00b6", X"fcfe", X"ff2b", X"0253", X"fe29", X"009b", X"fd3d", X"0290",
                                                        X"021a", X"00f7", X"ffc1", X"0081", X"fd8f", X"0014", X"fe84", X"0110", X"fde7", X"007a", X"fdf1", X"0143", X"ff93", X"ff30",
                                                        X"01a7", X"fd94", X"0022", X"ffd2", X"003b", X"fddf", X"ffe7", X"00a6", X"ff1b", X"005b", X"0164", X"fe30", X"ff3f", X"0117",
                                                        X"0261", X"028e", X"01ce", X"0151", X"fd0f", X"0115", X"022a", X"01d9", X"ff5e", X"fe59", X"fd11", X"0196", X"fd30", X"006a",
                                                        X"0183", X"01eb", X"0056", X"ffbb", X"016e", X"0230", X"feda", X"fd12", X"022c", X"01e4", X"01b7", X"ff76", X"fdb8", X"fef3",
                                                        X"fec9", X"fe35", X"fea1", X"ffe0", X"ffbe", X"024c", X"fdd8", X"006b", X"027e", X"0260", X"01d0", X"ff84", X"fe4a", X"fe5c",
                                                        X"0157", X"018e", X"0175", X"fd0c", X"fea6", X"fd8a", X"fe76", X"ff9a", X"fe43", X"fe42", X"fd98", X"ffdd", X"fdd5", X"ff5d",
                                                        X"fd60", X"fdfd", X"0254", X"0220", X"0187", X"fe2e", X"fd1d", X"ff02", X"013d", X"fce6", X"fffe", X"fd0d", X"0130", X"fd61",
                                                        X"fd21", X"00b4", X"0230", X"fd24", X"fe5b", X"ffec", X"fedb", X"fdd0", X"026b", X"0105", X"ff23", X"fce1", X"fdad", X"feaf",
                                                        X"ffa2", X"007c", X"fead", X"001d", X"001a", X"01bb", X"fdd7", X"01dc", X"ffb5", X"ffa3", X"ff8a", X"fe97", X"ff2e", X"007c",
                                                        X"fd67", X"fee9", X"009c", X"fd1d", X"0022", X"fdde", X"fdb1", X"fe84", X"01a0", X"fd0a", X"ff12", X"00d8", X"011d", X"01f1",
                                                        X"00ed", X"01d4", X"fed0", X"0140", X"fce6", X"ff17", X"fe89", X"fe60", X"00ea", X"fe58", X"ffec", X"fd8f", X"00c6", X"0274",
                                                        X"0145", X"027d", X"000e", X"00a5", X"fd5c", X"fdac", X"00c7", X"00c6", X"020f", X"0272", X"004b", X"ff9c", X"ff84", X"fe3b",
                                                        X"01ca", X"0096", X"fdf1", X"017e", X"01af", X"fed9", X"fe99", X"fda7", X"026b", X"fd9a", X"0148", X"002e", X"0164", X"fed5",
                                                        X"fff9", X"fe8b", X"0171", X"0159", X"ff33", X"000b", X"024f", X"ff1d", X"ff4d", X"0000", X"fe98", X"0174", X"fd65", X"029a",
                                                        X"023c", X"0136", X"009d", X"fd3c", X"02ca", X"013b", X"fd70", X"0288", X"000a", X"ff10", X"fd41", X"01d7", X"fd4b", X"fcf6",
                                                        X"fe39", X"fe73", X"0013", X"fd0c", X"01b0", X"fe66", X"01ae", X"ff41", X"00a2", X"fff4", X"fedb", X"006f", X"fea6", X"fde4",
                                                        X"ffe2", X"01c7", X"fd93", X"ffcf", X"ffb7", X"feeb", X"fef0", X"0037", X"ff3b", X"ffa5", X"ff82", X"ff35", X"fd8d", X"fd98",
                                                        X"fd95", X"01cc", X"fd9d", X"fd7a", X"002c", X"fd6e", X"fea7", X"feac", X"0210", X"fd9e", X"007c", X"fe53", X"0285", X"0092",
                                                        X"000e", X"00de", X"01bf", X"ffb0", X"fe61", X"015e", X"fd45", X"00c0", X"fd1c", X"019f", X"fdce", X"01a7", X"fdcc", X"fefb",
                                                        X"0150", X"01f6", X"fe7e", X"fcd3", X"008d", X"0296", X"00ca", X"00f9", X"ffcd", X"0271", X"fe98", X"0062", X"fd36", X"021b",
                                                        X"fecd", X"00f4", X"00fb", X"ffa1", X"0234", X"fdd9", X"fde9", X"0061", X"fdb6", X"0296", X"0034", X"ffcc", X"fdc2", X"0115",
                                                        X"ff82", X"0144", X"0118", X"0120", X"02c4", X"fe17", X"018e", X"0015", X"fe6a", X"011b", X"00fa", X"fd2a", X"ff37", X"0093",
                                                        X"fd0b", X"ffbb", X"ff83", X"0136", X"0178", X"00d0", X"00db", X"ffaa", X"0049", X"fd22", X"02bb", X"fe01", X"ff7d", X"ff4c",
                                                        X"fee5", X"fd5a", X"003a", X"fdca", X"ffb6", X"013e", X"0224", X"01a5", X"fd86", X"0231", X"fd4c", X"fd85", X"fd7a", X"feaa",
                                                        X"fe48", X"024c", X"fdf4", X"fed2", X"00d2", X"0029", X"ff9e", X"fe0c", X"0103", X"fedf", X"ff9e", X"017b", X"fdee", X"0085",
                                                        X"fe5e", X"00ba", X"018b", X"fdef", X"ff41", X"025b", X"0250", X"fe8d", X"00e9", X"fe16", X"fee3", X"ffc4", X"0269", X"ff77",
                                                        X"00c4", X"fe42", X"feef", X"fea5");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"fea5";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

