-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16_4x2/amc_cnn_16w16a_4x2_src_SinglePortRAM_generic_block452.vhd
-- Created: 2024-11-04 16:44:21
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_4x2_src_SinglePortRAM_generic_block452
-- Source Path: amc_model_w16a16_4x2/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage95/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_4x2_src_SinglePortRAM_generic_block452 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_4x2_src_SinglePortRAM_generic_block452;


ARCHITECTURE rtl OF amc_cnn_16w16a_4x2_src_SinglePortRAM_generic_block452 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0dc2", X"ed3a", X"f8f7", X"0490", X"f557", X"fff5",
                                                        X"1001", X"f8f0", X"032c", X"0a39", X"eed3", X"02d8", X"0589", X"e65c", X"05c3", X"076e", X"07f1", X"f6ec", X"0059", X"0113",
                                                        X"0198", X"0326", X"031d", X"fe0a", X"fbea", X"0a84", X"fb1f", X"fe2a", X"027b", X"f6ef", X"fce6", X"08ea", X"06ca", X"f18d",
                                                        X"ff06", X"06a5", X"fd2a", X"fffa", X"fd2d", X"058f", X"0853", X"05c0", X"f86c", X"fe09", X"ffd6", X"ffba", X"0389", X"0699",
                                                        X"030d", X"f122", X"fe66", X"0893", X"f342", X"01f4", X"fad7", X"053a", X"fec8", X"039f", X"fb0a", X"0632", X"0637", X"f1c0",
                                                        X"fd90", X"055c", X"055b", X"fadb", X"01d4", X"0c58", X"f3e3", X"042a", X"f13a", X"05d6", X"05c7", X"0016", X"fa63", X"044f",
                                                        X"017f", X"021c", X"fc6c", X"030c", X"0aaf", X"edd4", X"fac5", X"fc54", X"f9e1", X"01f4", X"f327", X"01df", X"003b", X"047d",
                                                        X"f893", X"0346", X"0261", X"f6be", X"0301", X"0cca", X"0a48", X"f398", X"07c2", X"02f8", X"0067", X"0150", X"f449", X"fc50",
                                                        X"0058", X"0430", X"f662", X"fb0f", X"0705", X"01d0", X"0135", X"0a62", X"0499", X"f82a", X"00fe", X"fd5a", X"fbde", X"02ca",
                                                        X"f74f", X"0259", X"f9ce", X"0323", X"f5ae", X"fd83", X"0876", X"fc31", X"f8e4", X"0997", X"0b0a", X"f963", X"fedb", X"ffb9",
                                                        X"fb12", X"fd5a", X"00e5", X"0137", X"030d", X"0318", X"fe2f", X"fc66", X"0239", X"0197", X"0199", X"0585", X"08ed", X"f392",
                                                        X"ff00", X"0509", X"f148", X"ff0d", X"04bf", X"ffcb", X"0242", X"0342", X"fc01", X"0096", X"fa3e", X"0041", X"0571", X"058b",
                                                        X"04d1", X"f173", X"fba0", X"fc22", X"ecfa", X"0361", X"0326", X"038b", X"0499", X"0153", X"f7aa", X"07df", X"07ac", X"f71f",
                                                        X"0479", X"03e5", X"05bb", X"f213", X"f74c", X"f6aa", X"f4e3", X"001a", X"fc55", X"02b2", X"ffa9", X"ff46", X"f941", X"0294",
                                                        X"0b8b", X"fa53", X"0415", X"05e1", X"04ff", X"ea57", X"fba3", X"fd0d", X"f29a", X"023b", X"f937", X"ff9e", X"fe21", X"0141",
                                                        X"fbc1", X"06a3", X"01d0", X"f95b", X"046e", X"03de", X"0895", X"f2b2", X"f5bb", X"009c", X"fa94", X"005e", X"f174", X"fe6e",
                                                        X"0276", X"03da", X"f579", X"ffc1", X"04ee", X"0064", X"fe33", X"043e", X"0920", X"f44d", X"fd01", X"feb7", X"f987", X"ffb7",
                                                        X"f36d", X"fb5d", X"fb67", X"f9b7", X"f408", X"f9db", X"f792", X"04a9", X"fafe", X"0794", X"0b7e", X"f861", X"0049", X"0719",
                                                        X"fcb0", X"00ae", X"ee52", X"006a", X"0525", X"016f", X"f762", X"ff8a", X"ff72", X"0826", X"0030", X"0a63", X"097d", X"f76b",
                                                        X"fdcb", X"ff8c", X"f709", X"00d7", X"fbaf", X"01dc", X"000d", X"ff6d", X"fb33", X"00b6", X"0457", X"fc26", X"0160", X"084c",
                                                        X"0721", X"f2da", X"fe93", X"0786", X"f637", X"02ba", X"f0a2", X"0094", X"01d0", X"03bc", X"fbaa", X"0c1f", X"0981", X"06cc",
                                                        X"fb6e", X"0254", X"0458", X"ece7", X"feb8", X"fc3b", X"f3d8", X"0305", X"fe02", X"02bf", X"02c4", X"0634", X"fe54", X"04d0",
                                                        X"005d", X"f818", X"ff0f", X"ff19", X"06df", X"f79d", X"fb1f", X"03f1", X"fc68", X"0295", X"f61e", X"03fe", X"022f", X"06ec",
                                                        X"feb6", X"fe93", X"fd0f", X"fbc2", X"013b", X"073a", X"0601", X"f73c", X"f543", X"fc62", X"f90c", X"fe92", X"0368", X"fdc2",
                                                        X"05a6", X"0347", X"fde5", X"0133", X"0174", X"016d", X"fe35", X"05f5", X"0812", X"f447", X"fbc2", X"f584", X"f6fc", X"008d",
                                                        X"f3a9", X"ff3c", X"0302", X"02a0", X"f878", X"fff6", X"03a2", X"0492", X"0011", X"0658", X"05b9", X"efcb", X"fb93", X"fba8",
                                                        X"f710", X"01bf", X"eb96", X"fb65", X"02c1", X"fd77", X"f523", X"ff1d", X"03a7", X"f98f", X"f83a", X"09fc", X"0c5a", X"fadb",
                                                        X"0625", X"fc1b", X"f7ca", X"0239", X"f867", X"015a", X"0030", X"0152", X"f7b9", X"00be", X"fe5c", X"f50f", X"fb92", X"098e",
                                                        X"097f", X"f55d", X"fee8", X"ffb8", X"f38b", X"0188", X"f3a4", X"fea7", X"fce0", X"fbc1", X"f730", X"038c", X"00f8", X"edba",
                                                        X"ff40", X"06ee", X"0ba0", X"f12c", X"fde0", X"fb48", X"fbf4", X"03e7", X"ec7d", X"05a1", X"020c", X"01c4", X"f4e2", X"fd5f",
                                                        X"0248", X"faa1", X"06bc", X"02dc", X"0b58", X"eca3", X"0007", X"fe98", X"f66d", X"02a4", X"fd82", X"00f9", X"f8dc", X"ffb9",
                                                        X"f091", X"fe4c", X"03fe", X"fd03", X"0430", X"02f9", X"0644", X"f3f5", X"06a1", X"fdb5", X"f574", X"0518", X"f6e8", X"0447",
                                                        X"fdf2", X"0483", X"f5ce", X"0926", X"036a", X"f861", X"0339", X"047f", X"0736", X"eea5", X"fe4c", X"0190", X"f09c", X"0332",
                                                        X"f2a7", X"0417", X"fd1e", X"0464", X"f9ec", X"04ed", X"0417", X"feb4", X"00d2", X"05ab", X"05ca", X"ecfd", X"0563", X"04ee",
                                                        X"f83e", X"00df", X"fc42", X"ff43", X"02ac", X"05a5", X"f696", X"01dd", X"00b8", X"0002", X"0533", X"0257", X"09de", X"ec4c",
                                                        X"ff2a", X"fd3f", X"fb52", X"fe89", X"f72c", X"ff6f", X"fcb0", X"048d", X"f943", X"0335", X"ff05", X"040f", X"fefc", X"0518",
                                                        X"0a54", X"ec27", X"0373", X"f98c", X"f768", X"fdd9", X"f47a", X"f491", X"02cb", X"0084", X"f16e", X"0204", X"05b3", X"fa44",
                                                        X"ff40", X"075e", X"083e", X"ef81", X"0488", X"fb3e", X"fe37", X"03ee", X"0521", X"000d", X"0032", X"0278", X"fbfb", X"fdff",
                                                        X"01a7", X"f334", X"fe7c", X"0536", X"0285", X"f5c0", X"fa2d", X"00b9", X"f5d7", X"0020", X"ff00", X"fc5b", X"fc73", X"0332",
                                                        X"f93f", X"0352", X"06e2", X"f3c1", X"0002", X"0461", X"0658", X"ed64", X"fc0e", X"f955", X"fc90", X"0317", X"fb47", X"01b9",
                                                        X"feb8", X"00b7", X"f922", X"0594", X"07d6", X"fd78", X"012a", X"0563", X"06ff", X"f2b1", X"fe0d", X"fe5c", X"f646", X"0426",
                                                        X"f996", X"02aa", X"0100", X"0281", X"f24b", X"fe1c", X"03f8", X"fcb6", X"fcb1", X"06f2", X"0a51", X"ee10", X"ffbd", X"03aa",
                                                        X"f1d5", X"0446", X"feca", X"064d", X"079d", X"fd80", X"f82b", X"019c", X"ffc4", X"ff4d", X"ff88", X"04bc", X"07ab", X"faf2",
                                                        X"ff42", X"027f", X"f4fb", X"fe5e", X"f66b", X"092e", X"0074", X"01a5", X"ffcb", X"00c0", X"0426", X"f761", X"033e", X"0883",
                                                        X"076a", X"ef93", X"fe23", X"060b", X"fa36", X"02e6", X"f9e4", X"ff21", X"01b2", X"fea5", X"fc2b", X"005f", X"fee6", X"fa9f",
                                                        X"0184", X"0274", X"0ba6", X"f4fd", X"018e", X"0478", X"ff5c", X"01d4", X"f4fd", X"fd85", X"fa64", X"019f", X"fc81", X"fe6e",
                                                        X"0253", X"f3a4", X"fc24", X"06a0", X"0b01", X"f16c", X"fb21", X"fd51", X"f983", X"02a8", X"00cf", X"012b", X"fd0e", X"ffca",
                                                        X"f9d5", X"fecc", X"00db", X"fb0b", X"fef0", X"0576", X"07bd", X"ea7c", X"0197", X"0b2e", X"f7a1", X"0173", X"fd78", X"fad4",
                                                        X"fb96", X"0220", X"f7e6", X"0093", X"0308", X"f1b4", X"0080", X"034c", X"079c", X"ec95", X"f983", X"f8ae", X"fe96", X"0297",
                                                        X"ee5c", X"fe12", X"05d3", X"00f2", X"f633", X"ff4e", X"0738", X"f323", X"ffb1", X"0446", X"07c9", X"ed44", X"ff7b", X"f861",
                                                        X"f2bb", X"0158", X"feb7", X"012d", X"030c", X"fe6b", X"fa10", X"fea5", X"004c", X"ef67", X"0166", X"0669", X"0a6f", X"efd0",
                                                        X"fb60", X"fbb4", X"f27d", X"04b9", X"f26e", X"0341", X"0379", X"fced", X"fce6", X"fef1", X"ff6c", X"fd57", X"0103", X"0335",
                                                        X"0714", X"f32e", X"f85d", X"0127", X"f026", X"0288", X"f44b", X"0707", X"0492", X"0190", X"f47d", X"04bc", X"fe84", X"02d4",
                                                        X"0324", X"063e", X"06c8", X"edd2", X"f4a2", X"0001", X"fc70", X"00c7", X"f4df", X"0101", X"0428", X"fe7d", X"f8b7", X"ff37",
                                                        X"fe20", X"0103", X"0059", X"06e0", X"067e", X"f586", X"f4ff", X"0423", X"fc53", X"0353", X"f0b7", X"0566", X"fda8", X"032d",
                                                        X"f7ba", X"039b", X"0182", X"043e", X"fb9d", X"087e", X"06f4", X"f051", X"f834", X"ff9e", X"fa4a", X"02b7", X"fb67", X"fd96",
                                                        X"ff1c", X"045a", X"f7b1", X"0149", X"0159", X"03bf", X"fc94", X"0946", X"0568", X"eea4", X"03df", X"02db", X"f9b7", X"04d8",
                                                        X"0722", X"000e", X"0006", X"05d7", X"f463", X"fcd4", X"fc25", X"0008", X"01f0", X"0611", X"047c", X"f118", X"fd4c", X"01a8",
                                                        X"f634", X"fe25", X"f957", X"fdd4", X"fed6", X"0077", X"f852", X"040d", X"04e9", X"ff59", X"00cb", X"0168", X"0703", X"ed00",
                                                        X"ff00", X"fba0", X"f6ac", X"040f", X"f4eb", X"034f", X"0339", X"fee5", X"f4f0", X"fbff", X"039f", X"ffa4", X"ff8f", X"0154",
                                                        X"06b0", X"e99b", X"0109", X"08f4", X"ed53", X"03aa", X"03af", X"0004", X"fe7c", X"fed8", X"f62f", X"00db", X"fff7", X"07e6",
                                                        X"ff92", X"041a", X"0a9f", X"f6f4", X"fc1e", X"00d7", X"f716", X"028b", X"febc", X"061b", X"0145", X"ff83", X"f7a3", X"fe89",
                                                        X"fb3d", X"ff46", X"fdc0", X"0675", X"087d", X"f412", X"fccf", X"ffd1", X"f8fd", X"fdb5", X"f621", X"0284", X"0054", X"0284",
                                                        X"f76a", X"03a0", X"ff83", X"f774", X"ff23", X"07b9", X"053c", X"f447", X"fe28", X"ffd5", X"fdd9", X"0036", X"01dd", X"02c8",
                                                        X"fc38", X"0205", X"fdce", X"0032", X"fd75", X"fda2", X"00b7", X"07e7", X"07c6", X"f336", X"feb4", X"f918", X"f950", X"064e",
                                                        X"0316", X"fc9a", X"007a", X"04c7", X"f758", X"0117", X"0412", X"efa5", X"ffa5", X"06c6", X"093f", X"e8f9", X"0212", X"04c4",
                                                        X"f18b", X"02c4", X"076c", X"fd3f", X"0072", X"0602", X"0048", X"fd41", X"0130", X"0183", X"007f", X"096b", X"087e", X"e8f0",
                                                        X"fc2a", X"fa8b", X"efcd", X"0071", X"fcc9", X"02e1", X"ff71", X"0360", X"fa87", X"ff35", X"00df", X"fddc", X"0437", X"0631",
                                                        X"0a4e", X"e9e2", X"fe5d", X"fdc1", X"f869", X"ffd2", X"fbad", X"fedc", X"01da", X"0299", X"fc44", X"fd67", X"fb22", X"074d",
                                                        X"01df", X"07dd", X"0918", X"f4aa", X"fc85", X"0490", X"f456", X"0237", X"eff9", X"0012", X"02ca", X"fec4", X"f6c0", X"ff8e",
                                                        X"fe64", X"ff56", X"000e", X"03ad", X"065e", X"f31b", X"ffb3", X"fa45", X"f762", X"018c", X"f1ad", X"02b9", X"0597", X"0088",
                                                        X"f4e0", X"05f8", X"0134", X"fea7", X"ff12", X"0410", X"0753", X"eefe", X"feff", X"ff0f", X"f3af", X"073c", X"f35e", X"fe7b",
                                                        X"0204", X"009c", X"f56b", X"f8ed", X"fdb2", X"f7cb", X"0067", X"0785", X"09b2", X"f0e8", X"038e", X"ff9c", X"f780", X"00bd",
                                                        X"fda4", X"f8ab", X"feea", X"0330", X"f74b", X"fcdf", X"fd2b", X"f90b", X"fd41", X"0a4f", X"092b", X"f2e3", X"ff38", X"f5dd",
                                                        X"f6f9", X"ffb2", X"f285", X"ffbf", X"006a", X"fd6b", X"f9aa", X"0526", X"0730", X"f84b", X"fffa", X"0716", X"0a47", X"edaf",
                                                        X"0529", X"f945", X"fc88", X"018d", X"fb22", X"028f", X"fd57", X"fdff", X"f9af", X"fd1c", X"027e", X"f897", X"ff75", X"04c7",
                                                        X"0bbe", X"f0d9", X"fd73", X"f76e", X"f4c1", X"04ca", X"f391", X"0277", X"0171", X"055b", X"fd9b", X"fd3b", X"0513", X"eecc",
                                                        X"ffff", X"04bd", X"05e3", X"f2f0", X"ff41", X"fdd8", X"f145", X"0474", X"f4d1", X"fed3", X"0385", X"001d", X"fe75", X"0142",
                                                        X"0226", X"0295", X"ffaa", X"06b6", X"0679", X"eefc", X"03e4", X"fe0a", X"f3fe", X"0628", X"ff14", X"ffe2", X"ff80", X"047f",
                                                        X"f93b", X"0815", X"071a", X"f92b", X"036f", X"062a", X"09fb", X"f35c", X"02b9", X"f771", X"f7aa", X"04ac", X"fc06", X"081f",
                                                        X"ff01", X"fe4b", X"fd27", X"fa9c", X"fea7", X"f3b4", X"ffec", X"045f", X"0929", X"eed6", X"f944", X"0207", X"f5fd", X"01cb",
                                                        X"f1a9", X"0499", X"fca6", X"02e2", X"fd6a", X"0070", X"fe9c", X"ff10", X"fbb3", X"0913", X"04e8", X"f3b0", X"fabc", X"04f4",
                                                        X"fa7d", X"fe9c", X"f730", X"00ef", X"fa1e", X"011d", X"fb00", X"0203", X"fa4e", X"06c1", X"fb94", X"07b9", X"0844", X"fa2c",
                                                        X"f871", X"ffe8", X"f7ee", X"02b0", X"f31f", X"fb0d", X"f923", X"fedb", X"f601", X"003c", X"0045", X"f982", X"fe73", X"0352",
                                                        X"0a26", X"f701", X"fd8b", X"fb94", X"f08a", X"ff70", X"f854", X"f9aa", X"010c", X"fd53", X"fbdc", X"0048", X"03ac", X"f750",
                                                        X"02e6", X"05cc", X"0572", X"f440", X"fb09", X"f3e3", X"f46f", X"0094", X"f3a1", X"02f9", X"0674", X"0698", X"fa5e", X"f46b",
                                                        X"0151", X"045e", X"08e4", X"0232", X"065d", X"f145", X"fff2", X"fe33", X"f9e0", X"ffd3", X"f9eb", X"01aa", X"062f", X"fd8e",
                                                        X"fb98", X"03a4", X"0b08", X"ffa5", X"000a", X"0501", X"05e5", X"eb2a", X"ffd0", X"fc74", X"f762", X"ff28", X"f3a1", X"fe96",
                                                        X"007a", X"fccd", X"f874", X"08f6", X"091d", X"071b", X"00cf", X"06d7", X"08ba", X"eb48", X"fdb7", X"0492", X"f83f", X"0067",
                                                        X"f43d", X"fe95", X"040d", X"fabc", X"f883", X"06b4", X"05b5", X"0d8f", X"fb1a", X"089c", X"0af0", X"f128", X"f266", X"0137",
                                                        X"f7aa", X"0320", X"e78b", X"fd2b", X"03a5", X"01b9", X"f61c", X"00b3", X"01d9", X"08f5", X"00c3", X"06d2", X"0779", X"f4ba",
                                                        X"fbf0", X"fccc", X"fa80", X"0279", X"ffa7", X"02cf", X"03f0", X"0106", X"f915", X"feb2", X"0122", X"002e", X"fdf5", X"0909",
                                                        X"0790", X"efd9", X"fc33", X"f709", X"fe61", X"0261", X"f639", X"0086", X"fb7b", X"052e", X"fbd6", X"0872", X"0408", X"f892",
                                                        X"03b0", X"095f", X"0795", X"ed60", X"ff0d", X"0333", X"f59f", X"066d", X"fe5d", X"0234", X"fe66", X"fcfa", X"f5fd", X"04eb",
                                                        X"0170", X"f99d", X"0055", X"06c2", X"08e6", X"f3fa", X"fdec", X"00fd", X"f428", X"0154", X"057f", X"011b", X"002e", X"ff08",
                                                        X"f4d3", X"fcda", X"03b9", X"f903", X"fdae", X"0398", X"0a83", X"e854", X"fcfd", X"0274", X"f748", X"02f1", X"ff72", X"0357",
                                                        X"fd16", X"03cc", X"f8fb", X"ff50", X"024a", X"fc07", X"036a", X"074b", X"03d8", X"f63e", X"f354", X"fa6e", X"f27b", X"0129",
                                                        X"f599", X"03de", X"0ab8", X"0532", X"fbd2", X"fe1e", X"00c1", X"f2ae", X"0747", X"0439", X"078a", X"f574", X"ff37", X"0011",
                                                        X"f33e", X"037f", X"fb20", X"0459", X"04e6", X"ffef", X"f579", X"ff9c", X"06db", X"fbe9", X"fe60", X"02f9", X"08e9", X"ef4a",
                                                        X"016e", X"0301", X"f7ce", X"02c0", X"fd6d", X"fdbb", X"fb4a", X"0257", X"f62d", X"016c", X"ffca", X"fd32", X"02f5", X"0a17",
                                                        X"0bba", X"f796", X"0382", X"035f", X"f9e2", X"fe0e", X"00a5", X"0386", X"fc18", X"fe9b", X"f7de", X"0509", X"fbbc", X"0778",
                                                        X"f88e", X"0693", X"08e4", X"ee79", X"f7fd", X"0009", X"f48a", X"0235", X"04f6", X"05f3", X"04a3", X"fdea", X"fb89", X"060c",
                                                        X"001c", X"f9ba", X"0017", X"080a", X"0794", X"ee1a", X"faaf", X"fb43", X"f503", X"006e", X"0265", X"fc0a", X"04c2", X"fac8",
                                                        X"fb56", X"0369", X"004f", X"fbf1", X"ff0a", X"0712", X"07ef", X"f72c", X"ff70", X"ffd8", X"f388", X"058a", X"019b", X"032d",
                                                        X"fe31", X"037c", X"f87b", X"fbb8", X"fffd", X"fb53", X"fc52", X"04cc", X"0c23", X"f4fc", X"fde8", X"0029", X"f0db", X"0307",
                                                        X"f8f3", X"fe20", X"00c6", X"0104", X"f707", X"037a", X"01d7", X"ff14", X"ffeb", X"03e9", X"06ee", X"eab0", X"fe0f", X"0153",
                                                        X"f439", X"01b2", X"f6d7", X"fc7d", X"000f", X"0437", X"f55b", X"fe03", X"049a", X"f3dd", X"0554", X"071f", X"07d1", X"ebe4",
                                                        X"f6fc", X"0389", X"f999", X"0047", X"f7fe", X"0125", X"0212", X"ffd4", X"f594", X"fe8b", X"07a7", X"0025", X"039a", X"02bd",
                                                        X"0cae", X"f22d", X"0365", X"f441", X"f68a", X"03c1", X"fe34", X"03b7", X"0560", X"fe8d", X"fbfb", X"fcbc", X"0255", X"ffa9",
                                                        X"fbb1", X"0689", X"0a76", X"e98a", X"0093", X"0c97", X"f7a6", X"0161", X"fa58", X"0106", X"fcf0", X"fb89", X"f876", X"0436",
                                                        X"fb8e", X"fca4", X"fb43", X"05ee", X"0d28", X"efe0", X"f9d9", X"00f6", X"fe4c", X"fe7f", X"f303", X"0060", X"fb39", X"0034",
                                                        X"f729", X"0140", X"ff76", X"fa8a", X"fd6a", X"0792", X"085d", X"f81f", X"fe50", X"fb53", X"fa97", X"00db", X"f0a5", X"0065",
                                                        X"fdde", X"0204", X"fa26", X"ff14", X"f622", X"0009", X"01cf", X"0596", X"0828", X"ebf1", X"08f9", X"fdd9", X"f58d", X"037b",
                                                        X"fdc6", X"fec2", X"faa0", X"ff98", X"f64a", X"f8a0", X"019a", X"feaf", X"ffca", X"0311", X"0483", X"f0c3", X"fbd7", X"fd65",
                                                        X"f434", X"021e", X"f94a", X"ff1a", X"00a1", X"fd26", X"fa90", X"0249", X"0bc6", X"f428", X"01a3", X"025f", X"0623", X"f009",
                                                        X"fee5", X"0490", X"f235", X"0485", X"05b1", X"04d2", X"013b", X"ffb3", X"f607", X"0529", X"fda2", X"f173", X"ffa7", X"03ed",
                                                        X"04e0", X"ebcc", X"fdb1", X"fea8", X"f791", X"01de", X"f494", X"0226", X"07bd", X"0150", X"ff20", X"04de", X"0049", X"fd8e",
                                                        X"0342", X"04d6", X"0a30", X"f3bf", X"fef6", X"01ef", X"f7f3", X"02e3", X"f9c9", X"fff0", X"fbee", X"013f", X"fc3e", X"020e",
                                                        X"fed9", X"f814", X"fda7", X"0707", X"032f", X"f64b", X"f855", X"085d", X"f9bc", X"0334", X"f030", X"f87c", X"010e", X"fe9d",
                                                        X"f940", X"fb9f", X"0160", X"06d5", X"fcd9", X"0995", X"06cc", X"f7e8", X"fe6f", X"ff38", X"f776", X"007a", X"f8b6", X"02e9",
                                                        X"fb03", X"fe2e", X"f406", X"fa14", X"fd50", X"0068", X"faa4", X"089e", X"0c04", X"f21a", X"f983", X"0510", X"f6d4", X"fddf",
                                                        X"f670", X"faf1", X"0321", X"ff6c", X"fa2b", X"ff83", X"fcda", X"f627", X"006e", X"047a", X"0808", X"f0e1", X"ff22", X"fb31",
                                                        X"ee33", X"0007", X"fd5f", X"fa0e", X"00ba", X"0222", X"f642", X"f8ed", X"fe6f", X"f756", X"01e8", X"08e1", X"067c", X"f746",
                                                        X"faf4", X"fc0e", X"f5cf", X"02e0", X"ef14", X"03f9", X"039d", X"046a", X"f840", X"f6a1", X"0586", X"f096", X"0412", X"0327",
                                                        X"027e", X"ef4b", X"fb45", X"0319", X"f4c6", X"0268", X"eb6e", X"07a1", X"fa12", X"013a", X"f148", X"ff0c", X"fe78", X"f89f",
                                                        X"00dd", X"fff2", X"0906", X"ef8b", X"013d", X"00d8", X"f2a9", X"00a4", X"ed44", X"ffdf", X"053a", X"006a", X"f6f9", X"fe1d",
                                                        X"0022", X"f727", X"05c2", X"053d", X"05f3", X"f277", X"04f3", X"0610", X"fd37", X"fd52", X"0040", X"025f", X"01e9", X"fbde",
                                                        X"f511", X"fcb6", X"0254", X"009c", X"fbc1", X"00a9", X"0642", X"eb8b", X"fc8c", X"0131", X"fd0d", X"00bf", X"f8f9", X"fc27",
                                                        X"0119", X"ffee", X"f488", X"0001", X"fe60", X"07c0", X"fae2", X"0584", X"05fe", X"f059", X"fe7e", X"fa90", X"fff8", X"fd8a",
                                                        X"fd26", X"01da", X"fde6", X"00a1", X"fc4a", X"fb03", X"fc59", X"0606", X"fcb8", X"0764", X"0727", X"f51f", X"ff05", X"f67d",
                                                        X"f5db", X"01a5", X"0032", X"00f9", X"0659", X"ff6c", X"f972", X"037d", X"fadd", X"face", X"ffac", X"0712", X"0214", X"f3a7",
                                                        X"fc7c", X"068c", X"f52e", X"fd36", X"fb60", X"00db", X"fe1c", X"0046", X"fc7f", X"0431", X"0451", X"ff94", X"ffc6", X"01b0",
                                                        X"0bf7", X"e992", X"fcef", X"fe37", X"f17e", X"0288", X"f2f1", X"febd", X"06e9", X"ff65", X"f40c", X"041d", X"031a", X"fd70",
                                                        X"fcd1", X"07b9", X"08a0", X"ed8e", X"fe11", X"fed3", X"f5ef", X"01c0", X"fb30", X"02e0", X"0356", X"fbc1", X"fa22", X"0139",
                                                        X"0055", X"ffa4", X"fda9", X"045b", X"0721", X"ec91", X"fc69", X"f642", X"fd29", X"02b7", X"f589", X"03f3", X"05a5", X"033d",
                                                        X"fd3f", X"028b", X"ff4a", X"054d", X"0365", X"0336", X"09b4", X"ee68", X"004b", X"f3cf", X"f9cc", X"033e", X"fdf0", X"027a",
                                                        X"0083", X"012c", X"fb7f", X"fd90", X"fd87", X"fa50", X"fb8b", X"049b", X"0854", X"f4a0", X"ff9c", X"016e", X"f85d", X"02a3",
                                                        X"fcaa", X"ffd9", X"fc22", X"fbd9", X"f669", X"0085", X"0188", X"fb32", X"fb57", X"0349", X"08fc", X"f02b", X"f942", X"fb6e",
                                                        X"fd8f", X"0120", X"fa85", X"fe65", X"ffa9", X"00a5", X"fe12", X"050a", X"fe29", X"f746", X"0206", X"0ab7", X"070c", X"f862",
                                                        X"fc49", X"0006", X"fb6d", X"ffb9", X"fc30", X"01dd", X"0504", X"02ab", X"f952", X"fd2c", X"0306", X"fffb", X"02fe", X"0b38",
                                                        X"029d", X"f144", X"f469", X"fd46", X"fb0c", X"032f", X"000a", X"00a5", X"0209", X"0561", X"f59d", X"0b14", X"057e", X"f561",
                                                        X"0191", X"04ea", X"0de5", X"ebe9", X"fcca", X"029f", X"e64c", X"0135", X"0430", X"f8ba", X"0398", X"01c5", X"f097", X"fda3",
                                                        X"04a5", X"e126", X"04bc", X"067d");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"067d";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

