-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/model_pqt_2x2_w8a16/amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block336.vhd
-- Created: 2025-02-23 13:17:06
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block336
-- Source Path: model_pqt_2x2_w8a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage104/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block336 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block336;


ARCHITECTURE rtl OF amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block336 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0130", X"f826", X"fdd7", X"0812", X"06b2", X"fffb",
                                                        X"f747", X"0440", X"fde7", X"fe62", X"fd4f", X"09d1", X"0240", X"03d4", X"01f1", X"fe7d", X"0260", X"fbae", X"f4dd", X"034c",
                                                        X"043a", X"0411", X"facf", X"04a1", X"0065", X"fcda", X"0238", X"0474", X"fe48", X"ff4e", X"0724", X"fa1a", X"00c9", X"f8f7",
                                                        X"f594", X"07ae", X"ffd1", X"fd70", X"f9c4", X"0350", X"00ac", X"ff9c", X"0527", X"0726", X"f764", X"fd1a", X"0667", X"f84b",
                                                        X"fbab", X"ffa1", X"f51b", X"03ee", X"059a", X"fffe", X"f14e", X"0473", X"0263", X"048f", X"04b5", X"041a", X"fbaf", X"01d3",
                                                        X"02e3", X"ffa7", X"0357", X"00e4", X"f12a", X"0140", X"020d", X"fc70", X"f684", X"0547", X"032a", X"0582", X"01cd", X"00f4",
                                                        X"f8a6", X"ffcd", X"02c6", X"0049", X"0252", X"02bb", X"efa0", X"0561", X"0115", X"fbf4", X"f7b3", X"08cf", X"01ac", X"0309",
                                                        X"08ea", X"012d", X"0292", X"fdc1", X"048d", X"044b", X"03f3", X"0275", X"f0a4", X"037e", X"01df", X"faf5", X"ea1a", X"04aa",
                                                        X"0352", X"ffe7", X"ff91", X"0229", X"fd6a", X"003d", X"fd8d", X"0529", X"00ca", X"0459", X"f407", X"016f", X"00ba", X"fba8",
                                                        X"f850", X"01d3", X"fe1a", X"ff72", X"05eb", X"046d", X"06ee", X"fe91", X"01e8", X"0155", X"fe27", X"022f", X"fb67", X"054f",
                                                        X"0441", X"fd22", X"fb16", X"fd92", X"ff3f", X"0229", X"0380", X"00c1", X"0330", X"000f", X"fea9", X"0074", X"0025", X"f938",
                                                        X"f656", X"09b3", X"039b", X"0326", X"edec", X"04d2", X"fef9", X"0597", X"01d4", X"02ea", X"f98e", X"00cf", X"030f", X"029d",
                                                        X"0395", X"fdb2", X"f19c", X"fc0b", X"0639", X"f88b", X"f3ca", X"038a", X"fef9", X"01a1", X"003b", X"06b6", X"f8e1", X"0013",
                                                        X"0190", X"ff79", X"071b", X"0303", X"f12f", X"fd4f", X"02ab", X"f981", X"f044", X"07f2", X"fe30", X"0068", X"01ed", X"064e",
                                                        X"ff75", X"fe65", X"072c", X"0482", X"031d", X"fabe", X"f4ce", X"0166", X"06b7", X"fe04", X"e6a3", X"05ca", X"034d", X"fd6c",
                                                        X"044d", X"0567", X"0110", X"0451", X"05ef", X"07a6", X"0524", X"f924", X"f156", X"ff0b", X"048f", X"f9d1", X"f67f", X"0773",
                                                        X"fdec", X"ffdc", X"01ae", X"09b1", X"fde8", X"fefe", X"03b4", X"026c", X"0596", X"fc05", X"f416", X"0365", X"09c0", X"057f",
                                                        X"ee07", X"0260", X"0300", X"00aa", X"0185", X"0660", X"fb36", X"ff79", X"08a1", X"0249", X"0230", X"f9f7", X"f67c", X"02d5",
                                                        X"0464", X"fc8d", X"f336", X"0919", X"008c", X"0032", X"04ed", X"0309", X"fc4d", X"fd7d", X"02db", X"04fc", X"0695", X"fdaa",
                                                        X"f280", X"0272", X"0378", X"01db", X"f2fa", X"0171", X"02bf", X"0259", X"002f", X"041f", X"fbc0", X"fded", X"0512", X"fe61",
                                                        X"0224", X"fa30", X"f67d", X"056e", X"063e", X"fe20", X"eee6", X"fff7", X"01ea", X"0263", X"0590", X"054b", X"fb97", X"ffdd",
                                                        X"055a", X"0179", X"0546", X"01cb", X"f84f", X"0204", X"01c5", X"06d2", X"ecee", X"fcf8", X"00d5", X"058a", X"0893", X"0209",
                                                        X"02c5", X"010d", X"0565", X"0224", X"046b", X"ff3c", X"f1dc", X"0646", X"04fc", X"0077", X"f95c", X"0431", X"00b1", X"03e5",
                                                        X"0776", X"0242", X"fa3d", X"003d", X"02ae", X"0346", X"032d", X"f7ca", X"f43d", X"044c", X"0357", X"f620", X"ef9d", X"06e3",
                                                        X"00be", X"022c", X"05a2", X"0639", X"fcec", X"0438", X"00ab", X"0722", X"026e", X"fc33", X"f127", X"0825", X"0182", X"055b",
                                                        X"f13e", X"0b66", X"03f3", X"0720", X"0305", X"04a0", X"f7e6", X"0504", X"02f4", X"031c", X"ff62", X"0059", X"f04b", X"08b7",
                                                        X"0189", X"06aa", X"ecb4", X"07cb", X"fff7", X"0261", X"0213", X"0524", X"0564", X"0162", X"0c06", X"03f6", X"02f3", X"faba",
                                                        X"f66f", X"0628", X"03f0", X"fed1", X"f722", X"0518", X"0302", X"03b4", X"03e7", X"04d4", X"f6a6", X"02d3", X"097e", X"04ee",
                                                        X"007f", X"f48b", X"f1e8", X"00fc", X"0319", X"f5fb", X"ee21", X"04ee", X"050b", X"fe04", X"0016", X"0864", X"f43b", X"0034",
                                                        X"0532", X"ffa0", X"031d", X"fe6a", X"f609", X"fe1f", X"0555", X"f38f", X"eee8", X"038e", X"07d1", X"00cf", X"0319", X"0429",
                                                        X"01e3", X"047b", X"04ce", X"0676", X"07ba", X"fce8", X"fc40", X"03e3", X"0671", X"0027", X"e815", X"ffd9", X"025d", X"fec3",
                                                        X"0765", X"06cf", X"fa4e", X"02f3", X"071c", X"07bb", X"0125", X"fca8", X"f431", X"055f", X"04da", X"0034", X"f215", X"01d7",
                                                        X"05ea", X"feaf", X"0aad", X"0340", X"0118", X"03af", X"062a", X"06d3", X"0693", X"fd83", X"f120", X"084a", X"044b", X"0096",
                                                        X"ef74", X"ff2e", X"061b", X"073b", X"fff0", X"ff9e", X"fb27", X"0417", X"0483", X"034b", X"ffb8", X"ffb6", X"f30c", X"0611",
                                                        X"0743", X"fa1c", X"f007", X"0539", X"0601", X"0501", X"01a1", X"067d", X"fe09", X"034d", X"009b", X"02b0", X"04a2", X"0422",
                                                        X"f346", X"082b", X"01a6", X"fe7f", X"f21f", X"0234", X"ff82", X"03a0", X"02e3", X"0752", X"faf3", X"fcdc", X"05c9", X"05bb",
                                                        X"0804", X"fedd", X"f4a5", X"0522", X"01fc", X"0197", X"fb0e", X"0484", X"0270", X"0250", X"0223", X"06c4", X"03be", X"feff",
                                                        X"045b", X"fde0", X"0270", X"fe74", X"f1a4", X"020f", X"061e", X"ffa3", X"f47c", X"03e0", X"050f", X"00b2", X"ffb3", X"00ab",
                                                        X"fa7f", X"000b", X"05fc", X"ff14", X"02ab", X"0271", X"f460", X"012b", X"02af", X"0030", X"e992", X"fd02", X"fff3", X"02d0",
                                                        X"046e", X"022e", X"f40d", X"fea2", X"009b", X"fbec", X"fcb1", X"fbb7", X"f0b8", X"00f3", X"011f", X"0267", X"eac0", X"004b",
                                                        X"0024", X"0080", X"06fa", X"0232", X"ffa0", X"0066", X"0445", X"00fb", X"fd4c", X"fbe0", X"f1f4", X"fd20", X"0477", X"f892",
                                                        X"e814", X"0225", X"ff54", X"fdd6", X"ff85", X"0377", X"f7ad", X"fcc7", X"07f2", X"fece", X"0647", X"01f5", X"f0a9", X"01dd",
                                                        X"045f", X"053e", X"f22d", X"fc2e", X"fbba", X"032e", X"0167", X"0446", X"fd5a", X"fce9", X"0723", X"013c", X"001e", X"fd5d",
                                                        X"ee48", X"fff5", X"00ba", X"f815", X"e1da", X"ff2e", X"0062", X"fb6a", X"0236", X"0532", X"f717", X"fd08", X"082c", X"ff7f",
                                                        X"ffe5", X"0028", X"f05d", X"02c3", X"fdad", X"f918", X"f1a6", X"fcef", X"fa79", X"00a6", X"02a9", X"05ad", X"fe03", X"fa6a",
                                                        X"055e", X"fe0c", X"fdb9", X"0367", X"e95c", X"01fe", X"fe01", X"fd7f", X"ee3e", X"0050", X"ffdf", X"febb", X"0576", X"0108",
                                                        X"fdfe", X"fbf5", X"fc43", X"0371", X"03d1", X"ff03", X"f5e5", X"00a5", X"f9e1", X"f839", X"f007", X"061b", X"fd27", X"0000",
                                                        X"049d", X"fe94", X"fe5c", X"fa7b", X"ff12", X"0062", X"064a", X"ff1c", X"ead2", X"0364", X"006e", X"fcb5", X"ebf5", X"00ef",
                                                        X"03e6", X"fea0", X"0765", X"002b", X"0535", X"fcc1", X"0438", X"052b", X"047d", X"fcd1", X"edf5", X"005b", X"02eb", X"f5d5",
                                                        X"f152", X"04eb", X"03fe", X"fead", X"01b1", X"03a4", X"f54f", X"0019", X"ff7b", X"0676", X"0135", X"fd93", X"f06c", X"04ce",
                                                        X"03a0", X"f49b", X"eb26", X"0236", X"01d8", X"0160", X"01e6", X"05f6", X"f6e5", X"017d", X"00f8", X"fd84", X"0445", X"fe04",
                                                        X"ea46", X"06a6", X"0379", X"0553", X"e9bb", X"03ce", X"01bd", X"04d5", X"02d8", X"039e", X"fb44", X"069c", X"09c0", X"f973",
                                                        X"01bc", X"ff2e", X"ef50", X"0754", X"0351", X"056f", X"edb0", X"06ec", X"04fb", X"0211", X"ff44", X"0243", X"f9d1", X"ff80",
                                                        X"06b2", X"fc40", X"0042", X"ff54", X"ee42", X"0680", X"0543", X"08a2", X"e91c", X"0357", X"fd25", X"fed6", X"047a", X"07c6",
                                                        X"fa8c", X"fdf1", X"0115", X"fdfc", X"fe5b", X"fac1", X"ec75", X"05a0", X"07ba", X"ff6f", X"fe61", X"fe9f", X"fe8d", X"02b8",
                                                        X"fe1b", X"0225", X"fc23", X"01f6", X"07ac", X"001c", X"ff4e", X"0123", X"f8e5", X"fec4", X"0354", X"00ed", X"ef47", X"fe2f",
                                                        X"fcdc", X"fd29", X"0208", X"027b", X"f755", X"fdac", X"01d8", X"06b3", X"03ef", X"fdff", X"f6a1", X"03bf", X"ffb2", X"02e7",
                                                        X"eb78", X"01dd", X"03c1", X"01a5", X"0197", X"0580", X"fb6a", X"01ae", X"fe66", X"07ef", X"034b", X"fa78", X"ed9f", X"0460",
                                                        X"00a4", X"f999", X"e987", X"026b", X"0556", X"02d8", X"015f", X"0587", X"fc1a", X"01fd", X"020a", X"056e", X"04f8", X"03dc",
                                                        X"f26f", X"feda", X"0792", X"011e", X"e6ff", X"0939", X"057e", X"fe9a", X"0c1f", X"04a7", X"fc3f", X"ff0e", X"0023", X"0317",
                                                        X"09a9", X"fc07", X"f72c", X"ff6a", X"0804", X"0340", X"f0b0", X"fec7", X"067a", X"fd20", X"00b7", X"00aa", X"f8f0", X"01a9",
                                                        X"057f", X"0183", X"094e", X"fb91", X"f512", X"081f", X"03f8", X"fc42", X"e885", X"fec6", X"0245", X"ff5f", X"00f5", X"0343",
                                                        X"fe3b", X"ffea", X"04bb", X"08f8", X"fdec", X"fe78", X"f1dd", X"074b", X"00e8", X"f8c3", X"f456", X"030c", X"fd0c", X"fed5",
                                                        X"0290", X"01dd", X"01ad", X"fc76", X"04de", X"054c", X"fd55", X"fc34", X"ef06", X"02f7", X"00df", X"0099", X"f3e2", X"059b",
                                                        X"fbed", X"fd04", X"03b5", X"0387", X"fbcb", X"f90b", X"0403", X"04c6", X"feeb", X"ff4c", X"efe8", X"029d", X"fe88", X"fed0",
                                                        X"e9b7", X"0086", X"f974", X"ff70", X"05a6", X"00bc", X"f8fc", X"fa93", X"0478", X"02ea", X"0216", X"0232", X"f19c", X"0434",
                                                        X"fb38", X"f693", X"f607", X"0914", X"fd5b", X"0234", X"0597", X"003d", X"fe9b", X"01db", X"0048", X"03ae", X"0209", X"0410",
                                                        X"f08f", X"06a1", X"01f6", X"f3dd", X"eacd", X"08cf", X"fede", X"0158", X"06e0", X"0290", X"fdaf", X"02af", X"0279", X"0583",
                                                        X"08a4", X"ff14", X"eeef", X"077c", X"056c", X"faf5", X"efc2", X"08cd", X"feb6", X"0142", X"02f6", X"0626", X"fab4", X"0201",
                                                        X"040a", X"0527", X"ffb1", X"ff66", X"f01d", X"0432", X"073e", X"fca1", X"ebae", X"0461", X"ff20", X"008c", X"03d7", X"014c",
                                                        X"f9df", X"0170", X"036b", X"0220", X"026e", X"f852", X"f262", X"0174", X"04d7", X"fc98", X"e841", X"0266", X"02b2", X"ffaa",
                                                        X"fe93", X"0328", X"f470", X"02fa", X"008b", X"029e", X"01bf", X"fabd", X"f00c", X"08c9", X"056a", X"fec9", X"0635", X"0406",
                                                        X"ffce", X"ff78", X"0018", X"055a", X"fd6a", X"051c", X"016d", X"0755", X"01bc", X"fffa", X"f610", X"08df", X"01ce", X"07b9",
                                                        X"f1f4", X"042c", X"0196", X"01d2", X"01ca", X"032e", X"fc60", X"0265", X"025c", X"075f", X"0228", X"fe64", X"f58d", X"0250",
                                                        X"05f3", X"05c8", X"f2d2", X"04d6", X"0396", X"0398", X"058b", X"00bb", X"faad", X"00e6", X"ff11", X"066a", X"0395", X"facd",
                                                        X"f8b9", X"019d", X"0137", X"fdad", X"eecd", X"0550", X"0614", X"02f0", X"0254", X"0644", X"fd7b", X"0650", X"fe76", X"079c",
                                                        X"00b4", X"00b7", X"f8e8", X"00d9", X"0220", X"ffe0", X"f7b0", X"0671", X"03ec", X"019c", X"0205", X"03f1", X"018e", X"010c",
                                                        X"03f1", X"0878", X"03eb", X"fca0", X"f68e", X"ff2f", X"ffe8", X"fb02", X"eb6e", X"0109", X"025e", X"ffd1", X"ff11", X"05ed",
                                                        X"fc98", X"01d1", X"0774", X"0934", X"0663", X"fade", X"f5bc", X"fd30", X"fa31", X"ff83", X"e45b", X"ffc0", X"0420", X"015c",
                                                        X"ffe3", X"05da", X"f590", X"01a5", X"027c", X"07f2", X"0149", X"ff0f", X"f36b", X"0855", X"ff38", X"fb0e", X"f72e", X"042b",
                                                        X"03ce", X"0224", X"0155", X"064f", X"f867", X"0558", X"fdae", X"00e0", X"ff1c", X"0176", X"f351", X"0c17", X"027d", X"fedf",
                                                        X"f767", X"036c", X"07f9", X"018b", X"fea0", X"043d", X"f721", X"04bb", X"01eb", X"02ab", X"fdd5", X"fffa", X"ed31", X"0476",
                                                        X"02c9", X"f985", X"00fc", X"0aac", X"016c", X"0354", X"03f9", X"039a", X"fd2e", X"0272", X"01f5", X"04f5", X"fb8f", X"fc56",
                                                        X"f0c4", X"0099", X"02fb", X"f717", X"ec2b", X"04f6", X"01ca", X"0157", X"0166", X"ffdd", X"f8ad", X"034b", X"fa8d", X"06fc",
                                                        X"0594", X"00f1", X"f0bf", X"0607", X"05ef", X"fe9c", X"e70e", X"0407", X"0357", X"0117", X"032f", X"0621", X"f7fa", X"0213",
                                                        X"ff59", X"0536", X"0393", X"03ff", X"f479", X"06bd", X"042f", X"fe53", X"ec82", X"0213", X"0176", X"fc2a", X"0910", X"02a8",
                                                        X"041f", X"fe68", X"fd3a", X"0277", X"0168", X"fc4d", X"f5c8", X"067f", X"038e", X"faf9", X"f203", X"022c", X"ff7d", X"0107",
                                                        X"0068", X"0344", X"f59a", X"ff95", X"01ac", X"01a4", X"0268", X"f8e8", X"f166", X"0531", X"0289", X"0705", X"f32f", X"00a5",
                                                        X"fe81", X"ff90", X"01f4", X"02c8", X"f8ca", X"faea", X"02be", X"06c5", X"05f8", X"01e4", X"edb6", X"0184", X"ff07", X"ffc3",
                                                        X"f60c", X"03e1", X"fcc9", X"0271", X"02d8", X"00a7", X"fe97", X"ffdf", X"0c0d", X"0128", X"02db", X"fecc", X"e630", X"021a",
                                                        X"fa06", X"f850", X"ee4b", X"0875", X"fefc", X"0026", X"ff45", X"04cd", X"f8ce", X"fd89", X"0250", X"0761", X"ff79", X"fda7",
                                                        X"f3e0", X"06fb", X"fef5", X"faa7", X"f49c", X"0bc1", X"00e9", X"00c5", X"0483", X"00fd", X"fc0f", X"0266", X"036e", X"02e4",
                                                        X"ff06", X"fad3", X"f364", X"093d", X"fb5b", X"ff18", X"e828", X"0724", X"03db", X"0220", X"fd53", X"fe82", X"f91f", X"ff81",
                                                        X"030f", X"00c3", X"0ae5", X"fdd0", X"ed8d", X"0a7f", X"037f", X"f4f5", X"f0fa", X"0acf", X"055e", X"0294", X"fead", X"00cc",
                                                        X"fafe", X"03cf", X"0312", X"0685", X"03db", X"0217", X"f11e", X"05eb", X"0521", X"fbba", X"e6f6", X"02d6", X"0b01", X"0140",
                                                        X"0376", X"00ad", X"fac0", X"0649", X"0400", X"ffbc", X"008d", X"fdd4", X"f527", X"ff3c", X"0308", X"fbcb", X"ea84", X"077e",
                                                        X"07d7", X"00d3", X"0428", X"047f", X"fe04", X"0510", X"0212", X"03fc", X"061e", X"f902", X"f06e", X"0213", X"00a1", X"ff0a",
                                                        X"efa9", X"0518", X"06d0", X"0156", X"ff21", X"0145", X"ff21", X"0124", X"0361", X"072d", X"05ca", X"fcc7", X"f6fb", X"01af",
                                                        X"ff39", X"fe6d", X"fdea", X"fac3", X"0590", X"049f", X"02bf", X"0410", X"fced", X"ffe4", X"0827", X"02e4", X"02e1", X"fdc1",
                                                        X"f565", X"0122", X"fc9b", X"010d", X"f637", X"f9b3", X"075f", X"020b", X"ff5c", X"059b", X"f8e0", X"08b2", X"048d", X"020e",
                                                        X"0646", X"fe27", X"f590", X"04c7", X"fdae", X"00e6", X"f7c5", X"0302", X"07ea", X"03e2", X"fe19", X"05cd", X"0026", X"03b0",
                                                        X"01a6", X"0428", X"0315", X"ffa3", X"f6c8", X"fe90", X"fdfb", X"fd63", X"edc7", X"02e7", X"0131", X"06b6", X"0361", X"016b",
                                                        X"fc69", X"0319", X"02ff", X"0930", X"03e4", X"089f", X"f7b8", X"0525", X"0196", X"f1b5", X"edcd", X"0506", X"05bc", X"02d4",
                                                        X"0832", X"06ef", X"03e3", X"04a0", X"ffa6", X"05e5", X"feec", X"ffdf", X"f654", X"0187", X"fc1e", X"ef22", X"ef5d", X"03db",
                                                        X"01fa", X"04bc", X"022d", X"0777", X"fe3c", X"0507", X"06a9", X"06b1", X"0399", X"fd6a", X"f4af", X"fe26", X"00c0", X"f659",
                                                        X"efbe", X"0e0b", X"0328", X"0166", X"0435", X"0624", X"fc76", X"058a", X"06af", X"06a2", X"021a", X"fdaa", X"f5ca", X"03c3",
                                                        X"05db", X"fae4", X"e399", X"045f", X"057c", X"fc97", X"ff80", X"08ad", X"fa45", X"0305", X"05e3", X"056e", X"0276", X"f868",
                                                        X"f3cd", X"07d8", X"04a0", X"fa75", X"efb7", X"0469", X"032a", X"fe91", X"041d", X"0249", X"f3f1", X"02dd", X"0641", X"00d9",
                                                        X"051a", X"fb5c", X"f08b", X"0b5f", X"0551", X"0093", X"eafa", X"0382", X"fecc", X"01a8", X"fcd1", X"07e8", X"f769", X"038b",
                                                        X"feb5", X"0208", X"fff0", X"f740", X"f3f6", X"03f7", X"002b", X"fc21", X"ec54", X"0512", X"04b6", X"031c", X"fd34", X"07b0",
                                                        X"fde3", X"fd7b", X"fda7", X"fe31", X"0605", X"fb1a", X"f44a", X"0294", X"fe56", X"fae9", X"ee19", X"ff71", X"0440", X"0506",
                                                        X"00eb", X"0369", X"fec3", X"039f", X"ffda", X"009a", X"0373", X"fb64", X"f720", X"0705", X"020e", X"fdb6", X"f28e", X"fcb5",
                                                        X"04fa", X"012c", X"04ba", X"03dd", X"002b", X"015b", X"0218", X"fedb", X"fd8f", X"fc82", X"f50e", X"031d", X"0618", X"0106",
                                                        X"e807", X"fef0", X"03d4", X"fdee", X"0467", X"023b", X"fbf7", X"0009", X"0518", X"0b4e", X"0134", X"04cc", X"f56d", X"0779",
                                                        X"08ff", X"0543", X"e613", X"0316", X"05f7", X"ff19", X"071c", X"06df", X"020a", X"02ac", X"01ea", X"0adb", X"0385", X"01f2",
                                                        X"f174", X"048e", X"0215", X"fb4b", X"e47c", X"06cd", X"0561", X"054a", X"0647", X"0692", X"fb11", X"0194", X"0817", X"0043",
                                                        X"0167", X"0402", X"ef88", X"fd98", X"0153", X"011d", X"e882", X"0a2f", X"014f", X"ffc4", X"08e6", X"0386", X"fb98", X"016b",
                                                        X"064b", X"09a1", X"fd53", X"047a", X"f30e", X"fbfe", X"052b", X"f99e", X"f6b7", X"046e", X"fc86", X"ff37", X"01d0", X"05c2",
                                                        X"ff88", X"fe05", X"0126", X"080d", X"fa14", X"fe0b", X"f041", X"026b", X"fe97", X"f7c1", X"f005", X"fccf", X"f84c", X"ffb4",
                                                        X"0320", X"011c", X"fdda", X"fdc1", X"fb2a", X"031e", X"0487", X"fa81", X"f708", X"03fa", X"fa80", X"febd", X"f61c", X"fea5",
                                                        X"fc89", X"fe2f", X"039d", X"045d", X"fbcd", X"fc44", X"fe07", X"fd5a", X"04fb", X"00f7", X"f626", X"0865", X"01b6", X"fce0",
                                                        X"f162", X"094b", X"011c", X"01f8", X"0551", X"0129", X"0011", X"0019", X"ff63", X"0365", X"ff83", X"033a", X"f403", X"02ae",
                                                        X"03af", X"fbc3", X"f1e2", X"0257", X"0358", X"0626", X"0146", X"0305", X"f75d", X"ffd0", X"03c1", X"070c", X"07fb", X"fe39",
                                                        X"f346", X"fd33", X"03a2", X"ff78", X"f501", X"0904", X"02af", X"0020", X"058b", X"04b3", X"fbaa", X"00f4", X"0706", X"06e9",
                                                        X"04f4", X"fb74", X"f457", X"03c2", X"feb8", X"041e", X"e7d1", X"feae", X"02b4", X"0472", X"01b7", X"06b0", X"fee9", X"fd65",
                                                        X"0508", X"0c13", X"0288", X"f807", X"f01e", X"06aa", X"046a", X"f907", X"ecce", X"0652", X"01bd", X"fe2d", X"fccc", X"01a9",
                                                        X"fb79", X"fbe1", X"064a", X"03c1", X"0347", X"f610", X"fbb7", X"09f9", X"06ca", X"0de3", X"f0e6", X"0839", X"fdbe", X"0344",
                                                        X"fedb", X"0674", X"f843", X"0186", X"014a", X"fde0", X"0417", X"0289", X"f775", X"027c", X"018d", X"04ed", X"fc8c", X"fed8",
                                                        X"038e", X"032e", X"0291", X"01f2", X"fde1", X"03d0", X"0733", X"004d", X"04c6", X"05c9", X"f75f", X"048d", X"042b", X"fa4d",
                                                        X"f6d2", X"039b", X"06a3", X"0317", X"06a4", X"0428", X"fbe5", X"047c", X"fefd", X"003d", X"0442", X"fdf7", X"f1ac", X"02bb",
                                                        X"077b", X"fcba", X"f261", X"0cee", X"031b", X"013d", X"086d", X"0350", X"01a1", X"0239", X"05a5", X"0234", X"061b", X"0260",
                                                        X"ef3d", X"07d7", X"0a1d", X"fe02", X"ee26", X"051f", X"059a", X"03e4", X"0174", X"03a3", X"f688", X"059e", X"0306", X"0793",
                                                        X"fe53", X"ffa7", X"f720", X"07da", X"02cc", X"024a", X"e7c7", X"00c8", X"044b", X"0412", X"072c", X"07ec", X"f83a", X"0307",
                                                        X"0348", X"08c6", X"01a8", X"fbe1", X"f562", X"082f", X"01e2", X"0853", X"ea47", X"05cc", X"0560", X"0210", X"07b9", X"0571",
                                                        X"0100", X"0507", X"0578", X"04b7", X"ffd8", X"fdf9", X"f5dc", X"0bf6", X"0cfc", X"05a9", X"f0a9", X"0759", X"0571", X"0598",
                                                        X"0218", X"03d0", X"f6b4", X"05ee", X"020f", X"01d4", X"ffc2", X"fdc5", X"f7a0", X"0603", X"0d0f", X"ffde", X"f0ee", X"0396",
                                                        X"0246", X"03a1", X"04b4", X"0147", X"fa8c", X"ff61", X"0431", X"001c", X"0351", X"f80a", X"f0da", X"073f", X"081e", X"037b",
                                                        X"f400", X"0e8c", X"fe2a", X"00fc", X"020e", X"0578", X"fdc5", X"fddd", X"06f4", X"02fb", X"0326", X"f9c0", X"f06f", X"05c0",
                                                        X"ff96", X"fb52", X"edc5", X"0935", X"015a", X"028d", X"031a", X"055c", X"fce8", X"f9f5", X"fffb", X"026c", X"0767", X"fabd",
                                                        X"efd0", X"04a4", X"0094", X"00fa", X"e887", X"0ca8", X"06ee", X"03a0", X"05f9", X"0329", X"f730", X"02b9", X"00ff", X"006a",
                                                        X"0669", X"0364", X"f953", X"0343", X"000c", X"f909", X"fe96", X"02b0", X"04a3", X"fe5a", X"00ef", X"ff05", X"f6ff", X"0282",
                                                        X"ff88", X"0586", X"0c96", X"ff67", X"f8ff", X"03a4", X"043a", X"f9ea", X"f9f2", X"02dd", X"ffdd", X"06a8", X"001f", X"06ff",
                                                        X"fba8", X"04c9", X"fbbe", X"074f");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"074f";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

