-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/model_pqt_2x2_w8a16/amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block407.vhd
-- Created: 2025-02-23 13:17:14
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block407
-- Source Path: model_pqt_2x2_w8a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage54/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block407 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block407;


ARCHITECTURE rtl OF amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block407 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"1688", X"fd9d", X"005e", X"0230", X"0277", X"ffe7",
                                                        X"fb24", X"a8ed", X"0402", X"02d8", X"da93", X"fa27", X"e7b2", X"f6cd", X"0165", X"ec08", X"050d", X"fa62", X"f668", X"f8df",
                                                        X"0a25", X"fd8f", X"07b9", X"c260", X"01ac", X"053e", X"e5ae", X"f678", X"ebe4", X"f8cb", X"06ec", X"e444", X"0877", X"ff34",
                                                        X"f328", X"07be", X"0c02", X"f82d", X"ffb9", X"ea97", X"f993", X"fa80", X"f929", X"f406", X"f9b0", X"f4c4", X"038e", X"f806",
                                                        X"0b2a", X"f3e5", X"f6d8", X"0cf1", X"0258", X"ff03", X"fbf6", X"03e8", X"fb1e", X"0189", X"f936", X"f4a1", X"f8ff", X"f910",
                                                        X"04fd", X"fc11", X"0250", X"f00d", X"fb4b", X"0561", X"0125", X"f392", X"08fc", X"1385", X"fe35", X"ff61", X"fa3a", X"f781",
                                                        X"0278", X"f822", X"0caa", X"0828", X"ff03", X"fa90", X"0064", X"00dd", X"039c", X"f624", X"0263", X"090b", X"fb99", X"fe20",
                                                        X"0351", X"0191", X"0c3a", X"f550", X"0287", X"07ae", X"fd36", X"ff56", X"fe6d", X"000f", X"00bb", X"f884", X"0cec", X"02e0",
                                                        X"02c7", X"0168", X"0957", X"054c", X"08ad", X"032d", X"0032", X"03f2", X"fd65", X"0436", X"053f", X"f83a", X"0031", X"ecf3",
                                                        X"05b7", X"002d", X"f6fc", X"ff13", X"f6a4", X"fb83", X"0041", X"f9f4", X"eb05", X"ff68", X"0143", X"02e2", X"0856", X"e8c9",
                                                        X"0363", X"eee3", X"f5c6", X"ff54", X"fcf6", X"0418", X"fb30", X"08d9", X"fcff", X"0ac5", X"f0ca", X"0314", X"fdf5", X"038f",
                                                        X"0019", X"ec3b", X"04b5", X"f6e1", X"01e6", X"f5fb", X"03ff", X"ff80", X"fc4c", X"009c", X"f4a0", X"03fe", X"f86b", X"021d",
                                                        X"fd3e", X"06d7", X"fd3c", X"ffc0", X"01ee", X"fa3e", X"019e", X"feac", X"0511", X"fef4", X"0236", X"07ca", X"fb8c", X"02b0",
                                                        X"0042", X"fd93", X"001d", X"04a7", X"fd34", X"fe44", X"06a7", X"f432", X"f8e6", X"0728", X"fef5", X"0215", X"04e1", X"fb74",
                                                        X"fb54", X"fd6d", X"0031", X"0712", X"0091", X"fd19", X"fb0c", X"0513", X"0228", X"f403", X"0cfd", X"141b", X"f87b", X"fe0c",
                                                        X"1044", X"fee8", X"0a49", X"00d6", X"0690", X"0186", X"0038", X"05d0", X"f90f", X"059a", X"fe70", X"052f", X"05ee", X"14ab",
                                                        X"fcca", X"0955", X"0f5c", X"f919", X"0554", X"fb52", X"0423", X"0251", X"070b", X"fc78", X"facc", X"fe0c", X"f729", X"fd8d",
                                                        X"0214", X"01ef", X"f6eb", X"062f", X"0a67", X"f6fb", X"f57d", X"f70b", X"0aee", X"f4d6", X"0e4e", X"f8d1", X"fbd5", X"0b44",
                                                        X"0908", X"fefc", X"07a2", X"d926", X"04d6", X"0222", X"eb24", X"f55e", X"ea94", X"fd4b", X"0531", X"f351", X"0b1c", X"fa3d",
                                                        X"fc84", X"0809", X"0f23", X"00d6", X"09c8", X"cc81", X"06ee", X"049c", X"ecfb", X"f9f3", X"ea53", X"011d", X"ffbb", X"f7f7",
                                                        X"06e0", X"f726", X"fe59", X"03b2", X"0c85", X"f175", X"0904", X"bb68", X"033e", X"0213", X"d2b8", X"f676", X"f1c6", X"01cd",
                                                        X"ffaa", X"ee2d", X"0894", X"fba9", X"fbf1", X"0124", X"03bc", X"0306", X"f77e", X"eb8e", X"022c", X"069c", X"e9fd", X"fa6e",
                                                        X"f37b", X"fb2e", X"0563", X"fbe1", X"f898", X"00c2", X"f851", X"fab8", X"03e7", X"099e", X"046e", X"04cb", X"f81e", X"fd0b",
                                                        X"03b8", X"fd53", X"ffa2", X"f5b8", X"0763", X"087d", X"f8dc", X"fb51", X"04cc", X"f8b8", X"05f2", X"f770", X"fdba", X"0d02",
                                                        X"04f3", X"fdfa", X"04c2", X"f890", X"09e9", X"f68e", X"071c", X"04a3", X"f4bb", X"01d3", X"fd21", X"ff89", X"fff2", X"044e",
                                                        X"08a1", X"13b4", X"fd2c", X"f832", X"1193", X"0025", X"1318", X"f6f8", X"055e", X"fe71", X"fc6a", X"0194", X"f821", X"0319",
                                                        X"0392", X"f364", X"0189", X"07be", X"feba", X"feac", X"0c2c", X"069d", X"0946", X"fc3c", X"07cd", X"0201", X"fa55", X"0a7c",
                                                        X"fea2", X"0584", X"ffcf", X"efba", X"0213", X"06a2", X"f879", X"f6f0", X"fb2b", X"fd80", X"fca7", X"fd6e", X"f452", X"01db",
                                                        X"0470", X"01ea", X"f9d0", X"f62b", X"0460", X"e3e7", X"0bf7", X"03ca", X"05dd", X"f5e8", X"fba3", X"04e1", X"f762", X"03de",
                                                        X"e8e4", X"01f3", X"fd16", X"0166", X"fbbc", X"f7e7", X"ff1a", X"e892", X"fb97", X"fb48", X"ff0a", X"f8d9", X"f8e5", X"06ab",
                                                        X"f38d", X"02e1", X"e8e7", X"ff4b", X"feb9", X"0390", X"04e8", X"fabf", X"038f", X"f586", X"f683", X"fe36", X"fbac", X"0015",
                                                        X"fef5", X"0977", X"fca5", X"0344", X"f51e", X"0394", X"fd00", X"0630", X"fc86", X"fb36", X"f83e", X"eebc", X"fead", X"0812",
                                                        X"fcf0", X"fb54", X"03ff", X"02f7", X"0985", X"09eb", X"0644", X"0a40", X"fb40", X"03f6", X"0623", X"0107", X"ff05", X"092f",
                                                        X"fa5d", X"098e", X"06d6", X"0375", X"0c12", X"01fa", X"0048", X"01e5", X"07e2", X"0e08", X"06cb", X"fb7f", X"0598", X"09e1",
                                                        X"036c", X"0483", X"fd4e", X"06de", X"fe16", X"0103", X"04b2", X"fffe", X"0295", X"018e", X"0688", X"0def", X"0bf6", X"074e",
                                                        X"fad4", X"019e", X"0690", X"fda9", X"fc0b", X"f022", X"028f", X"fdda", X"f0a7", X"fd13", X"f99f", X"fd36", X"0b14", X"0565",
                                                        X"08d5", X"fc52", X"fe9a", X"f8f9", X"0802", X"fe02", X"0a30", X"e68e", X"fb3f", X"02b9", X"f786", X"0147", X"f502", X"fcfc",
                                                        X"ff3f", X"f4df", X"0905", X"f3cd", X"fc16", X"fbed", X"074d", X"022c", X"0bf5", X"cafd", X"006b", X"038e", X"ec87", X"fd65",
                                                        X"f537", X"f75b", X"fe13", X"fad6", X"0817", X"f342", X"fa05", X"025b", X"04a2", X"fe66", X"0929", X"dfc7", X"0bb9", X"00a3",
                                                        X"def3", X"f6b6", X"ebe4", X"fb8d", X"02c7", X"0491", X"08b0", X"fb5e", X"f983", X"fff1", X"0e09", X"fa0e", X"005a", X"e9c2",
                                                        X"0083", X"ff67", X"f769", X"0044", X"ed9c", X"fab5", X"0341", X"f896", X"07c6", X"fa7a", X"fb8e", X"062b", X"046d", X"fbfb",
                                                        X"058a", X"034a", X"0539", X"0261", X"ef22", X"fd6a", X"fb7a", X"fcdb", X"07f8", X"fcf8", X"ff3b", X"08d9", X"fc9f", X"044c",
                                                        X"f77f", X"fc65", X"f813", X"1867", X"0114", X"008c", X"04ae", X"fee0", X"018c", X"012d", X"03cc", X"0731", X"fb86", X"0477",
                                                        X"0210", X"07e1", X"ff40", X"0a25", X"ed55", X"0222", X"fbd7", X"048e", X"0c3e", X"0413", X"06a8", X"0258", X"011e", X"0578",
                                                        X"f853", X"fe09", X"037a", X"00de", X"fc92", X"ef63", X"0157", X"f9c6", X"f39b", X"fe73", X"fdf3", X"0b36", X"09b6", X"04ca",
                                                        X"f5bf", X"07e5", X"fae3", X"04a4", X"0690", X"fe33", X"034b", X"031c", X"fb1d", X"fef4", X"00a6", X"f93b", X"fa1b", X"091b",
                                                        X"ff84", X"febf", X"fb38", X"098e", X"f682", X"0a48", X"05d1", X"e2c2", X"030b", X"f6ab", X"fefe", X"038f", X"fafa", X"f70f",
                                                        X"014b", X"0a0c", X"fe47", X"0043", X"eb80", X"0081", X"f645", X"0537", X"fcd9", X"f3a0", X"fe86", X"efd9", X"fd6b", X"fd3b",
                                                        X"fd58", X"fa2b", X"f6cb", X"068a", X"f53b", X"02a3", X"f757", X"0273", X"f6d6", X"0b4d", X"03a5", X"ed29", X"003c", X"f4fe",
                                                        X"fb28", X"fd12", X"f444", X"fce9", X"fed1", X"0624", X"fe5e", X"f784", X"fb3e", X"062c", X"f761", X"0937", X"012e", X"fc1b",
                                                        X"f885", X"0ad2", X"fe43", X"04c5", X"f89b", X"02bc", X"0267", X"0227", X"fd5b", X"ff4a", X"0bf6", X"0f02", X"ff29", X"030e",
                                                        X"fcda", X"08ae", X"04c6", X"ef69", X"0242", X"1315", X"fe39", X"0b6a", X"09b4", X"02f4", X"00a5", X"02b5", X"0649", X"0b2b",
                                                        X"0561", X"feb1", X"fd37", X"0e7a", X"fe30", X"0cc7", X"0f0b", X"10d9", X"03ce", X"ffa4", X"100b", X"fcec", X"00f9", X"fcaa",
                                                        X"0190", X"082b", X"08ef", X"02c2", X"f8d6", X"0fd6", X"0688", X"faca", X"fd05", X"f8a5", X"fcf8", X"fd1d", X"fbc6", X"00c2",
                                                        X"f662", X"fe94", X"0114", X"fbb1", X"0ab5", X"f467", X"f680", X"0b63", X"0823", X"fc4d", X"07ec", X"e3d3", X"f80d", X"0469",
                                                        X"ee57", X"f8c1", X"edee", X"f9f3", X"039c", X"fa2f", X"110e", X"f882", X"006b", X"0643", X"0b8d", X"048e", X"0640", X"cdc7",
                                                        X"0244", X"0692", X"eb2f", X"ff8e", X"f40a", X"f87b", X"0608", X"f3d5", X"0b58", X"f946", X"feb8", X"fe21", X"074f", X"fc3a",
                                                        X"0309", X"d8c1", X"0512", X"0443", X"ebb4", X"fda1", X"f23a", X"fb42", X"f9d6", X"00ca", X"03a0", X"f5bc", X"0376", X"f5d9",
                                                        X"0823", X"0079", X"0d0c", X"e8ad", X"05ce", X"01db", X"eebb", X"f984", X"fa60", X"fa35", X"04ea", X"eef3", X"fcdd", X"fb03",
                                                        X"03ce", X"fca3", X"ff72", X"05a4", X"074c", X"028d", X"04ca", X"05f7", X"fe80", X"f924", X"09c4", X"0392", X"0337", X"0603",
                                                        X"0013", X"fdde", X"017c", X"07ee", X"f9be", X"026d", X"1365", X"ffe0", X"080c", X"0adf", X"fb38", X"fc89", X"0525", X"0136",
                                                        X"0641", X"0848", X"fda4", X"f012", X"ffcd", X"07a5", X"0087", X"fc14", X"0677", X"0347", X"042b", X"014a", X"09e4", X"fc9e",
                                                        X"0ecb", X"fa58", X"01e0", X"02f3", X"fa6b", X"0a41", X"01b9", X"03e9", X"fef9", X"f9e7", X"ef49", X"fc55", X"0038", X"fd32",
                                                        X"056a", X"fd02", X"02c2", X"fe62", X"fb65", X"030d", X"0a18", X"055d", X"0840", X"f435", X"fa2f", X"fb14", X"0217", X"feb6",
                                                        X"ff3d", X"f9c1", X"fc48", X"0294", X"0671", X"018c", X"f33c", X"03c2", X"0913", X"0d36", X"fc86", X"f59b", X"f978", X"ea49",
                                                        X"0a21", X"0295", X"0268", X"fa37", X"fd00", X"0492", X"fa1b", X"03fd", X"ef18", X"fb5c", X"febe", X"02ba", X"fe89", X"f9fa",
                                                        X"086e", X"ee58", X"0243", X"0598", X"060d", X"f9df", X"fdf2", X"04bb", X"f5b3", X"062f", X"ed68", X"01b0", X"0074", X"0b4c",
                                                        X"07c2", X"f9ad", X"00ec", X"fcfb", X"f0ff", X"f5fb", X"0638", X"fb66", X"fec6", X"05a7", X"fe98", X"059a", X"fe4b", X"04cb",
                                                        X"fe62", X"fe7e", X"fc74", X"f7d8", X"f93f", X"fdde", X"fe94", X"04ce", X"fdcc", X"014b", X"051e", X"033e", X"00e8", X"021c",
                                                        X"ff3c", X"07ca", X"f7fd", X"0954", X"fc4c", X"faf2", X"04cc", X"fc18", X"0e48", X"067e", X"f4b9", X"0660", X"0678", X"fed9",
                                                        X"fde6", X"fdf1", X"024d", X"0210", X"fc18", X"ff27", X"00ef", X"0998", X"067f", X"07aa", X"0a95", X"1196", X"067b", X"02f0",
                                                        X"077d", X"fdf4", X"0c2f", X"feae", X"040a", X"041d", X"0624", X"fa96", X"0130", X"06d4", X"0711", X"00d4", X"edbf", X"fd91",
                                                        X"0081", X"fefd", X"03be", X"f369", X"fcf3", X"01e9", X"0199", X"003d", X"0bd5", X"02f7", X"f660", X"0bf5", X"0333", X"07a7",
                                                        X"f98a", X"f80f", X"0012", X"001f", X"fd14", X"fe09", X"fb39", X"f8e1", X"fe2b", X"0038", X"0536", X"03a9", X"f3ad", X"0b20",
                                                        X"09ff", X"0680", X"0dbf", X"d5be", X"fbb3", X"02a6", X"db73", X"fe38", X"e097", X"f3eb", X"f52d", X"fd83", X"0228", X"fd29",
                                                        X"f903", X"0189", X"090a", X"f83d", X"03a2", X"cc08", X"011a", X"037d", X"e723", X"fb38", X"ebc6", X"f277", X"039e", X"e804",
                                                        X"0796", X"002f", X"fdfc", X"0183", X"089a", X"01f2", X"f860", X"d748", X"010c", X"037f", X"fb80", X"fb62", X"fadc", X"f71a",
                                                        X"071f", X"ec2c", X"07a7", X"f231", X"fe1d", X"fecc", X"01b4", X"03a5", X"f8b7", X"0af6", X"0517", X"fe2e", X"000c", X"f965",
                                                        X"01fe", X"fc80", X"0fe1", X"f4e8", X"fd8c", X"fa34", X"fa78", X"fe7a", X"04c6", X"f48f", X"00fe", X"125a", X"08d0", X"0271",
                                                        X"03aa", X"0290", X"0d98", X"005c", X"03ed", X"021f", X"fd7b", X"0374", X"0317", X"0580", X"0670", X"fe9c", X"0731", X"07d8",
                                                        X"0331", X"fdce", X"074d", X"06e6", X"006e", X"fcee", X"f9ec", X"0452", X"fe5f", X"08b6", X"0194", X"ff7c", X"03bf", X"fc61",
                                                        X"021f", X"036d", X"fee1", X"fe18", X"0151", X"056c", X"04f1", X"fdaf", X"f4d9", X"0354", X"fdc9", X"066a", X"0488", X"fbcc",
                                                        X"08d2", X"f5ed", X"095c", X"0709", X"facd", X"f8ba", X"fbdf", X"0626", X"085b", X"fd3b", X"0287", X"0b2a", X"feb0", X"f643",
                                                        X"0b0c", X"f117", X"ffac", X"f87c", X"00eb", X"006e", X"fe30", X"fabc", X"f7f0", X"01f5", X"f624", X"0439", X"fc3a", X"ff4a",
                                                        X"f980", X"0033", X"0577", X"e703", X"001e", X"f14c", X"facf", X"f376", X"0a80", X"f51b", X"fb73", X"07c9", X"f924", X"0b26",
                                                        X"e77e", X"fe24", X"fb7c", X"0f73", X"0226", X"f9fd", X"00fd", X"e38a", X"f93f", X"fc95", X"0243", X"fc93", X"fb4c", X"033e",
                                                        X"fd90", X"028f", X"ef27", X"fc66", X"f3ec", X"08f4", X"001a", X"f25b", X"fc6d", X"ef9d", X"09ab", X"049c", X"00aa", X"febf",
                                                        X"05bb", X"0384", X"fd2b", X"ff9d", X"fe9a", X"036a", X"f97a", X"fec0", X"00f1", X"fe9a", X"0471", X"067d", X"fcd0", X"1395",
                                                        X"fd46", X"0290", X"095a", X"0011", X"0555", X"fe7e", X"ff0b", X"0a73", X"04f1", X"006d", X"031f", X"117d", X"0710", X"07cf",
                                                        X"0163", X"11e8", X"01ce", X"025c", X"0d59", X"f99d", X"08ab", X"fcb9", X"054e", X"05de", X"090b", X"f495", X"03ca", X"0a40",
                                                        X"0438", X"0365", X"ffaa", X"fe47", X"03d6", X"0199", X"fbe1", X"fee1", X"f8f5", X"ffd0", X"03dd", X"09f0", X"08da", X"f3a9",
                                                        X"fd1c", X"061b", X"0772", X"02c7", X"fb5f", X"d73b", X"00f6", X"fb38", X"f599", X"fb97", X"f239", X"fccb", X"06ca", X"ecf9",
                                                        X"093b", X"0511", X"f911", X"fec4", X"02ee", X"f78a", X"1a5e", X"dc07", X"fc7d", X"0242", X"ddf5", X"fb88", X"f35a", X"f765",
                                                        X"fb0c", X"e6ba", X"0688", X"033a", X"fb23", X"fe26", X"0e79", X"ef91", X"0a12", X"d939", X"ff23", X"febf", X"e33d", X"0271",
                                                        X"e7ed", X"fbaf", X"02a6", X"eed9", X"0b76", X"030c", X"fe65", X"0947", X"0b28", X"fe83", X"f653", X"eea3", X"005b", X"fb10",
                                                        X"f276", X"ff12", X"f167", X"fc07", X"0223", X"09ad", X"03da", X"f2dd", X"f277", X"07d7", X"0596", X"f625", X"01dd", X"f0cf",
                                                        X"fe9d", X"03cb", X"fcc8", X"fd2a", X"0354", X"0316", X"feb1", X"03ef", X"05d8", X"027d", X"fa59", X"058e", X"febe", X"fc9e",
                                                        X"0b53", X"05b7", X"010b", X"042d", X"0048", X"f72a", X"048c", X"f9d4", X"05cd", X"066d", X"f970", X"0467", X"ffde", X"0918",
                                                        X"0487", X"043b", X"0346", X"0e29", X"ffdf", X"ffcb", X"0e94", X"0231", X"0d55", X"f666", X"0321", X"0168", X"05b2", X"05fb",
                                                        X"fda4", X"05f3", X"02b1", X"fa41", X"fb2c", X"ffa9", X"fbfa", X"febd", X"0434", X"fe06", X"fe48", X"fd74", X"fdd8", X"0316",
                                                        X"f6f8", X"fdcb", X"fd7d", X"fb16", X"f32a", X"f2b2", X"f89f", X"f8a8", X"fc63", X"fa9b", X"052b", X"0504", X"041a", X"fd74",
                                                        X"0056", X"015b", X"f764", X"02bc", X"0470", X"e691", X"00a6", X"f1b9", X"0f07", X"0026", X"fad2", X"f9ff", X"fa35", X"0106",
                                                        X"f85b", X"fca3", X"f120", X"04b4", X"f96b", X"f95f", X"0281", X"f31a", X"04de", X"e52f", X"02d1", X"f66e", X"fec5", X"fc66",
                                                        X"f552", X"0684", X"f69a", X"0153", X"ef1c", X"00d6", X"fb45", X"0323", X"03c4", X"f717", X"03fb", X"f274", X"fd8f", X"0305",
                                                        X"fefb", X"01a9", X"085e", X"0776", X"fee1", X"0358", X"fcaf", X"02a5", X"ff20", X"063f", X"0ad4", X"fc39", X"fdb3", X"020a",
                                                        X"1022", X"00a9", X"0078", X"fc38", X"073c", X"024f", X"0561", X"0098", X"f6e8", X"08ec", X"05d2", X"0517", X"08d9", X"fb47",
                                                        X"f95f", X"f8e1", X"0341", X"10c3", X"03c0", X"046b", X"0a71", X"06cc", X"0ce5", X"0389", X"fec5", X"0958", X"0806", X"030b",
                                                        X"008f", X"06da", X"00b1", X"09f9", X"1355", X"1605", X"fd68", X"078f", X"016c", X"fc59", X"03ae", X"fbb5", X"0293", X"0843",
                                                        X"0739", X"faa1", X"04d5", X"01a9", X"0494", X"fad6", X"0883", X"ff4a", X"ff64", X"00d3", X"04da", X"fd71", X"fadc", X"ffe4",
                                                        X"01b6", X"09f6", X"0c85", X"f575", X"f9dd", X"0122", X"05e0", X"ff27", X"090e", X"e29b", X"0052", X"fbce", X"eb8e", X"f3de",
                                                        X"f55e", X"f7d4", X"0275", X"f5dc", X"0a2e", X"f82e", X"f3d4", X"0386", X"0948", X"0817", X"03f1", X"d92d", X"ff87", X"ff32",
                                                        X"ca12", X"f82a", X"dc1c", X"f8c3", X"00ef", X"e514", X"0489", X"005f", X"f69b", X"fae8", X"0f10", X"fce7", X"f830", X"c0ed",
                                                        X"ff74", X"02ab", X"d867", X"fbad", X"de6e", X"f1b8", X"0338", X"f3aa", X"0724", X"fc13", X"f7c9", X"04f4", X"0b3f", X"0eb6",
                                                        X"085c", X"ed3d", X"0174", X"fc19", X"eb58", X"ff75", X"ebc1", X"f993", X"fbca", X"fcd1", X"0287", X"fcd8", X"fd04", X"0441",
                                                        X"04c1", X"f43b", X"fe5b", X"ff61", X"00de", X"00f2", X"f2bd", X"023b", X"f854", X"02ca", X"ff25", X"0c59", X"03c3", X"ff08",
                                                        X"fc7f", X"052d", X"fe86", X"f8ee", X"fdc7", X"0c35", X"0315", X"0283", X"0eca", X"04d2", X"03df", X"0173", X"fd05", X"03bf",
                                                        X"fc29", X"00cf", X"fa73", X"fe72", X"fd4d", X"f738", X"00ba", X"03ae", X"fede", X"fe9c", X"039a", X"0093", X"0635", X"fe2d",
                                                        X"02b5", X"04f1", X"05ab", X"0174", X"04ee", X"0ace", X"0531", X"0435", X"0501", X"fa6b", X"f822", X"0074", X"fe21", X"ff74",
                                                        X"031c", X"faaf", X"ff7a", X"00a4", X"f839", X"fd19", X"fe2e", X"0135", X"fa44", X"f2c6", X"0286", X"ff56", X"fc21", X"fc11",
                                                        X"fc83", X"0243", X"09cb", X"02d9", X"f949", X"05f3", X"ff66", X"0526", X"fa0f", X"eff6", X"f681", X"ee59", X"0aa1", X"ff54",
                                                        X"fd4c", X"fe42", X"01e7", X"01d6", X"00cf", X"0257", X"e7e8", X"0163", X"f827", X"028c", X"fc8a", X"e99e", X"f9be", X"ee7e",
                                                        X"059f", X"efb4", X"fa6d", X"f929", X"f787", X"fe8d", X"fa9b", X"fe29", X"f386", X"ff0b", X"fbe7", X"031b", X"f9dc", X"f13f",
                                                        X"0158", X"fb55", X"f080", X"f684", X"f8b5", X"fc6d", X"fead", X"074b", X"f98d", X"fe4b", X"fd40", X"040d", X"fb93", X"084a",
                                                        X"ffba", X"f346", X"f72f", X"f6f3", X"ffd4", X"0575", X"f71d", X"f666", X"0f49", X"073e", X"0779", X"f96c", X"febb", X"084d",
                                                        X"00fb", X"061a", X"fa90", X"0128", X"f9f2", X"fb4a", X"fe26", X"0d0a", X"fff4", X"f6b6", X"0429", X"01ce", X"fea3", X"0500",
                                                        X"fd8f", X"0903", X"0252", X"f9ae", X"fcb1", X"049a", X"01fc", X"f58a", X"fd1f", X"10a1", X"fd41", X"fcc6", X"029e", X"01fd",
                                                        X"0127", X"fe26", X"069a", X"fc5f", X"0925", X"fd6e", X"f8c4", X"09da", X"06e0", X"0aca", X"00e5", X"035d", X"0319", X"0843",
                                                        X"0644", X"f91b", X"f7b5", X"fa37", X"00dd", X"fd44", X"05e1", X"f68d", X"fb99", X"0397", X"0670", X"f896", X"fdf0", X"dcbc",
                                                        X"0050", X"03c7", X"ef02", X"f510", X"f08b", X"f94e", X"fde6", X"fc90", X"1167", X"f77c", X"fa22", X"f946", X"130f", X"0739",
                                                        X"0eed", X"d0bc", X"01f1", X"0879", X"ee21", X"f9fc", X"ed30", X"f99b", X"048c", X"f915", X"0401", X"00b0", X"fc61", X"fad6",
                                                        X"0b9e", X"fbd3", X"fdcd", X"d21f", X"030c", X"052c", X"d769", X"ff43", X"f092", X"f7d3", X"04e6", X"f946", X"0cfc", X"fbf3",
                                                        X"0295", X"0114", X"021d", X"f92d", X"04b6", X"f17c", X"fcbf", X"0554", X"e56e", X"fdf6", X"f83c", X"f82f", X"0b18", X"f424",
                                                        X"05bd", X"fc10", X"ffc1", X"046a", X"01f3", X"0055", X"fba1", X"ff6c", X"0145", X"fd70", X"068a", X"003c", X"fcd6", X"fe97",
                                                        X"0815", X"fd57", X"fb8b", X"064e", X"fac2", X"06e1", X"fef5", X"ff20", X"fd38", X"002a", X"0348", X"ff02", X"fd31", X"05b9",
                                                        X"fed1", X"0290", X"ff54", X"068c", X"fd9e", X"fe7a", X"fc6c", X"0609", X"fbc1", X"fbd6", X"0494", X"10d6", X"fb75", X"002c",
                                                        X"024b", X"012a", X"0531", X"fc44", X"0b07", X"05e0", X"f9f8", X"0698", X"ff49", X"f513", X"faa6", X"f76a", X"06da", X"0ba4",
                                                        X"fba9", X"fba2", X"fa4d", X"007d", X"06ed", X"fe21", X"f915", X"09b2", X"061f", X"ffad", X"ff4d", X"f7c1", X"fd05", X"f84b",
                                                        X"ff80", X"00bf", X"0002", X"f7a9", X"fada", X"05db", X"f9b1", X"03f1", X"fc54", X"feae", X"ff2c", X"03c1", X"01b8", X"eb3c",
                                                        X"fe10", X"e931", X"fa63", X"049c", X"fa2c", X"fc79", X"f801", X"05ae", X"f97b", X"fe2f", X"f667", X"f778", X"02c0", X"134c",
                                                        X"0122", X"f6e5", X"0076", X"f4ef", X"f175", X"02da", X"fb52", X"fa89", X"0055", X"0531", X"066a", X"fe66", X"ecb8", X"fefd",
                                                        X"f51b", X"118d", X"0693", X"f242", X"fd6d", X"ef4e", X"fa05", X"0743", X"fa8d", X"f5f2", X"ffc8", X"0764", X"03fe", X"00d1",
                                                        X"f17c", X"0c51", X"fb7b", X"076b", X"026a", X"f871", X"00f4", X"0066", X"f30e", X"0154", X"fae8", X"fbfe", X"f7d9", X"02bc",
                                                        X"f5f0", X"0381", X"0e99", X"10e1");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"10e1";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

