-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/model_pqt_2x2_w8a16/amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block238.vhd
-- Created: 2025-02-23 13:17:05
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block238
-- Source Path: model_pqt_2x2_w8a16/DUT HDL/Conv Layer 2/Filter Matrix Multiplier1/ParallelMACs 4/Weight Storage13/SinglePortRAM_generic
-- Hierarchy Level: 5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block238 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block238;


ARCHITECTURE rtl OF amc_cnn_8w16a_ptq_src_SinglePortRAM_generic_block238 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0a19", X"00bc", X"0a66", X"0bb1", X"0443", X"04a0",
                                                        X"0789", X"face", X"0d20", X"0dc5", X"0791", X"0667", X"04c3", X"f8fc", X"0244", X"fe1e", X"02ba", X"0907", X"ff71", X"ff7e",
                                                        X"0355", X"fee1", X"fe1e", X"00f7");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"00f7";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

