-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/model_qat_2x2_w16a16/amc_cnn_qat_16w16a_src_SinglePortRAM_generic_block376.vhd
-- Created: 2025-02-27 17:52:00
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_qat_16w16a_src_SinglePortRAM_generic_block376
-- Source Path: model_qat_2x2_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage26/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_qat_16w16a_src_SinglePortRAM_generic_block376 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_qat_16w16a_src_SinglePortRAM_generic_block376;


ARCHITECTURE rtl OF amc_cnn_qat_16w16a_src_SinglePortRAM_generic_block376 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"fbd2", X"fa1a", X"009c", X"f365", X"03d7", X"ea98",
                                                        X"fd43", X"08f6", X"0295", X"e3d2", X"f2ee", X"f73e", X"f503", X"f70a", X"0b83", X"e717", X"f5f4", X"f84c", X"f706", X"f001",
                                                        X"f712", X"f8f5", X"f94e", X"02e6", X"02d8", X"edc4", X"fd66", X"fd3e", X"f6d0", X"fde4", X"fdcd", X"f32d", X"0106", X"f9a6",
                                                        X"e5f4", X"f678", X"f8a6", X"0409", X"f933", X"fcf3", X"f9ab", X"d421", X"044c", X"039b", X"025f", X"031f", X"0631", X"f778",
                                                        X"011e", X"fcf2", X"e91d", X"fc74", X"f55a", X"fbe4", X"fd66", X"0ae0", X"00a0", X"f48a", X"0403", X"fd0d", X"fbcc", X"f916",
                                                        X"0a0a", X"f604", X"0066", X"ff7f", X"eed0", X"05bd", X"f5d2", X"060b", X"06fb", X"1354", X"022c", X"06f0", X"fff3", X"f965",
                                                        X"f978", X"f4e3", X"0531", X"fab8", X"0341", X"ff36", X"f8bd", X"0af7", X"029d", X"036a", X"0bd8", X"0fc8", X"01ef", X"0016",
                                                        X"03ec", X"f4c2", X"fa20", X"faab", X"0762", X"0148", X"0914", X"0581", X"0398", X"05ac", X"0af4", X"0223", X"0867", X"133c",
                                                        X"070d", X"0099", X"07d8", X"0145", X"febd", X"00de", X"0802", X"fb0a", X"09e9", X"06b6", X"f6b8", X"0b91", X"033f", X"0706",
                                                        X"0ef8", X"188c", X"0c54", X"f7d4", X"0970", X"11fb", X"0183", X"fe4d", X"1575", X"0358", X"03ca", X"079c", X"f5fa", X"0f2c",
                                                        X"09b7", X"0e21", X"1531", X"192b", X"08e8", X"ec0a", X"065b", X"186a", X"0664", X"04b4", X"183c", X"0745", X"076b", X"0408",
                                                        X"0414", X"1a01", X"0d34", X"073c", X"1575", X"1979", X"1b24", X"f1ae", X"0bc3", X"10d0", X"0a0b", X"08d2", X"19b1", X"0c35",
                                                        X"0957", X"0fcc", X"0237", X"0af9", X"1242", X"09ee", X"1af7", X"1e69", X"1cb5", X"f668", X"0e3a", X"15e6", X"0b82", X"083f",
                                                        X"28b6", X"129a", X"0e44", X"0d5f", X"126e", X"147d", X"10b1", X"0730", X"0a95", X"212b", X"192b", X"f115", X"1415", X"1500",
                                                        X"0de7", X"0575", X"2539", X"10d5", X"0b3e", X"0320", X"0d09", X"1459", X"ff06", X"073c", X"0f88", X"1d0d", X"1ea1", X"ffb5",
                                                        X"0f9d", X"1535", X"0b0f", X"0591", X"2aa1", X"0d7e", X"1058", X"f89e", X"0855", X"1061", X"046a", X"03e3", X"0990", X"0ea1",
                                                        X"179a", X"fc95", X"071c", X"168f", X"048c", X"0a2d", X"21ca", X"0f23", X"0a8d", X"0443", X"fd9b", X"07ba", X"128c", X"051d",
                                                        X"0a81", X"1587", X"120e", X"ec81", X"0230", X"09d7", X"0147", X"fc7d", X"26ed", X"0c01", X"09e6", X"02dc", X"fe05", X"fbbd",
                                                        X"08db", X"ff81", X"00ca", X"0a95", X"14f1", X"f12a", X"06e2", X"0c60", X"fb5d", X"0316", X"151b", X"01f5", X"0325", X"0988",
                                                        X"f541", X"f881", X"06be", X"f89e", X"087f", X"0dfb", X"0a68", X"ed62", X"0880", X"0319", X"f91b", X"0389", X"13b4", X"fdc7",
                                                        X"01d2", X"feb1", X"eea1", X"00d4", X"fa62", X"f5bf", X"ff3a", X"0642", X"0397", X"ec7f", X"01a6", X"fbf6", X"f314", X"02e0",
                                                        X"020e", X"f246", X"fda1", X"f765", X"eead", X"006a", X"f8f8", X"f1c1", X"02b1", X"fd48", X"fde3", X"ebf3", X"f10f", X"fb87",
                                                        X"f79f", X"f8e0", X"f0ff", X"ef17", X"fde5", X"f45f", X"e8da", X"f046", X"f9b1", X"f5f2", X"0896", X"f9f4", X"fb90", X"e03e",
                                                        X"f2bc", X"f501", X"efdf", X"0123", X"ee57", X"f336", X"ead7", X"f486", X"ec88", X"f752", X"f20a", X"f74d", X"fe06", X"f5f3",
                                                        X"fa5c", X"f019", X"f4ea", X"ead7", X"f42a", X"f295", X"e5bb", X"ebed", X"f8ae", X"fde5", X"d9a7", X"edf5", X"0471", X"0288",
                                                        X"fba3", X"f713", X"f39d", X"e1d1", X"f9c2", X"e873", X"f7b9", X"f246", X"e5d6", X"dfb9", X"f160", X"fd6a", X"dc40", X"ec0b",
                                                        X"f543", X"f888", X"f6b0", X"f3f5", X"f022", X"f545", X"f5f7", X"e4ab", X"f498", X"fbe3", X"eaf7", X"e4b8", X"f7b2", X"0152",
                                                        X"d8b3", X"f718", X"fc5b", X"fdbe", X"fe34", X"ebdf", X"ec10", X"ddf5", X"fc2d", X"e4de", X"f62c", X"0a03", X"dccf", X"e369",
                                                        X"ef29", X"fe59", X"ede5", X"f6bb", X"ef84", X"f827", X"fd27", X"f031", X"f26b", X"dead", X"f7ab", X"edd4", X"f3a7", X"057e",
                                                        X"de7e", X"ef03", X"e73c", X"fb37", X"e32b", X"f093", X"fd6e", X"fb39", X"f0ce", X"f238", X"f0eb", X"ebf0", X"f510", X"f2ad",
                                                        X"f8ae", X"f6f7", X"e7a5", X"f189", X"f82f", X"f824", X"d678", X"f8c9", X"fe0f", X"f287", X"f3fd", X"f3ab", X"f99f", X"ea08",
                                                        X"ff85", X"ed16", X"f5da", X"fd43", X"f42e", X"f372", X"f4e0", X"fc81", X"dfe1", X"fef9", X"04b6", X"f8e9", X"f91d", X"0701",
                                                        X"f7ec", X"ec09", X"f4e3", X"ea6d", X"faed", X"f30d", X"fccf", X"f3da", X"fdb3", X"f5c6", X"df2b", X"0d6f", X"fe8f", X"0357",
                                                        X"0204", X"06a6", X"05e8", X"f258", X"f7f2", X"fc50", X"065a", X"f544", X"05ce", X"fcae", X"fcb3", X"059f", X"f100", X"09d9",
                                                        X"ff24", X"0719", X"0094", X"0b7a", X"0878", X"e49e", X"f700", X"feaf", X"0a2f", X"fe23", X"0eb1", X"fe44", X"01a9", X"04ef",
                                                        X"f5fa", X"0bd1", X"0426", X"ff5d", X"fdc6", X"0a4f", X"049d", X"efaf", X"f8f0", X"0b48", X"0c2f", X"07ec", X"0c1b", X"0819",
                                                        X"0763", X"ff1d", X"f1d2", X"0b2a", X"0847", X"03f6", X"f59c", X"0afd", X"0fd5", X"fb92", X"0870", X"0644", X"0bb2", X"162b",
                                                        X"1399", X"ff4e", X"047f", X"0439", X"fb7e", X"106f", X"08b0", X"fc7e", X"fbae", X"0f79", X"07e8", X"f4e7", X"09e6", X"0707",
                                                        X"012a", X"0b77", X"1f06", X"074b", X"0517", X"06a7", X"07f9", X"10c0", X"0556", X"ffd6", X"01c0", X"0ee0", X"0c89", X"e785",
                                                        X"07fe", X"122a", X"0632", X"0347", X"18eb", X"03e7", X"0b50", X"032f", X"02e2", X"18d8", X"0530", X"0773", X"06c7", X"1b33",
                                                        X"11a7", X"e7dc", X"fe5d", X"053d", X"060a", X"fb8a", X"22b9", X"0896", X"15bb", X"00a5", X"0dce", X"10b1", X"08a9", X"03ed",
                                                        X"0643", X"19c2", X"152b", X"f38e", X"05fb", X"14ad", X"12c1", X"0076", X"23ff", X"0a67", X"0d21", X"0354", X"03e3", X"0c23",
                                                        X"033f", X"02bc", X"12ed", X"1929", X"17d1", X"f4fc", X"fe7e", X"07e0", X"0404", X"029a", X"1e0a", X"0eb4", X"1168", X"0810",
                                                        X"fe38", X"1173", X"0a35", X"ff8f", X"0c64", X"1727", X"0a7a", X"ed0a", X"ff87", X"0491", X"0630", X"0409", X"11c4", X"0675",
                                                        X"0be4", X"00cb", X"0506", X"0bf2", X"0788", X"00dc", X"fa98", X"1074", X"0b9a", X"e66b", X"fcc4", X"0d2f", X"fd46", X"0ac7",
                                                        X"171a", X"047d", X"0d42", X"fd72", X"001e", X"030f", X"ffc8", X"fe65", X"ff2b", X"04ae", X"0b45", X"eaa1", X"0913", X"03c1",
                                                        X"ff00", X"03fc", X"0ecb", X"fe74", X"0164", X"083a", X"f125", X"0973", X"06c7", X"fe2f", X"0a04", X"fff3", X"03ae", X"e497",
                                                        X"0923", X"0548", X"f90c", X"01b2", X"fb49", X"f6bd", X"fe2b", X"0319", X"f15a", X"ffcb", X"05e5", X"0181", X"fde9", X"03a9",
                                                        X"06be", X"f053", X"09de", X"ff88", X"f2ec", X"ff95", X"f9b6", X"f438", X"fb6a", X"fdff", X"ee51", X"0bda", X"01ab", X"fb72",
                                                        X"fc1b", X"fc9b", X"02d6", X"ed28", X"03e8", X"f75b", X"f943", X"faf3", X"f704", X"f3c8", X"ee07", X"fb2e", X"e8a5", X"fe7d",
                                                        X"0296", X"f5aa", X"f85c", X"fac2", X"f7b1", X"e7fc", X"fe8d", X"edb7", X"fb11", X"f293", X"f3b7", X"f0bb", X"ea1d", X"eac7",
                                                        X"ea29", X"f83e", X"fcea", X"f6c7", X"f906", X"efdd", X"f3d1", X"f6ba", X"f3d6", X"e6ee", X"f8e7", X"f22d", X"f263", X"ea40",
                                                        X"e880", X"e7f3", X"e0a2", X"ee55", X"fc91", X"f4fe", X"f203", X"efdb", X"faaa", X"d796", X"fbe8", X"e866", X"fc93", X"f113",
                                                        X"fa87", X"ee10", X"ebcf", X"f199", X"deaa", X"f7f0", X"f289", X"f37c", X"f7b9", X"ed7d", X"f840", X"d0c4", X"f73a", X"f1f5",
                                                        X"f176", X"ffcd", X"eea5", X"ea07", X"ee1a", X"f8f7", X"dc80", X"0156", X"fa6a", X"f4cc", X"f2b0", X"fb0a", X"f872", X"f156",
                                                        X"fa77", X"e6ce", X"f11f", X"f844", X"fceb", X"ee55", X"ecf0", X"ff52", X"e019", X"f399", X"fb6f", X"f6a1", X"0b6f", X"fe61",
                                                        X"fa50", X"ec47", X"010f", X"eeec", X"f720", X"faf5", X"f411", X"e9fa", X"fa20", X"f771", X"f080", X"faf9", X"fb0a", X"f640",
                                                        X"fa11", X"ff16", X"ff81", X"ff4e", X"0a94", X"f9ef", X"f9ff", X"fdb7", X"f0f1", X"f64e", X"f1cc", X"f765", X"ec00", X"fc27",
                                                        X"f7b0", X"f7c3", X"fa55", X"04f5", X"f5d8", X"f2e1", X"fd82", X"f900", X"0108", X"02fa", X"00cf", X"f216", X"fa80", X"fba0",
                                                        X"f045", X"0664", X"f668", X"f863", X"fb21", X"00fc", X"015d", X"e544", X"f8f1", X"f6db", X"00d5", X"ffcb", X"0e1a", X"f5b3",
                                                        X"01f5", X"0061", X"fa83", X"1035", X"fe98", X"0e2d", X"0aae", X"ff98", X"060d", X"df5e", X"f3e1", X"f8e1", X"01e9", X"06bb",
                                                        X"07bf", X"0128", X"0755", X"fd4d", X"fb94", X"0833", X"fe52", X"0375", X"08a9", X"0915", X"0838", X"ef80", X"f866", X"fb55",
                                                        X"026b", X"f8bf", X"0851", X"00b6", X"06eb", X"fa0b", X"ffe2", X"08f4", X"fb0b", X"04c4", X"fa8c", X"0b41", X"05af", X"f310",
                                                        X"ffad", X"fc2e", X"013a", X"ff54", X"0e98", X"0075", X"0b4f", X"0206", X"f378", X"0a71", X"0569", X"053a", X"0378", X"0c6f",
                                                        X"0e63", X"ed41", X"0019", X"04ad", X"fefa", X"075c", X"0e1c", X"0251", X"0735", X"077f", X"ffe6", X"1326", X"078d", X"0069",
                                                        X"06a4", X"1130", X"09ce", X"fb2a", X"03c3", X"09dc", X"01b1", X"08ee", X"12b9", X"fd1d", X"0615", X"0bc1", X"ff36", X"12c6",
                                                        X"080c", X"ff31", X"053c", X"136a", X"0702", X"e80f", X"0e4f", X"128d", X"0325", X"f7f6", X"1395", X"0375", X"03e2", X"04fd",
                                                        X"0ce9", X"0a96", X"04f9", X"062f", X"fb78", X"1c80", X"0cce", X"eb7c", X"0ef8", X"177e", X"032e", X"035c", X"1e6e", X"090f",
                                                        X"1356", X"0b65", X"055e", X"1041", X"0134", X"0567", X"033c", X"14e5", X"0df7", X"f196", X"08d3", X"0d3f", X"06bd", X"fe38",
                                                        X"1c0c", X"0fba", X"097b", X"fe8b", X"015d", X"1001", X"fc91", X"0077", X"07d4", X"0c95", X"16fa", X"dbe1", X"0146", X"0a58",
                                                        X"13d0", X"0a8a", X"20b9", X"04f5", X"00bc", X"03a1", X"fb34", X"0894", X"08d7", X"fe74", X"fdca", X"0e08", X"14a9", X"f846",
                                                        X"f980", X"110e", X"068e", X"1230", X"14b3", X"021a", X"fc34", X"086c", X"0bd7", X"0199", X"1222", X"038e", X"fe26", X"096d",
                                                        X"116b", X"f0e7", X"feff", X"0819", X"0b05", X"0716", X"1836", X"ff54", X"07b7", X"fc21", X"0f1d", X"04d7", X"0b32", X"00f2",
                                                        X"0e2a", X"091a", X"1217", X"007f", X"0f14", X"0291", X"0068", X"0c1e", X"18b1", X"047a", X"fcba", X"01b6", X"0277", X"0d10",
                                                        X"0795", X"0614", X"09f5", X"1284", X"0c3e", X"f78a", X"fc86", X"0d45", X"0241", X"0947", X"1491", X"ff8c", X"0554", X"fdad",
                                                        X"0829", X"ff04", X"f8d8", X"ff29", X"0217", X"0c09", X"11ca", X"ea2f", X"fdeb", X"04c8", X"0349", X"f5ec", X"092d", X"02cf",
                                                        X"fcbd", X"fe42", X"fd53", X"f544", X"ff6b", X"f642", X"fdcc", X"078f", X"031c", X"04f9", X"0006", X"f9c6", X"fd47", X"fb17",
                                                        X"0923", X"f769", X"094c", X"0084", X"fcba", X"f633", X"fdb8", X"fd29", X"0b24", X"0666", X"061c", X"dad2", X"0ab2", X"fd6b",
                                                        X"f950", X"ffe7", X"0674", X"f383", X"0927", X"ff1d", X"fbf3", X"00dd", X"fe67", X"059b", X"0f1b", X"0f05", X"ff5a", X"f0dc",
                                                        X"0adf", X"016b", X"f92d", X"fbae", X"0456", X"f248", X"0501", X"fb85", X"0365", X"f941", X"eee2", X"0018", X"f906", X"0996",
                                                        X"f7a6", X"f01d", X"f460", X"fe98", X"009d", X"faa5", X"001d", X"f5f0", X"044b", X"fed8", X"fb16", X"fe76", X"f9b7", X"fe1a",
                                                        X"fbe2", X"0594", X"fdfc", X"d872", X"f9dc", X"f91e", X"0090", X"0082", X"024d", X"efd4", X"ff8e", X"fdd4", X"ed5a", X"fed1",
                                                        X"01fe", X"02e4", X"069b", X"04c6", X"f53a", X"e235", X"05f9", X"fa91", X"fecf", X"f97f", X"0200", X"f82e", X"fd6a", X"fa28",
                                                        X"f465", X"fd9c", X"04b7", X"fe1f", X"0228", X"ff9d", X"ff54", X"05f3", X"fafb", X"fcbb", X"ef05", X"f7c7", X"fcec", X"f17e",
                                                        X"0665", X"ff5a", X"ef37", X"f591", X"0704", X"05d3", X"08f3", X"0888", X"fea5", X"f6d6", X"0862", X"edf4", X"e9d9", X"f38f",
                                                        X"0234", X"f115", X"043f", X"00cb", X"f8bf", X"fc3c", X"069b", X"041b", X"0211", X"fe21", X"ff1f", X"dfed", X"fc7d", X"f351",
                                                        X"f37c", X"fdc6", X"fe04", X"f298", X"fb08", X"fb12", X"e567", X"fbda", X"ff28", X"f70b", X"fc50", X"0965", X"ff7d", X"dff0",
                                                        X"f5ed", X"ed1f", X"fb44", X"f7e1", X"0280", X"fc61", X"faf1", X"fd36", X"ee92", X"f7b5", X"fffd", X"fdc8", X"0a1b", X"ff0d",
                                                        X"0b87", X"ecf5", X"0220", X"f6a5", X"fee7", X"004d", X"049b", X"0163", X"f407", X"009b", X"edaf", X"0310", X"03dc", X"01e8",
                                                        X"056f", X"04c5", X"0a02", X"f276", X"fdaa", X"fcaf", X"0abc", X"0382", X"ffcb", X"f99a", X"0112", X"005e", X"f202", X"040f",
                                                        X"f5fd", X"0869", X"fbe8", X"f735", X"03a8", X"f5cf", X"0123", X"fa47", X"0c9a", X"0356", X"12eb", X"fd49", X"fdd5", X"04af",
                                                        X"ec20", X"0e13", X"ff4e", X"f8f5", X"f437", X"09e2", X"feee", X"e0b2", X"0140", X"0248", X"ff9b", X"ffb3", X"0ebd", X"fc89",
                                                        X"ffde", X"0abc", X"ee69", X"057e", X"06b5", X"f6a3", X"f68e", X"0b0c", X"fda6", X"e92b", X"02b9", X"0310", X"fb0c", X"0531",
                                                        X"159f", X"ff6d", X"fff9", X"0a63", X"ff46", X"0381", X"ff3c", X"f4c5", X"f88f", X"0b6e", X"0ab1", X"e38a", X"0c62", X"049a",
                                                        X"ff65", X"00bb", X"11ff", X"038f", X"00b3", X"06ce", X"f743", X"013b", X"0433", X"0768", X"0270", X"13b1", X"089b", X"ec88",
                                                        X"fe5e", X"0694", X"04e8", X"ff43", X"0e80", X"fd68", X"0aab", X"f1b4", X"0651", X"09fb", X"fc21", X"0510", X"086f", X"09f9",
                                                        X"01cd", X"e076", X"feeb", X"0b4b", X"0562", X"079b", X"0b8e", X"0112", X"0683", X"fa47", X"ee0c", X"0696", X"0042", X"0a5e",
                                                        X"15dd", X"0559", X"03e4", X"e32b", X"0051", X"fc3f", X"0875", X"070b", X"074e", X"ffd8", X"f8c7", X"fa7b", X"f462", X"0135",
                                                        X"0f26", X"0503", X"1321", X"0886", X"0541", X"e6e3", X"0451", X"ffda", X"f7b7", X"0bf9", X"080e", X"f92b", X"fcb2", X"0815",
                                                        X"ec6f", X"fc4c", X"04e8", X"f9e9", X"004e", X"08e9", X"fedc", X"ec18", X"0ea5", X"f25c", X"eec7", X"f225", X"0132", X"fc19",
                                                        X"fb4d", X"026e", X"ec1a", X"03d8", X"fd0a", X"fee7", X"fe97", X"0694", X"ff5d", X"e3a6", X"0983", X"033b", X"fa35", X"f4e1",
                                                        X"fa53", X"f43f", X"fedc", X"fe0e", X"ec4d", X"f8a0", X"f7c1", X"f72d", X"044a", X"faae", X"01d1", X"f3b8", X"fe59", X"ee63",
                                                        X"fcae", X"00d9", X"f760", X"f8e5", X"facc", X"fd44", X"ed89", X"0097", X"0818", X"f9d8", X"fcc8", X"f952", X"f674", X"e511",
                                                        X"0439", X"f44c", X"003f", X"0800", X"f126", X"f65c", X"f606", X"f865", X"f7a2", X"f6ed", X"07fc", X"fc73", X"f15c", X"f420",
                                                        X"02d0", X"ee02", X"fddb", X"f5bb", X"00aa", X"fdf5", X"f1ef", X"ee00", X"f4d7", X"f761", X"ee1f", X"efed", X"f67e", X"f8bd",
                                                        X"fd05", X"f46a", X"fd8a", X"f05d", X"014c", X"f19e", X"fb87", X"f5d7", X"f204", X"f346", X"ea3e", X"f942", X"e6fe", X"f10b",
                                                        X"0911", X"f6f2", X"0598", X"f73f", X"fa2a", X"f6be", X"fe9b", X"ef8a", X"f821", X"02c6", X"f7f4", X"f840", X"f14e", X"00f7",
                                                        X"e5bc", X"f037", X"fdff", X"f120", X"00bb", X"ff08", X"01d7", X"ebae", X"f8e0", X"f7e0", X"f86b", X"09e8", X"f950", X"f112",
                                                        X"eeaf", X"fe79", X"ea45", X"f3d5", X"0347", X"f600", X"0849", X"039d", X"015d", X"fb2f", X"f249", X"fb4a", X"fadc", X"00f7",
                                                        X"ffa7", X"fa25", X"f213", X"f555", X"ef0c", X"f6b5", X"fe8e", X"f417", X"fee2", X"f89e", X"0097", X"ee21", X"f829", X"fdd0",
                                                        X"f7ab", X"f80c", X"fb6d", X"f722", X"f57f", X"f5d9", X"f560", X"fad6", X"0483", X"fd5c", X"0c97", X"01e4", X"073c", X"f389",
                                                        X"fcd1", X"fb27", X"f396", X"006c", X"fca3", X"fa3d", X"f3a7", X"ff1d", X"fa2d", X"03e2", X"07a3", X"fc63", X"01c0", X"fc2a",
                                                        X"05c0", X"e76a", X"00ca", X"02a0", X"f995", X"fca8", X"ff21", X"fb35", X"00d3", X"0301", X"f695", X"1a84", X"10cd", X"092c",
                                                        X"01cc", X"0a68", X"0550", X"ea9f", X"1096", X"0232", X"ff85", X"fb28", X"1069", X"fbd2", X"007a", X"0903", X"ef9e", X"11f9",
                                                        X"0a43", X"0b8a", X"f803", X"0ce3", X"07a9", X"f280", X"18aa", X"0829", X"0508", X"f838", X"11c1", X"0594", X"03a4", X"fd5f",
                                                        X"fad1", X"1695", X"04e4", X"02e4", X"06b3", X"143e", X"0767", X"f8a4", X"11d9", X"fd96", X"0248", X"fccd", X"19bd", X"019e",
                                                        X"0c54", X"f778", X"f819", X"0d45", X"0066", X"0273", X"092a", X"171e", X"01ff", X"e940", X"fe88", X"07b7", X"0b80", X"f9f2",
                                                        X"142d", X"00be", X"102a", X"0002", X"f821", X"0e9c", X"0978", X"067f", X"1288", X"1178", X"164b", X"0442", X"0739", X"1010",
                                                        X"072a", X"fe2b", X"188a", X"020a", X"115a", X"0b7c", X"03a4", X"103a", X"0f24", X"0301", X"111b", X"1a96", X"0ceb", X"e800",
                                                        X"078d", X"1177", X"0f79", X"082b", X"1fd5", X"0508", X"0f7a", X"0c27", X"f33b", X"1150", X"0875", X"0a41", X"0d70", X"185e",
                                                        X"0a8e", X"f325", X"0be4", X"1122", X"0d7e", X"0657", X"21af", X"03f1", X"0788", X"027f", X"0400", X"041e", X"fff1", X"fd35",
                                                        X"fdbb", X"1364", X"0f2b", X"f01b", X"06b7", X"0aab", X"0706", X"0cde", X"210e", X"0971", X"1121", X"076e", X"05a0", X"0c7c",
                                                        X"0e59", X"02b7", X"1718", X"1c84", X"14f3", X"e39f", X"ff80", X"146a", X"0b4a", X"0df8", X"1ff4", X"07e6", X"129a", X"07c4",
                                                        X"07a9", X"0801", X"0c40", X"02cc", X"0ee7", X"16d8", X"15e6", X"f125", X"0daa", X"12c3", X"0582", X"0c8a", X"1e4d", X"0cfa",
                                                        X"1294", X"0632", X"1033", X"0ee3", X"0803", X"fe77", X"fe47", X"132b", X"1303", X"f5da", X"0e8e", X"0d97", X"04b7", X"012f",
                                                        X"1ceb", X"0ddd", X"0b99", X"019a", X"07fc", X"0d0d", X"13a3", X"0535", X"0275", X"0ce8", X"0e6f", X"f19d", X"039e", X"0e99",
                                                        X"0a15", X"0a23", X"2070", X"08ca", X"08b2", X"fe70", X"08e1", X"0e7e", X"1700", X"056a", X"fc02", X"1768", X"143f", X"f18e",
                                                        X"0510", X"0b73", X"0612", X"0705", X"2001", X"0a54", X"08a6", X"fdee", X"fef8", X"0724", X"feea", X"fa99", X"0092", X"12d2",
                                                        X"0bc1", X"f3f8", X"0774", X"05ca", X"097c", X"0723", X"1611", X"040b", X"05af", X"0471", X"009a", X"03e3", X"03ce", X"f5c1",
                                                        X"01ac", X"072e", X"04a0", X"db24", X"0b2d", X"0b29", X"08cb", X"0bfa", X"1607", X"00f9", X"0132", X"002d", X"02e8", X"f987",
                                                        X"026d", X"ff17", X"0521", X"02da", X"04f1", X"ee08", X"0a03", X"03c4", X"01c3", X"0a4c", X"0560", X"fe4a", X"010b", X"fc33",
                                                        X"f047", X"ff68", X"0017", X"ff65", X"0a90", X"0c5b", X"0865", X"f565", X"065e", X"0935", X"fcc2", X"08d0", X"0141", X"020b",
                                                        X"fecc", X"fbb1", X"f6ad", X"f74b", X"011d", X"f7a2", X"fe21", X"0497", X"ff86", X"ddb8", X"05ab", X"038a", X"00d0", X"0972",
                                                        X"fb35", X"f7b5", X"faff", X"fe85", X"e3b7", X"f83b", X"fb95", X"f342", X"0165", X"0c8b", X"fb6a", X"ecf8", X"f647", X"f879",
                                                        X"f702", X"fe7a", X"fb95", X"f9be", X"f739", X"fa48", X"e193", X"f6f5", X"f8a0", X"f28d", X"0456", X"03e0", X"0321", X"fae2",
                                                        X"ed95", X"ee60", X"f210", X"f8f8", X"f837", X"f025", X"f276", X"f1a1", X"ef40", X"f424", X"fe3f", X"f497", X"0493", X"0776",
                                                        X"fa04", X"e8f5", X"f065", X"ecef", X"fcbc", X"faf7", X"ff75", X"f490", X"fcd9", X"f7ed", X"eb3d", X"fe09", X"01eb", X"f8de",
                                                        X"febf", X"04d8", X"fb29", X"efa7", X"faee", X"f44e", X"f5a8", X"f8fd", X"f63b", X"f23a", X"fde8", X"0652", X"e72f", X"ff9c",
                                                        X"fcb0", X"fa44", X"024a", X"02c1", X"fbea", X"fc79", X"f934", X"ffb0", X"ff17", X"03d8", X"fb0e", X"ea56", X"ff49", X"ff77",
                                                        X"ebf0", X"fb5e", X"f59d", X"fedf", X"0c97", X"ff7c", X"fb4c", X"e844", X"fb15", X"046e", X"01df", X"fc51", X"f900", X"eba1",
                                                        X"f42e", X"fbdc", X"ea08", X"0725", X"fb64", X"08d2", X"17ad", X"0196", X"f8c1", X"dd02", X"f952", X"ff21", X"00ea", X"12fb",
                                                        X"feb3", X"f510", X"ef2a", X"f6b8", X"eaf0", X"f77d", X"08c1", X"f7ad", X"10c1", X"044d", X"ff0c", X"e458", X"f5ec", X"ea31",
                                                        X"fba8", X"0495", X"0088", X"eae5");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"eae5";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

